// Present Tense — Irregular Verbs mini-course
// 4 learning stages (Parts 1–18) + 30 progressive exercises + final proficiency test

export const irregolariStages = [
  {
    id: 'concept',
    title: 'What are Irregular Verbs?',
    subtitle: 'Regular verbs follow patterns; irregular verbs do not always follow them.',
    sections: [
      {
        heading: 'Part 1 — What is an Irregular Verb?',
        explanation:
          'In Italian, most verbs follow predictable patterns. Verbs that break those patterns are called irregular. The most common verbs in everyday Italian — essere, avere, andare, fare — are all irregular, so you need to learn them as useful patterns.',
        bullets: [
          {
            text: 'Regular verbs follow a pattern. -ARE verbs like parlare behave the same way.',
            example: 'io parlo · tu parli · lui/lei parla · noi parliamo · voi parlate · loro parlano',
          },
          {
            text: 'Irregular verbs break the pattern. Look at andare — the stem changes completely in several forms.',
            example: 'io vado ✓ (not "io ando") · tu vai · lui/lei va · noi andiamo · voi andate · loro vanno',
          },
          {
            text: 'These verbs are everywhere, so learn each one together with a real sentence.',
            example: 'Vado a Roma. · Vengo da Milano. · Faccio colazione.',
          },
        ],
        table: [
          { form: 'parlare — a regular -ARE verb', example: 'io parlo · tu parli · lui/lei parla · noi parliamo · voi parlate · loro parlano' },
          { form: 'andare — an irregular verb', example: 'io vado ✓ (not "io ando") · tu vai · lui/lei va · noi andiamo · voi andate · loro vanno' },
          { form: 'essere — a completely irregular verb', example: 'io sono · tu sei · lui/lei è · noi siamo · voi siete · loro sono' },
          { form: 'potere — an irregular modal verb', example: 'io posso · tu puoi · lui/lei può · noi possiamo · voi potete · loro possono' },
        ],
        note: 'Do not worry about grammar rules. Learn each irregular verb inside a useful sentence and the forms will feel natural quickly.',
      },
      {
        heading: 'Part 2 — Essere (to be)',
        explanation:
          'Essere is the most important verb in Italian — you use it constantly to say who you are, where you are, and how things are.',
        conjugation: {
          verb: 'essere',
          meaning: 'to be',
          rows: [
            { p: 'io', f: 'sono', example: 'Sono italiano.' },
            { p: 'tu', f: 'sei', example: 'Sei stanco.' },
            { p: 'lui/lei', f: 'è', example: 'Lei è italiana.' },
            { p: 'noi', f: 'siamo', example: 'Siamo amici.' },
            { p: 'voi', f: 'siete', example: 'Siete pronti.' },
            { p: 'loro', f: 'sono', example: 'Sono studenti.' },
          ],
          examples: [
            { it: 'Sono a casa.', en: 'I am at home.' },
            { it: 'Lei è italiana.', en: 'She is Italian.' },
            { it: 'Siete pronti?', en: 'Are you ready?' },
          ],
          note: 'io and loro both use "sono". The context — the verb person — tells you who it is.',
        },
      },
      {
        heading: 'Part 3 — Avere (to have)',
        explanation:
          'Avere means "to have", but Italian uses it in many expressions where English uses "to be": ho fame (I am hungry), ho sete (I am thirsty).',
        conjugation: {
          verb: 'avere',
          meaning: 'to have',
          rows: [
            { p: 'io', f: 'ho', example: 'Ho una macchina.' },
            { p: 'tu', f: 'hai', example: 'Hai tempo.' },
            { p: 'lui/lei', f: 'ha', example: 'Ha un cane.' },
            { p: 'noi', f: 'abbiamo', example: 'Abbiamo una casa.' },
            { p: 'voi', f: 'avete', example: 'Avete fame.' },
            { p: 'loro', f: 'hanno', example: 'Hanno due figli.' },
          ],
          examples: [
            { it: 'Ho fame.', en: 'I am hungry.' },
            { it: 'Ho sete.', en: 'I am thirsty.' },
            { it: 'Ho sonno.', en: 'I am sleepy.' },
            { it: 'Ho freddo.', en: 'I am cold.' },
            { it: 'Ho caldo.', en: 'I am hot.' },
            { it: 'Ho paura.', en: 'I am afraid.' },
          ],
          note: 'The "h-" is silent: ho sounds like "o". Remember the spelling — ho = I have, o = or.',
        },
      },
    ],
  },
  {
    id: 'basic',
    title: 'Andare, Fare, Stare & Dare',
    subtitle: 'Four short, high-frequency verbs for movement, actions, feelings, and giving.',
    sections: [
      {
        heading: 'Part 4 — Andare (to go)',
        explanation:
          'Andare is irregular: the stem changes in several forms. You already know it from everyday phrases like "vado a Roma" and "andiamo al ristorante".',
        conjugation: {
          verb: 'andare',
          meaning: 'to go',
          rows: [
            { p: 'io', f: 'vado', example: 'Vado a Roma.' },
            { p: 'tu', f: 'vai', example: 'Vai a scuola?' },
            { p: 'lui/lei', f: 'va', example: 'Lui va al lavoro.' },
            { p: 'noi', f: 'andiamo', example: 'Andiamo al ristorante.' },
            { p: 'voi', f: 'andate', example: 'Andate in Italia?' },
            { p: 'loro', f: 'vanno', example: 'Loro vanno a casa.' },
          ],
          patterns: ['a + city: a Roma', 'in + country: in Italia', 'a casa', 'al lavoro'],
          note: 'The io form is vado, NOT "io ando". The stem appears as va- in vado/vai/va/vanno.',
        },
      },
      {
        heading: 'Part 5 — Fare (to do / make)',
        explanation:
          'Fare is everywhere in everyday Italian, especially in set expressions like fare colazione, fare sport, and fare una passeggiata.',
        conjugation: {
          verb: 'fare',
          meaning: 'to do / make',
          rows: [
            { p: 'io', f: 'faccio', example: 'Faccio colazione.' },
            { p: 'tu', f: 'fai', example: 'Cosa fai?' },
            { p: 'lui/lei', f: 'fa', example: 'Lui fa sport.' },
            { p: 'noi', f: 'facciamo', example: 'Facciamo una pausa.' },
            { p: 'voi', f: 'fate', example: 'Fate il lavoro?' },
            { p: 'loro', f: 'fanno', example: 'Loro fanno una torta.' },
          ],
          patterns: ['fare colazione', 'fare sport', 'fare una passeggiata', 'fare una domanda', 'fare attenzione', 'fare il bagno'],
          note: '"Cosa fai?" — What are you doing? — is one of the most useful questions in Italian.',
        },
      },
      {
        heading: 'Part 6 — Stare (to stay / be / feel)',
        explanation:
          'Stare is used for health ("come stai?"), for staying somewhere, and for feeling. Learn the common beginner uses first.',
        conjugation: {
          verb: 'stare',
          meaning: 'to stay / be / feel',
          rows: [
            { p: 'io', f: 'sto', example: 'Sto bene.' },
            { p: 'tu', f: 'stai', example: 'Come stai?' },
            { p: 'lui/lei', f: 'sta', example: 'Sta a casa.' },
            { p: 'noi', f: 'stiamo', example: 'Stiamo bene.' },
            { p: 'voi', f: 'state', example: 'State bene?' },
            { p: 'loro', f: 'stanno', example: 'Loro stanno a Roma.' },
          ],
          examples: [
            { it: 'Come stai?', en: 'How are you?' },
            { it: 'Sto bene, grazie.', en: 'I am well, thank you.' },
            { it: 'Sto a casa.', en: 'I am staying at home.' },
          ],
          note: 'stare + a place = to be/stay somewhere: Sto a casa. Stiamo a Roma.',
        },
      },
      {
        heading: 'Part 7 — Dare (to give)',
        explanation:
          'Dare is short and irregular. Be careful with the accent on dà (he/she gives) — it looks like the preposition da (from) but means something completely different.',
        conjugation: {
          verb: 'dare',
          meaning: 'to give',
          rows: [
            { p: 'io', f: 'do', example: 'Ti do il libro.' },
            { p: 'tu', f: 'dai', example: 'Mi dai un caffè?' },
            { p: 'lui/lei', f: 'dà', example: 'Lui dà un regalo a Maria.' },
            { p: 'noi', f: 'diamo', example: 'Diamo una mano.' },
            { p: 'voi', f: 'date', example: 'Mi date il menu?' },
            { p: 'loro', f: 'danno', example: 'Ti danno una risposta.' },
          ],
          patterns: ['dà (accent) = gives', 'da (no accent) = from / at'],
          note: '"Marco dà un libro a Maria" — he gives. "Vengo da Roma" — from. The accent marks the verb.',
        },
      },
    ],
  },
  {
    id: 'connect',
    title: 'Dire, Venire, Uscire & Salire',
    subtitle: 'Talking, moving toward a place, going out, and going up.',
    sections: [
      {
        heading: 'Part 8 — Dire (to say / tell)',
        explanation:
          'Dire is used constantly for anything you say or tell. The io form is dico, and "dire la verità" is a common expression.',
        conjugation: {
          verb: 'dire',
          meaning: 'to say / tell',
          rows: [
            { p: 'io', f: 'dico', example: 'Dico la verità.' },
            { p: 'tu', f: 'dici', example: 'Cosa dici?' },
            { p: 'lui/lei', f: 'dice', example: 'Lui dice di sì.' },
            { p: 'noi', f: 'diciamo', example: 'Diciamo la stessa cosa.' },
            { p: 'voi', f: 'dite', example: 'Cosa dite?' },
            { p: 'loro', f: 'dicono', example: 'Loro dicono che è facile.' },
          ],
          patterns: ['dire la verità', 'dire di sì', 'dire di no'],
          note: '"La verità" = the truth. Dire la verità → to tell the truth.',
        },
      },
      {
        heading: 'Part 9 — Venire (to come)',
        explanation:
          'Venire means "to come" — movement toward the speaker. Compare it with andare ("to go", away from the speaker).',
        conjugation: {
          verb: 'venire',
          meaning: 'to come',
          rows: [
            { p: 'io', f: 'vengo', example: 'Vengo da Roma.' },
            { p: 'tu', f: 'vieni', example: 'Vieni con me?' },
            { p: 'lui/lei', f: 'viene', example: 'Lei viene domani.' },
            { p: 'noi', f: 'veniamo', example: 'Veniamo a casa tua.' },
            { p: 'voi', f: 'venite', example: 'Venite al ristorante?' },
            { p: 'loro', f: 'vengono', example: 'Loro vengono da Milano.' },
          ],
          patterns: ['andare → go (away from the speaker)', 'venire → come (toward the speaker)'],
          examples: [
            { it: 'Vado a Firenze.', en: 'I am going (away), to Florence.' },
            { it: 'Vengo a Firenze.', en: 'I am coming (here), to Florence.' },
          ],
          note: 'Also remember: "vengo da Roma" = I come FROM Rome. Venire + da = origin.',
        },
      },
      {
        heading: 'Part 10 — Uscire (to go out / leave)',
        explanation:
          'You use uscire every time you go out — with friends, in the evening, or out of the house. The io form is esco.',
        conjugation: {
          verb: 'uscire',
          meaning: 'to go out / leave',
          rows: [
            { p: 'io', f: 'esco', example: 'Esco alle otto.' },
            { p: 'tu', f: 'esci', example: 'Esci stasera?' },
            { p: 'lui/lei', f: 'esce', example: 'Lui esce con gli amici.' },
            { p: 'noi', f: 'usciamo', example: 'Usciamo insieme.' },
            { p: 'voi', f: 'uscite', example: 'Uscite oggi?' },
            { p: 'loro', f: 'escono', example: 'Loro escono dal lavoro.' },
          ],
          patterns: ['uscire con gli amici', 'uscire di casa', 'uscire stasera'],
          examples: [
            { it: 'Esco alle otto.', en: 'I go out at eight.' },
            { it: 'Esci stasera?', en: 'Are you going out tonight?' },
          ],
        },
      },
      {
        heading: 'Part 11 — Salire (to go up / get on)',
        explanation:
          'Salire means to go up stairs or to get on a train, bus, or plane. The io form is salgo.',
        conjugation: {
          verb: 'salire',
          meaning: 'to go up / get on',
          rows: [
            { p: 'io', f: 'salgo', example: 'Salgo le scale.' },
            { p: 'tu', f: 'sali', example: 'Sali con me?' },
            { p: 'lui/lei', f: 'sale', example: 'Lui sale sul treno.' },
            { p: 'noi', f: 'saliamo', example: 'Saliamo al secondo piano.' },
            { p: 'voi', f: 'salite', example: 'Salite in macchina.' },
            { p: 'loro', f: 'salgono', example: 'Loro salgono in autobus.' },
          ],
          note: 'Compare: salire sul treno (get on the train) vs scendere dal treno (get off the train).',
        },
      },
    ],
  },
  {
    id: 'know',
    title: 'Sapere & the Modal Verbs',
    subtitle: 'Knowing, and the three "helper" verbs potere, volere, dovere — plus bere.',
    sections: [
      {
        heading: 'Part 12 — Sapere (to know)',
        explanation:
          'Sapere means to know facts or know HOW to do something. It is different from conoscere, which means to be acquainted with a person, place, or thing.',
        conjugation: {
          verb: 'sapere',
          meaning: 'to know',
          rows: [
            { p: 'io', f: 'so', example: 'So la risposta.' },
            { p: 'tu', f: 'sai', example: 'Sai parlare italiano?' },
            { p: 'lui/lei', f: 'sa', example: 'Lui sa tutto.' },
            { p: 'noi', f: 'sappiamo', example: 'Sappiamo la verità.' },
            { p: 'voi', f: 'sapete', example: 'Sapete dove è Roma?' },
            { p: 'loro', f: 'sanno', example: 'Loro sanno tutto.' },
          ],
          examples: [
            { it: 'So parlare italiano.', en: 'I know how to speak Italian.' },
            { it: 'Conosco Marco.', en: 'I know Marco (I am acquainted with him).' },
          ],
          note: 'sapere = to know information / know how. conoscere = to know a person, place, or thing.',
        },
      },
      {
        heading: 'Part 13 — Potere (can / to be able to)',
        explanation:
          'Potere is a modal verb: it is always followed by an infinitive. Structure: potere + infinitive.',
        conjugation: {
          verb: 'potere',
          meaning: 'can / to be able to',
          rows: [
            { p: 'io', f: 'posso', example: 'Posso parlare.' },
            { p: 'tu', f: 'puoi', example: 'Puoi venire.' },
            { p: 'lui/lei', f: 'può', example: 'Lei può venire.' },
            { p: 'noi', f: 'possiamo', example: 'Possiamo andare.' },
            { p: 'voi', f: 'potete', example: 'Potete aspettare?' },
            { p: 'loro', f: 'possono', example: 'Loro possono parlare italiano.' },
          ],
          examples: [
            { it: 'Posso entrare?', en: 'Can I come in?' },
            { it: 'Puoi aiutarmi?', en: 'Can you help me?' },
            { it: 'Possiamo andare.', en: 'We can go.' },
          ],
          patterns: ['potere + infinitive: posso parlare', 'puoi venire', 'possiamo andare'],
        },
      },
      {
        heading: 'Part 14 — Volere (to want)',
        explanation:
          'Volere means to want. Like potere, it is followed by an infinitive — or directly by a noun like un caffè.',
        conjugation: {
          verb: 'volere',
          meaning: 'to want',
          rows: [
            { p: 'io', f: 'voglio', example: 'Voglio un caffè.' },
            { p: 'tu', f: 'vuoi', example: 'Vuoi una pizza?' },
            { p: 'lui/lei', f: 'vuole', example: 'Lui vuole andare a Roma.' },
            { p: 'noi', f: 'vogliamo', example: 'Vogliamo mangiare.' },
            { p: 'voi', f: 'volete', example: 'Volete venire con noi?' },
            { p: 'loro', f: 'vogliono', example: 'Loro vogliono partire.' },
          ],
          examples: [
            { it: 'Voglio mangiare.', en: 'I want to eat.' },
            { it: 'Vuoi un caffè?', en: 'Do you want a coffee?' },
            { it: 'Voglio imparare l\'italiano.', en: 'I want to learn Italian.' },
          ],
          patterns: ['volere + infinitive: voglio mangiare', 'volere + noun: vuoi un caffè'],
        },
      },
      {
        heading: 'Part 15 — Dovere (must / to have to)',
        explanation:
          'Dovere expresses obligation. Structure: dovere + infinitive. It is the verb you need for "I have to...".',
        conjugation: {
          verb: 'dovere',
          meaning: 'must / to have to',
          rows: [
            { p: 'io', f: 'devo', example: 'Devo lavorare.' },
            { p: 'tu', f: 'devi', example: 'Devi studiare.' },
            { p: 'lui/lei', f: 'deve', example: 'Deve partire.' },
            { p: 'noi', f: 'dobbiamo', example: 'Dobbiamo andare.' },
            { p: 'voi', f: 'dovete', example: 'Dovete aspettare.' },
            { p: 'loro', f: 'devono', example: 'Devono lavorare.' },
          ],
          examples: [
            { it: 'Devo andare.', en: 'I have to go.' },
            { it: 'Devi studiare.', en: 'You have to study.' },
            { it: 'Dobbiamo mangiare.', en: 'We have to eat.' },
          ],
          patterns: ['dovere + infinitive: devo andare', 'devi studiare', 'dobbiamo mangiare'],
          note: 'Oggi devo andare al lavoro, ma voglio andare a casa presto. — devo → dovere (I have to), voglio → volere (I want).',
        },
      },
      {
        heading: 'Part 16 — Bere (to drink)',
        explanation:
          'Bere is short and irregular — the io form is bevo, not "io beno". You use it for anything you drink.',
        conjugation: {
          verb: 'bere',
          meaning: 'to drink',
          rows: [
            { p: 'io', f: 'bevo', example: 'Bevo il caffè.' },
            { p: 'tu', f: 'bevi', example: 'Bevi acqua?' },
            { p: 'lui/lei', f: 'beve', example: 'Lei beve il tè.' },
            { p: 'noi', f: 'beviamo', example: 'Beviamo insieme.' },
            { p: 'voi', f: 'bevete', example: 'Bevete vino?' },
            { p: 'loro', f: 'bevono', example: 'Loro bevono molto.' },
          ],
          examples: [
            { it: 'Bevo il caffè.', en: 'I drink coffee.' },
            { it: 'Bevi acqua?', en: 'Do you drink water?' },
          ],
        },
      },
      {
        heading: 'Part 17 — Irregular Verbs in Real Sentences',
        explanation:
          'Now stop thinking about tables. Read each sentence and notice which verb is conjugated — then say the same sentence about yourself.',
        examples: [
          { it: 'Sono a casa.', en: 'I am at home.' },
          { it: 'Siamo italiani.', en: 'We are Italian.' },
          { it: 'Ho fame.', en: 'I am hungry.' },
          { it: 'Hai tempo?', en: 'Do you have time?' },
          { it: 'Vado al lavoro.', en: 'I go to work.' },
          { it: 'Andiamo a Roma.', en: 'We are going to Rome.' },
          { it: 'Faccio colazione.', en: 'I have breakfast.' },
          { it: 'Cosa fai oggi?', en: 'What are you doing today?' },
          { it: 'Vengo con te.', en: 'I come with you.' },
          { it: 'Vieni a casa?', en: 'Are you coming home?' },
          { it: 'Posso entrare?', en: 'Can I come in?' },
          { it: 'Puoi aiutarmi?', en: 'Can you help me?' },
          { it: 'Voglio un caffè.', en: 'I want a coffee.' },
          { it: 'Devo lavorare.', en: 'I have to work.' },
          { it: 'Dobbiamo andare.', en: 'We have to go.' },
        ],
        note: 'Recognize the verb first (voglio → volere, devo → dovere, vado → andare), then the infinitive that follows a modal verb (voglio ANDARE, devo LAVORARE).',
      },
      {
        heading: 'Part 18 — Irregular Verb Pattern Groups',
        explanation:
          'Compare these verbs side by side. Notice how fare, dare, and stare are short, and how andare changes its stem. You do not need grammar terms — just notice the patterns.',
        conjugations: [
          {
            verb: 'andare',
            meaning: 'to go — stem changes to va-',
            rows: [
              { p: 'io', f: 'vado' },
              { p: 'tu', f: 'vai' },
              { p: 'lui/lei', f: 'va' },
              { p: 'noi', f: 'andiamo' },
              { p: 'voi', f: 'andate' },
              { p: 'loro', f: 'vanno' },
            ],
          },
          {
            verb: 'fare',
            meaning: 'to do / make',
            rows: [
              { p: 'io', f: 'faccio' },
              { p: 'tu', f: 'fai' },
              { p: 'lui/lei', f: 'fa' },
              { p: 'noi', f: 'facciamo' },
              { p: 'voi', f: 'fate' },
              { p: 'loro', f: 'fanno' },
            ],
          },
          {
            verb: 'dare',
            meaning: 'to give',
            rows: [
              { p: 'io', f: 'do' },
              { p: 'tu', f: 'dai' },
              { p: 'lui/lei', f: 'dà' },
              { p: 'noi', f: 'diamo' },
              { p: 'voi', f: 'date' },
              { p: 'loro', f: 'danno' },
            ],
          },
          {
            verb: 'stare',
            meaning: 'to stay / feel',
            rows: [
              { p: 'io', f: 'sto' },
              { p: 'tu', f: 'stai' },
              { p: 'lui/lei', f: 'sta' },
              { p: 'noi', f: 'stiamo' },
              { p: 'voi', f: 'state' },
              { p: 'loro', f: 'stanno' },
            ],
          },
        ],
        patterns: ['-ARE regular: parlo, parli, parla...', 'andare: vado, vai, va, andiamo, andate, vanno', 'fare / dare / stare: faccio/do/sto, fai/dai/stai, fa/dà/sta'],
        note: 'Spot the echoes: vado / faccio / do / sto all end in -o. And vai / fai / dai / stai rhyme in the tu form.',
      },
    ],
  },
];

export const irregolariExercises = [
  // ── LEVEL 1 — RECOGNITION ─────────────────────────────────────────
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Regular or Irregular?',
    instruction: 'For each verb form, decide whether the verb is regular or irregular in the present tense.',
    questions: [
      { question: '"parlo" (from parlare) is:', options: ['Regular', 'Irregular'], answer: 'Regular', explanation: 'Parlare follows the normal -are pattern: io parlo.' },
      { question: '"vado" (from andare) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'Andare changes its stem: io vado, not "io ando".' },
      { question: '"sono" (from essere) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'Essere is completely irregular: sono is a unique form.' },
      { question: '"mangi" (from mangiare) is:', options: ['Regular', 'Irregular'], answer: 'Regular', explanation: 'Mangiare follows the normal pattern: tu mangi.' },
      { question: '"faccio" (from fare) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'Fare uses a special form: io faccio.' },
      { question: '"viviamo" (from vivere) is:', options: ['Regular', 'Irregular'], answer: 'Regular', explanation: 'Vivere is regular in the present: noi viviamo.' },
      { question: '"posso" (from potere) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'Potere breaks the pattern: io posso.' },
      { question: '"bevi" (from bere) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'Bere has its own forms: tu bevi.' },
    ],
  },
  {
    id: 2,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Verb',
    instruction: 'Read each sentence and identify which infinitive verb is being used.',
    questions: [
      { question: '"Vado a Roma." — the verb is:', options: ['andare', 'essere', 'potere'], answer: 'andare', explanation: 'Vado comes from andare (to go).' },
      { question: '"Ho una macchina." — the verb is:', options: ['avere', 'andare', 'volere'], answer: 'avere', explanation: 'Ho comes from avere (to have).' },
      { question: '"Faccio colazione." — the verb is:', options: ['fare', 'dire', 'dare'], answer: 'fare', explanation: 'Faccio comes from fare (to do / make).' },
      { question: '"Vengo da Milano." — the verb is:', options: ['venire', 'andare', 'stare'], answer: 'venire', explanation: 'Vengo comes from venire (to come).' },
      { question: '"So parlare italiano." — the verb is:', options: ['sapere', 'dovere', 'potere'], answer: 'sapere', explanation: 'So comes from sapere (to know).' },
      { question: '"Sto bene." — the verb is:', options: ['stare', 'essere', 'avere'], answer: 'stare', explanation: 'Sto comes from stare (to stay / feel).' },
      { question: '"Dico la verità." — the verb is:', options: ['dire', 'dare', 'bere'], answer: 'dire', explanation: 'Dico comes from dire (to say / tell).' },
      { question: '"Esco alle otto." — the verb is:', options: ['uscire', 'salire', 'sapere'], answer: 'uscire', explanation: 'Esco comes from uscire (to go out).' },
    ],
  },
  {
    id: 3,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match Infinitive to Meaning',
    instruction: 'Match each verb with its meaning in English.',
    pairs: [
      { left: 'essere', right: 'to be' },
      { left: 'avere', right: 'to have' },
      { left: 'andare', right: 'to go' },
      { left: 'fare', right: 'to do / make' },
      { left: 'venire', right: 'to come' },
      { left: 'sapere', right: 'to know' },
      { left: 'potere', right: 'can / to be able to' },
      { left: 'volere', right: 'to want' },
      { left: 'dovere', right: 'must / to have to' },
    ],
  },
  {
    id: 4,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Person',
    instruction: 'Look at the verb form and identify the subject (who is doing it).',
    questions: [
      { question: '"Vogliamo andare." — the subject is:', options: ['noi', 'voi', 'loro'], answer: 'noi', explanation: '"vogliamo" = we want → noi.' },
      { question: '"Hai tempo." — the subject is:', options: ['tu', 'io', 'lui'], answer: 'tu', explanation: '"hai" = you have → tu.' },
      { question: '"Deve partire." — the subject is:', options: ['lui/lei', 'io', 'noi'], answer: 'lui/lei', explanation: '"deve" = he/she must → lui/lei.' },
      { question: '"Bevo il caffè." — the subject is:', options: ['io', 'lei', 'loro'], answer: 'io', explanation: '"bevo" = I drink → io.' },
      { question: '"Siete pronti?" — the subject is:', options: ['voi', 'noi', 'loro'], answer: 'voi', explanation: '"siete" = you (plural) are → voi.' },
      { question: '"Salgono sul treno." — the subject is:', options: ['loro', 'io', 'noi'], answer: 'loro', explanation: '"salgono" = they get on → loro.' },
      { question: '"Dici la verità." — the subject is:', options: ['tu', 'lui', 'io'], answer: 'tu', explanation: '"dici" = you say → tu.' },
      { question: '"Va a scuola." — the subject is:', options: ['lui/lei', 'tu', 'voi'], answer: 'lui/lei', explanation: '"va" = he/she goes → lui/lei.' },
    ],
  },
  {
    id: 5,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Find the Irregular Verb',
    instruction: 'Each sentence has two verbs. Choose the one that is IRREGULAR in the present tense.',
    questions: [
      { question: '"Io parlo e poi esco." — the irregular verb is:', options: ['esco', 'parlo'], answer: 'esco', explanation: 'Parlare is regular; uscire is irregular (io esco).' },
      { question: '"Noi mangiamo e beviamo." — the irregular verb is:', options: ['beviamo', 'mangiamo'], answer: 'beviamo', explanation: 'Mangiare is regular; bere has irregular forms.' },
      { question: '"Tu studi e fai sport." — the irregular verb is:', options: ['fai', 'studi'], answer: 'fai', explanation: 'Studiare is regular; fare is irregular (tu fai).' },
      { question: '"Loro vivono a Roma e vanno in ufficio." — the irregular verb is:', options: ['vanno', 'vivono'], answer: 'vanno', explanation: 'Vivere is regular here; andare is irregular (loro vanno).' },
      { question: '"Lei scrive e dice la verità." — the irregular verb is:', options: ['dice', 'scrive'], answer: 'dice', explanation: 'Scrivere follows the pattern; dire is irregular (lei dice).' },
      { question: '"Marco legge e ha un cane." — the irregular verb is:', options: ['ha', 'legge'], answer: 'ha', explanation: 'Leggere has a regular present; avere is irregular (lui ha).' },
    ],
  },

  // ── LEVEL 2 — CONJUGATION ─────────────────────────────────────────
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 2 — Conjugation',
    title: 'Essere',
    instruction: 'Complete each sentence with the correct form of essere.',
    questions: [
      { sentence: 'Io ___ italiano.', options: ['sono', 'sei', 'è', 'siamo'], answer: 'sono', explanation: 'io → sono.' },
      { sentence: 'Tu ___ stanco.', options: ['sei', 'sono', 'siete', 'siamo'], answer: 'sei', explanation: 'tu → sei.' },
      { sentence: 'Lei ___ italiana.', options: ['è', 'sei', 'sono', 'siamo'], answer: 'è', explanation: 'lui/lei → è.' },
      { sentence: 'Noi ___ amici.', options: ['siamo', 'sono', 'siete', 'sei'], answer: 'siamo', explanation: 'noi → siamo.' },
      { sentence: 'Voi ___ pronti?', options: ['siete', 'siamo', 'sono', 'sei'], answer: 'siete', explanation: 'voi → siete.' },
      { sentence: 'Loro ___ studenti.', options: ['sono', 'siamo', 'sei', 'è'], answer: 'sono', explanation: 'loro → sono.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 2 — Conjugation',
    title: 'Avere',
    instruction: 'Complete each sentence with the correct form of avere.',
    questions: [
      { sentence: 'Io ___ una macchina.', options: ['ho', 'hai', 'ha', 'hanno'], answer: 'ho', explanation: 'io → ho (the h is silent).' },
      { sentence: 'Tu ___ tempo?', options: ['hai', 'ho', 'ha', 'abbiamo'], answer: 'hai', explanation: 'tu → hai.' },
      { sentence: 'Lui ___ un cane.', options: ['ha', 'ho', 'hai', 'avete'], answer: 'ha', explanation: 'lui/lei → ha.' },
      { sentence: 'Noi ___ una casa.', options: ['abbiamo', 'hanno', 'avete', 'ho'], answer: 'abbiamo', explanation: 'noi → abbiamo.' },
      { sentence: 'Voi ___ fame?', options: ['avete', 'hanno', 'abbiamo', 'hai'], answer: 'avete', explanation: 'voi → avete.' },
      { sentence: 'Loro ___ due figli.', options: ['hanno', 'avete', 'abbiamo', 'ha'], answer: 'hanno', explanation: 'loro → hanno.' },
    ],
  },
  {
    id: 8,
    type: 'fillblank',
    level: 'Level 2 — Conjugation',
    title: 'Andare + Fare',
    instruction: 'Complete each sentence with andare or fare, as shown by the context.',
    questions: [
      { sentence: 'Io ___ a Roma.', options: ['vado', 'vai', 'va', 'vanno'], answer: 'vado', explanation: 'io + andare → vado.' },
      { sentence: 'Tu ___ a scuola?', options: ['vai', 'vado', 'va', 'andiamo'], answer: 'vai', explanation: 'tu + andare → vai.' },
      { sentence: 'Lui ___ al lavoro.', options: ['va', 'vado', 'vai', 'vanno'], answer: 'va', explanation: 'lui/lei + andare → va.' },
      { sentence: 'Noi ___ al ristorante.', options: ['andiamo', 'andate', 'vanno', 'va'], answer: 'andiamo', explanation: 'noi + andare → andiamo.' },
      { sentence: 'Loro ___ a casa.', options: ['vanno', 'vai', 'andate', 'va'], answer: 'vanno', explanation: 'loro + andare → vanno.' },
      { sentence: 'Io ___ colazione.', options: ['faccio', 'fai', 'fa', 'fanno'], answer: 'faccio', explanation: 'io + fare → faccio.' },
      { sentence: 'Che cosa ___ tu?', options: ['fai', 'faccio', 'fa', 'fate'], answer: 'fai', explanation: 'tu + fare → fai.' },
      { sentence: 'Lui ___ sport.', options: ['fa', 'faccio', 'fai', 'fanno'], answer: 'fa', explanation: 'lui/lei + fare → fa.' },
      { sentence: 'Noi ___ una pausa.', options: ['facciamo', 'fate', 'fanno', 'fa'], answer: 'facciamo', explanation: 'noi + fare → facciamo.' },
      { sentence: 'Loro ___ una torta.', options: ['fanno', 'fate', 'facciamo', 'fa'], answer: 'fanno', explanation: 'loro + fare → fanno.' },
    ],
  },
  {
    id: 9,
    type: 'fillblank',
    level: 'Level 2 — Conjugation',
    title: 'Stare + Dare',
    instruction: 'Complete with stare or dare. Pay special attention to "dà" vs "da".',
    questions: [
      { sentence: 'Io ___ bene.', options: ['sto', 'stai', 'sta', 'stiamo'], answer: 'sto', explanation: 'io + stare → sto.' },
      { sentence: 'Come ___ tu?', options: ['stai', 'sto', 'sta', 'state'], answer: 'stai', explanation: 'tu + stare → stai.' },
      { sentence: 'Lui ___ a casa.', options: ['sta', 'sto', 'stai', 'stanno'], answer: 'sta', explanation: 'lui/lei + stare → sta.' },
      { sentence: 'Noi ___ bene.', options: ['stiamo', 'sto', 'state', 'stanno'], answer: 'stiamo', explanation: 'noi + stare → stiamo.' },
      { sentence: 'Io ti ___ il libro.', options: ['do', 'dai', 'dà', 'diamo'], answer: 'do', explanation: 'io + dare → do.' },
      { sentence: 'Mi ___ un caffè?', options: ['dai', 'do', 'dà', 'date'], answer: 'dai', explanation: 'tu + dare → dai.' },
      { sentence: 'Lui ___ un regalo a Maria.', options: ['dà', 'da', 'dai', 'do'], answer: 'dà', explanation: 'lui/lei + dare → dà (with accent).' },
      { sentence: 'Noi ___ una mano.', options: ['diamo', 'date', 'danno', 'dà'], answer: 'diamo', explanation: 'noi + dare → diamo.' },
      { sentence: 'Vengo ___ Roma.', options: ['da', 'dà', 'di', 'a'], answer: 'da', explanation: '"da" without accent = from — it is a preposition.' },
      { sentence: 'Marco ___ un libro a Maria.', options: ['dà', 'da', 'dai', 'diamo'], answer: 'dà', explanation: '"dà" with accent = gives — it is the verb dare.' },
    ],
  },
  {
    id: 10,
    type: 'fillblank',
    level: 'Level 2 — Conjugation',
    title: 'Venire + Dire + Uscire',
    instruction: 'Complete each sentence with the correct irregular form.',
    questions: [
      { sentence: 'Io ___ da Roma.', options: ['vengo', 'vieni', 'viene', 'vengono'], answer: 'vengo', explanation: 'io + venire → vengo.' },
      { sentence: 'Tu ___ con me?', options: ['vieni', 'vengo', 'viene', 'venite'], answer: 'vieni', explanation: 'tu + venire → vieni.' },
      { sentence: 'Lei ___ domani.', options: ['viene', 'vengo', 'vieni', 'veniamo'], answer: 'viene', explanation: 'lui/lei + venire → viene.' },
      { sentence: 'Loro ___ da Milano.', options: ['vengono', 'venite', 'veniamo', 'viene'], answer: 'vengono', explanation: 'loro + venire → vengono.' },
      { sentence: 'Io ___ la verità.', options: ['dico', 'dici', 'dice', 'diciamo'], answer: 'dico', explanation: 'io + dire → dico.' },
      { sentence: 'Che cosa ___ tu?', options: ['dici', 'dico', 'dice', 'dicono'], answer: 'dici', explanation: 'tu + dire → dici.' },
      { sentence: 'Lui ___ di sì.', options: ['dice', 'dico', 'dici', 'dicono'], answer: 'dice', explanation: 'lui/lei + dire → dice.' },
      { sentence: 'Noi ___ la stessa cosa.', options: ['diciamo', 'dite', 'dicono', 'dice'], answer: 'diciamo', explanation: 'noi + dire → diciamo.' },
      { sentence: 'Io ___ alle otto.', options: ['esco', 'esci', 'esce', 'escono'], answer: 'esco', explanation: 'io + uscire → esco.' },
      { sentence: 'Tu ___ stasera?', options: ['esci', 'esco', 'esce', 'uscite'], answer: 'esci', explanation: 'tu + uscire → esci.' },
      { sentence: 'Lui ___ con gli amici.', options: ['esce', 'esco', 'esci', 'usciamo'], answer: 'esce', explanation: 'lui/lei + uscire → esce.' },
      { sentence: 'Loro ___ dal lavoro.', options: ['escono', 'uscite', 'usciamo', 'esce'], answer: 'escono', explanation: 'loro + uscire → escono.' },
    ],
  },

  // ── LEVEL 3 — MODAL VERBS ─────────────────────────────────────────
  {
    id: 11,
    type: 'fillblank',
    level: 'Level 3 — Modal Verbs',
    title: 'Potere',
    instruction: 'Complete each sentence with the correct form of potere.',
    questions: [
      { sentence: 'Io ___ parlare italiano.', options: ['posso', 'puoi', 'può', 'possiamo'], answer: 'posso', explanation: 'io + potere → posso.' },
      { sentence: 'Tu ___ aiutarmi?', options: ['puoi', 'posso', 'può', 'potete'], answer: 'puoi', explanation: 'tu + potere → puoi.' },
      { sentence: 'Lei ___ venire.', options: ['può', 'posso', 'puoi', 'possiamo'], answer: 'può', explanation: 'lui/lei + potere → può.' },
      { sentence: 'Noi ___ andare.', options: ['possiamo', 'possono', 'potete', 'posso'], answer: 'possiamo', explanation: 'noi + potere → possiamo.' },
      { sentence: 'Voi ___ aspettare?', options: ['potete', 'possono', 'possiamo', 'può'], answer: 'potete', explanation: 'voi + potere → potete.' },
      { sentence: 'Loro ___ parlare italiano.', options: ['possono', 'possiamo', 'potete', 'posso'], answer: 'possono', explanation: 'loro + potere → possono.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 3 — Modal Verbs',
    title: 'Volere',
    instruction: 'Complete each sentence with the correct form of volere.',
    questions: [
      { sentence: 'Io ___ un caffè.', options: ['voglio', 'vuoi', 'vuole', 'vogliamo'], answer: 'voglio', explanation: 'io + volere → voglio.' },
      { sentence: 'Tu ___ una pizza?', options: ['vuoi', 'voglio', 'vuole', 'volete'], answer: 'vuoi', explanation: 'tu + volere → vuoi.' },
      { sentence: 'Lui ___ andare a Roma.', options: ['vuole', 'voglio', 'vuoi', 'vogliono'], answer: 'vuole', explanation: 'lui/lei + volere → vuole.' },
      { sentence: 'Noi ___ mangiare.', options: ['vogliamo', 'vogliono', 'volete', 'vuole'], answer: 'vogliamo', explanation: 'noi + volere → vogliamo.' },
      { sentence: 'Voi ___ venire con noi?', options: ['volete', 'vogliamo', 'vogliono', 'vuoi'], answer: 'volete', explanation: 'voi + volere → volete.' },
      { sentence: 'Loro ___ partire.', options: ['vogliono', 'volete', 'vogliamo', 'vuole'], answer: 'vogliono', explanation: 'loro + volere → vogliono.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 3 — Modal Verbs',
    title: 'Dovere',
    instruction: 'Complete each sentence with the correct form of dovere.',
    questions: [
      { sentence: 'Io ___ lavorare oggi.', options: ['devo', 'devi', 'deve', 'dobbiamo'], answer: 'devo', explanation: 'io + dovere → devo.' },
      { sentence: 'Tu ___ studiare.', options: ['devi', 'devo', 'deve', 'dovete'], answer: 'devi', explanation: 'tu + dovere → devi.' },
      { sentence: 'Lei ___ partire.', options: ['deve', 'devo', 'devi', 'devono'], answer: 'deve', explanation: 'lui/lei + dovere → deve.' },
      { sentence: 'Noi ___ andare.', options: ['dobbiamo', 'devono', 'dovete', 'deve'], answer: 'dobbiamo', explanation: 'noi + dovere → dobbiamo.' },
      { sentence: 'Voi ___ aspettare.', options: ['dovete', 'devono', 'dobbiamo', 'devi'], answer: 'dovete', explanation: 'voi + dovere → dovete.' },
      { sentence: 'Loro ___ lavorare.', options: ['devono', 'dovete', 'dobbiamo', 'deve'], answer: 'devono', explanation: 'loro + dovere → devono.' },
    ],
  },
  {
    id: 14,
    type: 'multiple',
    level: 'Level 3 — Modal Verbs',
    title: 'Modal + Infinitive',
    instruction: 'Choose the correct modal-verb + infinitive combination.',
    questions: [
      { question: 'Io ___ andare a casa.', options: ['posso andare', 'posso ando', 'potere andare', 'posso vado'], answer: 'posso andare', explanation: 'Potere is followed by an infinitive: posso + andare.' },
      { question: 'Tu ___ mangiare?', options: ['puoi mangiare', 'puoi mangio', 'potere mangiare', 'puoi mangi'], answer: 'puoi mangiare', explanation: 'puoi + mangiare (infinitive).' },
      { question: 'Lei ___ venire.', options: ['può venire', 'può viene', 'potere venire', 'può vieni'], answer: 'può venire', explanation: 'può + venire (infinitive).' },
      { question: 'Noi ___ studiare.', options: ['dobbiamo studiare', 'dobbiamo studio', 'dovere studiare', 'dobbiamo studiamo'], answer: 'dobbiamo studiare', explanation: 'dobbiamo + studiare (infinitive).' },
      { question: 'Io ___ imparare l\'italiano.', options: ['voglio imparare', 'voglio imparo', 'volere imparare', 'voglio imparano'], answer: 'voglio imparare', explanation: 'voglio + imparare (infinitive).' },
      { question: '"Vuoi ___ con noi?" (to go out)', options: ['uscire', 'esci', 'esce', 'usciamo'], answer: 'uscire', explanation: 'Modal verbs take the infinitive: vuoi + uscire.' },
    ],
  },
  {
    id: 15,
    type: 'multiple',
    level: 'Level 3 — Modal Verbs',
    title: 'Mixed Modal Verbs',
    instruction: 'Read the English meaning and choose the correct modal verb in Italian.',
    questions: [
      { question: '"I have to work today." → Io ___ lavorare oggi.', options: ['devo', 'posso', 'voglio'], answer: 'devo', explanation: 'have to = dovere → devo.' },
      { question: '"Can you help me?" → Tu ___ aiutarmi?', options: ['puoi', 'vuoi', 'devi'], answer: 'puoi', explanation: 'can = potere → puoi.' },
      { question: '"I want a coffee." → Io ___ un caffè.', options: ['voglio', 'devo', 'posso'], answer: 'voglio', explanation: 'want = volere → voglio.' },
      { question: '"We can leave now." → Noi ___ partire ora.', options: ['possiamo', 'vogliamo', 'dobbiamo'], answer: 'possiamo', explanation: 'can = potere → possiamo.' },
      { question: '"She must study." → Lei ___ studiare.', options: ['deve', 'vuole', 'può'], answer: 'deve', explanation: 'must = dovere → deve.' },
      { question: '"Do you want to come?" → Tu ___ venire?', options: ['vuoi', 'puoi', 'devi'], answer: 'vuoi', explanation: 'want = volere → vuoi.' },
    ],
  },

  // ── LEVEL 4 — SENTENCE COMPLETION ─────────────────────────────────
  {
    id: 16,
    type: 'fillblank',
    level: 'Level 4 — Sentence Completion',
    title: 'Complete the Sentence',
    instruction: 'Complete each sentence with the missing irregular verb form.',
    questions: [
      { sentence: 'Io ___ italiano.', options: ['sono', 'ho', 'vado', 'faccio'], answer: 'sono', explanation: 'essere: io sono italiano.' },
      { sentence: 'Io ___ una macchina.', options: ['ho', 'sono', 'sto', 'voglio'], answer: 'ho', explanation: 'avere: io ho una macchina.' },
      { sentence: 'Domani io ___ a Roma.', options: ['vado', 'vengo', 'sto', 'faccio'], answer: 'vado', explanation: 'andare: io vado a Roma.' },
      { sentence: 'Oggi io ___ colazione alle otto.', options: ['faccio', 'fai', 'do', 'bevo'], answer: 'faccio', explanation: 'fare: io faccio colazione.' },
      { sentence: 'Io ___ da Roma.', options: ['vengo', 'vado', 'voglio', 'posso'], answer: 'vengo', explanation: 'venire: io vengo da Roma.' },
      { sentence: 'Io ___ parlare italiano.', options: ['posso', 'devo', 'voglio', 'so'], answer: 'posso', explanation: 'potere: io posso parlare italiano.' },
      { sentence: 'Io ___ un caffè.', options: ['voglio', 'devo', 'posso', 'sono'], answer: 'voglio', explanation: 'volere: io voglio un caffè.' },
      { sentence: 'Oggi io ___ lavorare.', options: ['devo', 'voglio', 'posso', 'so'], answer: 'devo', explanation: 'dovere: io devo lavorare.' },
    ],
  },
  {
    id: 17,
    type: 'multiple',
    level: 'Level 4 — Sentence Completion',
    title: 'Choose the Correct Form',
    instruction: 'Choose the form that matches the subject of each sentence.',
    questions: [
      { question: 'Marco ___ a Roma.', options: ['va', 'vado', 'vai', 'vanno'], answer: 'va', explanation: 'Marco = lui → va.' },
      { question: 'Noi ___ italiani.', options: ['siamo', 'sono', 'siete', 'sei'], answer: 'siamo', explanation: 'noi → siamo.' },
      { question: 'Loro ___ una casa.', options: ['hanno', 'ho', 'hai', 'abbiamo'], answer: 'hanno', explanation: 'loro → hanno.' },
      { question: 'Tu e Luca ___ al cinema stasera.', options: ['andate', 'vanno', 'andiamo', 'va'], answer: 'andate', explanation: 'tu e Luca = voi → andate.' },
      { question: 'Maria ___ un caffè.', options: ['vuole', 'vuoi', 'voglio', 'volete'], answer: 'vuole', explanation: 'Maria = lei → vuole.' },
      { question: 'Io e Marta ___ insieme.', options: ['usciamo', 'escono', 'esci', 'esce'], answer: 'usciamo', explanation: 'io e Marta = noi → usciamo.' },
    ],
  },
  {
    id: 18,
    type: 'fillblank',
    level: 'Level 4 — Sentence Completion',
    title: 'Subject + Verb',
    instruction: 'Conjugate the verb for the given subject.',
    questions: [
      { sentence: 'noi + fare → ___', options: ['facciamo', 'fate', 'fanno', 'faccio'], answer: 'facciamo', explanation: 'noi + fare → facciamo.' },
      { sentence: 'loro + venire → ___', options: ['vengono', 'venite', 'veniamo', 'viene'], answer: 'vengono', explanation: 'loro + venire → vengono.' },
      { sentence: 'tu + sapere → ___', options: ['sai', 'so', 'sa', 'sappiamo'], answer: 'sai', explanation: 'tu + sapere → sai.' },
      { sentence: 'io + bere → ___', options: ['bevo', 'beve', 'bevi', 'beviamo'], answer: 'bevo', explanation: 'io + bere → bevo.' },
      { sentence: 'voi + stare → ___', options: ['state', 'stanno', 'stiamo', 'sto'], answer: 'state', explanation: 'voi + stare → state.' },
      { sentence: 'lui + salire → ___', options: ['sale', 'salgo', 'sali', 'saliamo'], answer: 'sale', explanation: 'lui/lei + salire → sale.' },
    ],
  },
  {
    id: 19,
    type: 'multiple',
    level: 'Level 4 — Sentence Completion',
    title: 'Correct the Sentence',
    instruction: 'Choose the corrected version of each sentence.',
    questions: [
      { question: '"Io vai a Roma."', options: ['Io vado a Roma.', 'Io vai Roma.', 'Io va a Roma.', 'Io ando a Roma.'], answer: 'Io vado a Roma.', explanation: 'Andare is irregular: io vado, not "io vai".' },
      { question: '"Lei sono italiana."', options: ['Lei è italiana.', 'Lei sono italiano.', 'Lei sei italiana.', 'Lei è italiano.'], answer: 'Lei è italiana.', explanation: 'Lei = ella → è (essere).' },
      { question: '"Noi fa colazione."', options: ['Noi facciamo colazione.', 'Noi fa colazione.', 'Noi fai colazione.', 'Noi fanno colazione.'], answer: 'Noi facciamo colazione.', explanation: 'Noi + fare → facciamo.' },
      { question: '"Tu ho un cane."', options: ['Tu hai un cane.', 'Tu ho un cane.', 'Tu ha un cane.', 'Tu hanno un cane.'], answer: 'Tu hai un cane.', explanation: 'Tu + avere → hai.' },
      { question: '"Loro va al lavoro."', options: ['Loro vanno al lavoro.', 'Loro va al lavoro.', 'Loro vado al lavoro.', 'Loro vai al lavoro.'], answer: 'Loro vanno al lavoro.', explanation: 'Loro + andare → vanno.' },
    ],
  },
  {
    id: 20,
    type: 'multiple',
    level: 'Level 4 — Sentence Completion',
    title: 'Choose Based on Meaning',
    instruction: 'Read the English sentence and choose the correct Italian translation.',
    questions: [
      { question: '"I have to work."', options: ['Devo lavorare.', 'Posso lavorare.', 'Voglio lavorare.'], answer: 'Devo lavorare.', explanation: 'have to = dovere → devo lavorare.' },
      { question: '"I want to eat."', options: ['Voglio mangiare.', 'Devo mangiare.', 'Posso mangiare.'], answer: 'Voglio mangiare.', explanation: 'want = volere → voglio mangiare.' },
      { question: '"I can come."', options: ['Posso venire.', 'Voglio venire.', 'Devo venire.'], answer: 'Posso venire.', explanation: 'can = potere → posso venire.' },
      { question: '"I am Italian."', options: ['Sono italiano.', 'Ho italiano.', 'Sto italiano.'], answer: 'Sono italiano.', explanation: 'essere → sono italiano.' },
      { question: '"I have a car."', options: ['Ho una macchina.', 'Sono una macchina.', 'Ho uno macchina.'], answer: 'Ho una macchina.', explanation: 'avere → ho una macchina.' },
      { question: '"We are going to Rome."', options: ['Andiamo a Roma.', 'Veniamo a Roma.', 'Stiamo a Roma.'], answer: 'Andiamo a Roma.', explanation: 'andare in the noi form → andiamo a Roma.' },
    ],
  },

  // ── LEVEL 5 — SENTENCE BUILDING ───────────────────────────────────
  {
    id: 21,
    type: 'wordorder',
    level: 'Level 5 — Sentence Building',
    title: 'Put the Words in Order',
    instruction: 'Tap the words in the correct order to build each sentence.',
    questions: [
      { words: ['a', 'Roma', 'vado'], answer: 'Vado a Roma.', explanation: '"Vado a Roma." = I go (am going) to Rome.' },
      { words: ['alle', 'otto', 'esco'], answer: 'Esco alle otto.', explanation: '"Esco alle otto." = I go out at eight.' },
      { words: ['il', 'libro', 'ti', 'do'], answer: 'Ti do il libro.', explanation: '"Ti do il libro." = I give you the book.' },
      { words: ['italiano', 'parlare', 'posso'], answer: 'Posso parlare italiano.', explanation: 'Modal + infinitive: posso parlare italiano.' },
      { words: ['un', 'caffè', 'voglio'], answer: 'Voglio un caffè.', explanation: '"Voglio un caffè." = I want a coffee.' },
      { words: ['devo', 'lavorare', 'oggi'], answer: 'Oggi devo lavorare.', explanation: 'Dovere + infinitive: oggi devo lavorare.' },
    ],
  },
  {
    id: 22,
    type: 'wordorder',
    level: 'Level 5 — Sentence Building',
    title: 'Build a Sentence From Prompts',
    instruction: 'Use the given words to build the sentence for the prompt (subject + verb + object).',
    questions: [
      { words: ['una', 'macchina', 'hai'], answer: 'Hai una macchina.', explanation: 'Prompt: tu + avere + macchina → Hai una macchina.' },
      { words: ['Lui', 'colazione', 'fa'], answer: 'Lui fa colazione.', explanation: 'Prompt: lui + fare + colazione → Lui fa colazione.' },
      { words: ['dobbiamo', 'studiare'], answer: 'Dobbiamo studiare.', explanation: 'Prompt: noi + dovere + studiare → Dobbiamo studiare.' },
      { words: ['puoi', 'venire'], answer: 'Puoi venire.', explanation: 'Prompt: tu + potere + venire → Puoi venire.' },
      { words: ['è', 'Lui', 'stanco'], answer: 'Lui è stanco.', explanation: 'Prompt: lui + essere + stanco → Lui è stanco.' },
      { words: ['bevo', 'acqua'], answer: 'Bevo acqua.', explanation: 'Prompt: io + bere + acqua → Bevo acqua.' },
      { words: ['veniamo', 'da', 'Milano'], answer: 'Veniamo da Milano.', explanation: 'Prompt: noi + venire + da Milano → Veniamo da Milano.' },
    ],
  },
  {
    id: 23,
    type: 'text',
    level: 'Level 5 — Sentence Building',
    title: 'Change the Subject',
    instruction: 'Rewrite each sentence with the new subject. The verb form must change too.',
    questions: [
      { question: 'Cambia il soggetto a "noi": Io vado a Roma.', answer: 'Andiamo a Roma.', acceptedAnswers: ['andiamo a roma', 'noi andiamo a roma'], explanation: 'noi + andare → andiamo: "Andiamo a Roma."' },
      { question: 'Cambia il soggetto a "tu": Io sono stanco.', answer: 'Sei stanco?', acceptedAnswers: ['sei stanco', 'tu sei stanco'], explanation: 'tu + essere → sei: "(Tu) sei stanco."' },
      { question: 'Cambia il soggetto a "lui": Io faccio colazione.', answer: 'Lui fa colazione.', acceptedAnswers: ['lui fa colazione', 'fa colazione'], explanation: 'lui + fare → fa: "Lui fa colazione."' },
      { question: 'Cambia il soggetto a "voi": Io devo lavorare.', answer: 'Voi dovete lavorare.', acceptedAnswers: ['voi dovete lavorare', 'dovete lavorare'], explanation: 'voi + dovere → dovete: "Voi dovete lavorare."' },
      { question: 'Cambia il soggetto a "loro": Io vengo da Roma.', answer: 'Loro vengono da Roma.', acceptedAnswers: ['loro vengono da roma', 'vengono da roma'], explanation: 'loro + venire → vengono: "Loro vengono da Roma."' },
      { question: 'Cambia il soggetto a "noi": Io posso venire.', answer: 'Possiamo venire.', acceptedAnswers: ['possiamo venire', 'noi possiamo venire'], explanation: 'noi + potere → possiamo: "Possiamo venire."' },
    ],
  },
  {
    id: 24,
    type: 'text',
    level: 'Level 5 — Sentence Building',
    title: 'Make It Negative',
    instruction: 'Rewrite each sentence in the negative by adding "non" before the verb.',
    questions: [
      { question: 'Voglio un caffè.', answer: 'Non voglio un caffè.', acceptedAnswers: ['non voglio un caffè'], explanation: 'Negation goes before the verb: Non voglio un caffè.' },
      { question: 'Sono italiano.', answer: 'Non sono italiano.', acceptedAnswers: ['non sono italiano'], explanation: 'Non + sono → Non sono italiano.' },
      { question: 'Ho una macchina.', answer: 'Non ho una macchina.', acceptedAnswers: ['non ho una macchina'], explanation: 'Non + ho → Non ho una macchina.' },
      { question: 'Vado a Roma.', answer: 'Non vado a Roma.', acceptedAnswers: ['non vado a roma'], explanation: 'Non + vado → Non vado a Roma.' },
      { question: 'Posso venire.', answer: 'Non posso venire.', acceptedAnswers: ['non posso venire'], explanation: 'Non + posso → Non posso venire.' },
      { question: 'Devo lavorare oggi.', answer: 'Non devo lavorare oggi.', acceptedAnswers: ['non devo lavorare oggi'], explanation: 'Non + devo → Non devo lavorare oggi.' },
    ],
  },
  {
    id: 25,
    type: 'text',
    level: 'Level 5 — Sentence Building',
    title: 'Ask a Question',
    instruction: 'Turn each statement into a question. In Italian you can simply change the intonation.',
    questions: [
      { question: 'Tu hai tempo.', answer: 'Hai tempo?', acceptedAnswers: ['hai tempo', 'tu hai tempo'], explanation: 'Question: "Hai tempo?" — the verb comes first.' },
      { question: 'Tu vuoi un caffè.', answer: 'Vuoi un caffè?', acceptedAnswers: ['vuoi un caffè', 'tu vuoi un caffè'], explanation: 'Question: "Vuoi un caffè?"' },
      { question: 'Tu puoi venire.', answer: 'Puoi venire?', acceptedAnswers: ['puoi venire', 'tu puoi venire'], explanation: 'Question: "Puoi venire?"' },
      { question: 'Tu vai a scuola.', answer: 'Vai a scuola?', acceptedAnswers: ['vai a scuola', 'tu vai a scuola'], explanation: 'Question: "Vai a scuola?"' },
      { question: 'Tu sei stanco.', answer: 'Sei stanco?', acceptedAnswers: ['sei stanco', 'tu sei stanco'], explanation: 'Question: "Sei stanco?"' },
      { question: 'Tu vieni con me.', answer: 'Vieni con me?', acceptedAnswers: ['vieni con me', 'tu vieni con me'], explanation: 'Question: "Vieni con me?"' },
    ],
  },

  // ── LEVEL 6 — UNDERSTANDING ───────────────────────────────────────
  {
    id: 26,
    type: 'translation',
    level: 'Level 6 — Understanding',
    title: 'Italian → English',
    instruction: 'Read each Italian sentence and choose the best English meaning.',
    direction: 'it-en',
    questions: [
      { sentence: 'Devo andare al lavoro.', options: ['I have to go to work.', 'I want to go to work.', 'I can go to work.'], answer: 'I have to go to work.', explanation: 'devo → dovere (I have to).' },
      { sentence: 'Voglio imparare l\'italiano.', options: ['I want to learn Italian.', 'I must learn Italian.', 'I can speak Italian.'], answer: 'I want to learn Italian.', explanation: 'voglio → volere (I want).' },
      { sentence: 'Posso venire con te.', options: ['I can come with you.', 'I want to come with you.', 'I have to come with you.'], answer: 'I can come with you.', explanation: 'posso → potere (I can).' },
      { sentence: 'Sai parlare italiano?', options: ['Do you know how to speak Italian?', 'Do you want to speak Italian?', 'Do you have to speak English?'], answer: 'Do you know how to speak Italian?', explanation: 'sai → sapere (you know how).' },
      { sentence: 'Vengo da Milano.', options: ['I come from Milan.', 'I go to Milan.', 'I stay in Milan.'], answer: 'I come from Milan.', explanation: 'venire → to come: vengo da Milano.' },
      { sentence: 'Sto bene, grazie.', options: ['I am well, thank you.', 'I am in the sea, thank you.', 'She is tall, thank you.'], answer: 'I am well, thank you.', explanation: 'stare → to feel: sto bene.' },
      { sentence: 'Faccio colazione alle otto.', options: ['I have breakfast at eight.', 'I make coffee at eight.', 'I have dinner at eight.'], answer: 'I have breakfast at eight.', explanation: 'fare colazione → to have breakfast.' },
    ],
  },
  {
    id: 27,
    type: 'translation',
    level: 'Level 6 — Understanding',
    title: 'English → Italian',
    instruction: 'Choose the correct Italian translation for each English sentence.',
    direction: 'en-it',
    questions: [
      { sentence: 'I am Italian.', options: ['Sono italiano/a.', 'Ho italiano/a.', 'Sto italiano/a.'], answer: 'Sono italiano/a.', explanation: 'essere → sono.' },
      { sentence: 'I have a car.', options: ['Ho una macchina.', 'Sono una macchina.', 'Ho un cane.'], answer: 'Ho una macchina.', explanation: 'avere → ho.' },
      { sentence: 'I want a coffee.', options: ['Voglio un caffè.', 'Devo un caffè.', 'Posso un caffè.'], answer: 'Voglio un caffè.', explanation: 'volere → voglio.' },
      { sentence: 'I have to work.', options: ['Devo lavorare.', 'Voglio lavorare.', 'Lavoro devo.'], answer: 'Devo lavorare.', explanation: 'dovere → devo, then the infinitive lavorare.' },
      { sentence: 'I can come tomorrow.', options: ['Posso venire domani.', 'Voglio venire domani.', 'Devo venire domani.'], answer: 'Posso venire domani.', explanation: 'potere → posso.' },
      { sentence: 'She goes out at eight.', options: ['Lei esce alle otto.', 'Lei esce le otto.', 'Lei esco alle otto.'], answer: 'Lei esce alle otto.', explanation: 'lei + uscire → esce.' },
      { sentence: 'We want to eat.', options: ['Vogliamo mangiare.', 'Possiamo mangiare.', 'Dobbiamo mangiare.'], answer: 'Vogliamo mangiare.', explanation: 'noi + volere → vogliamo.' },
    ],
  },

  // ── LEVEL 7 — REAL-LIFE COMMUNICATION ─────────────────────────────
  {
    id: 28,
    type: 'story',
    level: 'Level 7 — Communication',
    title: 'Dialogue — Cosa facciamo oggi?',
    storyTitle: 'Cosa facciamo oggi?',
    story: 'Anna: Come stai?\n\nMarco: Sto bene, grazie. E tu?\n\nAnna: Non c\'è male. Cosa fai oggi?\n\nMarco: Oggi devo lavorare, ma voglio andare a casa presto.\n\nAnna: Hai tempo per un caffè?\n\nMarco: Sì, posso venire alle cinque. Dove andiamo?\n\nAnna: Andiamo al bar vicino a casa mia. Fanno un caffè buonissimo!\n\nMarco: Perfetto, vengo con te. Poi possiamo uscire stasera?\n\nAnna: Certo! Io esco alle otto. Vuoi mangiare qualcosa insieme?\n\nMarco: Sì, voglio andare al ristorante. Sai un posto buono?\n\nAnna: Sì, il ristorante di Giovanni. Ti dico sempre che è il migliore!\n\nMarco: Allora d\'accordo. Ti do il mio numero.',
    vocab: [
      { word: 'non c\'è male', meaning: 'not bad' },
      { word: 'presto', meaning: 'early' },
      { word: 'il bar', meaning: 'the café / bar' },
      { word: 'buonissimo', meaning: 'very good' },
      { word: 'il posto', meaning: 'the place' },
      { word: 'd\'accordo', meaning: 'agreed / OK' },
      { word: 'insieme', meaning: 'together' },
    ],
    translation: 'Anna: How are you?\n\nMarco: I am well, thanks. And you?\n\nAnna: Not bad. What are you doing today?\n\nMarco: Today I have to work, but I want to go home early.\n\nAnna: Do you have time for a coffee?\n\nMarco: Yes, I can come at five. Where are we going?\n\nAnna: Let\'s go to the café near my house. They make a delicious coffee!\n\nMarco: Perfect, I\'ll come with you. Then can we go out tonight?\n\nAnna: Of course! I go out at eight. Do you want to eat something together?\n\nMarco: Yes, I want to go to a restaurant. Do you know a good place?\n\nAnna: Yes, Giovanni\'s restaurant. I always tell you it\'s the best!\n\nMarco: Then it\'s agreed. I\'ll give you my number.',
    questions: [
      { question: 'How is Marco?', options: ['He is well', 'He is tired', 'He is not well'], answer: 'He is well', explanation: '"Sto bene, grazie." — stare for health.' },
      { question: 'What does Marco have to do today?', options: ['Work', 'Study', 'Cook'], answer: 'Work', explanation: '"Oggi devo lavorare" — devo → dovere (I have to).' },
      { question: 'Where do they go for coffee?', options: ['The café near Anna\'s house', 'The restaurant', 'The museum'], answer: 'The café near Anna\'s house', explanation: '"Andiamo al bar vicino a casa mia."' },
      { question: 'What time does Anna go out?', options: ['At eight (alle otto)', 'At five', 'At nine'], answer: 'At eight (alle otto)', explanation: '"Io esco alle otto." — uscire.' },
      { question: 'Which irregular verbs appear in "Vengo con te" and "Esco alle otto"?', options: ['venire, uscire', 'andare, fare', 'avere, essere'], answer: 'venire, uscire', explanation: 'vengo → venire, esco → uscire.' },
      { question: 'In "Posso venire alle cinque", the structure is:', options: ['potere + infinitive', 'venire + infinitive', 'essere + infinitive'], answer: 'potere + infinitive', explanation: 'posso (potere) + venire (infinitive).' },
      { question: 'Now try it yourself: Write a short invitation (2 questions in Italian) asking a friend to go out for a coffee.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: "Hai tempo? Vuoi prendere un caffè con me?" Any natural invitation is accepted.' },
    ],
  },

  // ── LEVEL 8 — STORY ───────────────────────────────────────────────
  {
    id: 29,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Story — La mia giornata',
    storyTitle: 'La mia giornata',
    story: 'Mi chiamo Anna e ogni giorno è sempre pieno. La mattina mi alzo alle sette, ho una colazione veloce e poi vado al lavoro in autobus. Al lavoro faccio molte cose: parlo con i colleghi e rispondo alle mail. A mezzogiorno ho fame e voglio mangiare qualcosa di buono, quindi vado in una piccola trattoria con i miei amici. Devo tornare al lavoro alle due, ma stiamo bene e ridiamo molto. La sera esco volentieri: o vengo a casa di Marco o andiamo al cinema insieme. Lo so che domani devo alzarmi presto, ma voglio godermi la serata. Alla fine torno a casa, posso fare una doccia veloce e vado a dormire. Sto con gli amici e mi sento felice.',
    vocab: [
      { word: 'pieno', meaning: 'full' },
      { word: 'mi alzo', meaning: 'I get up' },
      { word: 'la colazione', meaning: 'breakfast' },
      { word: 'i colleghi', meaning: 'colleagues' },
      { word: 'la mail', meaning: 'the email' },
      { word: 'la trattoria', meaning: 'simple restaurant' },
      { word: 'mi sento felice', meaning: 'I feel happy' },
    ],
    translation: 'My name is Anna and every day is always full. In the morning I get up at seven, I have a quick breakfast and then I go to work by bus. At work I do many things: I talk with my colleagues and answer emails. At noon I am hungry and want to eat something good, so I go to a small family restaurant with my friends. I have to get back to work at two, but we are fine and laugh a lot. In the evening I like to go out: either I come to Marco\'s house or we go to the cinema together. I know that tomorrow I have to get up early, but I want to enjoy the evening. In the end I come home, I can take a quick shower and I go to sleep. I am with my friends and I feel happy.',
    questions: [
      { question: 'How does Anna get to work?', options: ['By bus', 'By car', 'On foot'], answer: 'By bus', explanation: '"vado al lavoro in autobus."' },
      { question: 'What does Anna do at work?', options: ['She talks with colleagues and answers emails', 'She sleeps', 'She makes coffee'], answer: 'She talks with colleagues and answers emails', explanation: '"parlo con i colleghi e rispondo alle mail."' },
      { question: 'Why must Anna get up early tomorrow?', options: ['She has to work', 'She wants to relax', 'She goes on holiday'], answer: 'She has to work', explanation: '"domani devo alzarmi presto" — devo + infinitive.' },
      { question: 'Which irregular verb means "I know (how)"?', options: ['so', 'vado', 'voglio'], answer: 'so', explanation: '"Lo so che domani devo alzarmi presto" — so → sapere.' },
      { question: 'Noi ___ bene e ridiamo molto.', options: ['stiamo', 'sto', 'stai', 'state'], answer: 'stiamo', explanation: 'noi + stare → stiamo.' },
      { question: '"Devo tornare al lavoro alle due" means:', options: ['I have to go back to work at two', 'I want to go back to work at two', 'I can go back to work at two'], answer: 'I have to go back to work at two', explanation: 'devo → dovere (I have to) + tornare (infinitive).' },
      { question: 'Now try it yourself: Write two sentences (in Italian) about YOUR daily routine using "faccio" and "vado".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: "La mattina faccio colazione. Poi vado a scuola." Any correct sentences are accepted.' },
    ],
  },

  // ── LEVEL 8 — STORIES (additional) ───────────────────────────────────
  {
    id: 31,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Story — La mattina di Marco',
    storyTitle: 'La mattina di Marco',
    story: 'Marco si sveglia presto. Ogni mattina si alza alle sei e mezza, fa una doccia veloce e beve un espresso. Dice sempre: "Il caffè mi dà energia!"\n\nPoi prende la sua bicicletta e va al lavoro. Marco fa il cuoco in un ristorante del centro. Al lavoro sa sempre cosa fare: prepara le verdure, taglia il pesce e cucina le zuppe.\n\nAlle sette e mezza finisce e viene a casa. Vuole vedere una partita in televisione, ma è molto stanco. Così dice a sua moglie: "Stasera posso solo dormire!"',
    vocab: [
      { word: 'si alza', meaning: 'he gets up (alzarsi)' },
      { word: 'beve', meaning: 'he drinks (bere)' },
      { word: 'dà', meaning: 'he gives (dare)' },
      { word: 'sa', meaning: 'he knows (sapere)' },
      { word: 'viene', meaning: 'he comes (venire)' },
      { word: 'vuole', meaning: 'he wants (volere)' },
      { word: 'posso', meaning: 'I can (potere)' },
    ],
    translation: 'Marco wakes up early. Every morning he gets up at six thirty, takes a quick shower and drinks an espresso. He always says: "Coffee gives me energy!"\n\nThen he takes his bicycle and goes to work. Marco works as a cook in a restaurant in the centre. At work he always knows what to do: he prepares the vegetables, cuts the fish and cooks the soups.\n\nAt seven thirty he finishes and comes home. He wants to watch a match on television, but he is very tired. So he says to his wife: "Tonight I can only sleep!"',
    questions: [
      { question: 'What time does Marco get up?', options: ['At six thirty', 'At seven', 'At eight'], answer: 'At six thirty', explanation: '"si alza alle sei e mezza."' },
      { question: 'What is Marco\'s job?', options: ['He is a cook', 'He is a teacher', 'He is a doctor'], answer: 'He is a cook', explanation: '"Marco fa il cuoco in un ristorante."' },
      { question: 'What does Marco always say about coffee?', options: ['"Coffee gives me energy!"', '"Coffee is too bitter!"', '"I drink it only in winter!"'], answer: '"Coffee gives me energy!"', explanation: '"Il caffè mi dà energia!"' },
      { question: '"Dice sempre" — "dice" is the present of which verb?', options: ['dire', 'dare', 'fare'], answer: 'dire', explanation: 'io dico, tu dici, lui dice — dire (to say/tell).' },
      { question: '"beve un espresso" — "beve" is the present of...?', options: ['bere', 'vedere', 'arrivare'], answer: 'bere', explanation: 'io bevo, tu bevi, lui/lei beve — bere (to drink), irregular.' },
      { question: 'Choose the correct irregular verb: "Marco ___ vedere la partita." (he wants)', options: ['vuole', 'sa', 'va'], answer: 'vuole', explanation: 'volere (to want): io voglio, lui vuole.' },
      { question: 'Write one sentence about your morning routine using at least two irregular verbs (andare, fare, bere, essere, ...).', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Mi alzo presto, bevo il caffè e vado al lavoro. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 32,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Dialogue — Al ristorante',
    storyTitle: 'Al ristorante',
    story: 'Anna e Luca vanno al ristorante di Giovanni.\n\nAnna: Che bello! Vengo qui ogni sabato.\n\nLuca: Io no. Posso venire solo una volta al mese. Sai, il lavoro è sempre tanto.\n\nAnna: Vuoi dell\'acqua o del vino?\n\nLuca: Bevo dell\'acqua, per favore. Oggi devo guidare.\n\nAnna: Io invece bevo un buon bicchiere di vino rosso. Mi piace rilassarmi.\n\nIl cameriere viene al tavolo e dice: "Oggi il pesce è perfetto!"\n\nAnna: Allora prendiamo il pesce. Luca, sei d\'accordo?\n\nLuca: Sì, va benissimo. E alla fine dobbiamo assolutamente provare il tiramisù!',
    vocab: [
      { word: 'vengo', meaning: 'I come (venire)' },
      { word: 'posso', meaning: 'I can (potere)' },
      { word: 'sai', meaning: 'you know (sapere)' },
      { word: 'vuoi', meaning: 'you want (volere)' },
      { word: 'bevo', meaning: 'I drink (bere)' },
      { word: 'devo', meaning: 'I must (dovere)' },
      { word: 'dobbiamo', meaning: 'we must (dovere)' },
    ],
    translation: 'Anna and Luca go to Giovanni\'s restaurant.\n\nAnna: How lovely! I come here every Saturday.\n\nLuca: Not me. I can only come once a month. You know, work is always a lot.\n\nAnna: Do you want some water or some wine?\n\nLuca: I drink water, please. Today I have to drive.\n\nAnna: I instead drink a good glass of red wine. I like to relax.\n\nThe waiter comes to the table and says: "Today the fish is perfect!"\n\nAnna: Then we will take the fish. Luca, do you agree?\n\nLuca: Yes, that is fine. And in the end we absolutely must try the tiramisù!',
    questions: [
      { question: 'How often can Luca come to the restaurant?', options: ['Once a month', 'Every Saturday', 'Every day'], answer: 'Once a month', explanation: '"Posso venire solo una volta al mese."' },
      { question: 'Why does Luca drink water?', options: ['Because he has to drive today', 'Because he does not like wine', 'Because wine is expensive'], answer: 'Because he has to drive today', explanation: '"Oggi devo guidare." — dovere + infinitive.' },
      { question: 'What does the waiter say about the fish?', options: ['"Today the fish is perfect!"', '"Today the fish is sold out!"', '"The fish is too expensive!"'], answer: '"Today the fish is perfect!"', explanation: '"Oggi il pesce è perfetto!"' },
      { question: 'What must they absolutely try at the end?', options: ['The tiramisù', 'The panna cotta', 'The cake'], answer: 'The tiramisù', explanation: '"dobbiamo assolutamente provare il tiramisù!"' },
      { question: 'Which irregular verb means "I can"?', options: ['posso', 'sai', 'devo'], answer: 'posso', explanation: 'potere → io posso, tu puoi, lui/lei può (I can).' },
      { question: '"Bevo dell\'acqua" — "bevo" is the present of...?', options: ['bere', 'bere', 'avere'], answer: 'bere', explanation: 'bere (to drink): io bevo, tu bevi, lui beve.' },
      { question: 'Write a short sentence offering a drink to a friend, using one of these verbs: vuoi, bevi, prendi.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vuoi dell\'acqua? / Bevi qualcosa? Any natural sentence is accepted.' },
    ],
  },
  {
    id: 33,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Story — Una gita al lago',
    storyTitle: 'Una gita al lago',
    story: 'Questo sabato vogliamo fare una gita al lago. La mia famiglia sa già cosa portare. "Io preparo i panini e mia madre fa la torta," dice mio padre.\n\nMio fratello deve comprare l\'acqua, mentre io posso portare la radio e le sedie. Mia sorella non può venire perché deve studiare.\n\nCi alziamo presto e partiamo alle sette. Papà va in macchina e noi cantiamo. Che gioia! Al lago facciamo un bagno e mangiamo tutto. Poi torniamo a casa e… io sono stanchissimo!',
    vocab: [
      { word: 'vogliamo', meaning: 'we want (volere)' },
      { word: 'sa', meaning: 'he/she knows (sapere)' },
      { word: 'deve', meaning: 'he/she must (dovere)' },
      { word: 'posso', meaning: 'I can (potere)' },
      { word: 'può', meaning: 'he/she can (potere)' },
      { word: 'va', meaning: 'he goes (andare)' },
    ],
    translation: 'This Saturday we want to take a trip to the lake. My family already knows what to bring. "I prepare the sandwiches and my mother makes the cake," says my father.\n\nMy brother has to buy the water, while I can bring the radio and the chairs. My sister cannot come because she has to study.\n\nWe get up early and leave at seven. Dad goes by car and we sing. What joy! At the lake we take a swim and eat everything. Then we return home and… I am exhausted!',
    questions: [
      { question: 'What do they want to do this Saturday?', options: ['Go on a trip to the lake', 'Go to the beach', 'Visit a museum'], answer: 'Go on a trip to the lake', explanation: '"Questo sabato vogliamo fare una gita al lago."' },
      { question: 'Who makes the cake?', options: ['The mother', 'The father', 'The sister'], answer: 'The mother', explanation: '"mia madre fa la torta." — fare.' },
      { question: 'Why can\'t the sister come?', options: ['Because she must study', 'Because she is tired', 'Because she is at work'], answer: 'Because she must study', explanation: '"Mia sorella non può venire perché deve studiare."' },
      { question: 'What must the brother do?', options: ['Buy the water', 'Bring the radio', 'Make the sandwiches'], answer: 'Buy the water', explanation: '"Mio fratello deve comprare l\'acqua."' },
      { question: '"vogliamo" is the present of which verb?', options: ['volere', 'dovere', 'potere'], answer: 'volere', explanation: 'volere (to want): noi vogliamo.' },
      { question: 'Choose the correct irregular verb: "Mio fratello ___ comprare l\'acqua." (he has to)', options: ['deve', 'va', 'sa'], answer: 'deve', explanation: 'dovere (must): io devo, lui deve.' },
      { question: 'Write one sentence about a trip you want to take, using "voglio" or "vogliamo".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vogliamo andare in montagna. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 34,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Dialogue — Un consiglio',
    storyTitle: 'Un consiglio',
    story: 'Marco: Ho un problema. Il mio computer non va più veloce.\n\nGiulia: Hai provato a spegnerlo?\n\nMarco: Sì, ma non serve. Non so cosa fare.\n\nGiulia: Hai chiesto a Luigi? Lui sa tutto sui computer.\n\nMarco: Giusto! Ma come lo trovo?\n\nGiulia: Ti do il suo numero. Però devi chiamarlo subito: domani parte!\n\nMarco: Perfetto! Posso chiamarlo ora?\n\nGiulia: Sì, ora è libero. Vai pure!\n\nMarco: Grazie mille! Dopo ti offro un caffè.\n\nGiulia: Un caffè? Ma io bevo solo tè! E di solito sto a casa la sera.',
    vocab: [
      { word: 'non va', meaning: 'it does not go / work (andare)' },
      { word: 'so', meaning: 'I know (sapere)' },
      { word: 'sa', meaning: 'he knows (sapere)' },
      { word: 'ti do', meaning: 'I give you (dare)' },
      { word: 'devi', meaning: 'you must (dovere)' },
      { word: 'posso', meaning: 'I can (potere)' },
      { word: 'bevo', meaning: 'I drink (bere)' },
    ],
    translation: 'Marco: I have a problem. My computer is no longer fast.\n\nGiulia: Did you try turning it off?\n\nMarco: Yes, but it does not help. I do not know what to do.\n\nGiulia: Did you ask Luigi? He knows everything about computers.\n\nMarco: Right! But how do I find him?\n\nGiulia: I will give you his number. But you have to call him immediately: tomorrow he leaves!\n\nMarco: Perfect! Can I call him now?\n\nGiulia: Yes, now he is free. Go ahead!\n\nMarco: Thanks a lot! Afterwards I will offer you a coffee.\n\nGiulia: A coffee? But I only drink tea! And usually I stay at home in the evening.',
    questions: [
      { question: 'What is Marco\'s problem?', options: ['His computer is slow', 'He lost his phone', 'He cannot sleep'], answer: 'His computer is slow', explanation: '"Il mio computer non va più veloce."' },
      { question: 'Who knows everything about computers?', options: ['Luigi', 'Marco', 'Giulia'], answer: 'Luigi', explanation: '"Lui sa tutto sui computer."' },
      { question: 'Why must Marco call Luigi immediately?', options: ['Because he leaves tomorrow', 'Because it is too late tonight', 'Because the phone is closed'], answer: 'Because he leaves tomorrow', explanation: '"devi chiamarlo subito: domani parte!"' },
      { question: 'What does Giulia drink instead of coffee?', options: ['Tea', 'Juice', 'Milk'], answer: 'Tea', explanation: '"io bevo solo tè!"' },
      { question: '"Non so cosa fare" — "so" is the present of which verb?', options: ['sapere', 'avere', 'venire'], answer: 'sapere', explanation: 'sapere (to know): io so, tu sai, lui/lei sa.' },
      { question: '"Ti do il suo numero" — "do" is the present of...?', options: ['dare', 'dire', 'fare'], answer: 'dare', explanation: 'dare (to give): io do, tu dai, lui/lei dà.' },
      { question: 'Write one sentence where you give a piece of advice using "devi" + an infinitive.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Devi riposare di più. / Devi chiamarlo domani. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 35,
    type: 'story',
    level: 'Level 8 — Story',
    title: 'Read and Answer in Italian — La mia domenica',
    storyTitle: 'La mia domenica',
    story: 'La domenica mi sveglio tardi e vorrei dormire ancora, ma devo aiutare in casa. Mia madre dice: "Per favore, vai a comprare il pane!"\n\nIo vado al panificio e faccio la fila. Davanti a me c\'è un signore che beve il caffè e legge il giornale. Al ritorno trovo mio padre in giardino: dice che vuole piantare dei fiori, ma non sa dove metterli.\n\nIo ho una buona idea: "Possiamo metterli vicino alla finestra!" Papà è contento. La sera ognuno può scegliere il suo film preferito. Io non esco, sto a casa e mi riposo: domani ritornerò al lavoro!',
    vocab: [
      { word: 'vorrei', meaning: 'I would like (conditional of volere)' },
      { word: 'vai', meaning: 'you go (andare)' },
      { word: 'faccio', meaning: 'I do/make (fare)' },
      { word: 'vuole', meaning: 'he wants (volere)' },
      { word: 'posso / può', meaning: 'I / he can (potere)' },
      { word: 'esco', meaning: 'I go out (uscire)' },
      { word: 'sto', meaning: 'I stay (stare)' },
    ],
    translation: 'On Sunday I wake up late and I would like to sleep more, but I have to help at home. My mother says: "Please, go and buy the bread!"\n\nI go to the bakery and queue. In front of me there is a man who drinks his coffee and reads the newspaper. On my way back I find my father in the garden: he says he wants to plant flowers, but he does not know where to put them.\n\nI have a good idea: "We can put them near the window!" Dad is happy. In the evening everyone can choose his favourite film. I do not go out, I stay at home and rest: tomorrow I will go back to work!',
    questions: [
      { question: 'Cosa deve fare chi racconta la domenica? (What must the narrator do on Sunday?)', type: 'text', acceptedAnswers: ['aiutare in casa', 'deve aiutare in casa', 'andare a comprare il pane', 'aiutare la madre'], answer: 'Deve aiutare in casa e andare a comprare il pane.', explanation: 'The story says: "devo aiutare in casa" and "vai a comprare il pane!"' },
      { question: 'Cosa dice la madre? (What does the mother say?)', type: 'text', acceptedAnswers: ['vai a comprare il pane', 'per favore vai a comprare il pane', 'va a comprare il pane', 'andare a comprare il pane'], answer: '"Per favore, vai a comprare il pane!"', explanation: 'The mother says: "Per favore, vai a comprare il pane!"' },
      { question: 'Cosa fa il signore davanti al panificio? (What does the man in front of the bakery do?)', type: 'text', acceptedAnswers: ['beve il caffè e legge il giornale', 'beve il caffè', 'legge il giornale', 'beve il caffè e legge il giornale insieme'], answer: 'Beve il caffè e legge il giornale.', explanation: 'The story says: "beve il caffè e legge il giornale."' },
      { question: 'Cosa vuole piantare il padre? (What does the father want to plant?)', type: 'text', acceptedAnswers: ['dei fiori', 'vuole piantare dei fiori', 'piantare dei fiori', 'i fiori'], answer: 'Vuole piantare dei fiori.', explanation: 'The story says: "vuole piantare dei fiori."' },
      { question: 'Dove possono mettere i fiori? (Where can they put the flowers?)', type: 'text', acceptedAnswers: ['vicino alla finestra', 'vicino alla finestra', 'sopra la finestra', 'nella finestra'], answer: 'Possono metterli vicino alla finestra.', explanation: 'The story says: "Possiamo metterli vicino alla finestra!"' },
      { question: 'Cosa fa chi racconta la sera? (What does the narrator do in the evening?)', type: 'text', acceptedAnswers: ['non esce e sta a casa', 'sta a casa', 'sta a casa e si riposa', 'si riposa', 'non esco', 'resta a casa'], answer: 'Non esce, sta a casa e si riposa.', explanation: 'The story says: "Io non esco, sto a casa e mi riposo."' },
      { question: 'Trova tre verbi irregolari nella storia. (Find three irregular verbs in the story.)', type: 'text', acceptedAnswers: [], answer: 'Any three, e.g. vado (andare), faccio (fare), beve (bere), so (sapere), posso (potere), esco (uscire), sto (stare), vuole (volere), devo (dovere), ho (avere).', explanation: 'Examples: vado, faccio, beve, so, posso, esco, sto, vuole, devo, ho.' },
    ],
  },
  // ── LEVEL 9 — FINAL PROFICIENCY TEST ──────────────────────────────
  {
    id: 30,
    type: 'mastery',
    level: 'Level 9 — Final Proficiency Test',
    title: 'Irregular Present Tense Mastery Test',
    instruction: 'Answer all the questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Recognition
      { question: '"beviamo" (from bere) is:', options: ['Irregular', 'Regular'], answer: 'Irregular', explanation: 'bere has its own forms: io bevo.' },
      { question: '"Avete fame?" — the subject is:', options: ['voi', 'noi', 'loro'], answer: 'voi', explanation: '"avete" = you (plural) → voi.' },
      // Essere, Avere, Andare, Fare, Stare, Dare, Dire
      { question: 'Noi ___ italiani.', options: ['siamo', 'sono', 'siete'], answer: 'siamo', explanation: 'noi + essere → siamo.' },
      { question: 'Luigi ___ due fratelli.', options: ['ha', 'hai', 'ho'], answer: 'ha', explanation: 'lui/lei + avere → ha.' },
      { question: 'I bambini ___ a scuola.', options: ['vanno', 'va', 'vai'], answer: 'vanno', explanation: 'loro + andare → vanno.' },
      { question: 'Che cosa ___ tu?', options: ['fai', 'faccio', 'fa'], answer: 'fai', explanation: 'tu + fare → fai.' },
      { question: 'Come ___ oggi?', options: ['stai', 'sto', 'sta'], answer: 'stai', explanation: 'tu + stare → stai.' },
      { question: 'Maria ___ un regalo a sua madre. (gives)', options: ['dà', 'da', 'di'], answer: 'dà', explanation: '"dà" (accent) = gives; "da" = from.' },
      { question: 'Loro ___ che è facile.', options: ['dicono', 'dice', 'diciamo'], answer: 'dicono', explanation: 'loro + dire → dicono.' },
      // Venire, Uscire, Salire, Sapere, Modals, Bere
      { question: 'Tu ___ con me stasera?', options: ['vieni', 'viene', 'vengo'], answer: 'vieni', explanation: 'tu + venire → vieni.' },
      { question: 'Io ___ alle otto.', options: ['esco', 'esce', 'esci'], answer: 'esco', explanation: 'io + uscire → esco.' },
      { question: 'Loro ___ sul treno.', options: ['salgono', 'sale', 'saliamo'], answer: 'salgono', explanation: 'loro + salire → salgono.' },
      { question: 'Io non ___ la risposta.', options: ['so', 'sai', 'sa'], answer: 'so', explanation: 'io + sapere → so.' },
      { question: '(tu) ___ parlare italiano?', options: ['Puoi', 'Posso', 'Può'], answer: 'Puoi', explanation: 'tu + potere → puoi.' },
      { question: 'Loro ___ comprare una casa.', options: ['vogliono', 'vuole', 'volete'], answer: 'vogliono', explanation: 'loro + volere → vogliono.' },
      { question: 'Noi ___ studiare ogni giorno.', options: ['dobbiamo', 'devono', 'dovete'], answer: 'dobbiamo', explanation: 'noi + dovere → dobbiamo.' },
      { question: 'Io ___ il caffè ogni mattina.', options: ['bevo', 'beve', 'bevono'], answer: 'bevo', explanation: 'io + bere → bevo.' },
      // Meanings
      { question: '"Siamo amici" means:', options: ['We are friends.', 'I am a friend.', 'They are friends.'], answer: 'We are friends.', explanation: 'siamo = we are.' },
      // Confusions
      { question: 'Vuoi il tè ___ il caffè? (or)', options: ['o', 'ho', 'a'], answer: 'o', explanation: '"o" = or; "ho" = I have.' },
      { question: 'Maria ___ una macchina e va ___ Roma.', options: ['ha, a', 'a, ha', 'ha, o'], answer: 'ha, a', explanation: '"ha" = has (avere); "a" = to (preposition).' },
      { question: 'Marco ___ italiano ___ abita a Roma. (is / and)', options: ['è, e', 'e, è', 'è, è'], answer: 'è, e', explanation: '"è" = is; "e" = and.' },
      // Modal + infinitive + negative + correction + order
      { question: '"Voglio ___ a casa." (to go)', options: ['andare', 'vado', 'ando'], answer: 'andare', explanation: 'volere + infinitive: voglio andare a casa.' },
      { question: '"Non voglio un caffè" means:', options: ['I do not want a coffee.', 'I want two coffees.', 'I never drink coffee.'], answer: 'I do not want a coffee.', explanation: 'non + verb = negative.' },
      { question: 'Which sentence is correct?', options: ['Lui va al lavoro.', 'Lui vado al lavoro.', 'Lui vai al lavoro.'], answer: 'Lui va al lavoro.', explanation: 'lui + andare → va.' },
      { question: 'Choose the correct order: "a / Roma / vado"', options: ['Vado a Roma.', 'a Vado Roma.', 'Vado Roma a.'], answer: 'Vado a Roma.', explanation: 'Vado a Roma.' },
      // Reading passage (Story 3 — "Una giornata in città")
      { question: 'READ FIRST: "Oggi è sabato e Anna va in città con Marco e Luca. È una bella giornata di sole. Anna ha un\'idea: «Andiamo al mercato in piazza.» Marco dice che è d\'accordo, ma Luca ha fame e vuole mangiare subito. Allora vanno in una pasticceria vicino al mercato. Luca beve un caffè e mangia un dolce, Anna beve un succo d\'arancia e Marco prende un tè. Poi vogliono visitare il museo, ma il biglietto è caro. Marco deve tornare a casa presto perché domani ha molto lavoro, quindi dicono di incontrarsi di nuovo fra due giorni. Anna sale sul tram e va all\'università; Luca viene con lei perché deve comprare dei libri. In libreria scelgono un libro insieme e fanno una lunga chiacchierata. Alla fine Anna dice: «Stasera esco con Giulia, volete venire anche voi?» Marco vorrebbe ma deve lavorare; Luca può. «Allora ci vediamo alle otto!» Anna è felice: una giornata in città è sempre speciale."\n\nWhat is Anna\'s idea?', options: ['Go to the market in the square', 'Go to the museum', 'Buy a book'], answer: 'Go to the market in the square', explanation: '"«Andiamo al mercato in piazza.»"' },
      { question: 'READ AGAIN: Why do they NOT visit the museum?', options: ['The ticket is expensive', 'It is closed', 'They are tired'], answer: 'The ticket is expensive', explanation: '"il biglietto è caro."' },
      { question: 'READ AGAIN: "Anna sale sul tram" — "sale" comes from:', options: ['salire', 'scendere', 'saltare'], answer: 'salire', explanation: 'salire → io salgo, lui/lei sale.' },
      { question: 'READ AGAIN: Who can go out with the group in the evening?', options: ['Luca', 'Marco', 'Neither'], answer: 'Luca', explanation: '"Marco vorrebbe ma deve lavorare; Luca può."' },
      // Independent production (5 questions)
      { question: 'Write "I want to eat" in Italian:', type: 'text', answer: 'Voglio mangiare', acceptedAnswers: ['voglio mangiare'] },
      { question: 'Write "I have to work today" in Italian:', type: 'text', answer: 'Devo lavorare oggi', acceptedAnswers: ['devo lavorare oggi', 'oggi devo lavorare'] },
      { question: 'Write "I can speak Italian" in Italian:', type: 'text', answer: 'Posso parlare italiano', acceptedAnswers: ['posso parlare italiano'] },
      { question: 'Write one sentence (in Italian) using "sono" (essere).', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Sono italiano/a. Any correct sentence is accepted.' },
      { question: 'Write one question (in Italian) using "vuoi" (volere).', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vuoi un caffè? Any natural question is accepted.' },
    ],
  },
];

export const irregolariFinalTest = irregolariExercises.find((e) => e.id === 30).questions;

export const irregolariFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You can confidently use the most common irregular present-tense verbs.' },
  { min: 75, grade: 'Very good!', message: 'You understand the main irregular verbs. Review the forms you missed.' },
  { min: 60, grade: 'Almost there!', message: 'Review the core verbs and practice them in complete sentences.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the conjugations and everyday examples before taking the final test again.' },
];

export const irregolariReview = [
  { verb: 'essere', meaning: 'to be', forms: ['sono', 'sei', 'è', 'siamo', 'siete', 'sono'], example: 'Sono italiano.', translation: 'I am Italian.' },
  { verb: 'avere', meaning: 'to have', forms: ['ho', 'hai', 'ha', 'abbiamo', 'avete', 'hanno'], example: 'Ho una macchina.', translation: 'I have a car.' },
  { verb: 'andare', meaning: 'to go', forms: ['vado', 'vai', 'va', 'andiamo', 'andate', 'vanno'], example: 'Vado a Roma.', translation: 'I go to Rome.' },
  { verb: 'fare', meaning: 'to do / make', forms: ['faccio', 'fai', 'fa', 'facciamo', 'fate', 'fanno'], example: 'Faccio colazione.', translation: 'I have breakfast.' },
  { verb: 'stare', meaning: 'to stay / feel', forms: ['sto', 'stai', 'sta', 'stiamo', 'state', 'stanno'], example: 'Sto bene.', translation: 'I am well.' },
  { verb: 'dare', meaning: 'to give', forms: ['do', 'dai', 'dà', 'diamo', 'date', 'danno'], example: 'Ti do il libro.', translation: 'I give you the book.' },
  { verb: 'dire', meaning: 'to say / tell', forms: ['dico', 'dici', 'dice', 'diciamo', 'dite', 'dicono'], example: 'Dico la verità.', translation: 'I tell the truth.' },
  { verb: 'venire', meaning: 'to come', forms: ['vengo', 'vieni', 'viene', 'veniamo', 'venite', 'vengono'], example: 'Vengo da Roma.', translation: 'I come from Rome.' },
  { verb: 'uscire', meaning: 'to go out', forms: ['esco', 'esci', 'esce', 'usciamo', 'uscite', 'escono'], example: 'Esco alle otto.', translation: 'I go out at eight.' },
  { verb: 'salire', meaning: 'to go up / get on', forms: ['salgo', 'sali', 'sale', 'saliamo', 'salite', 'salgono'], example: 'Salgo le scale.', translation: 'I go up the stairs.' },
  { verb: 'sapere', meaning: 'to know', forms: ['so', 'sai', 'sa', 'sappiamo', 'sapete', 'sanno'], example: 'So parlare italiano.', translation: 'I know how to speak Italian.' },
  { verb: 'potere', meaning: 'can / to be able to', forms: ['posso', 'puoi', 'può', 'possiamo', 'potete', 'possono'], example: 'Posso venire.', translation: 'I can come.' },
  { verb: 'volere', meaning: 'to want', forms: ['voglio', 'vuoi', 'vuole', 'vogliamo', 'volete', 'vogliono'], example: 'Voglio un caffè.', translation: 'I want a coffee.' },
  { verb: 'dovere', meaning: 'must / to have to', forms: ['devo', 'devi', 'deve', 'dobbiamo', 'dovete', 'devono'], example: 'Devo lavorare.', translation: 'I have to work.' },
  { verb: 'bere', meaning: 'to drink', forms: ['bevo', 'bevi', 'beve', 'beviamo', 'bevete', 'bevono'], example: 'Bevo il caffè.', translation: 'I drink coffee.' },
];