export const congiuntivoStages = [
  {
    id: 'concept',
    title: 'What is the Congiuntivo?',
    subtitle: 'The subjunctive mood — doubt, wishes, opinions, and emotions',
    sections: [
      {
        heading: 'Part 1 — A mood, not a tense',
        explanation: 'The congiuntivo (subjunctive) is the mood of SUBJECTIVITY: doubt, uncertainty, opinion, emotion, wishes, and demands. Unlike the indicativo, which states facts (Maria è a Roma), the congiuntivo expresses how we feel or think about something (Penso che Maria sia a Roma). It rarely stands alone — it appears in a subordinate clause introduced by "che".',
        bullets: [
          { text: 'Maria è a Roma.', example: 'INDICATIVO — a fact. Certainty.' },
          { text: 'Penso che Maria sia a Roma.', example: 'CONGIUNTIVO — my opinion. Not fully certain.' },
        ],
        timeline: { left: 'INDICATIVO (facts)', center: 'CHE (the trigger)', right: 'CONGIUNTIVO (doubts & wishes)', examples: ['Maria è a Roma', 'Penso che…', '…Maria sia a Roma'] },
        note: 'The congiuntivo is not optional: once a trigger like penso che, spero che, or è possibile che introduces the clause, the verb in that clause must be in the subjunctive.',
      },
      {
        heading: 'Part 2 — The trigger words',
        explanation: 'Certain verbs and expressions "trigger" the subjunctive. Learn them as families: opinions (penso che, credo che, sembra che), wishes (voglio che, spero che), emotions (mi dispiace che, sono felice che), impersonal expressions (è possibile che, è necessario che), and doubt (non credo che, non sono sicuro che).',
        bullets: [
          { text: 'Penso che sia una buona idea.', example: 'I think it is a good idea.' },
          { text: 'Spero che tu venga.', example: 'I hope you come.' },
          { text: 'Mi dispiace che tu stia male.', example: 'I am sorry you are unwell.' },
          { text: 'È possibile che piova.', example: 'It may rain / is possible that it rains.' },
        ],
        focus: { sentence: 'Penso che sia giusto.', breakdown: [{ part: 'Penso che', role: 'trigger (opinion)' }, { part: 'sia', role: 'congiuntivo (essere)' }, { part: 'giusto', role: 'adjective' }], meaning: 'I think it is right. The opinion verb forces the subjunctive after "che".' },
        note: 'Opposite pairs are common in exams: "so che" + INDICATIVO (I know a fact) vs "credo che" + CONGIUNTIVO (I believe, maybe).',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Forming the Present Subjunctive',
    subtitle: 'The regular -ARE, -ERE, and -IRE endings',
    sections: [
      {
        heading: 'Part 3 — -ARE verbs swap to -i-',
        explanation: 'For -ARE verbs the subjunctive is built on the "io" stem and adds the vowels -i, -i, -i, -iamo, -iate, -ino. Interestingly, the tu and lui/lei forms are identical to the io form in the modern language.',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'parli' }, { pronoun: 'che tu', ending: 'parli' }, { pronoun: 'che lui/lei', ending: 'parli' }, { pronoun: 'che noi', ending: 'parliamo' }, { pronoun: 'che voi', ending: 'parliate' }, { pronoun: 'che loro', ending: 'parlino' }] },
        examples: [
          { italian: 'Spero che tu parli italiano.', translation: 'I hope you speak Italian.' },
          { italian: 'È importante che voi studiate molto.', translation: 'It is important that you study a lot.' },
          { italian: 'Voglio che loro arrivino presto.', translation: 'I want them to arrive soon.' },
        ],
      },
      {
        heading: 'Part 4 — -ERE and -IRE verbs',
        explanation: 'For -ERE and -IRE verbs the singular "io/tu/lui" forms end in -A (not -e), and the noi form is the same as the indicative. -IRE verbs with -isc- keep it only in the singular and loro forms.',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'prenda / parta / finisca' }, { pronoun: 'che tu', ending: 'prenda / parta / finisca' }, { pronoun: 'che lui/lei', ending: 'prenda / parta / finisca' }, { pronoun: 'che noi', ending: 'prendiamo / partiamo / finiamo' }, { pronoun: 'che voi', ending: 'prendiate / partiate / finiate' }, { pronoun: 'che loro', ending: 'prendano / partano / finiscano' }] },
        examples: [
          { italian: 'Credo che lui prenda il treno.', translation: 'I believe he is taking the train.' },
          { italian: 'È meglio che noi partiamo domani.', translation: 'It is better that we leave tomorrow.' },
          { italian: 'Voglio che voi finiate i compiti.', translation: 'I want you to finish the homework.' },
        ],
        note: 'Watch the noi form: it NEVER gains -sc-. It is "che noi finiamo", not "che noi finiscano".',
      },
      {
        heading: 'Part 5 — Essere and avere',
        explanation: 'Essere and avere have highly irregular subjunctive forms. Learn them by heart:',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'sia / abbia' }, { pronoun: 'che tu', ending: 'sia / abbia' }, { pronoun: 'che lui/lei', ending: 'sia / abbia' }, { pronoun: 'che noi', ending: 'siamo / abbiamo' }, { pronoun: 'che voi', ending: 'siate / abbiate' }, { pronoun: 'che loro', ending: 'siano / abbiano' }] },
        examples: [
          { italian: 'Penso che tu sia felice.', translation: 'I think you are happy.' },
          { italian: 'Spero che voi abbiate tempo.', translation: 'I hope you have time.' },
          { italian: 'Non so che io abbia ragione.', translation: 'I am not sure I am right.' },
        ],
        patterns: ['dare → dia', 'stare → stia', 'fare → faccia', 'andare → vada', 'dovere → debba', 'potere → possa', 'volere → voglia'],
        note: 'The modal verbs dovere, potere, volere follow the pattern: debba, possa, voglia (singular) — debbano, possano, vogliano (loro).',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'Passato & Imperfetto Congiuntivo',
    subtitle: 'abbia/sia + participle, then the -assi/-essi/-issi endings',
    sections: [
      {
        heading: 'Part 6 — Passato: abbia or sia + participle',
        explanation: 'The passato congiuntivo is the subjunctive of the passato prossimo: abbia/sia + past participle. Choose ABBIA with avere verbs and SIA with essere/motion/reflexive verbs, exactly as in the passato prossimo.',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'abbia mangiato / sia andato/a' }, { pronoun: 'che tu', ending: 'abbia mangiato / sia andato/a' }, { pronoun: 'che lui/lei', ending: 'abbia mangiato / sia andato/a' }, { pronoun: 'che noi', ending: 'abbiamo mangiato / siamo andati/e' }, { pronoun: 'che voi', ending: 'abbiate mangiato / siate andati/e' }, { pronoun: 'che loro', ending: 'abbiano mangiato / siano andati/e' }] },
        examples: [
          { italian: 'Mi dispiace che tu abbia perso il treno.', translation: 'I am sorry you missed the train.' },
          { italian: 'Spero che Anna sia arrivata a casa.', translation: 'I hope Anna has arrived home.' },
        ],
        patterns: ['mangiare → abbia mangiato', 'perdere → abbia perso', 'arrivare → sia arrivato/a', 'partire → sia partito/a'],
        note: 'Use the passato congiuntivo when the action in the subordinate clause happened BEFORE the main verb: Penso che Marco abbia mangiato troppo (the eating came before the thinking).',
      },
      {
        heading: 'Part 7 — Imperfetto: -ASSI, -ESSI, -ISSI',
        explanation: 'The imperfetto congiuntivo is used after past-tense triggers (Volevo che…, Speravo che…) and in hypothetical se-clauses (Se avessi tempo…). The endings are regular for every group:',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'parlassi' }, { pronoun: 'che tu', ending: 'parlassi' }, { pronoun: 'che lui/lei', ending: 'parlasse' }, { pronoun: 'che noi', ending: 'parlassimo' }, { pronoun: 'che voi', ending: 'parlaste' }, { pronoun: 'che loro', ending: 'parlassero' }] },
        examples: [
          { italian: 'Volevo che tu parlassi con lui.', translation: 'I wanted you to talk to him.' },
          { italian: 'Credetti che leggesse il libro.', translation: 'He believed she was reading the book.' },
          { italian: 'Se avessi tempo, verrei.', translation: 'If I had time, I would come.' },
        ],
        patterns: ['-ARE → parlassi (io/tu)', '-ERE → prendessi (io/tu)', '-IRE → partissi (io/tu)', 'essere → fossi', 'avere → avessi', 'dovere → dovessi', 'potere → potessi', 'volere → volessi'],
      },
      {
        heading: 'Part 8 — Trapassato: avessi/fossi + participle',
        explanation: 'The trapassato congiuntivo joins avessi/fossi + past participle. It appears after past triggers (Era possibile che…) and — critically — inside se-clauses for impossible past conditions: Se avessi saputo, sarei venuto.',
        conjugations: { rows: [{ pronoun: 'che io', ending: 'avessi mangiato / fossi andato/a' }, { pronoun: 'che tu', ending: 'avessi mangiato / fossi andato/a' }, { pronoun: 'che lui/lei', ending: 'avesse mangiato / fosse andato/a' }, { pronoun: 'che noi', ending: 'avessimo mangiato / fossimo andati/e' }, { pronoun: 'che voi', ending: 'aveste mangiato / foste andati/e' }, { pronoun: 'che loro', ending: 'avessero mangiato / fossero andati/e' }] },
        examples: [
          { italian: 'Se avessi saputo, ti avrei chiamato.', translation: 'If I had known, I would have called you.' },
          { italian: 'Non pensavo che avessimo sbagliato.', translation: 'I did not think we had made a mistake.' },
          { italian: 'Era possibile che avessero perso il treno.', translation: 'It was possible that they had missed the train.' },
        ],
        patterns: ['se + trapassato congiuntivo → condizionale passato', 'Se avessi studiato, avresti passato.', 'Se fossi stato lì, ti avrei aiutato.'],
        note: 'This is the famous periodo ipotetico type 3: Se avessi studiato (congiuntivo trapassato), avresti passato (condizionale passato) — a regret about the past.',
      },
    ],
  },
  {
    id: 'usage',
    title: 'When to Use the Congiuntivo',
    subtitle: 'Opinions, wishes, emotions, impersonal expressions, and conditions',
    sections: [
      {
        heading: 'Part 9 — Opinions and thoughts',
        explanation: 'Verbs of opinion and belief trigger the subjunctive in the subordinate clause: credere, pensare, sembrare, supporre, immaginare.',
        verbs: [
          { infinitive: 'credere che', meaning: 'to believe that (+ subj.)' },
          { infinitive: 'pensare che', meaning: 'to think that (+ subj.)' },
          { infinitive: 'sembrare che', meaning: 'to seem that (+ subj.)' },
        ],
        examples: [
          { italian: 'Credo che Marco sia sincero.', translation: 'I believe Marco is sincere.' },
          { italian: 'Non penso che sia una buona idea.', translation: 'I do not think it is a good idea.' },
          { italian: 'Sembra che il ristorante sia chiuso.', translation: 'It seems the restaurant is closed.' },
        ],
        note: 'After NEGATED opinion verbs (non credo che, non penso che) the subjunctive is still required — and in fact it is almost compulsory.',
      },
      {
        heading: 'Part 10 — Impersonal expressions',
        explanation: 'Impersonal constructions are a large trigger family: è possibile che, è necessario che, è importante che, è meglio che, bisogna che, è strano che. Think "can be / must be / is better that…".',
        examples: [
          { italian: 'È necessario che tu vada dal dottore.', translation: 'It is necessary that you go to the doctor.' },
          { italian: 'È meglio che noi usciamo ora.', translation: 'It is better that we leave now.' },
          { italian: 'Bisogna che parliate con l\'agente.', translation: 'You must / it is necessary that you talk to the agent.' },
        ],
        note: 'Watch the trap: è chiaro che, è ovvio che, è certo che express CERTAINTY and normally take the INDICATIVO. Only "doubt / need / value" expressions like è possibile, è necessario, è meglio take the congiuntivo.',
      },
      {
        heading: 'Part 11 — Emotions, wishes, and desires',
        explanation: 'Emotions (mi dispiace che, sono felice che, che peccato che) and wishes/desires (voglio che, desidero che, spero che, preferisco che, sono contento che) all take the subjunctive.',
        examples: [
          { italian: 'Mi dispiace che tu stia male.', translation: 'I am sorry that you are unwell.' },
          { italian: 'Sono felice che voi veniate.', translation: 'I am happy that you are coming.' },
          { italian: 'Voglio che tutti siano puntuali.', translation: 'I want everyone to be punctual.' },
          { italian: 'Preferisco che tu aspetti qui.', translation: 'I prefer you to wait here.' },
        ],
      },
      {
        heading: 'Part 12 — Doubt, se-clauses, and everyday patterns',
        explanation: 'Doubt and unresolved questions also use the subjunctive (non so se sia possibile, non sono sicuro che venga). And in hypothetical sentences, the se-clause takes the imperfetto congiuntivo (type 2) or trapassato congiuntivo (type 3):',
        bullets: [
          { text: 'Non so se sia una buona idea.', example: 'I do not know whether it is a good idea.' },
          { text: 'Se avessi tempo, verrei con voi.', example: 'If I had time, I would come with you. (type 2)' },
          { text: 'Se avessi saputo, ti avrei chiamato.', example: 'If I had known, I would have called you. (type 3)' },
        ],
        patterns: ['è possibile che → congiuntivo', 'è chiaro che → indicativo', 'se + imperfetto congiuntivo → condizionale presente', 'se + trapassato congiuntivo → condizionale passato'],
        note: 'Vogliamo tutti che tu sia contento. The congiuntivo appears after nearly every expression of feeling or thought — it is the heart of natural, fluent Italian.',
      },
    ],
  },
];

export const congiuntivoExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Meet the Congiuntivo',
    instruction: 'Recognise what the congiuntivo is and when it is used.',
    questions: [
      { question: 'The congiuntivo (subjunctive) is the mood of:', options: ['doubt, wishes, opinions, emotions', 'only commands', 'only past facts', 'only future facts'], answer: 'doubt, wishes, opinions, emotions', explanation: 'The subjunctive expresses subjectivity and uncertainty.' },
      { question: 'The congiuntivo usually appears in a clause introduced by:', options: ['che', 'of', 'to', 'and'], answer: 'che', explanation: 'The subordinate clause is almost always introduced by "che".' },
      { question: '"Penso che Maria ___ brava." — the correct subjunctive is:', options: ['sia', 'e', 'è', 'sarà'], answer: 'sia', explanation: 'After "penso che" we use the congiuntivo: sia (essere).' },
      { question: 'Which sentence uses the congiuntivo?', options: ['Penso che Maria sia gentile.', 'Maria è gentile.', 'Maria sarà gentile.', 'Maria era gentile.'], answer: 'Penso che Maria sia gentile.', explanation: 'Only the che-clause with "penso che" uses the subjunctive.' },
      { question: 'The indicativo, by contrast, expresses:', options: ['facts and certainty', 'wishes', 'emotions', 'doubts'], answer: 'facts and certainty', explanation: 'Indicativo = the mood of reality and facts.' },
      { question: '"Non credo che tu ___ (dovere) partire." (congiuntivo of dovere)', options: ['debba', 'devi', 'doveva', 'dovrai'], answer: 'debba', explanation: 'After a negated opinion verb the subjunctive is required: debba.' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match the Meaning',
    instruction: 'Match each term with its meaning in the subjunctive system.',
    pairs: [
      { left: 'congiuntivo', right: 'doubt, wish, or emotion' },
      { left: 'indicativo', right: 'fact, certainty' },
      { left: 'che', right: 'the word that introduces the subjunctive clause' },
      { left: 'Credo che', right: 'I think that (+ subjunctive)' },
      { left: 'Spero che', right: 'I hope that (+ subjunctive)' },
      { left: 'È possibile che', right: 'It is possible that (+ subjunctive)' },
    ],
    explanation: 'Every trigger expression ends with "che" and pushes the next verb into the subjunctive.',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Indicative or Subjunctive?',
    instruction: 'Tell whether the sentence expresses fact (indicativo) or subjectivity (congiuntivo).',
    questions: [
      { question: '"Maria è a Roma." →', options: ['an indicative fact', 'a subjunctive wish', 'a command', 'a question'], answer: 'an indicative fact', explanation: 'No trigger, no "che" — plain fact in the indicative.' },
      { question: '"Spero che Maria sia a Roma." →', options: ['a subjunctive wish', 'an indicative fact', 'a command', 'a surprise'], answer: 'a subjunctive wish', explanation: '"Spero che" + subjunctive (sia).' },
      { question: 'The indicativo tells us something is:', options: ['certain', 'uncertain', 'hoped', 'feared'], answer: 'certain', explanation: 'The indicative states what the speaker treats as certain.' },
      { question: 'The congiuntivo tells us something is:', options: ['felt or not certain', 'proven', 'mathematical', 'historical'], answer: 'felt or not certain', explanation: 'The subjunctive marks emotion, doubt, or opinion.' },
      { question: '"Credo che lui ___ (parlare) tre lingue."', options: ['parli', 'parla', 'parlava', 'parlerà'], answer: 'parli', explanation: 'After "credo che" → congiuntivo: parli.' },
    ],
  },

  // LEVEL 2 — FORMATION
  {
    id: 4,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Present Subjunctive: -ARE',
    instruction: 'Complete each sentence with the correct -ARE subjunctive form.',
    questions: [
      { sentence: 'Spero che io ___ (parlare) italiano bene.', options: ['parli', 'parla', 'parlano', 'parlava'], answer: 'parli', explanation: 'che io parli.' },
      { sentence: 'Penso che tu ___ (lavorare) troppo.', options: ['lavori', 'lavora', 'lavorano', 'lavorava'], answer: 'lavori', explanation: 'che tu lavori.' },
      { sentence: 'È importante che lui ___ (studiare) ogni giorno.', options: ['studi', 'studia', 'studiano', 'studiava'], answer: 'studi', explanation: 'che lui studi.' },
      { sentence: 'Voglio che noi ___ (parlare) insieme domani.', options: ['parliamo', 'parlate', 'parlino', 'parla'], answer: 'parliamo', explanation: 'che noi parliamo.' },
      { sentence: 'Desidero che voi ___ (guardare) questo film.', options: ['guardiate', 'guardino', 'guardiamo', 'guardate'], answer: 'guardiate', explanation: 'che voi guardiate.' },
      { sentence: 'È possibile che loro ___ (viaggiare) in estate.', options: ['viaggino', 'viaggiano', 'viaggia', 'viaggiava'], answer: 'viaggino', explanation: 'che loro viaggino.' },
    ],
  },
  {
    id: 5,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Present Subjunctive: -ERE and -IRE',
    instruction: 'Complete each sentence with the correct -ERE or -IRE subjunctive form.',
    questions: [
      { sentence: 'Credo che lui ___ (prendere) il treno.', options: ['prenda', 'prende', 'prendono', 'prendeva'], answer: 'prenda', explanation: 'che lui prenda.' },
      { sentence: 'Voglio che tu ___ (leggere) questo libro.', options: ['legga', 'leggi', 'leggono', 'leggeva'], answer: 'legga', explanation: 'che tu legga.' },
      { sentence: 'Penso che noi ___ (vendere) la macchina.', options: ['vendiamo', 'vendete', 'vendono', 'vendo'], answer: 'vendiamo', explanation: 'che noi vendiamo.' },
      { sentence: 'È meglio che voi ___ (vendere) ora.', options: ['vendiate', 'vendono', 'vendete', 'vendiamo'], answer: 'vendiate', explanation: 'che voi vendiate.' },
      { sentence: 'Spero che loro ___ (partire) presto.', options: ['partano', 'partono', 'parta', 'partite'], answer: 'partano', explanation: 'che loro partano.' },
      { sentence: 'Voglio che noi ___ (finire) il progetto.', options: ['finiamo', 'finiate', 'finiscano', 'finisco'], answer: 'finiamo', explanation: 'che noi finiamo (no -sc-!).' },
    ],
  },

  // LEVEL 3 — ESSERE, AVERE & IRREGULARS
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 3 — Essere, Avere & Irregulars',
    title: 'Essere and Avere',
    instruction: 'Complete each sentence with the correct subjunctive of essere or avere.',
    questions: [
      { sentence: 'Penso che Mario ___ (essere) bravo.', options: ['sia', 'e', 'è', 'sarà'], answer: 'sia', explanation: 'che Mario sia.' },
      { sentence: 'Voglio che tu ___ (essere) felice.', options: ['sia', 'sei', 'eri', 'sarei'], answer: 'sia', explanation: 'che tu sia.' },
      { sentence: 'Credo che noi ___ (avere) ragione.', options: ['abbiamo', 'abbia', 'avete', 'avremo'], answer: 'abbiamo', explanation: 'che noi abbiamo.' },
      { sentence: 'È possibile che voi ___ (avere) freddo.', options: ['abbiate', 'abbiamo', 'avete', 'avevi'], answer: 'abbiate', explanation: 'che voi abbiate.' },
      { sentence: 'Spero che loro ___ (avere) tempo.', options: ['abbiano', 'abbia', 'hanno', 'avranno'], answer: 'abbiano', explanation: 'che loro abbiano.' },
      { sentence: 'Penso che lei ___ (essere) italiana.', options: ['sia', 'e', 'è', 'sarà'], answer: 'sia', explanation: 'che lei sia.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 3 — Essere, Avere & Irregulars',
    title: 'Dare, Stare, Fare & the Modals',
    instruction: 'Complete the irregular subjunctive forms.',
    questions: [
      { sentence: 'Credo che tu ___ (dovere) partire.', options: ['debba', 'devi', 'doveva', 'dovrai'], answer: 'debba', explanation: 'che tu debba.' },
      { sentence: 'Voglio che voi ___ (potere) venire.', options: ['possiate', 'potete', 'potreste', 'possono'], answer: 'possiate', explanation: 'che voi possiate.' },
      { sentence: 'Spero che loro ___ (volere) aiutarci.', options: ['vogliano', 'vogliono', 'vorrebbero', 'volete'], answer: 'vogliano', explanation: 'che loro vogliano.' },
      { sentence: 'È meglio che noi ___ (stare) a casa.', options: ['stiamo', 'stiano', 'state', 'siamo'], answer: 'stiamo', explanation: 'che noi stiamo.' },
      { sentence: 'Penso che loro ___ (dare) una festa.', options: ['diano', 'danno', 'davano', 'daranno'], answer: 'diano', explanation: 'che loro diano.' },
      { sentence: 'Voglio che lui ___ (fare) i compiti.', options: ['faccia', 'fa', 'faceva', 'farà'], answer: 'faccia', explanation: 'che lui faccia.' },
    ],
  },
  {
    id: 8,
    type: 'matching',
    level: 'Level 3 — Essere, Avere & Irregulars',
    title: 'Match the Subject',
    instruction: 'Match each che + subject with the correct subjunctive form.',
    pairs: [
      { left: 'che io', right: 'sia / abbia / possa' },
      { left: 'che tu', right: 'sia / abbia / voglia' },
      { left: 'che lui/lei', right: 'sia / abbia / debba' },
      { left: 'che noi', right: 'siamo / abbiamo / possiamo' },
      { left: 'che voi', right: 'siate / abbiate / dobbiate' },
      { left: 'che loro', right: 'siano / abbiano / vogliano' },
    ],
    explanation: 'Learn essere, avere, and the modals together: sia, abbia, possa, and their plurals.',
  },

  // LEVEL 4 — THE "CHE" TRIGGERS
  {
    id: 9,
    type: 'multiple',
    level: 'Level 4 — The "Che" Triggers',
    title: 'Opinions and Thoughts',
    instruction: 'Choose the correct form after verbs of opinion.',
    questions: [
      { question: 'Which verb REQUIRES the subjunctive?', options: ['Credo che…', 'So per certo che…', 'È un fatto che…', 'Vedo che…'], answer: 'Credo che…', explanation: '"Credo che" = opinion → subjunctive. The others are certainties.' },
      { question: '"Penso che Anna ___ (studiare) molto."', options: ['studi', 'studia', 'studiava', 'studierà'], answer: 'studi', explanation: 'After "penso che" → studi.' },
      { question: '"Sembra che il ristorante ___ (essere) chiuso."', options: ['sia', 'è', 'era', 'sarà'], answer: 'sia', explanation: 'Sembra che → subjunctive: sia.' },
      { question: '"Credo che questo film ___ (piacere) a tutti."', options: ['piaccia', 'piace', 'piaceva', 'piacerà'], answer: 'piaccia', explanation: 'piacere → che piaccia.' },
      { question: 'After "non credo che" we ALWAYS use:', options: ['the congiuntivo', 'the infinito', 'the indicativo', 'the gerundio'], answer: 'the congiuntivo', explanation: 'A negated opinion still triggers the subjunctive.' },
    ],
  },
  {
    id: 10,
    type: 'multiple',
    level: 'Level 4 — The "Che" Triggers',
    title: 'Impersonal Expressions & Emotions',
    instruction: 'Choose the correct form after impersonal expressions and emotions.',
    questions: [
      { question: '"È necessario che tu ___ (andare) dal dottore."', options: ['vada', 'vai', 'andrai', 'andavi'], answer: 'vada', explanation: 'È necessario che → congiuntivo: vada.' },
      { question: '"Mi dispiace che tu ___ (stare) male."', options: ['stia', 'stai', 'stavi', 'starai'], answer: 'stia', explanation: 'Mi dispiace che → che tu stia.' },
      { question: '"Sono felice che voi ___ (venire)."', options: ['veniate', 'venite', 'venivate', 'verrete'], answer: 'veniate', explanation: 'che voi veniate.' },
      { question: '"È meglio che noi ___ (uscire) ora."', options: ['usciamo', 'usciate', 'uscite', 'usciremo'], answer: 'usciamo', explanation: 'che noi usciamo (noi form).' },
      { question: '"Desidero che tutto ___ (andare) bene."', options: ['vada', 'va', 'andrà', 'andava'], answer: 'vada', explanation: 'desidero che → vada.' },
    ],
  },
  {
    id: 11,
    type: 'fillblank',
    level: 'Level 4 — The "Che" Triggers',
    title: 'Use Them in Context',
    instruction: 'Complete each sentence with the right subjunctive form.',
    questions: [
      { sentence: 'Spero che il treno ___ (arrivare) in orario.', options: ['arrivi', 'arriva', 'arrivava', 'arriverà'], answer: 'arrivi', explanation: 'spero che → arrivi.' },
      { sentence: 'Voglio che tu ___ (fare) attenzione.', options: ['faccia', 'fai', 'facevi', 'farai'], answer: 'faccia', explanation: 'voglio che → faccia.' },
      { sentence: 'Non penso che ___ (essere) una buona idea.', options: ['sia', 'è', 'era', 'sarà'], answer: 'sia', explanation: 'non penso che → sia.' },
      { sentence: 'Che bello che tu ___ (venire)!', options: ['venga', 'vieni', 'venivi', 'verrai'], answer: 'venga', explanation: 'che tu venga.' },
      { sentence: 'Spero che voi ___ (potere) aiutarci.', options: ['possiate', 'potete', 'potreste', 'potevate'], answer: 'possiate', explanation: 'che voi possiate.' },
    ],
  },

  // LEVEL 5 — PASSATO CONGIUNTIVO
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 5 — Passato Congiuntivo',
    title: 'Passato: abbia/sia + participle',
    instruction: 'Build the passato congiuntivo with the correct auxiliary.',
    questions: [
      { sentence: 'Penso che Marco ___ (mangiare) troppo.', options: ['abbia mangiato', 'abbia mangiare', 'ha mangiato', 'avrebbe mangiato'], answer: 'abbia mangiato', explanation: 'mangiare (avere) → abbia mangiato.' },
      { sentence: 'Credo che Anna ___ (arrivare) a casa.', options: ['sia arrivata', 'abbia arrivato', 'è arrivata', 'fosse arrivata'], answer: 'sia arrivata', explanation: 'arrivare (essere) → sia arrivata.' },
      { sentence: 'Mi dispiace che tu ___ (perdere) il treno.', options: ['abbia perso', 'sia perso', 'hai perso', 'avesse perso'], answer: 'abbia perso', explanation: 'perdere (avere) → abbia perso.' },
      { sentence: 'Sono felice che voi ___ (vedere) la mostra.', options: ['abbiate visto', 'abbiano visto', 'avete visto', 'avreste visto'], answer: 'abbiate visto', explanation: 'che voi abbiate visto.' },
      { sentence: 'Che strano che lui non ___ (venire)!', options: ['sia venuto', 'abbia venuto', 'venisse', 'viene'], answer: 'sia venuto', explanation: 'venire (essere) → non sia venuto.' },
      { sentence: 'Spero che voi ___ (arrivare) presto.', options: ['siate arrivati', 'abbiate arrivato', 'siete arrivati', 'sarete arrivati'], answer: 'siate arrivati', explanation: 'arrivare (essere, voi) → siate arrivati.' },
    ],
  },
  {
    id: 13,
    type: 'multiple',
    level: 'Level 5 — Passato Congiuntivo',
    title: 'Presente or Passato?',
    instruction: 'Choose the presente (same time) or passato congiuntivo (completed before).',
    questions: [
      { question: '"Penso che lui ___ adesso. (now)"', options: ['dorma', 'abbia dormito', 'dormisse', 'dormiva'], answer: 'dorma', explanation: 'Same time as "penso" → presente congiuntivo.' },
      { question: '"Penso che lui ___ dua notti fa. (two nights ago)"', options: ['abbia dormito', 'dorma', 'dormisse', 'dormiva'], answer: 'abbia dormito', explanation: 'A completed past action → passato congiuntivo.' },
      { question: '"Credo che Maria ___ già a casa. (already home)"', options: ['sia', 'è', 'fosse', 'sarà'], answer: 'sia', explanation: 'State already reached → sia.' },
      { question: '"Mi dispiace che tu ___ male ieri sera."', options: ['abbia dormito', 'dorma', 'dormi', 'dormissi'], answer: 'abbia dormito', explanation: '«ieri sera» = past → abbia dormito.' },
      { question: '"Spero che ___ bel tempo domani."', options: ['ci sia', 'ci fosse', 'ci è', 'ci fu'], answer: 'ci sia', explanation: 'About tomorrow but still not certain → presente congiuntivo.' },
      { question: '"È possibile che ___ sbagliato. (we may have made a mistake)"', options: ['abbiamo sbagliato', 'sbagliamo', 'avessimo sbagliato', 'sbagliammo'], answer: 'abbiamo sbagliato', explanation: 'doubt + completed → abbiamo sbagliato.' },
    ],
  },

  // LEVEL 6 — IMPERFETTO CONGIUNTIVO
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 6 — Imperfetto Congiuntivo',
    title: 'Imperfetto: Regular Endings',
    instruction: 'Complete each sentence with the imperfetto congiuntivo (-assi/-essi/-issi).',
    questions: [
      { sentence: 'Speravo che tu ___ (arrivare) presto.', options: ['arrivassi', 'arrivi', 'arrivavi', 'arriverai'], answer: 'arrivassi', explanation: 'Past trigger → arrivassi.' },
      { sentence: 'Desideravo che lui ___ (mangiare) di più.', options: ['mangiasse', 'mangi', 'mangiava', 'mangerà'], answer: 'mangiasse', explanation: 'che lui mangiasse.' },
      { sentence: 'Volevo che noi ___ (leggere) insieme.', options: ['leggessimo', 'leggiamo', 'leggevamo', 'leggeremo'], answer: 'leggessimo', explanation: 'che noi leggessimo.' },
      { sentence: 'Bisognava che voi ___ (parlare) con lui.', options: ['parlaste', 'parliate', 'parlavate', 'parlerete'], answer: 'parlaste', explanation: 'che voi parlaste.' },
      { sentence: 'Era importante che loro ___ (partire) subito.', options: ['partissero', 'partano', 'partivano', 'partiranno'], answer: 'partissero', explanation: 'che loro partissero.' },
      { sentence: 'Non credevo che tu ___ (finire) in tempo.', options: ['finissi', 'finisci', 'finivi', 'finirai'], answer: 'finissi', explanation: 'che tu finissi.' },
    ],
  },
  {
    id: 15,
    type: 'fillblank',
    level: 'Level 6 — Imperfetto Congiuntivo',
    title: 'Essere, Avere & the Modals',
    instruction: 'Complete with the irregular imperfetto congiuntivo forms.',
    questions: [
      { sentence: 'Vorrei che tu ___ (essere) qui.', options: ['fossi', 'sia', 'eri', 'sarai'], answer: 'fossi', explanation: 'essere imperfetto congiuntivo → fossi.' },
      { sentence: 'Speravo che tu ___ (avere) tempo domenica.', options: ['avessi', 'abbia', 'avevi', 'avrai'], answer: 'avessi', explanation: 'avere → avessi.' },
      { sentence: 'Volevo che lui ___ (potere) venire.', options: ['potesse', 'possa', 'poteva', 'potrà'], answer: 'potesse', explanation: 'potere → potesse.' },
      { sentence: 'Non pensavo che lei ___ (volere) restare.', options: ['volesse', 'voglia', 'voleva', 'vorrà'], answer: 'volesse', explanation: 'volere → volesse.' },
      { sentence: 'Se ___ (io, avere) tempo, viaggerei.', options: ['avessi', 'abbia', 'avevo', 'avrò'], answer: 'avessi', explanation: 'Hypothetical se-clause → avessi.' },
      { sentence: 'Se tu ___ (essere) ricco, cosa faresti?', options: ['fossi', 'sia', 'eri', 'sarai'], answer: 'fossi', explanation: 'Secondo condizionale → fossi.' },
    ],
  },
  {
    id: 16,
    type: 'matching',
    level: 'Level 6 — Imperfetto Congiuntivo',
    title: 'Match the Imperfetto',
    instruction: 'Match each che + subject with its imperfetto congiuntivo form.',
    pairs: [
      { left: 'che io', right: 'parlassi / fossi' },
      { left: 'che tu', right: 'parlassi / avessi' },
      { left: 'che lui/lei', right: 'parlasse / fosse' },
      { left: 'che noi', right: 'parlassimo / fossimo' },
      { left: 'che voi', right: 'parlaste / foste' },
      { left: 'che loro', right: 'parlassero / fossero' },
    ],
    explanation: 'The imperfetto congiuntivo by heart: io/tu -assi, lui -asse, noi -assimo, voi -aste, loro -assero.',
  },

  // LEVEL 7 — TRAPASSATO & SE-CLAUSES
  {
    id: 17,
    type: 'fillblank',
    level: 'Level 7 — Trapassato & Se-clauses',
    title: 'Trapassato: avessi/fossi + participle',
    instruction: 'Build the trapassato congiuntivo with the correct auxiliary.',
    questions: [
      { sentence: 'Se ___ (io, sapere), sarei venuto.', options: ['avessi saputo', 'ho saputo', 'avrò saputo', 'sapevo'], answer: 'avessi saputo', explanation: 'sapere (avere) → avessi saputo.' },
      { sentence: 'Se ___ (tu, studiare) di più, avresti passato.', options: ['avessi studiato', 'hai studiato', 'avevi studiato', 'studierai'], answer: 'avessi studiato', explanation: 'se + trapassato congiuntivo.' },
      { sentence: 'Se lei ___ (arrivare) prima, avremmo preso il treno.', options: ['fosse arrivata', 'avesse arrivato', 'è arrivata', 'arriverà'], answer: 'fosse arrivata', explanation: 'arrivare (essere) → fosse arrivata.' },
      { sentence: 'Era possibile che ___ (loro, perdere) il treno.', options: ['avessero perso', 'abbiano perso', 'hanno perso', 'perdevano'], answer: 'avessero perso', explanation: 'Past trigger + past action → avessero perso.' },
      { sentence: 'Non pensavo che noi ___ (sbagliare).', options: ['avessimo sbagliato', 'abbiamo sbagliato', 'abbiate sbagliato', 'sbagliavamo'], answer: 'avessimo sbagliato', explanation: 'che noi avessimo sbagliato.' },
      { sentence: 'Se ___ (voi, dire) la verità, nessuno si sarebbe arrabbiato.', options: ['aveste detto', 'avete detto', 'abbiate detto', 'dicevate'], answer: 'aveste detto', explanation: 'che voi aveste detto.' },
    ],
  },
  {
    id: 18,
    type: 'multiple',
    level: 'Level 7 — Trapassato & Se-clauses',
    title: 'Se-clauses & Conditions',
    instruction: 'Choose the correct form for each conditional sentence.',
    questions: [
      { question: '"Se ___ tempo, partirei. (present hypothetical)"', options: ['avessi', 'ho', 'avrò', 'avrei'], answer: 'avessi', explanation: 'Type 2: se + imperfetto congiuntivo → condizionale.' },
      { question: '"Se ___ (io, sapere), avrei chiamato. (past)"', options: ['avessi saputo', 'sapevo', 'ho saputo', 'avrò saputo'], answer: 'avessi saputo', explanation: 'Type 3: se + trapassato congiuntivo.' },
      { question: '"Se piove, prendo l\'ombrello." uses:', options: ['the indicativo (real condition)', 'the congiuntivo only', 'the condizionale only', 'the imperfetto'], answer: 'the indicativo (real condition)', explanation: 'Real condition (tipo 1) → presente indicativo in both clauses.' },
      { question: 'In "Se avessi studiato, avrei passato" the se-clause is:', options: ['congiuntivo trapassato', 'indicativo', 'infinito', 'gerundio'], answer: 'congiuntivo trapassato', explanation: 'avessi studiato = trapassato congiuntivo.' },
      { question: '"Se tu ___ (andare) via prima, non avresti perso il treno."', options: ['fossi andato', 'avessi andato', 'sei andato', 'andasti'], answer: 'fossi andato', explanation: 'andare (essere) → fossi andato.' },
      { question: 'For a PAST impossible condition we use:', options: ['se + trapassato congiuntivo + condizionale passato', 'se + presente + futuro', 'se + indicativo + futuro', 'se + imperfetto indicativo'], answer: 'se + trapassato congiuntivo + condizionale passato', explanation: 'The classic periodo ipotetico type 3.' },
    ],
  },
  {
    id: 19,
    type: 'wordorder',
    level: 'Level 7 — Trapassato & Se-clauses',
    title: 'Build the Sentence',
    instruction: 'Put the words in the correct order to make a correct sentence.',
    questions: [
      { words: ['se', 'avessi', 'tempo', 'verrei'], answer: 'se avessi tempo verrei', explanation: 'se + imperfetto congiuntivo → condizionale.' },
      { words: ['credo', 'che', 'lei', 'sia', 'brava'], answer: 'credo che lei sia brava', explanation: 'credo che + congiuntivo (sia).' },
      { words: ['spero', 'che', 'tu', 'stia', 'bene'], answer: 'spero che tu stia bene', explanation: 'spero che + congiuntivo (stia).' },
      { words: ['era', 'possibile', 'che', 'perdessimo', 'il', 'treno'], answer: 'era possibile che perdessimo il treno', explanation: 'Past trigger → imperfetto congiuntivo.' },
      { words: ['se', 'tu', 'mi', 'avessi', 'chiamato', 'sarei', 'venuto'], answer: 'se tu mi avessi chiamato sarei venuto', explanation: 'Type 3 condition with trapassato congiuntivo.' },
    ],
  },

  // LEVEL 8 — CONGIUNTIVO VS INDICATIVO
  {
    id: 20,
    type: 'multiple',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Congiuntivo or Indicativo?',
    instruction: 'Choose the correct mood: certainty (indicativo) or subjectivity (congiuntivo).',
    questions: [
      { question: '"Sono sicuro che tu ___ (avere) ragione."', options: ['hai', 'abbia', 'avessi', 'avrai'], answer: 'hai', explanation: 'Certainty → indicativo.' },
      { question: '"Credo che tu ___ (avere) ragione."', options: ['abbia', 'hai', 'avessi', 'abbi'], answer: 'abbia', explanation: 'Opinion → congiuntivo.' },
      { question: '"Non sono sicuro che ___ (essere) la scelta giusta."', options: ['sia', 'è', 'era', 'sarà'], answer: 'sia', explanation: 'Doubt → congiuntivo.' },
      { question: '"Mi hai detto che ___ (arrivare) domani."', options: ['arriva', 'arrivi', 'arrivasse', 'arriverebbe'], answer: 'arriva', explanation: 'Reported fact → indicativo (arriva).' },
      { question: '"Vedo che ___ (piovere)."', options: ['piove', 'piova', 'piovesse', 'pioverà'], answer: 'piove', explanation: '"Vedo che" = fact → indicativo.' },
      { question: '"Non vedo l\'ora che ___ (iniziare) le vacanze."', options: ['iniziino', 'iniziano', 'iniziavano', 'inizieranno'], answer: 'iniziino', explanation: 'Desire → congiuntivo (iniziino).' },
    ],
  },
  {
    id: 21,
    type: 'translation',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Translate with the Congiuntivo',
    instruction: 'Choose the correct English equivalent.',
    direction: 'it-en',
    questions: [
      { sentence: 'Penso che sia meglio aspettare.', options: ['I think it is better to wait', 'I think (fact) it is better', 'It is definitely better', 'Wait, I think so'], answer: 'I think it is better to wait', explanation: 'literally "I think that it (subj.) be better to wait".' },
      { sentence: 'Non credo che venga.', options: ['I don\'t think he is coming', 'He is not coming', 'Don\'t believe him', 'He won\'t believe it'], answer: 'I don\'t think he is coming', explanation: 'non credo che + subjunctive (venga).' },
      { sentence: 'Mi dispiace che tu stia male.', options: ['I am sorry that you are unwell', 'You are upset that I am unwell', 'I am sorry, be unwell', 'I am unwell, sorry'], answer: 'I am sorry that you are unwell', explanation: 'mi dispiace che + subjunctive (stia).' },
      { sentence: 'Se avessi saputo, ti avrei chiamato.', options: ['If I had known, I would have called you', 'If I knew, I call you', 'If I will know, I will call', 'I knew and I called'], answer: 'If I had known, I would have called you', explanation: 'Type 3 regret: trapassato congiuntivo + condizionale passato.' },
      { sentence: 'Spero che ci sia sole domani.', options: ['I hope there is sun tomorrow', 'There is sun tomorrow (fact)', 'I hope for sun (certain)', 'Sunny tomorrow, I am sure'], answer: 'I hope there is sun tomorrow', explanation: 'spero che + subjunctive (ci sia).' },
    ],
  },
  {
    id: 22,
    type: 'matching',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Match the Use',
    instruction: 'Match each expression with the mood it requires.',
    pairs: [
      { left: 'Credo che…', right: 'opinion → congiuntivo' },
      { left: 'È possibile che…', right: 'possibility → congiuntivo' },
      { left: 'Voglio che…', right: 'wish / desire → congiuntivo' },
      { left: 'Mi dispiace che…', right: 'emotion → congiuntivo' },
      { left: 'Sono sicuro che…', right: 'certainty → indicativo' },
      { left: 'So che…', right: 'fact → indicativo' },
    ],
    explanation: 'Certainty families (so, è chiaro, sono sicuro) take the indicativo; everything subjective takes the congiuntivo.',
  },
  {
    id: 23,
    type: 'fillblank',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Mixed Tenses',
    instruction: 'Complete each sentence with the right form or tense.',
    questions: [
      { sentence: 'Penso che tuo fratello ___ (essere) molto simpatico.', options: ['sia', 'è', 'era', 'sarà'], answer: 'sia', explanation: 'opinion → sia.' },
      { sentence: 'Non sapevo che Anna ___ (essere) sposata.', options: ['fosse', 'è', 'sarà', 'sia'], answer: 'fosse', explanation: 'Past trigger → imperfetto congiuntivo (fosse).' },
      { sentence: 'Voglio che tu ___ (aspettare) qui.', options: ['aspetti', 'aspettare', 'aspetta', 'aspetterai'], answer: 'aspetti', explanation: 'voglio che → aspetti.' },
      { sentence: 'Se ___ (io, potere), viaggerei tutto l\'anno.', options: ['potessi', 'posso', 'potrò', 'potrei'], answer: 'potessi', explanation: 'se + imperfetto congiuntivo (potessi).' },
      { sentence: 'Bisogna che tu ___ (studiare) di più.', options: ['studi', 'studia', 'studierai', 'studiassi'], answer: 'studi', explanation: 'bisogna che → congiuntivo (studi).' },
      { sentence: 'Credo che la riunione ___ (cominciare) tra poco.', options: ['cominci', 'comincia', 'cominciò', 'comincerà'], answer: 'cominci', explanation: 'credo che → cominci.' },
    ],
  },
  {
    id: 24,
    type: 'wordorder',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Build More Sentences',
    instruction: 'Put the words in the correct order.',
    questions: [
      { words: ['credo', 'che', 'sia', 'ottima', 'idea'], answer: 'credo che sia ottima idea', explanation: 'credo che + subjunctive.' },
      { words: ['spero', 'che', 'tu', 'possa', 'venire'], answer: 'spero che tu possa venire', explanation: 'spero che + poss(a) venire.' },
      { words: ['non', 'credo', 'che', 'piova'], answer: 'non credo che piova', explanation: 'negated opinion → subjunctive.' },
      { words: ['mi', 'dispiace', 'che', 'tu', 'stia', 'male'], answer: 'mi dispiace che tu stia male', explanation: 'emotion → subjunctive.' },
      { words: ['se', 'avessimo', 'saputo', 'non', 'saremmo', 'partiti'], answer: 'se avessimo saputo non saremmo partiti', explanation: 'Type 3 condition.' },
    ],
  },
  {
    id: 25,
    type: 'multiple',
    level: 'Level 8 — Congiuntivo vs Indicativo',
    title: 'Everyday Review',
    instruction: 'Choose the correct form used in everyday situations.',
    questions: [
      { question: '"Il cameriere suggerisce che ___ (noi, prendere) il pesce."', options: ['prendiamo', 'prendiate', 'prendano', 'prendo'], answer: 'prendiamo', explanation: 'suggerisce che → congiuntivo (noi prendiamo).' },
      { question: '"Ti prego che tu non ___ (andare) via."', options: ['vada', 'vai', 'andrai', 'andi'], answer: 'vada', explanation: 'ti prego che → non vada.' },
      { question: '"Che Dio ti ___ (benedire)!"', options: ['benedica', 'benedice', 'benedirà', 'benedisse'], answer: 'benedica', explanation: 'Fixed wish: Che Dio ti benedica!' },
      { question: '"Spero che la cena ___ (piacere) a tutti."', options: ['piaccia', 'piace', 'piacerà', 'piaceva'], answer: 'piaccia', explanation: 'spero che → piaccia.' },
      { question: '"Accidenti, se ___ (io, studiare)!"', options: ['avessi studiato', 'ho studiato', 'studiassi', 'studierei'], answer: 'avessi studiato', explanation: 'Rueful exclamation: "If only I had studied!"' },
      { question: '"Mi auguro che tutto ___ (andare) bene."', options: ['vada', 'va', 'andrò', 'andava'], answer: 'vada', explanation: 'mi auguro che → vada.' },
    ],
  },

  // LEVEL 9 — REAL-LIFE COMMUNICATION (STORIES)
  {
    id: 26,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Opinions',
    storyTitle: 'Che venga?',
    story: 'Anna: Credi che Mario venga alla festa sabato?\n\nMarco: Non so. Spero che venga, ma penso che sia molto stanco.\n\nAnna: Sembra che lavori troppo. Credo che lui debba riposarsi.\n\nMarco: Hai ragione. Ma mi dispiace che non possa venire spesso.\n\nAnna: Forse è meglio che lo invitiamo di persona. Vuoi che lo chiami?\n\nMarco: Sì, spero che abbia tempo sabato.\n\nAnna: Se avesse tempo, sarei molto felice.',
    vocab: [
      { word: 'credi che', meaning: 'do you think that (+ subj.)' },
      { word: 'venga', meaning: 'comes (congiuntivo di venire)' },
      { word: 'spero che', meaning: 'I hope that (+ subj.)' },
      { word: 'sembra che', meaning: 'it seems that (+ subj.)' },
      { word: 'sia', meaning: 'is (congiuntivo di essere)' },
      { word: 'debba', meaning: 'must (congiuntivo di dovere)' },
    ],
    translation: 'Anna: Do you think Mario will come to the party on Saturday?\n\nMarco: I don\'t know. I hope he comes, but I think he is very tired.\n\nAnna: It seems he works too much. I believe he should rest.\n\nMarco: You are right. But I am sorry that he can\'t come often.\n\nAnna: Maybe it is better that we invite him in person. Do you want me to call him?\n\nMarco: Yes, I hope he has time on Saturday.\n\nAnna: If he had time, I would be very happy.',
    questions: [
      { question: 'What do they hope about Mario?', options: ['That he comes to the party', 'That he works less', 'That he calls them', 'That he rests tomorrow'], answer: 'That he comes to the party', explanation: '"Spero che venga, ma penso che sia molto stanco."' },
      { question: 'What does Anna think Mario needs to do?', options: ['Rest', 'Work harder', 'Call his boss', 'Leave town'], answer: 'Rest', explanation: '"Credo che lui debba riposarsi."' },
      { question: '"Sembra che lavori troppo" — "lavori" is:', options: ['congiuntivo', 'indicativo', 'infinito', 'imperativo'], answer: 'congiuntivo', explanation: 'After "sembra che" we use the congiuntivo.' },
      { question: '"Mi dispiace che non ___ venire spesso." (potere)', options: ['possa', 'può', 'poteva', 'potrà'], answer: 'possa', explanation: 'mi dispiace che → congiuntivo (possa).' },
      { question: '"Se avesse tempo, sarei felice" is type:', options: ['2 (hypothetical)', '1 (real)', '3 (past impossible)', 'an order'], answer: '2 (hypothetical)', explanation: 'se + imperfetto congiuntivo → condizionale presente.' },
      { question: 'Write one sentence using "credere che" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Credo che sia stanco. Any correct sentence with credere che + cong. is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Impersonal Expressions',
    storyTitle: 'Bisogna che',
    story: 'Dottore: Bisogna che tu beva più acqua e che riposi.\n\nMarco: Lo so, dottore. È necessario che io vada a letto prima.\n\nDottore: È importante che tu non prenda medicine da solo.\n\nMarco: Va bene. È meglio che parliate con mia madre della dieta?\n\nDottore: Certo. Spero che lei sia disponibile domani.\n\nMarco: Mi dispiace che il problema sia tornato.\n\nDottore: Non ti preoccupare. È possibile che tutto si risolva in fretta, se segui i consigli.',
    vocab: [
      { word: 'bisogna che', meaning: 'it is necessary that (+ subj.)' },
      { word: 'riposi', meaning: 'rest (congiuntivo di riposare)' },
      { word: 'è necessario che', meaning: 'it is necessary that (+ subj.)' },
      { word: 'è importante che', meaning: 'it is important that (+ subj.)' },
      { word: 'è meglio che', meaning: 'it is better that (+ subj.)' },
      { word: 'si risolva', meaning: 'resolves itself (congiuntivo)' },
    ],
    translation: 'Doctor: You must drink more water and rest.\n\nMarco: I know, doctor. It is necessary that I go to bed earlier.\n\nDoctor: It is important that you don\'t take medicine by yourself.\n\nMarco: OK. Is it better that you talk to my mother about the diet?\n\nDoctor: Of course. I hope she is available tomorrow.\n\nMarco: I am sorry that the problem has come back.\n\nDoctor: Don\'t worry. It is possible that everything resolves quickly, if you follow the advice.',
    questions: [
      { question: 'What must Marco drink and do?', options: ['More water and rest', 'Coffee and work', 'Tea and walk', 'Juice and run'], answer: 'More water and rest', explanation: '"Bisogna che tu beva più acqua e che riposi."' },
      { question: '"Bisogna che tu béva" — "béva" is the congiuntivo of:', options: ['bere', 'avere', 'essere', 'fare'], answer: 'bere', explanation: 'bere → che io beva.' },
      { question: 'What does the doctor hope is available tomorrow?', options: ['Marco\'s mother', 'The pharmacy', 'The medicine', 'The clinic'], answer: 'Marco\'s mother', explanation: '"Spero che lei sia disponibile domani."' },
      { question: '"È possibile che tutto si risolva" — this expresses:', options: ['possibility', 'a fact', 'an order', 'a question'], answer: 'possibility', explanation: 'è possibile che + congiuntivo = possibility.' },
      { question: 'The phrase used to forbid alone-medicine is:', options: ['È importante che tu non prenda medicine da solo', 'Prendi medicina da solo', 'Non importante', 'Devi comprare medicine'], answer: 'È importante che tu non prenda medicine da solo', explanation: 'Present in the dialogue.' },
      { question: 'Write one sentence using "è importante che" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: È importante che tu riposi. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 28,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Passato Congiuntivo',
    storyTitle: 'Il matrimonio',
    story: 'Lucia: Sono felice che tu sia venuto al matrimonio.\n\nPaolo: Certo! Non avrei voluto mancare. Peccato che abbia piovuto.\n\nLucia: Non importa! Penso che la cerimonia sia stata bellissima.\n\nPaolo: Sì. Credo che gli sposi abbiano scelto un luogo perfetto.\n\nLucia: Spero che i bambini si siano divertiti.\n\nPaolo: Pare che abbiano ballato tutta la sera!\n\nLucia: Che bello. Mi dispiace solo che mia cugina non sia potuta venire.',
    vocab: [
      { word: 'sia venuto', meaning: 'has come (passato congiuntivo, essere)' },
      { word: 'abbia piovuto', meaning: 'has rained (passato congiuntivo, avere)' },
      { word: 'sia stata', meaning: 'has been (passato congiuntivo, essere)' },
      { word: 'abbiano scelto', meaning: 'they have chosen (passato congiuntivo)' },
      { word: 'si siano divertiti', meaning: 'they have enjoyed themselves (passato congiuntivo)' },
      { word: 'non sia potuta venire', meaning: 'could not come (passato congiuntivo)' },
    ],
    translation: 'Lucia: I am happy that you came to the wedding.\n\nPaolo: Of course! I would not have wanted to miss it. Too bad it rained.\n\nLucia: It doesn\'t matter! I think the ceremony was beautiful.\n\nPaolo: Yes. I believe the couple chose a perfect venue.\n\nLucia: I hope the children had fun.\n\nPaolo: It seems they danced all evening!\n\nLucia: How nice. I am only sorry that my cousin could not come.',
    questions: [
      { question: 'How does Lucia feel about Paolo coming?', options: ['Happy', 'Angry', 'Indifferent', 'Surprised'], answer: 'Happy', explanation: '"Sono felice che tu sia venuto."' },
      { question: 'What is the regret in the dialogue?', options: ['It rained', 'The food was cold', 'The music was bad', 'The guests left early'], answer: 'It rained', explanation: '"Peccato che abbia piovuto."' },
      { question: '"Abbia piovuto" is the...', options: ['passato congiuntivo', 'presente congiuntivo', 'imperfetto congiuntivo', 'indicativo'], answer: 'passato congiuntivo', explanation: 'abbia + participle = passato congiuntivo.' },
      { question: '"Peccato che ___ piovuto." — the subject of the clause is:', options: ['the weather (it)', 'the couple', 'the children', 'Lucia'], answer: 'the weather (it)', explanation: 'piovuto is impersonal — "it rained".' },
      { question: 'The children: pare che ___ (ballare) tutta la sera.', options: ['abbiano ballato', 'abbia ballato', 'ballavano', 'balle'], answer: 'abbiano ballato', explanation: 'Che loro abbiano ballato.' },
      { question: 'Write a sentence with "penso che" + a past idea in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Penso che la cerimonia sia stata bella. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Regrets',
    storyTitle: 'Se solo avessi…',
    story: 'Giulia: Se solo avessi accettato quel lavoro a Roma!\n\nMarco: Perché non l\'hai fatto?\n\nGiulia: Avevo paura. Se fossi partita, ora vivrei in una città magnifica.\n\nMarco: Se avessi avuto più coraggio, avresti trovato tanti amici.\n\nGiulia: Forse. E se avessi studiato di più, parlarci meglio italiano.\n\nMarco: Non dire così. Se non avessi conosciuto Marco, non avresti neanche questa vita felice.\n\nGiulia: Hai ragione. È meglio che io pensi al presente.',
    vocab: [
      { word: 'se solo', meaning: 'if only' },
      { word: 'avessi accettato', meaning: 'I had accepted (trapassato cong., avere)' },
      { word: 'fossi partita', meaning: 'I had left (trapassato cong., essere)' },
      { word: 'avessi avuto', meaning: 'I had had (trapassato cong.)' },
      { word: 'avresti trovato', meaning: 'you would have found (condizionale passato)' },
      { word: 'parleresti', meaning: 'you would speak (condizionale presente)' },
    ],
    translation: 'Giulia: If only I had accepted that job in Rome!\n\nMarco: Why didn\'t you?\n\nGiulia: I was afraid. If I had left, now I would be living in a magnificent city.\n\nMarco: If you had had more courage, you would have found many friends.\n\nGiulia: Maybe. And if I had studied more, I would speak Italian better.\n\nMarco: Don\'t say that. If you hadn\'t met Marco, you wouldn\'t have this happy life either.\n\nGiulia: You are right. It is better that I think about the present.',
    questions: [
      { question: 'What does Giulia regret?', options: ['Not accepting a job in Rome', 'Accepting a job', 'Moving to Rome', 'Meeting Marco'], answer: 'Not accepting a job in Rome', explanation: '"Se solo avessi accettato quel lavoro a Roma!"' },
      { question: '"Avessi accettato" is the...', options: ['trapassato congiuntivo', 'presente congiuntivo', 'passato prossimo', 'condizionale passato'], answer: 'trapassato congiuntivo', explanation: 'avessi + participle = trapassato congiuntivo.' },
      { question: 'If she had left, she ___ in a magnificent city now. (imperfect cond.)', options: ['vivrebbe', 'vivrà', 'viveva', 'vivesse'], answer: 'vivrebbe', explanation: '"Se fossi partita, ora vivrei in una città magnifica."' },
      { question: 'The structure "se + trapassato cong. + condizionale passato" appears in:', options: ['avresti trovato tanti amici', 'vivrei in una città', 'è meglio che io pensi', 'non dire così'], answer: 'avresti trovato tanti amici', explanation: 'Se avessi avuto coraggio → avresti trovato.' },
      { question: 'Marco reminds Giulia that if she hadn\'t met Marco she:', options: ['wouldn\'t have this happy life', 'would be richer', 'would have moved', 'would be alone'], answer: 'wouldn\'t have this happy life', explanation: '"Se non avessi conosciuto Marco, non avresti neanche questa vita felice."' },
      { question: 'Write one regret using "se avessi…" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Se avessi saputo, sarei venuto. Any correct sentence is accepted.' },
    ],
  },

  // LEVEL 10 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 10 — Final Proficiency Test',
    title: 'Congiuntivo Mastery Test',
    instruction: 'Answer all the questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Recognition
      { question: 'The congiuntivo expresses:', options: ['subjectivity, doubt, emotion', 'only facts', 'only commands', 'only measurements'], answer: 'subjectivity, doubt, emotion' },
      { question: 'A subjunctive clause is usually introduced by:', options: ['che', 'di', 'per', 'e'], answer: 'che' },
      { question: 'The indicativo tells us something is:', options: ['certain', 'uncertain', 'hoped', 'feared'], answer: 'certain' },
      // Present forms
      { question: 'Penso che tu ___ (parlare) italiano.', options: ['parli', 'parla', 'parlava', 'parlerai'], answer: 'parli' },
      { question: 'Voglio che lui ___ (prendere) il treno.', options: ['prenda', 'prende', 'prendeva', 'prenderà'], answer: 'prenda' },
      { question: 'Spero che loro ___ (finire) i compiti.', options: ['finiscano', 'finiscono', 'finivano', 'finiranno'], answer: 'finiscano' },
      // Essere/avere/irregulars
      { question: 'Credo che tu ___ (essere) stanco.', options: ['sia', 'sei', 'eri', 'sarai'], answer: 'sia' },
      { question: 'È possibile che noi ___ (avere) ritardo.', options: ['abbiamo', 'abbi', 'avremo', 'avessimo'], answer: 'abbiamo' },
      { question: 'Voglio che voi ___ (fare) attenzione.', options: ['facciate', 'fate', 'farete', 'facevate'], answer: 'facciate' },
      { question: 'Spero che lui ___ (potere) venire.', options: ['possa', 'può', 'poteva', 'potrà'], answer: 'possa' },
      // Triggers: congiuntivo or indicativo
      { question: 'Which expression takes the INDICATIVO?', options: ['Sono sicuro che', 'Credo che', 'Mi dispiace che', 'È possibile che'], answer: 'Sono sicuro che' },
      { question: 'Which expression takes the CONGIUNTIVO?', options: ['Spero che', 'So che', 'È chiaro che', 'Vedo che'], answer: 'Spero che' },
      // Passato congiuntivo
      { question: 'Penso che Marco ___ (mangiare) troppo.', options: ['abbia mangiato', 'ha mangiato', 'avrà mangiato', 'mangia'], answer: 'abbia mangiato' },
      { question: 'Spero che Anna ___ (arrivare) a casa.', options: ['sia arrivata', 'abbi arrivato', 'ha arrivato', 'arrivasse'], answer: 'sia arrivata' },
      // Imperfetto congiuntivo
      { question: 'Volevo che tu ___ (parlare) con lui.', options: ['parlassi', 'parli', 'parlavi', 'parlerai'], answer: 'parlassi' },
      { question: 'Se ___ (io, essere) in te, non lo farei.', options: ['fossi', 'sono', 'sarò', 'essere'], answer: 'fossi' },
      // Trapassato & se-clauses
      { question: 'Se ___ (io, sapere), sarei venuto.', options: ['avessi saputo', 'ho saputo', 'avrò saputo', 'sappo'], answer: 'avessi saputo' },
      { question: 'Se tu ___ (studiare) di più, avresti passato.', options: ['avessi studiato', 'hai studiato', 'studiassi', 'studi'], answer: 'avessi studiato' },
      { question: 'In "Se avessi tempo, verrei" the se-clause is:', options: ['congiuntivo imperfetto', 'indicativo', 'futuro', 'condizionale'], answer: 'congiuntivo imperfetto' },
      // Structure & translation
      { question: '"Non credo che venga" means:', options: ['I don\'t think he is coming', 'He is not coming (fact)', 'Don\'t believe him', 'He cannot come here'], answer: 'I don\'t think he is coming' },
      { question: 'Correct structure for "It is better that we leave":', options: ['È meglio che noi usciamo ora', 'È meglio che noi esce', 'Noi è meglio uscire che', 'Che usciamo è meglio no'], answer: 'È meglio che noi usciamo ora' },
      // Reading
      { question: 'READ FIRST: "Penso che Marta sia molto capace, ma temo che non abbia abbastanza esperienza. Se avesse studiato economia, avrebbe trovato subito lavoro. È possibile che le offrano comunque un posto, ma è meglio che mandi anche altri curricula."\n\nWhat does the speaker think of Marta?', options: ['She is very capable', 'She is lazy', 'She is rude', 'She is too old'], answer: 'She is very capable' },
      { question: 'READ AGAIN: "temo che non abbia abbastanza esperienza" — the speaker:', options: ['fears she lacks experience', 'is sure she lacks experience', 'wants her experience', 'counts her experience'], answer: 'fears she lacks experience' },
      { question: 'READ AGAIN: "è meglio che mandi anche altri curricula" means:', options: ['It is better that she also send other CVs', 'She must not send CVs', 'The CVs are ready', 'She has already sent CVs'], answer: 'It is better that she also send other CVs' },
      // Production
      { question: 'Write "I think you are right" in Italian (opinion, not fact):', type: 'text', answer: 'Credo che tu abbia ragione', acceptedAnswers: ['credo che tu abbia ragione', 'io credo che tu abbia ragione', 'penso che tu abbia ragione'] },
      { question: 'Write "If I had known, I would have come" in Italian:', type: 'text', answer: 'Se avessi saputo, sarei venuto', acceptedAnswers: ['se avessi saputo sarei venuto', 'se avessi saputo, sarei venuto'] },
    ],
  },
];

export const congiuntivoStories = congiuntivoExercises.filter((e) => e.type === 'story');

export const congiuntivoFinalTest = congiuntivoExercises.find((e) => e.id === 30).questions;

export const congiuntivoFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You confidently use the congiuntivo in the present, past, and hypothetical sentences.' },
  { min: 75, grade: 'Very good!', message: 'You understand the subjunctive system. Review the irregular forms (sia, abbia, faccia) and the passato/imperfetto contrast.' },
  { min: 60, grade: 'Almost there!', message: 'Review the trigger expressions (penso che, è possibile che, mi dispiace che) and the regular subjunctive endings.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the lessons before taking the final test again.' },
];