export const condizionaleStages = [
  {
    id: 'concept',
    title: 'What is the Condizionale?',
    subtitle: 'The conditional mood and the periodo ipotetico (se-clauses)',
    sections: [
      {
        heading: 'Part 1 — What is the condizionale?',
        explanation: 'The condizionale is the Italian mood used for hypothetical situations, wishes, polite requests, and advice. It is the Italian equivalent of English "would" (andare – io andrei = I would go).',
        bullets: [
          { text: 'Vorrei un caffè, per favore.', example: 'I would like a coffee, please. (polite request)' },
          { text: 'Se avessi tempo, andrei al mare.', example: 'If I had time, I would go to the sea. (hypothetical)' },
          { text: 'Dovresti studiare di più.', example: 'You should study more. (advice with dovere)' },
        ],
        timeline: { left: 'PRESENT / FUTURE', center: 'HYPOTHETICAL', right: 'IMPOSSIBLE PAST', examples: ['Tipo 1: Se piove, resto a casa', 'Tipo 2: Se avessi tempo, uscirei', 'Tipo 3: Se avessi studiato, avrei passato'] },
        note: 'The condizionale never appears inside the "se" clause — it only appears in the main (result) clause of a conditional sentence.',
      },
      {
        heading: 'Part 2 — The periodo ipotetico',
        explanation: 'A conditional sentence (periodo ipotetico) has two parts: the "if" clause (protasi, introduced by SE) stating the condition, and the main clause (apodosi) stating the result. Italian has three types, from really possible to impossible.',
        bullets: [
          { text: 'PROTASI (se-clause): the condition, introduced by SE.', example: 'Se piove… → If it rains…' },
          { text: 'APODOSI (main clause): the result.', example: '…resto a casa. → …I stay home.' },
          { text: 'TIPO 1 — real/possible. SE + presente + presente/futuro.', example: 'Se studi, passi l\'esame. → If you study, you pass the exam.' },
          { text: 'TIPO 2 — hypothetical but possible. SE + congiuntivo imperfetto + condizionale presente.', example: 'Se avessi tempo, andrei in palestra. → If I had time, I would work out.' },
          { text: 'TIPO 3 — impossible (past). SE + congiuntivo trapassato + condizionale passato.', example: 'Se avessi studiato, avrei passato l\'esame. → If I had studied, I would have passed the exam.' },
        ],
        note: 'Remember the three types: TIPO 1 (present), TIPO 2 (congiuntivo imperfetto + condizionale), TIPO 3 (congiuntivo trapassato + condizionale passato).',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Forming the Condizionale',
    subtitle: 'Regular endings of the condizionale presente, plus the condizionale passato',
    sections: [
      {
        heading: 'Part 3 — The formula',
        explanation: 'Most verbs build the condizionale presente from the INFINITIVE, changing the final vowel like the future does, then adding conditional endings:\n\n• -ARE verbs change A → E: parlare → parler-\n• -ERE verbs keep -ER: prendere → prender- (many shorten: vedere → vedr-)\n• -IRE verbs keep -IR: partire → partir-\n\nThen add:',
        comparison: [
          { form: 'io', are: '-erei', ere: '-erei', ire: '-irei' },
          { form: 'tu', are: '-eresti', ere: '-eresti', ire: '-iresti' },
          { form: 'lui/lei', are: '-erebbe', ere: '-erebbe', ire: '-irebbe' },
          { form: 'noi', are: '-eremmo', ere: '-eremmo', ire: '-iremmo' },
          { form: 'voi', are: '-ereste', ere: '-ereste', ire: '-ireste' },
          { form: 'loro', are: '-erebbero', ere: '-erebbero', ire: '-irebbero' },
        ],
        note: 'The endings are the same for -ARE and -ERE verbs, but different for -IRE. Compare with the future: parlare → parlerò → parlerei.',
      },
      {
        heading: 'Part 4 — Regular -ARE verbs',
        explanation: 'Parlare → parlerei, mangiare → mangerei, lavorare → lavorerei, studiare → studierei.',
        verbs: [
          { infinitive: 'parlare', meaning: 'parlerei — I would speak' },
          { infinitive: 'lavorare', meaning: 'lavorerei — I would work' },
          { infinitive: 'mangiare', meaning: 'mangerei — I would eat' },
          { infinitive: 'studiare', meaning: 'studierei — I would study' },
          { infinitive: 'comprare', meaning: 'comprerei — I would buy' },
          { infinitive: 'guardare', meaning: 'guarderei — I would watch' },
          { infinitive: 'viaggiare', meaning: 'viaggerei — I would travel' },
        ],
        group: '-ARE',
        focus: { sentence: 'Se fossi ricco, comprerei una casa.', breakdown: [{ part: 'Se fossi', role: 'se-clause (condition)' }, { part: 'comprerei', role: 'condizionale di comprare' }, { part: 'una casa', role: 'object' }], meaning: 'If I were rich, I would buy a house.' },
      },
      {
        heading: 'Part 5 — Regular -ERE and -IRE verbs',
        explanation: '-ERE verbs keep -ER- and many shorten their stem exactly like the future: vedere → vedr-, vivere → vivr-. -IRE verbs stay regular: partire → partirei, dormire → dormirei.',
        verbs: [
          { infinitive: 'prendere', meaning: 'prenderei — I would take' },
          { infinitive: 'credere', meaning: 'crederei — I would believe' },
          { infinitive: 'vedere', meaning: 'vedrei — I would see' },
          { infinitive: 'vivere', meaning: 'vivrei — I would live' },
          { infinitive: 'partire', meaning: 'partirei — I would leave' },
          { infinitive: 'dormire', meaning: 'dormirei — I would sleep' },
          { infinitive: 'finire', meaning: 'finirei — I would finish' },
          { infinitive: 'sentire', meaning: 'sentirei — I would hear/feel' },
        ],
        group: '-ERE',
        examples: [
          { italian: 'Domani vedrei Marco.', translation: 'I would see Marco tomorrow.' },
          { italian: 'Vivrei in Italia.', translation: 'I would live in Italy.' },
          { italian: 'Partirei volentieri.', translation: 'I would happily leave.' },
        ],
        note: 'With -CARE/-GARE verbs you must add an H to keep the hard sound: giocare → giocherei (not "giocerei").',
      },
      {
        heading: 'Part 6 — The condizionale passato',
        explanation: 'The past conditional (condizionale passato) = condizionale of AVERE or ESSERE + past participle. It means "would have done" and is used for tipo 3 and regret.',
        bullets: [
          { text: 'avrei parlato — I would have spoken', example: 'Avrei parlato con lui, ma era tardi.' },
          { text: 'avrei mangiato — I would have eaten', example: 'Non avrei mangiato tanto.' },
          { text: 'sarei andato/a — I would have gone', example: 'Sarei andato al concerto, ma non avevo tempo.' },
          { text: 'saremmo partiti — we would have left', example: 'Saremmo partiti prima, se avessimo potuto.' },
        ],
        examples: [
          { italian: 'Avrei mangiato prima, ma non ho avuto tempo.', translation: 'I would have eaten earlier, but I didn\'t have time.' },
          { italian: 'Sarei andato/a a Roma.', translation: 'I would have gone to Rome.' },
          { italian: 'Non saremmo arrivati in ritardo.', translation: 'We wouldn\'t have arrived late.' },
        ],
        note: 'With ESSERE the participle agrees with the subject: Laura sarebbe andata, noi saremmo partiti.',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'Essere, Avere & Irregular Stems',
    subtitle: 'The most useful irregular conditional verbs, plus the subjunctive in se-clauses',
    sections: [
      {
        heading: 'Part 7 — Essere',
        explanation: 'Essere has the irregular stem SAR- in the condizionale: sarei, saresti, sarebbe… Learn these forms by heart:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'sarei' }, { pronoun: 'tu', ending: 'saresti' }, { pronoun: 'lui/lei', ending: 'sarebbe' }, { pronoun: 'noi', ending: 'saremmo' }, { pronoun: 'voi', ending: 'sareste' }, { pronoun: 'loro', ending: 'sarebbero' }] },
        examples: [
          { italian: 'Sarei a casa domani.', translation: 'I would be at home tomorrow.' },
          { italian: 'Sarebbe meglio partire presto.', translation: 'It would be better to leave early.' },
          { italian: 'Non saremmo stanchi.', translation: 'We wouldn\'t be tired.' },
        ],
      },
      {
        heading: 'Part 8 — Avere',
        explanation: 'Avere has the irregular stem AVR- in the condizionale: avrei, avresti, avrebbe…',
        conjugations: { rows: [{ pronoun: 'io', ending: 'avrei' }, { pronoun: 'tu', ending: 'avresti' }, { pronoun: 'lui/lei', ending: 'avrebbe' }, { pronoun: 'noi', ending: 'avremmo' }, { pronoun: 'voi', ending: 'avreste' }, { pronoun: 'loro', ending: 'avrebbero' }] },
        examples: [
          { italian: 'Avrei una domanda.', translation: 'I would have a question.' },
          { italian: 'Avresti fame?', translation: 'Would you (tu) be hungry?' },
          { italian: 'Avremmo più tempo.', translation: 'We would have more time.' },
        ],
      },
      {
        heading: 'Part 9 — Common irregular stems',
        explanation: 'The most common irregular condizionale stems are the same ones you know from the FUTURE. The endings -ei, -esti, -ebbe never change — only the stem is irregular.',
        patterns: ['andare → andr- → andrei', 'venire → verr- → verrei', 'fare → far- → farei', 'dare → dar- → darei', 'potere → potr- → potrei', 'dovere → dovr- → dovrei', 'volere → vorr- → vorrei', 'sapere → sapr- → saprei', 'bere → berr- → berrei', 'rimanere → rimarr- → rimarrei'],
        examples: [
          { italian: 'Vorrei due biglietti.', translation: 'I would like two tickets.' },
          { italian: 'Potresti aiutarmi?', translation: 'Could you help me?' },
          { italian: 'Dovremmo parlare.', translation: 'We should talk.' },
        ],
        note: 'vorrei (I would like), potrei (I could), dovrei (I should), potresti (you could) are essential for everyday politeness.',
      },
      {
        heading: 'Part 10 — The subjunctive in the se-clause',
        explanation: 'In TIPO 2 and TIPO 3, the se-clause does NOT use the conditional or the future — it uses the CONGIUNTIVO (subjunctive). Learn the congiuntivo imperfetto of essere and avere:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'fossi / avessi' }, { pronoun: 'tu', ending: 'fossi / avessi' }, { pronoun: 'lui/lei', ending: 'fosse / avesse' }, { pronoun: 'noi', ending: 'fossimo / avessimo' }, { pronoun: 'voi', ending: 'foste / aveste' }, { pronoun: 'loro', ending: 'fossero / avessero' }] },
        bullets: [
          { text: 'Se fossi in te, lo farei.', example: 'If I were you, I would do it.' },
          { text: 'Se avessi tempo, ti aiuterei.', example: 'If I had time, I would help you.' },
          { text: 'Other verbs add -assi (parlare), -essi (prendere), -issi (partire).', example: 'Se parlassi italiano bene… / Se partissi domani…' },
        ],
        note: 'In se-clauses the present/past subjunctive replaces the imperfetto indicativo you might expect from English: "se avessi" = if I had, "se fossi andato" = if I had gone.',
      },
    ],
  },
  {
    id: 'usage',
    title: 'The Three Types & Everyday Use',
    subtitle: 'Real, hypothetical, and impossible conditions — plus polite requests and advice',
    sections: [
      {
        heading: 'Part 11 — TIPO 1: real and possible',
        explanation: 'TIPO 1 describes real, likely conditions. SE + presente, result in presente or futuro. It is the most common type in speech.',
        bullets: [
          { text: 'Se piove, prendo l\'ombrello.', example: 'If it rains, I take the umbrella.' },
          { text: 'Se studi, passerai l\'esame.', example: 'If you study, you will pass the exam.' },
          { text: 'Se vuoi, vengo con te.', example: 'If you want, I\'m coming with you.' },
          { text: 'Se hai caldo, apri la finestra.', example: 'If you\'re hot, open the window.' },
        ],
        note: 'In the se-clause we never use the future: "Se domani fa bel tempo, usciamo" (not "se farà"). The presente covers the future condition.',
      },
      {
        heading: 'Part 12 — TIPO 2: hypothetical',
        explanation: 'TIPO 2 describes situations that are only imagined or unlikely: SE + congiuntivo imperfetto + condizionale presente.',
        bullets: [
          { text: 'Se avessi più soldi, viaggerei di più.', example: 'If I had more money, I would travel more.' },
          { text: 'Se fossi ricco, comprerei una casa al mare.', example: 'If I were rich, I would buy a seaside house.' },
          { text: 'Se potessi, ti aiuterei.', example: 'If I could, I would help you.' },
          { text: 'Se fossi in te, parlerei con lui.', example: 'If I were you, I would talk to him.' },
        ],
        note: 'This is the standard structure for ADVICE and WISHES. Learn the pair: congiuntivo imperfetto (se-clause) + condizionale presente (result).',
      },
      {
        heading: 'Part 13 — TIPO 3: impossible past',
        explanation: 'TIPO 3 describes conditions that did NOT happen (regret about the past): SE + congiuntivo trapassato + condizionale passato.',
        bullets: [
          { text: 'Se avessi studiato, avrei passato l\'esame.', example: 'If I had studied, I would have passed the exam. (I didn\'t study → I failed)' },
          { text: 'Se fossi partito prima, non avrei perso il treno.', example: 'If I had left earlier, I wouldn\'t have missed the train.' },
          { text: 'L\'avrei aiutato, se avessi saputo.', example: 'I would have helped him if I had known.' },
          { text: 'Saremmo usciti, se non avesse piovuto.', example: 'We would have gone out if it hadn\'t rained.' },
        ],
        note: 'Congiuntivo trapassato = congiuntivo imperfetto of avere/essere + participle (avessi studiato, fossi partito).',
      },
      {
        heading: 'Part 14 — Politeness, wishes, and advice',
        explanation: 'The condizionale makes requests, questions, and suggestions much more polite. It is essential in shops, restaurants, offices, and with strangers.',
        bullets: [
          { text: 'Vorrei un caffè, per favore.', example: 'I would like a coffee, please.' },
          { text: 'Potrebbe aiutarmi?', example: 'Could you help me? (formal Lei)' },
          { text: 'Mi piacerebbe visitare Roma.', example: 'I would love to visit Rome.' },
          { text: 'Dovremmo parlare.', example: 'We should talk.' },
          { text: 'Se fossi in te, non lo farei.', example: 'If I were you, I wouldn\'t do it.' },
        ],
        note: 'Compare: "Voglio un caffè" (direct, casual) vs "Vorrei un caffè" (polite). In formal situations always prefer the condizionale.',
      },
    ],
  },
];

export const condizionaleExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Understanding the Conditional Mood',
    instruction: 'Recognise what a condizionale sentence is and how it is used.',
    questions: [
      { question: '"Vorrei un caffè" is an example of a:', options: ['Polite request', 'Past event', 'Command', 'Habit'], answer: 'Polite request', explanation: '"Vorrei" = I would like. It softens a request.' },
      { question: 'The condizionale is the Italian equivalent of the English word:', options: ['would', 'will', 'did', 'should have been'], answer: 'would', explanation: 'andrei = I would go, avrei = I would have.' },
      { question: 'Which sentence uses the condizionale?', options: ['Se avessi tempo, andrei al mare', 'Domani andrò al mare', 'Ieri sono andato al mare', 'Vado al mare ogni estate'], answer: 'Se avessi tempo, andrei al mare', explanation: '"andrei" is the condizionale; "andrò" is future, "sono andato" is past, "vado" is present.' },
      { question: '"Se studi, passi l\'esame" is a:', options: ['Real condition (tipo 1)', 'Hypothetical condition (tipo 2)', 'Past condition (tipo 3)', 'A question'], answer: 'Real condition (tipo 1)', explanation: 'Both verbs are present — real and possible.' },
      { question: 'The "protasi" (se-clause) states:', options: ['The condition', 'The result', 'The polite request', 'The question'], answer: 'The condition', explanation: 'Protasi = the if-clause introduced by SE.' },
    ],
  },
  {
    id: 2,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Spot the Three Types',
    instruction: 'Identify whether each sentence is tipo 1, 2, or 3.',
    questions: [
      { question: '"Se avessi tempo, andrei in palestra."', options: ['Tipo 2', 'Tipo 1', 'Tipo 3', 'No conditional'], answer: 'Tipo 2', explanation: 'congiuntivo imperfetto (avessi) + condizionale (andrei) → hypothetical.' },
      { question: '"Se avessi studiato, avrei passato l\'esame."', options: ['Tipo 3', 'Tipo 1', 'Tipo 2', 'Polite request'], answer: 'Tipo 3', explanation: 'congiuntivo trapassato (avessi studiato) + condizionale passato (avrei passato) → impossible past.' },
      { question: '"Se piove, prendo l\'ombrello."', options: ['Tipo 1', 'Tipo 2', 'Tipo 3', 'A wish'], answer: 'Tipo 1', explanation: 'SE + presente + presente → real, possible.' },
      { question: '"Se fossi in te, parlerei con il capo."', options: ['Tipo 2', 'Tipo 3', 'Tipo 1', 'A fact'], answer: 'Tipo 2', explanation: '"fossi" (congiuntivo) + "parlerei" (condizionale) → hypothetical advice.' },
      { question: 'In the se-clause we NEVER use:', options: ['The condizionale', 'The presente', 'The congiuntivo', 'The verb essere'], answer: 'The condizionale', explanation: 'The conditional only appears in the result (main) clause.' },
    ],
  },
  {
    id: 3,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match the Conditional Sentences',
    instruction: 'Match each conditional sentence with the correct type.',
    pairs: [
      { left: 'Se piove, resto a casa.', right: 'Tipo 1 (real)' },
      { left: 'Se avessi tempo, verrei.', right: 'Tipo 2 (hypothetical)' },
      { left: 'Se avessi saputo, sarei venuto.', right: 'Tipo 3 (impossible past)' },
      { left: 'Se vuoi, ti aiuto.', right: 'Tipo 1 (real)' },
      { left: 'Se fossi ricco, comprerei una villa.', right: 'Tipo 2 (hypothetical)' },
    ],
    explanation: 'Check the verb forms: type 1 uses presente, type 2 uses congiuntivo imperfetto + condizionale, type 3 uses congiuntivo trapassato + condizionale passato.',
  },

  // LEVEL 2 — FORMATION
  {
    id: 4,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Regular -ARE Endings',
    instruction: 'Choose the correct condizionale presente form of each -are verb.',
    questions: [
      { sentence: 'Io ___ (parlare) con Marco.', options: ['parlerei', 'parlavo', 'parlerò', 'parlerai'], answer: 'parlerei', explanation: 'parlare → parler- + -ei.' },
      { sentence: 'Tu ___ (mangiare) la pizza.', options: ['mangeresti', 'mangerai', 'mangiavi', 'mangiassi'], answer: 'mangeresti', explanation: 'mangiare → manger- + -esti. (drop the i of -giare)' },
      { sentence: 'Lui ___ (lavorare) qui.', options: ['lavorerebbe', 'lavorerà', 'lavorava', 'lavori'], answer: 'lavorerebbe', explanation: 'lavorare → lavorer- + -ebbe.' },
      { sentence: 'Noi ___ (comprare) una casa.', options: ['compreremmo', 'compreremo', 'compravamo', 'comprerei'], answer: 'compreremmo', explanation: 'comprare → comprer- + -emmo.' },
      { sentence: 'Loro ___ (guardare) la partita.', options: ['guarderebbero', 'guarderanno', 'guardavano', 'guardereste'], answer: 'guarderebbero', explanation: 'guardare → guarder- + -ebbero.' },
    ],
  },
  {
    id: 5,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Regular -ERE and -IRE Endings',
    instruction: 'Choose the correct condizionale presente form of each -ere/-ire verb.',
    questions: [
      { sentence: 'Io ___ (prendere) il treno.', options: ['prenderei', 'prenderò', 'prendeva', 'prendessi'], answer: 'prenderei', explanation: 'prendere → prender- + -ei (regular -ere).' },
      { sentence: 'Lei ___ (vedere) il film.', options: ['vedrebbe', 'vederà', 'vedeva', 'vedeste'], answer: 'vedrebbe', explanation: 'vedere shortens to vedr- + -ebbe.' },
      { sentence: 'Noi ___ (dormire) di più.', options: ['dormiremmo', 'dormiremo', 'dormivamo', 'dormireste'], answer: 'dormiremmo', explanation: 'dormire → dormir- + -emmo.' },
      { sentence: 'Voi ___ (partire) domani.', options: ['partireste', 'partirete', 'partivate', 'partirei'], answer: 'partireste', explanation: 'partire → partir- + -este.' },
      { sentence: 'Loro ___ (vivere) in Italia.', options: ['vivrebbero', 'vivranno', 'vivevano', 'vivrebbe'], answer: 'vivrebbero', explanation: 'vivere shortens to vivr- + -ebbero.' },
    ],
  },
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Spelling Changes',
    instruction: 'Complete the sentences with the correct forms (watch the -care/-gare/-ciare changes).',
    questions: [
      { sentence: 'Noi ___ (giocare) a calcio.', options: ['giocheremmo', 'gioceremmo', 'giocheremo', 'giocavamo'], answer: 'giocheremmo', explanation: '-care keeps the hard sound: giocare → giocher- + -emmo.' },
      { sentence: 'Tu ___ (pagare) di più.', options: ['pagheresti', 'pagaresti', 'pagarai', 'pagavi'], answer: 'pagheresti', explanation: 'pagare → pagher- + -esti.' },
      { sentence: 'Io ___ (mangiare) volentieri.', options: ['mangerei', 'mangieri', 'mangierei', 'mangerò'], answer: 'mangerei', explanation: '-giare drops the i: mang-… + -erei → mangerei.' },
      { sentence: 'Se potessi, noi ___ (viaggiare) più spesso.', options: ['viaggeremmo', 'viaggieremmo', 'viaggeremo', 'viaggiavamo'], answer: 'viaggeremmo', explanation: 'viaggiare → viagger- + -emmo.' },
      { sentence: 'Lei ___ (cercare) la chiave.', options: ['cercherebbe', 'cierebbe', 'cercherà', 'cercava'], answer: 'cercherebbe', explanation: 'cercare → cercher- + -ebbe.' },
    ],
  },

  // LEVEL 3 — IRREGULARS
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 3 — Essere, Avere & Irregular Stems',
    title: 'Essere and Avere',
    instruction: 'Complete the sentences with the condizionale of ESSERE or AVERE.',
    questions: [
      { sentence: 'Io ___ (essere) a casa.', options: ['sarei', 'sarò', 'ero', 'sarebe'], answer: 'sarei', explanation: 'essere → sarei.' },
      { sentence: 'Tu ___ (avere) fame.', options: ['avresti', 'avrai', 'avevi', 'avessi'], answer: 'avresti', explanation: 'avere → avresti.' },
      { sentence: 'Lui ___ (essere) contento.', options: ['sarebbe', 'sarà', 'era', 'sarebe'], answer: 'sarebbe', explanation: 'essere → sarebbe.' },
      { sentence: 'Noi ___ (avere) più tempo.', options: ['avremmo', 'avremo', 'avevamo', 'avessimo'], answer: 'avremmo', explanation: 'avere → avremmo.' },
      { sentence: 'Loro ___ (essere) d\'accordo.', options: ['sarebbero', 'saranno', 'erano', 'sarebe'], answer: 'sarebbero', explanation: 'essere → sarebbero.' },
    ],
  },
  {
    id: 8,
    type: 'fillblank',
    level: 'Level 3 — Essere, Avere & Irregular Stems',
    title: 'Irregular Stems I',
    instruction: 'Complete with the correct irregular condizionale form.',
    questions: [
      { sentence: 'Io ___ (andare) con voi.', options: ['andrei', 'andrei', 'andrebbero', 'andai'], answer: 'andrei', explanation: 'andare → andr- + -ei.' },
      { sentence: 'Che cosa ___ (fare) tu?', options: ['faresti', 'farai', 'fai', 'faro'], answer: 'faresti', explanation: 'fare → far- + -esti.' },
      { sentence: 'Loro ___ (venire) alla festa.', options: ['verrebbero', 'verranno', 'venivano', 'verrebbe'], answer: 'verrebbero', explanation: 'venire → verr- + -ebbero.' },
      { sentence: 'Io ___ (potere) aiutarti.', options: ['potrei', 'potrò', 'posso', 'potevo'], answer: 'potrei', explanation: 'potere → potr- + -ei.' },
      { sentence: 'Noi ___ (dovere) studiare.', options: ['dovremmo', 'dovremo', 'dovevamo', 'dovrei'], answer: 'dovremmo', explanation: 'dovere → dovr- + -emmo.' },
    ],
  },
  {
    id: 9,
    type: 'matching',
    level: 'Level 3 — Essere, Avere & Irregular Stems',
    title: 'Irregular Stems II',
    instruction: 'Match each infinitive with its irregular condizionale stem.',
    pairs: [
      { left: 'volere', right: 'vorr- → vorrei' },
      { left: 'sapere', right: 'sapr- → saprei' },
      { left: 'bere', right: 'berr- → berrei' },
      { left: 'rimanere', right: 'rimarr- → rimarrei' },
      { left: 'vedere', right: 'vedr- → vedrei' },
    ],
    explanation: 'These irregular stems are identical to the future stems. Only the ending changes.',
  },
  {
    id: 10,
    type: 'multiple',
    level: 'Level 3 — Essere, Avere & Irregular Stems',
    title: 'The Subjunctive in the se-clause',
    instruction: 'Choose the correct CONGIUNTIVO form for the se-clause.',
    questions: [
      { question: 'Se ___ in te, non andrei. (essere)', options: ['fossi', 'sei', 'ero', 'sarei'], answer: 'fossi', explanation: 'Se + congiuntivo imperfetto of essere → fossi.' },
      { question: 'Se ___ tempo, ti aiuterei. (avere)', options: ['avessi', 'ho', 'avevo', 'avrei'], answer: 'avessi', explanation: 'Se + congiuntivo imperfetto → avessi.' },
      { question: 'Se ___ italiano meglio, vivrei qui. (parlare)', options: ['parlassi', 'parlo', 'parlavo', 'parlerei'], answer: 'parlassi', explanation: '-are → -assi: parlare → parlassi.' },
      { question: 'Se ___ domani, ti avviserei. (partire)', options: ['partissi', 'parto', 'partivo', 'partirei'], answer: 'partissi', explanation: '-ire → -issi: partire → partissi.' },
      { question: 'Se ___ qui, sarebbe perfetto. (essere, loro)', options: ['fossero', 'sono', 'erano', 'sarebbero'], answer: 'fossero', explanation: 'essere (loro) → fossero.' },
    ],
  },

  // LEVEL 4 — PAST CONDITIONAL
  {
    id: 11,
    type: 'multiple',
    level: 'Level 4 — The Condizionale Passato',
    title: 'Would Have + Participle',
    instruction: 'Complete the condizionale passato with the correct words.',
    questions: [
      { question: 'Avrei ___ (mangiare) quella pizza.', options: ['mangiato', 'mangiare', 'mangiata', 'mangiasse'], answer: 'mangiato', explanation: 'avrei + past participle (mangiato).' },
      { question: 'Avresti ___ (parlare) con lui.', options: ['parlato', 'parlare', 'parlato il', 'parlerei'], answer: 'parlato', explanation: 'avresti + parlato.' },
      { question: 'Sarei ___ (andare) al concerto.', options: ['andato', 'andare', 'andato a', 'andata e'], answer: 'andato', explanation: 'sarei + andato (m.).' },
      { question: 'Non ___ mangiato tanto. (io)', options: ['avrei', 'sarei', 'ho', 'avrò'], answer: 'avrei', explanation: 'mangiare takes avere → non avrei mangiato.' },
      { question: 'Sarebbe ___ con noi. (venire, lui)', options: ['venuto', 'venire', 'venuta', 'viene'], answer: 'venuto', explanation: 'venire takes essere → sarebbe venuto.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 4 — The Condizionale Passato',
    title: 'avrei or sarei?',
    instruction: 'Choose the correct auxiliary: AVERE or ESSERE.',
    questions: [
      { sentence: 'Io ___ mangiato prima.', options: ['avrei', 'sarei', 'ho', 'sarò'], answer: 'avrei', explanation: 'mangiare uses avere.' },
      { sentence: 'Laura ___ andata a Roma.', options: ['sarebbe', 'avrebbe', 'era', 'andasso'], answer: 'sarebbe', explanation: 'andare uses essere; participle agrees (andata).' },
      { sentence: 'Noi ___ parlato tanto.', options: ['avremmo', 'saremmo', 'abbiamo', 'avranno'], answer: 'avremmo', explanation: 'parlare uses avere.' },
      { sentence: 'Voi ___ partiti prima.', options: ['sareste', 'avreste', 'siete', 'andreste'], answer: 'sareste', explanation: 'partire uses essere; participle agrees (partiti).' },
      { sentence: 'Loro ___ cenato al ristorante.', options: ['avrebbero', 'sarebbero', 'hanno', 'avrò'], answer: 'avrebbero', explanation: 'cenare uses avere.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 4 — The Condizionale Passato',
    title: 'Build the Past Conditional',
    instruction: 'Complete each sentence with the full condizionale passato.',
    questions: [
      { sentence: 'Io ___ (finire) prima.', options: ['avrei finito', 'sarei finito', 'finirei', 'finivo'], answer: 'avrei finito', explanation: 'finire (avere) → avrei finito.' },
      { sentence: 'Lei ___ (uscire) con noi.', options: ['sarebbe uscita', 'avrebbe uscito', 'uscirebbe', 'usciva'], answer: 'sarebbe uscita', explanation: 'uscire (essere) → sarebbe uscita (agreement).' },
      { sentence: 'Tu ___ (leggere) il libro.', options: ['avresti letto', 'saresti letto', 'leggeresti', 'leggevi'], answer: 'avresti letto', explanation: 'leggere (avere), irregular participle letto → avresti letto.' },
      { sentence: 'Noi ___ (arrivare) in tempo.', options: ['saremmo arrivati', 'avremmo arrivato', 'arriveremmo', 'arrivavamo'], answer: 'saremmo arrivati', explanation: 'arrivare (essere) → saremmo arrivati.' },
      { sentence: 'Loro ___ (bere) troppo.', options: ['avrebbero bevuto', 'sarebbero bevuto', 'berranno', 'bevevano'], answer: 'avrebbero bevuto', explanation: 'bere (avere), participle bevuto → avrebbero bevuto.' },
    ],
  },

  // LEVEL 5 — TIPO 1
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 5 — Tipo 1: Real Conditions',
    title: 'Se + Presente → Presente',
    instruction: 'Complete the tipo 1 sentences (real conditions).',
    questions: [
      { sentence: 'Se ___ bel tempo, andiamo al parco. (fare)', options: ['fa', 'faccia', 'farebbe', 'farà'], answer: 'fa', explanation: 'Se + presente → presente. Never use future in the se-clause.' },
      { sentence: 'Se hai freddo, ___ la giacca. (mettere)', options: ['metti', 'metteresti', 'metterai', 'mettessi'], answer: 'metti', explanation: 'Imperative or present in the result: "metti" (you put on).' },
      { sentence: 'Se studi, ___ l\'esame. (passare)', options: ['passerai', 'passereesti', 'passi', 'passassi'], answer: 'passerai', explanation: 'The result may use the future: passerai.' },
      { sentence: 'Se vuoi, ___ con te. (venire)', options: ['vengo', 'verrei', 'venissi', 'vieni'], answer: 'vengo', explanation: 'Se + presente (vuoi) → presente (vengo).' },
      { sentence: 'Se non hai tempo, ___ dopo. (chiamare)', options: ['chiama', 'chiamerebbe', 'chiamerai', 'chiamasse'], answer: 'chiama', explanation: 'Result as imperative: "chiama" (call me later).' },
    ],
  },
  {
    id: 15,
    type: 'multiple',
    level: 'Level 5 — Tipo 1: Real Conditions',
    title: 'Real Conditions in Context',
    instruction: 'Choose the best or correct tipo 1 sentence.',
    questions: [
      { question: '"Se piove, prendo l\'ombrello" in English:', options: ['If it rains, I take the umbrella', 'If it rained, I would take the umbrella', 'If it had rained, I would have taken it'], answer: 'If it rains, I take the umbrella', explanation: 'Both present → real condition.' },
      { question: 'Which sentence is correct tipo 1?', options: ['Se domani fa bel tempo, usciamo', 'Se domani farà bel tempo, usciamo', 'Se domani farebbe bel tempo, usciamo'], answer: 'Se domani fa bel tempo, usciamo', explanation: 'Italian uses present in the se-clause even for tomorrow.' },
      { question: '"Se hai sete, ___ acqua."', options: ['bevi', 'berresti', 'beva', 'bevvi'], answer: 'bevi', explanation: 'Result often imperative: bevi (drink).' },
      { question: 'Tipo 1 describes:', options: ['Real, possible conditions', 'Impossible past conditions', 'Polite wishes', 'Hypothetical dreams'], answer: 'Real, possible conditions', explanation: 'Tipo 1 = real and likely.' },
      { question: '"Se studi molto, imparerai l\'italiano" — the result uses:', options: ['futuro', 'condizionale passato', 'congiuntivo', 'imperfetto'], answer: 'futuro', explanation: 'imparerai = future (passerai-type result).' },
    ],
  },

  // LEVEL 6 — TIPO 2
  {
    id: 16,
    type: 'fillblank',
    level: 'Level 6 — Tipo 2: Hypothetical',
    title: 'Se + Congiuntivo → Condizionale',
    instruction: 'Complete the tipo 2 sentences.',
    questions: [
      { sentence: 'Se ___ tempo, andrei al mare. (avere)', options: ['avessi', 'ho', 'avevo', 'avrei'], answer: 'avessi', explanation: 'se-clause needs congiuntivo imperfetto: avessi.' },
      { sentence: 'Se ___ ricco, comprerei una casa. (essere)', options: ['fossi', 'sono', 'ero', 'sarei'], answer: 'fossi', explanation: 'essere → fossi.' },
      { sentence: 'Se potessi, ___ in Sicilia. (vivere)', options: ['vivrei', 'vivo', 'vivevo', 'vivrò'], answer: 'vivrei', explanation: 'result uses condizionale: vivrei.' },
      { sentence: 'Se ___ di più, parleresti meglio. (studiare)', options: ['studiassi', 'studi', 'studiavi', 'studieresti'], answer: 'studiassi', explanation: 'studiare → studiassi (congiuntivo).' },
      { sentence: 'Se fossi in te, io ___ con lui. (parlare)', options: ['parlerei', 'parlessi', 'parlo', 'parlai'], answer: 'parlerei', explanation: 'result: condizionale presente parlerei.' },
    ],
  },
  {
    id: 17,
    type: 'multiple',
    level: 'Level 6 — Tipo 2: Hypothetical',
    title: 'Choose the Correct Pair',
    instruction: 'Select the correct se-clause + result combination for tipo 2.',
    questions: [
      { question: 'Se ___ , ti aiuterei.', options: ['potessi', 'posso', 'potevo', 'potrei'], answer: 'potessi', explanation: 'se-clause takes congiuntivo (potessi); result takes condizionale (aiuterei).' },
      { question: 'Which is correct?', options: ['Se avessi tempo, ti aiuterei', 'Se ho tempo, ti aiuterei', 'Se avevo tempo, ti aiuterei', 'Se avrei tempo, ti aiuterei'], answer: 'Se avessi tempo, ti aiuterei', explanation: 'avessi (congiuntivo) + aiuterei (condizionale).' },
      { question: '"Se fossi in te" means:', options: ['If I were you', 'If I am you', 'You are me', 'If I have you'], answer: 'If I were you', explanation: 'Se + fosse (imperfetto congiuntivo di essere), fixed expression for advice.' },
      { question: '"If I had money, I would travel" =', options: ['Se avessi soldi, viaggerei', 'Se ho soldi, viaggio', 'Se avevo soldi, viaggiavo', 'Se avrò soldi, viaggerò'], answer: 'Se avessi soldi, viaggerei', explanation: 'avessi (congiuntivo) + viaggerei (condizionale).' },
      { question: 'Tipo 2 is used to:', options: ['Talk about hypothetical/unlikely situations', 'Describe facts', 'Give commands', 'Talk about the past'], answer: 'Talk about hypothetical/unlikely situations', explanation: 'e.g. wishes and advice.' },
    ],
  },
  {
    id: 18,
    type: 'translation',
    level: 'Level 6 — Tipo 2: Hypothetical',
    title: 'Translate the Hypotheticals',
    instruction: 'Choose the correct English meaning.',
    direction: 'it-en',
    questions: [
      { sentence: 'Se avessi più tempo, studierei l\'italiano.', options: ['If I had more time, I would study Italian', 'If I have more time, I will study Italian', 'If I had had more time, I would have studied Italian'], answer: 'If I had more time, I would study Italian', explanation: 'tipo 2: avessi + studierei.' },
      { sentence: 'Se fossi ricco, comprerei una villa.', options: ['If I were rich, I would buy a villa', 'If I am rich, I buy a villa', 'If I had been rich, I would have bought a villa'], answer: 'If I were rich, I would buy a villa', explanation: 'tipo 2 hypothetical.' },
      { sentence: 'Vorrei due biglietti, per favore.', options: ['I would like two tickets, please', 'I will take two tickets, please', 'I had two tickets, please'], answer: 'I would like two tickets, please', explanation: 'polite request with vorrei.' },
      { sentence: 'Potresti chiudere la porta?', options: ['Could you close the door?', 'You closed the door?', 'Were you closing the door?'], answer: 'Could you close the door?', explanation: 'potresti (tu) + infinitive = polite request.' },
    ],
  },

  // LEVEL 7 — TIPO 3
  {
    id: 19,
    type: 'fillblank',
    level: 'Level 7 — Tipo 3: Impossible Past',
    title: 'Se + Congiuntivo Trapassato → Condizionale Passato',
    instruction: 'Complete the tipo 3 sentences (regret about the past).',
    questions: [
      { sentence: 'Se ___ studiato, avrei passato l\'esame. (avere)', options: ['avessi', 'ho', 'avevo', 'avessi ho'], answer: 'avessi', explanation: 'congiuntivo trapassato = avessi + studiato.' },
      { sentence: 'Se ___ partito prima, non avrei perso il treno. (essere)', options: ['fossi', 'ero', 'sono', 'sarei'], answer: 'fossi', explanation: 'congiuntivo trapassato con essere = fossi + partito.' },
      { sentence: 'Se avessi saputo, ___ venuto. (essere)', options: ['sarei', 'avrei', 'sarò', 'ero'], answer: 'sarei', explanation: 'venire (essere) → sarei venuto.' },
      { sentence: 'L\'avrei mangiato, se ___ fame. (avere)', options: ['avessi avuto', 'ho avuto', 'avevo avuto', 'avrò avuto'], answer: 'avessi avuto', explanation: 'congiuntivo trapassato di avere = avessi avuto.' },
      { sentence: 'Saremmo usciti, se ___ piovuto. (non avere)', options: ['non avesse', 'non aveva', 'non abbia', 'non aveva avuto'], answer: 'non avesse', explanation: 'piovono/l’uomo → impersonal with avere: non avesse piovuto.' },
    ],
  },
  {
    id: 20,
    type: 'multiple',
    level: 'Level 7 — Tipo 3: Impossible Past',
    title: 'Choose the Correct Tipo 3 Form',
    instruction: 'Select the correct forms to build tipo 3 sentences.',
    questions: [
      { question: '"Se avessi studiato, avrei passato l\'esame" implies:', options: ['I didn\'t study and I failed', 'I studied and passed', 'I will study', 'I am studying now'], answer: 'I didn\'t study and I failed', explanation: 'Tipo 3 = the condition did NOT happen.' },
      { question: 'Which is correct?', options: ['Se fossi andato, l\'avrei vista', 'Se sarei andato, l\'avrei vista', 'Se sono andato, la vedo', 'Se andrei, la vedo'], answer: 'Se fossi andato, l\'avrei vista', explanation: 'fossi andato (congiuntivo trapassato) + avrei vista (condizionale passato).' },
      { question: '"Se non avessi dormito tanto, ___ il treno."', options: ['avresti preso', 'prenderesti', 'prenderai', 'prendi'], answer: 'avresti preso', explanation: 'condizionale passato = avresti + preso.' },
      { question: 'Tipo 3 expresses:', options: ['Regret about the past', 'A present wish', 'A future plan', 'A fact'], answer: 'Regret about the past', explanation: 'imagining how the past could have been different.' },
      { question: '"___ , non sarei in ritardo."', options: ['Se fossi uscito prima', 'Se esco prima', 'Se uscirò prima', 'Se uscirei prima'], answer: 'Se fossi uscito prima', explanation: 'congiuntivo trapassato of uscire = fossi uscito.' },
    ],
  },
  {
    id: 21,
    type: 'translation',
    level: 'Level 7 — Tipo 3: Impossible Past',
    title: 'Understand the Regrets',
    instruction: 'Choose the correct meaning.',
    direction: 'it-en',
    questions: [
      { sentence: 'Se avessi saputo, ti avrei chiamato.', options: ['If I had known, I would have called you', 'If I know, I will call you', 'If I knew, I would call you'], answer: 'If I had known, I would have called you', explanation: 'tipo 3: avessi saputo + avrei chiamato.' },
      { sentence: 'Sarei venuto, ma non ho potuto.', options: ['I would have come, but I couldn\'t', 'I will come, but I can\'t', 'I came, but I couldn\'t'], answer: 'I would have come, but I couldn\'t', explanation: 'sarei venuto = condizionale passato of venire.' },
      { sentence: 'Non avrei mangiato così tanto.', options: ['I wouldn\'t have eaten so much', 'I would not eat so much now', 'I didn\'t eat so much'], answer: 'I wouldn\'t have eaten so much', explanation: 'condizionale passato, regret about eating.' },
      { sentence: 'L\'avrei aiutato, se me lo avessi chiesto.', options: ['I would have helped him if you had asked me', 'I help him if you ask', 'I will help him if you asked'], answer: 'I would have helped him if you had asked me', explanation: 'L\'avrei aiutato = I would have helped him.' },
    ],
  },

  // LEVEL 8 — MIXED CONSTRUCTION
  {
    id: 22,
    type: 'wordorder',
    level: 'Level 8 — Mixed Construction Skills',
    title: 'Build the Conditional Sentences',
    instruction: 'Put the words in the correct order to make a correct sentence.',
    questions: [
      { words: ['se', 'piove', 'prendo', 'l\'ombrello'], answer: 'se piove prendo l\'ombrello', explanation: 'Tipo 1: Se + presente + presente. (Order: condition first, result second.)' },
      { words: ['se', 'avessi', 'tempo', 'andrei', 'al', 'mare'], answer: 'se avessi tempo andrei al mare', explanation: 'Tipo 2: se + congiuntivo (avessi) + condizionale (andrei).' },
      { words: ['vorrei', 'un', 'caffè', 'per favore'], answer: 'vorrei un caffè per favore', explanation: 'Polite request with vorrei.' },
      { words: ['se', 'avessi', 'studiato', 'avrei', 'passato', 'l\'esame'], answer: 'se avessi studiato avrei passato l\'esame', explanation: 'Tipo 3: avessi studiato + avrei passato.' },
      { words: ['se', 'fossi', 'in te', 'parlerei', 'con lui'], answer: 'se fossi in te parlerei con lui', explanation: 'Advice: se fossi in te + condizionale.' },
    ],
  },
  {
    id: 23,
    type: 'translation',
    level: 'Level 8 — Mixed Construction Skills',
    title: 'Italian in Real Life',
    instruction: 'Choose the correct sentence for each everyday situation.',
    direction: 'it-en',
    questions: [
      { sentence: '"Potrebbe aiutarmi?" (formal)', options: ['Could you help me?', 'You helped me?', 'Help him?', 'Would you have helped me?'], answer: 'Could you help me?', explanation: 'potrebbe (Lei) = polite formal request.' },
      { sentence: '"Mi piacerebbe visitare Roma."', options: ['I would love to visit Rome', 'I like visiting Rome', 'I visited Rome', 'I will visit Rome'], answer: 'I would love to visit Rome', explanation: 'piacerebbe = it would please me → I would love.' },
      { sentence: '"Se fossi in te, non lo farei."', options: ['If I were you, I wouldn\'t do it', 'If I am you, I don\'t do it', 'If I was him, I won\'t do it'], answer: 'If I were you, I wouldn\'t do it', explanation: 'Advice with se fossi in te.' },
      { sentence: '"Dovremmo partire presto."', options: ['We should leave early', 'We will leave early', 'We left early', 'We would have left early'], answer: 'We should leave early', explanation: 'dovere → dovremmo = we should.' },
    ],
  },
  {
    id: 24,
    type: 'multiple',
    level: 'Level 8 — Mixed Construction Skills',
    title: 'All Three Types Mixed',
    instruction: 'Identify the correct use or meaning of each sentence type.',
    questions: [
      { question: '"Se hai sete, bevi." is:', options: ['Tipo 1 — a real instruction', 'Tipo 2 — hypothetical', 'Tipo 3 — past regret', 'A wish'], answer: 'Tipo 1 — a real instruction', explanation: 'Present + present/imperative.' },
      { question: '"Se lavorassi di meno, starei meglio." is:', options: ['Tipo 2 — hypothetical, possible in theory', 'Tipo 1', 'Tipo 3', 'A command'], answer: 'Tipo 2 — hypothetical, possible in theory', explanation: 'lavorassi (congiuntivo) + starei (condizionale).' },
      { question: '"Se avessi fatto il biglietto, avremmo viaggiato." is:', options: ['Tipo 3 — impossible past', 'Tipo 1', 'Tipo 2', 'A plan'], answer: 'Tipo 3 — impossible past', explanation: 'avessi fatto + avremmo viaggiato → regret.' },
      { question: 'The most polite way to ask for the bill is:', options: ['Vorrei il conto, per favore', 'Voglio il conto', 'Conto!', 'Il conto ora'], answer: 'Vorrei il conto, per favore', explanation: 'Vorrei (condizionale) is the polite form of voglio.' },
      { question: '"Se avessimo più soldi, compreremmo una macchina." means:', options: ['If we had more money, we would buy a car', 'If we have money, we buy a car', 'If we had had money, we would have bought a car'], answer: 'If we had more money, we would buy a car', explanation: 'tipo 2: avessimo + compreremmo.' },
    ],
  },
  {
    id: 25,
    type: 'fillblank',
    level: 'Level 8 — Mixed Construction Skills',
    title: 'Choose the Right Form',
    instruction: 'Pick the form that completes each sentence correctly.',
    questions: [
      { sentence: 'Se ___ più tempo, ___ di più. (avere, riposare)', options: ['avessi / riposerei', 'ho / riposo', 'avevo / riposavo', 'avrò / riposerò'], answer: 'avessi / riposerei', explanation: 'tipo 2: avessi (congiuntivo) + riposerei (condizionale).' },
      { sentence: 'Se ___ primo, ___ il posto. (arrivare, prendere)', options: ['fossi arrivato / avrei preso', 'sono arrivato / prendo', 'arrivo / prendo', 'sono arrivato / prendevo'], answer: 'fossi arrivato / avrei preso', explanation: 'tipo 3: fossi arrivato + avrei preso.' },
      { sentence: 'Non ___ tanto, se ___ tempo. (mangiare, avere)', options: ['mangerei / avessi', 'mangio / ho', 'mangiavo / avevo', 'mangerò / avrò'], answer: 'mangerei / avessi', explanation: 'tipo 2 order: result + se-clause.' },
      { sentence: '___ telefonarmi quando arrivi? (potere, tu)', options: ['Potresti', 'Puoi', 'Potrai', 'Potevi'], answer: 'Potresti', explanation: 'Polite request: potresti + infinitive.' },
      { sentence: 'Se ___ , te lo direi. (sapere)', options: ['sapessi', 'so', 'sapevo', 'saprò'], answer: 'sapessi', explanation: 'sapere → sapessi (congiuntivo) + direi (condizionale).' },
    ],
  },

  // LEVEL 9 — REAL-LIFE COMMUNICATION (STORIES)
  {
    id: 26,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Wishes and Dreams',
    storyTitle: 'Se avessi più tempo',
    story: 'Anna: Cosa faresti se avessi più tempo?\n\nMarco: Se avessi più tempo, viaggerei molto di più. Vorrei visitare la Toscana e la Sicilia.\n\nAnna: E cosa altro faresti?\n\nMarco: Studierei il pianoforte e leggerei più libri. Dovrei anche fare più sport.\n\nAnna: Anch\'io vorrei fare più sport, ma non ho mai tempo!\n\nMarco: Se lavorassi meno, sarei più riposato. E tu? Cosa faresti?\n\nAnna: Se potessi, imparerei a cucinare piatti nuovi. Mi piacerebbe anche imparare il tedesco.',
    vocab: [
      { word: 'faresti', meaning: 'you would do (fare)' },
      { word: 'viaggerei', meaning: 'I would travel (viaggiare)' },
      { word: 'vorrei', meaning: 'I would like (volere)' },
      { word: 'studierei', meaning: 'I would study (studiare)' },
      { word: 'riposato', meaning: 'rested' },
      { word: 'imparerei', meaning: 'I would learn (imparare)' },
    ],
    translation: 'Anna: What would you do if you had more time?\n\nMarco: If I had more time, I would travel much more. I would like to visit Tuscany and Sicily.\n\nAnna: And what else would you do?\n\nMarco: I would study the piano and read more books. I should also do more sport.\n\nAnna: I would also like to do more sport, but I never have time!\n\nMarco: If I worked less, I would be more rested. And you? What would you do?\n\nAnna: If I could, I would learn to cook new dishes. I would also love to learn German.',
    questions: [
      { question: 'What would Marco do if he had more time?', options: ['Travel much more', 'Work more', 'Sleep more', 'Watch TV'], answer: 'Travel much more', explanation: '"Se avessi più tempo, viaggerei molto di più."' },
      { question: 'Where would Marco like to visit?', options: ['Tuscany and Sicily', 'Rome and Milan', 'Venice and Naples', 'Florence only'], answer: 'Tuscany and Sicily', explanation: '"Vorrei visitare la Toscana e la Sicilia."' },
      { question: 'What would Anna like to learn?', options: ['To cook new dishes', 'To play piano', 'To ski', 'To drive'], answer: 'To cook new dishes', explanation: '"imparerei a cucinare piatti nuovi."' },
      { question: 'How many condizionale verbs can you find?', options: ['At least 9', 'Only 2', 'None', 'Just 1'], answer: 'At least 9', explanation: 'faresti, viaggerei, vorrei, studierei, leggerei, dovrei, vorrei, lavorassi, sarei, potessi, imparerei, piacerebbe.' },
      { question: 'Write what you would do if you had more time.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Se avessi più tempo, viaggerei. Any correct tipo 2 is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Polite Requests',
    storyTitle: 'Al ristorante',
    story: 'Cameriere: Buonasera! Vorrebbe ordinare?\n\nCliente: Sì, vorrei gli spaghetti alla carbonara. Potrebbe dirmi cosa suggerisce?\n\nCameriere: Oggi consiglio il pesce del giorno. Sarebbe una scelta perfetta.\n\nCliente: Mi piacerebbe provare il pesce. E per il vino, cosa mi consiglierebbe?\n\nCameriere: Le suggerirei un bianco frizzante. Sarebbe un abbinamento perfetto.\n\nCliente: Perfetto, prenderei anche il contorno. Alla fine, potrebbe portare il conto?\n\nCameriere: Certamente! Vorrebbe un dolce prima?\n\nCliente: No, grazie, sarei già molto soddisfatto.',
    vocab: [
      { word: 'vorrebbe', meaning: 'would you like (volere, formal)' },
      { word: 'ordinare', meaning: 'to order' },
      { word: 'suggerisce', meaning: 'recommends (indicative)' },
      { word: 'sarebbe', meaning: 'it would be (essere)' },
      { word: 'suggerirei', meaning: 'I would recommend (suggerire)' },
      { word: 'abbinamento', meaning: 'pairing' },
    ],
    translation: 'Waiter: Good evening! Would you like to order?\n\nCustomer: Yes, I would like spaghetti alla carbonara. Could you tell me what you recommend?\n\nWaiter: Today I recommend the fish of the day. It would be a perfect choice.\n\nCustomer: I would love to try the fish. And for the wine, what would you recommend?\n\nWaiter: I would suggest a sparkling white wine. It would be a perfect pairing.\n\nCustomer: Perfect, I would also take the side dish. At the end, could you bring the bill?\n\nWaiter: Certainly! Would you like a dessert first?\n\nCustomer: No thanks, I would already be very satisfied.',
    questions: [
      { question: 'What does the customer order?', options: ['Fish of the day', 'Spaghetti alla carbonara', 'A steak', 'A pizza'], answer: 'Fish of the day', explanation: 'First he asks for spaghetti but then chooses the fish: "Mi piacerebbe provare il pesce."' },
      { question: 'What wine does the waiter recommend?', options: ['A sparkling white wine', 'Red wine', 'Rosé', 'No wine'], answer: 'A sparkling white wine', explanation: '"Le suggerirei un bianco frizzante."' },
      { question: 'The polite way to ask for the bill is:', options: ['Potrebbe portare il conto?', 'Il conto!', 'Dammi il conto', 'Conto ora'], answer: 'Potrebbe portare il conto?', explanation: 'Potrebbe (Lei) + infinitive = very polite request.' },
      { question: 'Find the fixed order of two polite phrases:', options: ['Vorrebbe / Mi piacerebbe', 'Voglio / Ho', 'Devo / Farò', 'Sono / Avevo'], answer: 'Vorrebbe / Mi piacerebbe', explanation: 'Both are polite condizionale forms for ordering.' },
      { question: 'Write a polite sentence you would say to a waiter.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vorrei un acqua, per favore. Any polite request is accepted.' },
    ],
  },
  {
    id: 28,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Advice',
    storyTitle: 'I consigli di Marco',
    story: 'Anna: Marco, non so cosa fare. Il mio capo è molto severo e non sono felice nel lavoro.\n\nMarco: Se fossi in te, parlerei con lui dei tuoi problemi.\n\nAnna: Ho paura. E se si arrabbia?\n\nMarco: Se si arrabbiasse, aspetteresti un po\' e riproveresti. Dovresti anche valutare altre offerte di lavoro.\n\nAnna: Credi che dovrei cambiare lavoro?\n\nMarco: Se trovassi un lavoro migliore, lo cambierei. Ma prima parlerei con il tuo capo.\n\nAnna: Hai ragione. Se non parlassi, non saprei mai la verità.\n\nMarco: Esatto. E se avessi bisogno di aiuto, chiamami quando vuoi!',
    vocab: [
      { word: 'severo', meaning: 'strict' },
      { word: 'se fossi in te', meaning: 'if I were you' },
      { word: 'si arrabbia', meaning: 'he gets angry (present)' },
      { word: 'riproveresti', meaning: 'you would try again' },
      { word: 'valutare', meaning: 'to evaluate' },
      { word: 'verità', meaning: 'truth' },
    ],
    translation: 'Anna: Marco, I don\'t know what to do. My boss is very strict and I\'m not happy at work.\n\nMarco: If I were you, I would talk to him about your problems.\n\nAnna: I\'m afraid. What if he gets angry?\n\nMarco: If he got angry, you would wait a bit and try again. You should also evaluate other job offers.\n\nAnna: Do you think I should change jobs?\n\nMarco: If you found a better job, I would change it. But first I would talk to your boss.\n\nAnna: You\'re right. If I didn\'t talk, I would never know the truth.\n\nMarco: Exactly. And if you needed help, call me whenever you want!',
    questions: [
      { question: 'Why is Anna unhappy?', options: ['Her boss is very strict', 'She lives far away', 'She has no friends', 'She hates the city'], answer: 'Her boss is very strict', explanation: '"Il mio capo è molto severo e non sono felice nel lavoro."' },
      { question: 'What is Marco\'s main advice?', options: ['Talk to her boss', 'Quit immediately', 'Move abroad', 'Ignore the problem'], answer: 'Talk to her boss', explanation: '"Se fossi in te, parlerei con lui."' },
      { question: '"Se fossi in te" uses which type?', options: ['Tipo 2', 'Tipo 1', 'Tipo 3', 'A command'], answer: 'Tipo 2', explanation: 'fossi (congiuntivo) + parlerei (condizionale) → hypothetical advice.' },
      { question: '"Dovresti" means:', options: ['You should', 'You must', 'You had to', 'You will have to'], answer: 'You should', explanation: 'dovere → dovresti = you should (gentle advice).' },
      { question: 'Which sentence uses tipo 3 (impossible past)?', options: ['None in this dialogue', 'Se fossi in te, parlerei', 'Se trovassi un lavoro migliore', 'Chiamami quando vuoi'], answer: 'None in this dialogue', explanation: 'All the se-clauses here are tipo 2 (hypothetical present), not tipo 3.' },
      { question: 'Write a piece of advice using "Se fossi in te, …".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Se fossi in te, studierei italiano ogni giorno. Any correct advice sentence is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Regrets',
    storyTitle: 'Se avessi saputo',
    story: 'Luca: Che peccato! Se avessi prenotato il ristorante, avremmo mangiato qui.\n\nMarta: Hai ragione. Se fossimo partiti prima, non avremmo perso il tavolo.\n\nLuca: Se avessi saputo che era così famoso, avrei chiamato un mese fa.\n\nMarta: Anche io. Se avessi visto le recensioni, avrei fatto la prenotazione.\n\nLuca: Non importa. Se avessimo mangiato da un\'altra parte, non avremmo scoperto questo quartiere.\n\nMarta: Vero! Saremmo andati al solito posto e non avremmo visto le luci della città.\n\nLuca: Stasera mangeremo una pizza deliziosa. Se il ristorante fosse pieno, mangeremmo in un altro locale.\n\nMarta: Va bene, ma domani prenoterò subito!',
    vocab: [
      { word: 'che peccato', meaning: 'what a pity' },
      { word: 'avessi prenotato', meaning: 'I had booked (cong. trapassato)' },
      { word: 'recensioni', meaning: 'reviews' },
      { word: 'prenotazione', meaning: 'booking/reservation' },
      { word: 'quartiere', meaning: 'neighbourhood' },
      { word: 'locale', meaning: 'restaurant (local)' },
    ],
    translation: 'Luca: What a pity! If I had booked the restaurant, we would have eaten here.\n\nMarta: You\'re right. If we had left earlier, we wouldn\'t have missed the table.\n\nLuca: If I had known it was so famous, I would have called a month ago.\n\nMarta: Me too. If I had seen the reviews, I would have made the reservation.\n\nLuca: It doesn\'t matter. If we had eaten somewhere else, we wouldn\'t have discovered this neighbourhood.\n\nMarta: True! We would have gone to the usual place and wouldn\'t have seen the lights of the city.\n\nLuca: Tonight we will eat a delicious pizza. If the restaurant were full, we would eat at another place.\n\nMarta: Fine, but tomorrow I\'ll book right away!',
    questions: [
      { question: 'Why can\'t they eat at the famous restaurant?', options: ['They didn\'t book a table', 'It\'s closed', 'It\'s too expensive', 'They have no time'], answer: 'They didn\'t book a table', explanation: '"Se avessi prenotato il ristorante, avremmo mangiato qui."' },
      { question: 'What would Marta have done if she had seen the reviews?', options: ['Made a reservation', 'Stayed home', 'Gone to another city', 'Called a friend'], answer: 'Made a reservation', explanation: '"Se avessi visto le recensioni, avrei fatto la prenotazione."' },
      { question: 'Why is the situation not completely bad?', options: ['They discovered a nice neighbourhood', 'The food was free', 'They met the chef', 'The restaurant opened'], answer: 'They discovered a nice neighbourhood', explanation: '"non avremmo scoperto questo quartiere."' },
      { question: '"Se avessimo mangiato da un\'altra parte" uses:', options: ['congiuntivo trapassato', 'congiuntivo imperfetto', 'presente', 'futuro'], answer: 'congiuntivo trapassato', explanation: 'avessimo mangiato = past subjunctive (tipo 3).' },
      { question: 'What type is "Se il ristorante fosse pieno, mangeremmo in un altro locale"?', options: ['Tipo 2', 'Tipo 1', 'Tipo 3', 'No conditional'], answer: 'Tipo 2', explanation: 'fosse (congiuntivo imperfetto) + mangeremmo (condizionale).' },
      { question: 'Write a sentence with "Se avessi/i…" about a past regret.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Se avessi studiato, avrei passato l\'esame. Any correct tipo 3 is accepted.' },
    ],
  },

  // LEVEL 10 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 10 — Final Proficiency Test',
    title: 'Condizionale Mastery Test',
    instruction: 'Answer all the questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Recognition
      { question: '"Vorrei un caffè" is a:', options: ['Polite request', 'Command', 'Past event', 'Prediction'], answer: 'Polite request' },
      { question: 'The condizionale corresponds to the English word:', options: ['would', 'will', 'did', 'have'], answer: 'would' },
      // Types
      { question: '"Se piove, resto a casa" is:', options: ['Tipo 1 (real)', 'Tipo 2 (hypothetical)', 'Tipo 3 (impossible past)', 'A wish'], answer: 'Tipo 1 (real)' },
      { question: '"Se avessi tempo, andrei al mare" is:', options: ['Tipo 2', 'Tipo 1', 'Tipo 3', 'A command'], answer: 'Tipo 2' },
      { question: '"Se avessi studiato, avrei passato" is:', options: ['Tipo 3', 'Tipo 1', 'Tipo 2', 'A question'], answer: 'Tipo 3' },
      // Formation -are/-ere/-ire
      { question: 'Domani io ___ con te. (parlare)', options: ['parlerei', 'parlavo', 'parlerò', 'parlai'], answer: 'parlerei' },
      { question: 'Loro ___ il film. (vedere)', options: ['vedrebbero', 'vedranno', 'vedevano', 'vedono'], answer: 'vedrebbero' },
      { question: 'Noi ___ presto. (partire)', options: ['partiremmo', 'partiremo', 'partivamo', 'partiamo'], answer: 'partiremmo' },
      { question: '"parlerebbero" uses the ending:', options: ['-erebbero', '-ebbero', '-eranno', '-eremo'], answer: '-erebbero' },
      // Irregular stems
      { question: '"sarei" — essere has the condizionale stem:', options: ['sar-', 's-', 'ser-', 'esser-'], answer: 'sar-' },
      { question: 'Se potessi, ___ in Italia. (vivere)', options: ['vivrei', 'vivo', 'vivevo', 'vivrò'], answer: 'vivrei' },
      { question: 'Vorrei, potrei, dovrei are', options: ['irregular condizionale forms', 'regular future forms', 'past participles', 'imperatives'], answer: 'irregular condizionale forms' },
      // Past conditional
      { question: 'Io ___ mangiato prima. (avere)', options: ['avrei', 'sarei', 'ho', 'avevo'], answer: 'avrei' },
      { question: 'Laura ___ andata a Roma. (essere)', options: ['sarebbe', 'avrebbe', 'è', 'andava'], answer: 'sarebbe' },
      { question: '"avresti preso" is:', options: ['condizionale passato', 'futuro anteriore', 'presente', 'imperativo'], answer: 'condizionale passato' },
      // Se-clause subjunctive
      { question: 'Se ___ in te, non andrei. (essere)', options: ['fossi', 'sei', 'ero', 'sarei'], answer: 'fossi' },
      { question: 'Se ___ studiato di più, avresti passato. (avere)', options: ['avessi', 'hai', 'avevi', 'avresti'], answer: 'avessi' },
      // Translation
      { question: '"Se fossi ricco, comprerei una villa" means:', options: ['If I were rich, I would buy a villa', 'If I am rich, I buy a villa', 'If I had been rich, I would have bought a villa'], answer: 'If I were rich, I would buy a villa' },
      { question: 'The polite way to ask "Could you help me?" (formal) is:', options: ['Potrebbe aiutarmi?', 'Mi aiuti!', 'Aiutami!', 'Hai aiutato?'], answer: 'Potrebbe aiutarmi?' },
      { question: '"Se fossi in te, non lo farei." is advice because:', options: ['It uses tipo 2 (would)', 'It uses tipo 3', 'It states a fact', 'It is a command'], answer: 'It uses tipo 2 (would)' },
      // Reading
      { question: 'READ FIRST: "Luca e Marta vogliono cenare in un ristorante famoso, ma non hanno prenotato. «Se avessi prenotato, avremmo mangiato qui», dice Luca. Marta risponde: «Se fossimo partiti prima, non avremmo perso il tavolo. Domani prenoterò subito!» Alla fine decidono di mangiare la pizza in un altro locale. Se il locale fosse pieno, mangerebbero a casa."\n\nHave Luca and Marta booked a table?', options: ['No, they haven\'t', 'Yes, they have', 'They booked one month ago', 'It\'s not mentioned'], answer: 'No, they haven\'t' },
      { question: 'READ AGAIN: "Se fossimo partiti prima…" is:', options: ['Tipo 3 condition (past)', 'Tipo 1 condition', 'Tipo 2 condition', 'A question'], answer: 'Tipo 3 condition (past)' },
      { question: 'READ AGAIN: "Se il locale fosse pieno, mangerebbero a casa." is:', options: ['Tipo 2', 'Tipo 3', 'Tipo 1', 'No conditional'], answer: 'Tipo 2' },
      // Production
      { question: 'Write "I would live in Italy" in Italian:', type: 'text', answer: 'Vivrei in Italia', acceptedAnswers: ['vivrei in italia', 'io vivrei in italia', 'vivrei in italia'] },
      { question: 'Write "If I were you, I would study more" in Italian:', type: 'text', answer: 'Se fossi in te, studierei di più', acceptedAnswers: ['se fossi in te studierei di più', 'se fossi in te studierei piu', 'se fossi in te studierei di piu', 'se fossi in te io studierei di più', 'se fossi in te studierei di più'] },
    ],
  },
];

export const condizionaleStories = condizionaleExercises.filter((e) => e.type === 'story');

export const condizionaleFinalTest = condizionaleExercises.find((e) => e.id === 30).questions;

export const condizionaleFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You confidently understand and use the condizionale and all three types of periodo ipotetico.' },
  { min: 75, grade: 'Very good!', message: 'You understand the main patterns. Review irregular stems and the past conditional.' },
  { min: 60, grade: 'Almost there!', message: 'Review regular formation, irregular verbs, and the three types of se-clauses.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the lessons before taking the final test again.' },
];