export const passatoStages = [
  {
    id: 'concept',
    title: 'What is the Past?',
    subtitle: 'Understanding the passato prossimo and the two-part formula',
    sections: [
      {
        heading: 'Part 1 — What is the past tense?',
        explanation: 'The passato prossimo is the most common Italian past tense. It is used to talk about completed actions in the past.',
        bullets: [
          { text: 'Oggi lavoro. → I work today. (present)', example: 'Ieri ho lavorato. → Yesterday I worked. (past)' },
          { text: 'Mangio una pizza. → I eat a pizza. (present)', example: 'Ho mangiato una pizza. → I ate a pizza. (past)' },
        ],
        timeline: { left: 'PAST', center: 'NOW', right: 'FUTURE', examples: ['Ieri ho mangiato', 'Oggi mangio', 'Domani mangerò'] },
        note: 'Italian has other past tenses (imperfetto, passato remoto), which you will learn in later lessons. The passato prossimo is the first and most useful one.',
      },
      {
        heading: 'Part 2 — The two parts',
        explanation: 'Every passato prossimo sentence is built with two parts: an auxiliary verb (essere or avere) + a past participle.',
        focus: { sentence: 'Ho mangiato.', breakdown: [{ part: 'Ho', role: 'auxiliary' }, { part: 'mangiato', role: 'past participle' }], meaning: 'I ate / I have eaten.' },
        examples: [
          { italian: 'Hai mangiato.', translation: 'You ate.' },
          { italian: 'Ha mangiato.', translation: 'He/she ate.' },
          { italian: 'Abbiamo mangiato.', translation: 'We ate.' },
          { italian: 'Avete mangiato.', translation: 'You (pl) ate.' },
          { italian: 'Hanno mangiato.', translation: 'They ate.' },
        ],
        note: 'When using avere, the auxiliary changes but the past participle stays the same.',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Past Participles',
    subtitle: 'How to form regular past participles from -are, -ere, and -ire verbs',
    sections: [
      {
        heading: '-ARE → -ATO',
        explanation: 'Remove the -are ending and add -ato.',
        verbs: [
          { infinitive: 'parlare', meaning: 'parlato — to speak' },
          { infinitive: 'mangiare', meaning: 'mangiato — to eat' },
          { infinitive: 'lavorare', meaning: 'lavorato — to work' },
          { infinitive: 'studiare', meaning: 'studiato — to study' },
        ],
        group: '-ARE',
      },
      {
        heading: '-ERE → -UTO',
        explanation: 'Remove the -ere ending and add -uto.',
        verbs: [
          { infinitive: 'credere', meaning: 'creduto — to believe' },
          { infinitive: 'ricevere', meaning: 'ricevuto — to receive' },
          { infinitive: 'conoscere', meaning: 'conosciuto — to know (someone)' },
        ],
        group: '-ERE',
        note: 'Many common -ERE verbs have irregular past participles, which you will learn later.',
      },
      {
        heading: '-IRE → -ITO',
        explanation: 'Remove the -ire ending and add -ito.',
        verbs: [
          { infinitive: 'dormire', meaning: 'dormito — to sleep' },
          { infinitive: 'partire', meaning: 'partito — to leave' },
          { infinitive: 'finire', meaning: 'finito — to finish' },
          { infinitive: 'sentire', meaning: 'sentito — to hear/feel' },
        ],
        group: '-IRE',
      },
      {
        patterns: ['-ARE → -ATO', '-ERE → -UTO', '-IRE → -ITO'],
        note: 'These three patterns cover the majority of regular Italian verbs. Memorise them and you can form the past participle for hundreds of verbs.',
      },
    ],
  },
  {
    id: 'auxiliaries',
    title: 'Avere & Essere',
    subtitle: 'The two auxiliary verbs and how agreement works with essere',
    sections: [
      {
        heading: 'Part 4 — Avere',
        explanation: 'Most Italian verbs use avere as their auxiliary. The auxiliary changes for each person, while the past participle stays the same.',
        conjugations: { stem: '', rows: [{ pronoun: 'io', ending: 'ho' }, { pronoun: 'tu', ending: 'hai' }, { pronoun: 'lui/lei', ending: 'ha' }, { pronoun: 'noi', ending: 'abbiamo' }, { pronoun: 'voi', ending: 'avete' }, { pronoun: 'loro', ending: 'hanno' }] },
        examples: [
          { italian: 'ho parlato', translation: 'I spoke' },
          { italian: 'hai mangiato', translation: 'you ate' },
          { italian: 'ha studiato', translation: 'he/she studied' },
          { italian: 'abbiamo comprato', translation: 'we bought' },
          { italian: 'avete visto', translation: 'you (pl) saw' },
          { italian: 'hanno letto', translation: 'they read' },
        ],
      },
      {
        heading: 'Part 5 — Essere',
        explanation: 'Verbs of movement, change of state, and reflexive verbs use essere. The common ones include:',
        examples: [
          { italian: 'andare → sono andato/a', translation: 'to go — I went' },
          { italian: 'venire → sono venuto/a', translation: 'to come — I came' },
          { italian: 'arrivare → sono arrivato/a', translation: 'to arrive — I arrived' },
          { italian: 'partire → sono partito/a', translation: 'to leave — I left' },
          { italian: 'tornare → sono tornato/a', translation: 'to return — I returned' },
          { italian: 'uscire → sono uscito/a', translation: 'to go out — I went out' },
          { italian: 'nascere → sono nato/a', translation: 'to be born — I was born' },
          { italian: 'morire → è morto/a', translation: 'to die — he/she died' },
        ],
        note: 'You do not need to memorise an exhaustive list. Focus on the most common movement and change-of-state verbs.',
      },
      {
        heading: 'Part 6 — Agreement with Essere',
        explanation: 'When the auxiliary is essere, the past participle agrees with the subject in gender and number.',
        focus: { sentence: 'Marco è andato. / Anna è andata.', breakdown: [{ part: 'è', role: 'auxiliary' }, { part: 'andato', role: 'masc. sing.' }, { part: 'andata', role: 'fem. sing.' }], meaning: 'Marco (m) went. / Anna (f) went.' },
        comparison: [
          { form: 'masc. sing.', are: '-o', ere: 'Marco è andat_o.', ire: 'Luca è partit_o.' },
          { form: 'fem. sing.', are: '-a', ere: 'Anna è andat_a.', ire: 'Maria è partit_a.' },
          { form: 'masc./mixed pl.', are: '-i', ere: 'Marco e Luca sono andat_i.', ire: 'Luca e Paolo sono partit_i.' },
          { form: 'fem. pl.', are: '-e', ere: 'Anna e Giulia sono andat_e.', ire: 'Maria ePaola sono partit_e.' },
        ],
        note: 'Agreement only happens with essere. When you use avere, the past participle never changes.',
      },
    ],
  },
  {
    id: 'choose',
    title: 'Choosing & Patterns',
    subtitle: 'Avere vs essere, irregular participles, time expressions, and breaking down sentences',
    sections: [
      {
        heading: 'Part 7 — Avere vs Essere',
        explanation: 'The key to the passato prossimo is knowing which auxiliary to use. Most verbs use avere. Movement, change-of-state, and reflexive verbs use essere.',
        examples: [
          { italian: 'Ho mangiato una pizza.', translation: 'I ate a pizza. (avere)' },
          { italian: 'Maria ha comprato il libro.', translation: 'Maria bought the book. (avere)' },
          { italian: 'Sono andato a Roma.', translation: 'I went to Rome. (essere)' },
          { italian: 'Maria è andata a Roma.', translation: 'Maria went to Rome. (essere)' },
        ],
        note: 'Start by identifying the auxiliary — that is the first step to understanding any passato prossimo sentence.',
      },
      {
        heading: 'Part 8 — Common Irregular Past Participles',
        explanation: 'Some of the most useful Italian verbs have irregular past participles. These must be learned individually.',
        patterns: ['fare → fatto', 'dire → detto', 'leggere → letto', 'scrivere → scritto', 'vedere → visto', 'prendere → preso', 'mettere → messo', 'bere → bevuto', 'aprire → aperto', 'chiudere → chiuso', 'venire → venuto'],
        note: 'Focus on these high-frequency verbs — you will encounter them constantly in stories and everyday conversation.',
      },
      {
        heading: 'Part 9 — Time Expressions',
        explanation: 'Certain words signal that a sentence is in the past. Learn to recognise them.',
        examples: [
          { italian: 'ieri', translation: 'yesterday' },
          { italian: 'ieri mattina', translation: 'yesterday morning' },
          { italian: 'ieri sera', translation: 'yesterday evening' },
          { italian: 'la settimana scorsa', translation: 'last week' },
          { italian: 'il mese scorso', translation: 'last month' },
          { italian: "l'anno scorso", translation: 'last year' },
          { italian: 'due giorni fa', translation: 'two days ago' },
          { italian: "un'ora fa", translation: 'an hour ago' },
          { italian: 'stamattina', translation: 'this morning' },
        ],
      },
      {
        heading: 'Part 10 — Understanding a Sentence',
        explanation: 'To understand any past-tense sentence, break it into parts: subject + auxiliary + past participle + other information.',
        focus: {
          sentence: 'Marco ha mangiato una pizza ieri sera.',
          breakdown: [
            { part: 'Marco', role: 'subject' },
            { part: 'ha', role: 'auxiliary' },
            { part: 'mangiato', role: 'past participle' },
            { part: 'una pizza', role: 'what' },
            { part: 'ieri sera', role: 'when' },
          ],
          meaning: 'Marco ate a pizza yesterday evening.',
        },
        note: 'You can understand almost any Italian past-tense sentence with this four-step breakdown.',
      },
    ],
  },
];

export const passatoExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify Present vs Past',
    instruction: 'Is this sentence in the present or the past?',
    questions: [
      { question: 'Ieri ho lavorato.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Ieri" (yesterday) signals the past. "Ho lavorato" uses the passato prossimo.' },
      { question: 'Oggi lavoro.', options: ['Present', 'Past'], answer: 'Present', explanation: '"Oggi" (today) and "lavoro" are present tense.' },
      { question: 'Ho mangiato una pizza.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Ho mangiato" = auxiliary + past participle → past.' },
      { question: 'Marco studia italiano.', options: ['Present', 'Past'], answer: 'Present', explanation: '"Studia" is present tense (no auxiliary).' },
      { question: 'Siamo andati a Roma.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Siamo andati" = essere + past participle → past.' },
      { question: 'Lei parla con Marco.', options: ['Present', 'Past'], answer: 'Present', explanation: '"Parla" is present tense (single verb, no auxiliary).' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Identify the Auxiliary',
    instruction: 'Match each auxiliary verb to whether it comes from avere or essere.',
    pairs: [
      { left: 'ho', right: 'avere' },
      { left: 'sei', right: 'essere' },
      { left: 'hanno', right: 'avere' },
      { left: 'siamo', right: 'essere' },
      { left: 'ha', right: 'avere' },
      { left: 'è', right: 'essere' },
    ],
    explanation: 'Ho, ha, hanno = forms of avere. Sei, siamo, è = forms of essere.',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Past Participle',
    instruction: 'Which word is the past participle in each sentence?',
    questions: [
      { question: 'Maria ha mangiato una pizza.', options: ['Maria', 'ha', 'mangiato', 'pizza'], answer: 'mangiato', explanation: '"Mangiato" is the past participle of mangiare. "Ha" is the auxiliary.' },
      { question: 'Luca è arrivato alle otto.', options: ['Luca', 'è', 'arrivato', 'otto'], answer: 'arrivato', explanation: '"Arrivato" is the past participle of arrivare. "È" is the auxiliary.' },
      { question: 'Abbiamo studiato italiano.', options: ['Abbiamo', 'studiato', 'italiano'], answer: 'studiato', explanation: '"Studiato" is the past participle of studiare.' },
      { question: 'Ho letto un libro.', options: ['Ho', 'letto', 'libro'], answer: 'letto', explanation: '"Letto" is the irregular past participle of leggere.' },
      { question: 'Sono andata a scuola.', options: ['Sono', 'andata', 'scuola'], answer: 'andata', explanation: '"Andata" is the past participle of andare (feminine form).' },
    ],
  },
  {
    id: 4,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Infinitive → Past Participle',
    instruction: 'Match each infinitive to its regular past participle.',
    pairs: [
      { left: 'parlare', right: 'parlato' },
      { left: 'dormire', right: 'dormito' },
      { left: 'credere', right: 'creduto' },
      { left: 'mangiare', right: 'mangiato' },
      { left: 'finire', right: 'finito' },
      { left: 'ricevere', right: 'ricevuto' },
    ],
    explanation: '-ARE → -ATO, -ERE → -UTO, -IRE → -ITO.',
  },
  {
    id: 5,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'AVERE or ESSERE?',
    instruction: 'Which auxiliary does each verb use?',
    questions: [
      { question: 'parlare', options: ['avere', 'essere'], answer: 'avere', explanation: 'Parlare uses avere → ho parlato.' },
      { question: 'andare', options: ['avere', 'essere'], answer: 'essere', explanation: 'Andare uses essere → sono andato/a.' },
      { question: 'mangiare', options: ['avere', 'essere'], answer: 'avere', explanation: 'Mangiare uses avere → ho mangiato.' },
      { question: 'arrivare', options: ['avere', 'essere'], answer: 'essere', explanation: 'Arrivare uses essere → sono arrivato/a.' },
      { question: 'comprare', options: ['avere', 'essere'], answer: 'avere', explanation: 'Comprare uses avere → ho comprato.' },
      { question: 'uscire', options: ['avere', 'essere'], answer: 'essere', explanation: 'Uscire uses essere → sono uscito/a.' },
    ],
  },
  // LEVEL 2 — FORMATION
  {
    id: 6,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Complete -ARE Past Participles',
    instruction: 'Match each -ARE verb to its past participle.',
    pairs: [
      { left: 'studiare', right: 'studiato' },
      { left: 'lavorare', right: 'lavorato' },
      { left: 'comprare', right: 'comprato' },
      { left: 'chiamare', right: 'chiamato' },
      { left: 'guardare', right: 'guardato' },
    ],
    explanation: 'All -ARE verbs follow the pattern: remove -are, add -ato.',
  },
  {
    id: 7,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Complete -IRE Past Participles',
    instruction: 'Match each -IRE verb to its past participle.',
    pairs: [
      { left: 'partire', right: 'partito' },
      { left: 'sentire', right: 'sentito' },
      { left: 'finire', right: 'finito' },
      { left: 'dormire', right: 'dormito' },
      { left: 'aprire', right: 'aperto' },
    ],
    explanation: 'Most -IRE verbs → -ITO. Note: aprire → aperto is irregular.',
  },
  {
    id: 8,
    type: 'multiple',
    level: 'Level 2 — Formation',
    title: 'Build Passato Prossimo with AVERE',
    instruction: 'Choose the correct passato prossimo form.',
    questions: [
      { question: 'io + mangiare → ho ___', options: ['mangiato', 'mangiata', 'mangiat'], answer: 'mangiato', explanation: 'With avere, the past participle does not change. "Ho mangiato."' },
      { question: 'tu + parlare → hai ___', options: ['parlato', 'parlata', 'parlati'], answer: 'parlato', explanation: '"Hai parlato." With avere, no agreement.' },
      { question: 'lui + comprare → ha ___', options: ['comprato', 'comprata', 'comprati'], answer: 'comprato', explanation: '"Ha comprato." Avere: past participle stays the same.' },
      { question: 'noi + studiare → abbiamo ___', options: ['studiato', 'studiata', 'studiati'], answer: 'studiato', explanation: '"Abbiamo studiato."' },
      { question: 'loro + guardare → hanno ___', options: ['guardato', 'guardata', 'guardati'], answer: 'guardato', explanation: '"Hanno guardato." No agreement with avere.' },
    ],
  },
  {
    id: 9,
    type: 'multiple',
    level: 'Level 2 — Formation',
    title: 'Build Passato Prossimo with ESSERE',
    instruction: 'Choose the correct form (remember agreement!).',
    questions: [
      { question: 'Marco + andare → Marco ___ andato.', options: ['è', 'ha', 'sono'], answer: 'è', explanation: 'Andare uses essere. "Marco è andato."' },
      { question: 'Anna + partire → Anna ___ partita.', options: ['è', 'ha', 'si'], answer: 'è', explanation: 'Feminine agreement: "Anna è partita."' },
      { question: 'io + venire → ___ venuto/a.', options: ['sono', 'ho', 'ha'], answer: 'sono', explanation: 'Venire uses essere. "Sono venuto/a."' },
      { question: 'noi + tornare → ___ tornati.', options: ['siamo', 'abbiamo', 'hanno'], answer: 'siamo', explanation: '"Siamo tornati." Essere + masculine plural.' },
    ],
  },
  {
    id: 10,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Complete the Sentence',
    instruction: 'Fill in the blank with the correct passato prossimo.',
    questions: [
      { sentence: 'Ieri io ___ una pizza. (mangiare)', options: ['ho mangiato', 'è mangiato', 'sono mangiato'], answer: 'ho mangiato', explanation: 'Mangiare uses avere. "Ho mangiato."' },
      { sentence: 'Marco ___ alle otto. (arrivare)', options: ['è arrivato', 'ha arrivato', 'sono arrivato'], answer: 'è arrivato', explanation: 'Arrivare uses essere. "È arrivato."' },
      { sentence: 'Loro ___ il film ieri. (guardare)', options: ['hanno guardato', 'sono guardato', 'è guardato'], answer: 'hanno guardato', explanation: 'Guardare uses avere. "Hanno guardato."' },
    ],
  },
  // LEVEL 3 — AVERE VS ESSERE
  {
    id: 11,
    type: 'fillblank',
    level: 'Level 3 — Avere vs Essere',
    title: 'Choose AVERE or ESSERE',
    instruction: 'Select the correct auxiliary.',
    questions: [
      { sentence: 'Io ___ parlato con Marco.', options: ['ho', 'sono', 'ha'], answer: 'ho', explanation: 'Parlare uses avere. "Ho parlato."' },
      { sentence: 'Maria ___ andata a Roma.', options: ['è', 'ha', 'sono'], answer: 'è', explanation: 'Andare uses essere. "È andata."' },
      { sentence: 'Loro ___ mangiato la pizza.', options: ['hanno', 'sono', 'ha'], answer: 'hanno', explanation: 'Mangiare uses avere. "Hanno mangiato."' },
      { sentence: 'Tu ___ arrivato tardi.', options: ['sei', 'hai', 'è'], answer: 'sei', explanation: 'Arrivare uses essere. "Sei arrivato."' },
    ],
  },
  {
    id: 12,
    type: 'multiple',
    level: 'Level 3 — Avere vs Essere',
    title: 'Choose the Complete Form',
    instruction: 'Select the correct auxiliary + past participle.',
    questions: [
      { question: 'Maria ___ a Roma.', options: ['ha andato', 'è andata', 'ha andata'], answer: 'è andata', explanation: 'Maria (f) + andare (essere) → è andata.' },
      { question: 'Io ___ un libro ieri.', options: ['ho letto', 'sono letto', 'ha letto'], answer: 'ho letto', explanation: 'Leggere uses avere. "Ho letto."' },
      { question: 'Marco e Paolo ___ al cinema.', options: ['sono andati', 'hanno andato', 'è andato'], answer: 'sono andati', explanation: 'Andare uses essere. Masc. plural → sono andati.' },
      { question: 'Lei ___ molto stanca.', options: ['è tornata', 'ha tornato', 'sono tornata'], answer: 'è tornata', explanation: 'Tornare uses essere. Fem. sing. → è tornata.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 3 — Avere vs Essere',
    title: 'Gender Agreement',
    instruction: 'Choose the correct ending for the past participle.',
    questions: [
      { sentence: 'Marco è andat___.', options: ['o', 'a', 'i', 'e'], answer: 'o', explanation: 'Marco = masculine singular → andato.' },
      { sentence: 'Anna è andat___.', options: ['a', 'o', 'i', 'e'], answer: 'a', explanation: 'Anna = feminine singular → andata.' },
      { sentence: 'Paolo è partit___.', options: ['o', 'a', 'i', 'e'], answer: 'o', explanation: 'Paolo = masculine singular → partito.' },
      { sentence: 'Giulia è arrivat___.', options: ['a', 'o', 'i', 'e'], answer: 'a', explanation: 'Giulia = feminine singular → arrivata.' },
    ],
  },
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 3 — Avere vs Essere',
    title: 'Singular → Plural',
    instruction: 'Change the singular sentence to plural.',
    questions: [
      { sentence: 'Maria è arrivata. → Maria e Anna ___ .', options: ['sono arrivate', 'hanno arrivato', 'è arrivata'], answer: 'sono arrivate', explanation: 'Fem. plural → sono arrivate.' },
      { sentence: 'Marco è andato. → Marco e Luca ___.', options: ['sono andati', 'hanno andato', 'è andato'], answer: 'sono andati', explanation: 'Masc. plural → sono andati.' },
      { sentence: 'Io sono uscito. → Noi ___.', options: ['siamo usciti', 'abbiamo uscito', 'sono usciti'], answer: 'siamo usciti', explanation: 'Noi + masc. plural → siamo usciti.' },
      { sentence: 'Anna è partita. → Anna e Giulia ___.', options: ['sono partite', 'hanno partito', 'è partita'], answer: 'sono partite', explanation: 'Fem. plural → sono partite.' },
    ],
  },
  {
    id: 15,
    type: 'multiple',
    level: 'Level 3 — Avere vs Essere',
    title: 'Mixed Auxiliary Practice',
    instruction: 'Choose the correct complete form for each sentence.',
    questions: [
      { question: 'Ieri Marco ___ un film.', options: ['ha guardato', 'è guardato', 'ha guardata'], answer: 'ha guardato', explanation: 'Guardare uses avere. "Ha guardato."' },
      { question: 'Anna ___ al ristorante.', options: ['è andata', 'ha andato', 'sono andata'], answer: 'è andata', explanation: 'Andare uses essere. Fem. sing. → è andata.' },
      { question: 'Noi ___ il pane.', options: ['abbiamo comprato', 'siamo comprati', 'ha comprato'], answer: 'abbiamo comprato', explanation: 'Comprare uses avere. "Abbiamo comprato."' },
      { question: 'Loro ___ ieri sera.', options: ['sono usciti', 'hanno uscito', 'è uscita'], answer: 'sono usciti', explanation: 'Uscire uses essere. Masc. plural → sono usciti.' },
      { question: 'Io ___ molto.', options: ['ho lavorato', 'sono lavorato', 'ha lavorato'], answer: 'ho lavorato', explanation: 'Lavorare uses avere. "Ho lavorato."' },
    ],
  },
  // LEVEL 4 — UNDERSTANDING
  {
    id: 16,
    type: 'translation',
    level: 'Level 4 — Understanding',
    title: 'Italian → English',
    instruction: 'Choose the correct English translation.',
    direction: 'it-en',
    questions: [
      { sentence: 'Ho visto Maria ieri.', options: ['I saw Maria yesterday.', 'I see Maria yesterday.', 'Maria saw me yesterday.', 'I will see Maria.'], answer: 'I saw Maria yesterday.', explanation: '"Ho visto" = I saw. "Ieri" = yesterday.' },
      { sentence: 'Siamo andati al cinema.', options: ['We go to the cinema.', 'We went to the cinema.', 'They went to the cinema.', 'We are going to the cinema.'], answer: 'We went to the cinema.', explanation: '"Siamo andati" = we went (essere, masc. plural).' },
      { sentence: 'Anna ha comprato il libro.', options: ['Anna buys the book.', 'Anna bought the book.', 'Anna is buying the book.', 'Anna has been buying the book.'], answer: 'Anna bought the book.', explanation: '"Ha comprato" = bought/has bought.' },
      { sentence: 'Marco è arrivato alle otto.', options: ['Marco arrives at eight.', 'Marco arrived at eight.', 'Marco is arriving at eight.', 'Marco will arrive at eight.'], answer: 'Marco arrived at eight.', explanation: '"È arrivato" = arrived (past).' },
      { sentence: 'Loro hanno mangiato la pizza.', options: ['They eat the pizza.', 'They ate the pizza.', 'They are eating the pizza.', 'They will eat the pizza.'], answer: 'They ate the pizza.', explanation: '"Hanno mangiato" = they ate.' },
    ],
  },
  {
    id: 17,
    type: 'translation',
    level: 'Level 4 — Understanding',
    title: 'English → Italian',
    instruction: 'Choose the correct Italian translation.',
    direction: 'en-it',
    questions: [
      { sentence: 'I ate pizza yesterday.', options: ['Ho mangiato la pizza ieri.', 'Mangio la pizza ieri.', 'Ho mangiato la pizza domani.', 'La pizza ho mangiato ieri.'], answer: 'Ho mangiato la pizza ieri.', explanation: '"Ho mangiato" (avere + past participle) + "la pizza" + "ieri."' },
      { sentence: 'Maria went to Rome.', options: ['Maria è andata a Roma.', 'Maria ha andato a Roma.', 'Maria va a Roma.', 'Maria andava a Roma.'], answer: 'Maria è andata a Roma.', explanation: 'Andare uses essere. Maria (f) → è andata a Roma.' },
      { sentence: 'We studied Italian.', options: ['Abbiamo studiato italiano.', 'Siamo studiato italiano.', 'Studiamo italiano.', 'Abbiamo studiare italiano.'], answer: 'Abbiamo studiato italiano.', explanation: 'Studiare uses avere. "Abbiamo studiato."' },
      { sentence: 'Luca arrived at eight.', options: ['Luca è arrivato alle otto.', 'Luca ha arrivato alle otto.', 'Luca arrivare alle otto.', 'Luca è arrivata alle otto.'], answer: 'Luca è arrivato alle otto.', explanation: 'Arrivare uses essere. Luca (m) → è arrivato.' },
    ],
  },
  {
    id: 18,
    type: 'multiple',
    level: 'Level 4 — Understanding',
    title: 'Who Did What?',
    instruction: 'Read the sentence and answer the comprehension questions.',
    questions: [
      { question: 'Luca ha comprato un libro. — Who bought a book?', options: ['Luca', 'The book', 'Nobody', 'Marco'], answer: 'Luca', explanation: 'Luca is the subject — the person who did the action.' },
      { question: 'Luca ha comprato un libro. — What did Luca buy?', options: ['A book', 'A pizza', 'A car', 'A ticket'], answer: 'A book', explanation: '"Un libro" = a book (direct object).' },
      { question: 'Anna è andata a Roma. — Where did Anna go?', options: ['To Rome', 'To Milan', 'To school', 'Home'], answer: 'To Rome', explanation: '"A Roma" = to Rome.' },
      { question: 'Ho lavorato ieri sera. — When did I work?', options: ['Yesterday evening', 'This morning', 'Tomorrow', 'Last week'], answer: 'Yesterday evening', explanation: '"Ieri sera" = yesterday evening.' },
    ],
  },
  {
    id: 19,
    type: 'multiple',
    level: 'Level 4 — Understanding',
    title: 'When Did It Happen?',
    instruction: 'Match the time expression to its meaning, then answer.',
    questions: [
      { question: '"La settimana scorsa" means:', options: ['Last week', 'This week', 'Every week', 'Next week'], answer: 'Last week', explanation: '"Scorsa" = last/previous.' },
      { question: '"Ieri mattina" means:', options: ['Yesterday morning', 'Yesterday evening', 'This morning', 'Tomorrow morning'], answer: 'Yesterday morning', explanation: '"Mattina" = morning.' },
      { question: '"Anna è partita la settimana scorsa." When did Anna leave?', options: ['Last week', 'This week', 'Yesterday', 'Last month'], answer: 'Last week', explanation: '"La settimana scorsa" = last week.' },
      { question: '"Due giorni fa" means:', options: ['Two days ago', 'In two days', 'Two days before', 'Every two days'], answer: 'Two days ago', explanation: '"Fa" = ago.' },
    ],
  },
  {
    id: 20,
    type: 'matching',
    level: 'Level 4 — Understanding',
    title: 'Sentence Breakdown',
    instruction: 'Match each part of the sentence to its grammatical role.',
    pairs: [
      { left: 'Marco', right: 'subject' },
      { left: 'ha', right: 'auxiliary' },
      { left: 'mangiato', right: 'past participle' },
      { left: 'una pizza', right: 'object' },
      { left: 'ieri sera', right: 'time' },
    ],
    explanation: 'Marco (who?) ha (auxiliary) mangiato (action) una pizza (what?) ieri sera (when?).',
  },
  // LEVEL 5 — SENTENCE BUILDING
  {
    id: 21,
    type: 'wordorder',
    level: 'Level 5 — Sentence Building',
    title: 'Put the Words in Order',
    instruction: 'Arrange the words to form a correct Italian sentence.',
    questions: [
      { words: ['ieri', 'pizza', 'ho', 'mangiato', 'una'], answer: 'ieri ho mangiato una pizza', explanation: '"Ieri ho mangiato una pizza." = Yesterday I ate a pizza.' },
      { words: ['Maria', 'è', 'Roma', 'andata', 'a'], answer: 'Maria è andata a Roma', explanation: '"Maria è andata a Roma." = Maria went to Rome.' },
      { words: ['noi', 'al', 'siamo', 'cinema', 'andati'], answer: 'noi siamo andati al cinema', explanation: '"Noi siamo andati al cinema." = We went to the cinema.' },
    ],
  },
  {
    id: 22,
    type: 'fillblank',
    level: 'Level 5 — Sentence Building',
    title: 'Complete the Sentence',
    instruction: 'Fill in the blank with the correct passato prossimo form.',
    questions: [
      { sentence: 'Ieri Marco ___ un film. (guardare)', options: ['ha guardato', 'è guardato', 'ha guardata'], answer: 'ha guardato', explanation: 'Guardare uses avere. "Ha guardato."' },
      { sentence: 'Stamattina Maria ___ presto. (svegliarsi)', options: ['si è svegliata', 'ha svegliato', 'è svegliata'], answer: 'si è svegliata', explanation: 'Svegliarsi is reflexive → essere. "Si è svegliata."' },
      { sentence: 'Ieri noi ___ il pane. (comprare)', options: ['abbiamo comprato', 'siamo comprati', 'ha comprato'], answer: 'abbiamo comprato', explanation: 'Comprare uses avere. "Abbiamo comprato."' },
    ],
  },
  {
    id: 23,
    type: 'multiple',
    level: 'Level 5 — Sentence Building',
    title: 'Change the Subject',
    instruction: 'Rewrite the sentence with the new subject.',
    questions: [
      { question: 'Io ho mangiato. → Tu ___ .', options: ['hai mangiato', 'ho mangiato', 'ha mangiato'], answer: 'hai mangiato', explanation: 'Tu + avere → hai mangiato.' },
      { question: 'Io ho mangiato. → Lui ___ .', options: ['ha mangiato', 'ho mangiato', 'hai mangiato'], answer: 'ha mangiato', explanation: 'Lui/lei + avere → ha mangiato.' },
      { question: 'Io ho mangiato. → Noi ___ .', options: ['abbiamo mangiato', 'ho mangiato', 'hanno mangiato'], answer: 'abbiamo mangiato', explanation: 'Noi + avere → abbiamo mangiato.' },
      { question: 'Io ho mangiato. → Voi ___ .', options: ['avete mangiato', 'abbiamo mangiato', 'hanno mangiato'], answer: 'avete mangiato', explanation: 'Voi + avere → avete mangiato.' },
      { question: 'Io ho mangiato. → Loro ___ .', options: ['hanno mangiato', 'ho mangiato', 'avete mangiato'], answer: 'hanno mangiato', explanation: 'Loro + avere → hanno mangiato.' },
    ],
  },
  {
    id: 24,
    type: 'fillblank',
    level: 'Level 5 — Sentence Building',
    title: 'Change Masculine / Feminine',
    instruction: 'Rewrite with the new subject, remembering agreement.',
    questions: [
      { sentence: 'Marco è andato. → Anna ___ .', options: ['è andata', 'ha andato', 'è andato'], answer: 'è andata', explanation: 'Anna = feminine → è andata.' },
      { sentence: 'Anna è partita. → Marco ___ .', options: ['è partito', 'ha partito', 'è partita'], answer: 'è partito', explanation: 'Marco = masculine → è partito.' },
      { sentence: 'Luca è arrivato. → Giulia ___ .', options: ['è arrivata', 'ha arrivato', 'è arrivato'], answer: 'è arrivata', explanation: 'Giulia = feminine → è arrivata.' },
      { sentence: 'Maria è uscita. → Paolo ___ .', options: ['è uscito', 'ha uscito', 'è uscita'], answer: 'è uscito', explanation: 'Paolo = masculine → è uscito.' },
    ],
  },
  {
    id: 25,
    type: 'translation',
    level: 'Level 5 — Sentence Building',
    title: 'Create Your Own Sentence',
    instruction: 'Translate the cues into a complete Italian sentence.',
    direction: 'en-it',
    questions: [
      { sentence: 'Yesterday I ate a pizza.', options: ['Ieri ho mangiato una pizza.', 'Ieri mangio una pizza.', 'Ieri ho mangiato pizza.', 'Ho ieri mangiato una pizza.'], answer: 'Ieri ho mangiato una pizza.', explanation: 'Ieri + ho mangiato (avere + past participle) + una pizza.' },
      { sentence: 'Maria went to school this morning.', options: ['Maria è andata a scuola stamattina.', 'Maria ha andato a scuola stamattina.', 'Maria va a scuola stamattina.', 'Maria è andata a scuola ieri.'], answer: 'Maria è andata a scuola stamattina.', explanation: 'Andare uses essere. Maria (f) → è andata. Stamattina = this morning.' },
    ],
  },
  // LEVEL 6 — REAL-LIFE COMMUNICATION
  {
    id: 26,
    type: 'story',
    level: 'Level 6 — Real-Life Communication',
    title: 'Yesterday — A Dialogue',
    storyTitle: 'Cosa hai fatto ieri?',
    story: "Anna: Cosa hai fatto ieri?\n\nMarco: Ho lavorato la mattina. La sera sono andato al ristorante con un amico.\n\nAnna: Che cosa avete mangiato?\n\nMarco: Abbiamo mangiato la pizza e abbiamo bevuto una birra.\n\nAnna: Siete tornati tardi?\n\nMarco: No, siamo tornati a casa alle dieci.",
    vocab: [
      { word: 'fatto', meaning: 'done (fare → fatto)' },
      { word: 'la sera', meaning: 'in the evening' },
      { word: 'bevuto', meaning: 'drunk (bere → bevuto)' },
      { word: 'birra', meaning: 'beer' },
      { word: 'tardi', meaning: 'late' },
    ],
    translation: "Anna: What did you do yesterday?\n\nMarco: I worked in the morning. In the evening I went to a restaurant with a friend.\n\nAnna: What did you eat?\n\nMarco: We ate pizza and drank a beer.\n\nAnna: Did you come home late?\n\nMarco: No, we came home at ten.",
    questions: [
      { question: 'Where did Marco go in the evening?', options: ['To a restaurant', 'To the cinema', 'To a bar', 'Home'], answer: 'To a restaurant', explanation: '"Sono andato al ristorante." = He went to a restaurant.' },
      { question: 'What did they eat?', options: ['Pizza', 'Pasta', 'Rice', 'Fish'], answer: 'Pizza', explanation: '"Abbiamo mangiato la pizza."' },
      { question: 'What auxiliary does Marco use for "andare"?', options: ['essere', 'avere'], answer: 'essere', explanation: '"Sono andato" — andare uses essere.' },
      { question: 'What time did they return home?', options: ['Ten o\'clock', 'Eleven o\'clock', 'Nine o\'clock', 'Midnight'], answer: 'Ten o\'clock', explanation: '"Siamo tornati a casa alle dieci."' },
      { question: 'What is the past participle of "bere" (to drink)?', options: ['bevuto', 'bevito', 'bere', 'bevo'], answer: 'bevuto', explanation: 'Bere is irregular → bevuto.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 6 — Real-Life Communication',
    title: 'Weekend Conversation',
    storyTitle: 'Il weekend di Luca',
    story: "Sabato sono andato al cinema con mia sorella. Ho visto un film italiano — era molto bello. Dopo il film siamo andati a mangiare al ristorante. Io ho preso la pasta e lei ha preso il pesce.\n\nDomenica mi sono svegliato presto. Ho fatto colazione e poi ho studiato italiano per due ore. Nel pomeriggio sono uscito con gli amici e siamo andati a prendere un caffè in centro.",
    vocab: [
      { word: 'era', meaning: 'was (essere, imperfetto)' },
      { word: 'preso', meaning: 'taken/ordered (prendere → preso)' },
      { word: 'pesce', meaning: 'fish' },
      { word: 'svegliato', meaning: 'woken up (svegliarsi)' },
      { word: 'colazione', meaning: 'breakfast' },
      { word: 'in centro', meaning: 'in the centre/downtown' },
    ],
    translation: "On Saturday I went to the cinema with my sister. I saw an Italian film — it was very good. After the film we went to eat at a restaurant. I had the pasta and she had the fish.\n\nOn Sunday I woke up early. I had breakfast and then I studied Italian for two hours. In the afternoon I went out with friends and we went to have a coffee downtown.",
    questions: [
      { question: 'Where did Luca go on Saturday morning?', options: ['To the cinema', 'To school', 'To a restaurant', 'To the park'], answer: 'To the cinema', explanation: '"Sabato sono andato al cinema."' },
      { question: 'What did his sister order?', options: ['Fish', 'Pasta', 'Pizza', 'Meat'], answer: 'Fish', explanation: '"Lei ha preso il pesce."' },
      { question: 'What time did Luca wake up on Sunday?', options: ['Early', 'Late', 'At noon', 'At midnight'], answer: 'Early', explanation: '"Mi sono svegliato presto."' },
      { question: 'What did Luca study on Sunday?', options: ['Italian', 'Math', 'History', 'English'], answer: 'Italian', explanation: '"Ho studiato italiano per due ore."' },
      { question: 'Which auxiliary does "uscire" use?', options: ['essere', 'avere'], answer: 'essere', explanation: '"Sono uscito" — uscire uses essere.' },
    ],
  },
  // LEVEL 7 — STORIES
  {
    id: 28,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Beginner Story — Ieri di Marco',
    storyTitle: 'Ieri di Marco',
    story: "Ieri Marco si è svegliato alle sette. Ha fatto colazione velocemente e poi è andato al lavoro in autobus. A pranzo ha mangiato un panino al bar vicino all'ufficio.\n\nLa sera è tornato a casa alle sei. Ha cucinato la pasta e ha guardato un film in televisione. Prima di dormire ha letto un libro per mezz'ora. Si è addormentato alle undici.",
    vocab: [
      { word: 'velocemente', meaning: 'quickly' },
      { word: 'autobus', meaning: 'bus' },
      { word: 'vicino', meaning: 'near/close to' },
      { word: 'cucinato', meaning: 'cooked (cucinare)' },
      { word: 'addormentato', meaning: 'fell asleep (addormentarsi)' },
    ],
    translation: "Yesterday Marco woke up at seven. He had breakfast quickly and then went to work by bus. At lunch he ate a sandwich at the bar near the office.\n\nIn the evening he came home at six. He cooked pasta and watched a film on television. Before sleeping he read a book for half an hour. He fell asleep at eleven.",
    questions: [
      { question: 'What time did Marco wake up?', options: ['At seven', 'At six', 'At eight', 'At five'], answer: 'At seven', explanation: '"Si è svegliato alle sette."' },
      { question: 'How did Marco go to work?', options: ['By bus', 'By car', 'On foot', 'By bike'], answer: 'By bus', explanation: '"È andato al lavoro in autobus."' },
      { question: 'What did Marco eat for lunch?', options: ['A sandwich', 'Pasta', 'Pizza', 'Rice'], answer: 'A sandwich', explanation: '"Ha mangiato un panino."' },
      { question: 'What time did Marco fall asleep?', options: ['At eleven', 'At ten', 'At midnight', 'At nine'], answer: 'At eleven', explanation: '"Si è addormentato alle undici."' },
      { question: 'Which past participles use ESSERE in this story?', options: ['svegliato, andato, tornato, addormentato', 'fatto, mangiato, cucinato, letto', 'svegliato, fatto, letto, addormentato', 'andato, mangiato, cucinato, guardato'], answer: 'svegliato, andato, tornato, addormentato', explanation: 'Verbs with essere: svegliarsi, andare, tornare, addormentarsi.' },
      { question: 'Write a sentence about what you did yesterday using passato prossimo.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Ieri ho mangiato la pasta. / Ieri sono andato/a a scuola. Any correct use of passato prossimo is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Story With Missing Verbs',
    storyTitle: 'Un giorno di Sofia',
    story: "Ieri Sofia ______ (andare) al supermercato di mattina. Ha fatto la spesa e ______ (comprare) della frutta, del pane e del formaggio.\n\nPoi ______ (tornare) a casa e ______ (preparare) un pranzo delizioso. Ha mangiato una insalata con il pane fresco.\n\nNel pomeriggio ______ (uscire) con le amiche. Sono ______ (andare) al parco e ______ (passare) due ore a parlare e ridere.\n\nLa sera ______ (tornare) a casa stanca ma felice. ______ (Fare) una doccia calda e poi ______ (leggere) un libro prima di dormire.",
    vocab: [
      { word: 'spesa', meaning: 'shopping/groceries' },
      { word: 'delizioso', meaning: 'delicious' },
      { word: 'insalata', meaning: 'salad' },
      { word: 'parco', meaning: 'park' },
      { word: 'ridere', meaning: 'to laugh' },
    ],
    questions: [
      { question: 'Fill blank 1: Sofia ___ al supermercato.', options: ['è andata', 'ha andato', 'sono andata'], answer: 'è andata', explanation: 'Andare uses essere. Sofia (f) → è andata.' },
      { question: 'Fill blank 2: ___ della frutta.', options: ['ha comprato', 'è comprata', 'ha comprata'], answer: 'ha comprato', explanation: 'Comprare uses avere. "Ha comprato."' },
      { question: 'Fill blank 3: ___ a casa.', options: ['è tornata', 'ha tornato', 'sono tornata'], answer: 'è tornata', explanation: 'Tornare uses essere. Fem. sing. → è tornata.' },
      { question: 'Fill blank 4: ___ un pranzo.', options: ['ha preparato', 'è preparata', 'ha preparata'], answer: 'ha preparato', explanation: 'Preparare uses avere. "Ha preparato."' },
      { question: 'Fill blank 5: ___ con le amiche.', options: ['è uscita', 'ha uscito', 'sono uscita'], answer: 'è uscita', explanation: 'Uscire uses essere. Fem. sing. → è uscita.' },
      { question: 'Fill blank 6: Sono ___ al parco.', options: ['andate', 'andati', 'andato'], answer: 'andate', explanation: 'Fem. plural (Sofia + amiche) → sono andate.' },
      { question: 'Fill blank 7: ___ due ore.', options: ['hanno passato', 'sono passate', 'è passata'], answer: 'hanno passato', explanation: 'Passare uses avere. "Hanno passato."' },
      { question: 'Fill blank 8: ___ a casa.', options: ['è tornata', 'ha tornato', 'sono tornata'], answer: 'è tornata', explanation: 'Tornare uses essere. Fem. sing. → è tornata.' },
      { question: 'Fill blank 9: ___ una doccia.', options: ['ha fatto', 'è fatta', 'ha fatta'], answer: 'ha fatto', explanation: 'Fare uses avere. "Ha fatto."' },
      { question: 'Fill blank 10: ___ un libro.', options: ['ha letto', 'è letto', 'ha letta'], answer: 'ha letto', explanation: 'Leggere uses avere. Irregular participle → letto.' },
    ],
  },
  // LEVEL 8 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 8 — Final Proficiency Test',
    title: 'Passato Prossimo Mastery Test',
    instruction: 'Answer all 25 questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Present vs past recognition
      { question: '"Ieri ho lavorato" is:', options: ['Present', 'Past'], answer: 'Past' },
      // Regular -are participle
      { question: 'The past participle of "studiare" is:', options: ['studiato', 'studiuta', 'studiiti', 'studiare'], answer: 'studiato' },
      // Regular -ere participle
      { question: 'The past participle of "credere" is:', options: ['creduto', 'credato', 'credito', 'crediuto'], answer: 'creduto' },
      // Regular -ire participle
      { question: 'The past participle of "dormire" is:', options: ['dormito', 'dormuto', 'dormato', 'dormito'], answer: 'dormito' },
      // Avere conjugation
      { question: 'Io ___ parlato.', options: ['ho', 'hai', 'ha', 'ho'], answer: 'ho' },
      // Essere conjugation
      { question: 'Marco ___ andato.', options: ['è', 'ha', 'sono', 'è'], answer: 'è' },
      // Avere vs essere
      { question: '"Mangiare" uses auxiliary:', options: ['avere', 'essere'], answer: 'avere' },
      // Avere vs essere
      { question: '"Arrivare" uses auxiliary:', options: ['essere', 'avere'], answer: 'essere' },
      // Gender agreement
      { question: 'Anna è ___ a Roma.', options: ['andata', 'andato', 'andati', 'andate'], answer: 'andata' },
      // Plural agreement
      { question: 'Marco e Paolo sono ___ al cinema.', options: ['andati', 'andate', 'andato', 'andata'], answer: 'andati' },
      // Common irregular
      { question: 'The past participle of "fare" is:', options: ['fatto', 'fattuto', 'fatto', 'faito'], answer: 'fatto' },
      // Common irregular
      { question: 'The past participle of "vedere" is:', options: ['visto', 'veduto', 'vedito', 'vistuto'], answer: 'visto' },
      // Italian → English
      { question: '"Ho letto un libro ieri" means:', options: ['I read a book yesterday.', 'I read a book.', 'I was reading a book.', 'I will read a book.'], answer: 'I read a book yesterday.' },
      // Italian → English
      { question: '"Siamo andati al cinema" means:', options: ['We went to the cinema.', 'We go to the cinema.', 'We are going to the cinema.', 'They went to the cinema.'], answer: 'We went to the cinema.' },
      // English → Italian
      { question: '"Maria ate a pizza" in Italian is:', options: ['Maria ha mangiato una pizza.', 'Maria è mangiata una pizza.', 'Maria mangiato una pizza.', 'Maria ho mangiato una pizza.'], answer: 'Maria ha mangiato una pizza.' },
      // Sentence ordering
      { question: 'Choose the correct order: "ieri / ho / pizza / mangiato / una"', options: ['Ieri ho mangiato una pizza.', 'Ho mangiato ieri una pizza.', 'Una pizza ho mangiato ieri.', 'Ieri una pizza ho mangiato.'], answer: 'Ieri ho mangiato una pizza.' },
      // Sentence completion
      { question: 'Io ___ a Roma l\'anno scorso. (andare)', options: ['sono andato', 'ho andato', 'è andato', 'siamo andati'], answer: 'sono andato' },
      // Irregular participle
      { question: 'The past participle of "scrivere" is:', options: ['scritto', 'scrituto', 'scrivuto', 'scritto'], answer: 'scritto' },
      // Agreement mastery
      { question: 'Lei è ___ tardi ieri sera. (arrivare)', options: ['arrivata', 'arrivato', 'arrivati', 'arrivate'], answer: 'arrivata' },
      // Comprehension
      { question: '"Luca ha preso il caffè al bar" — What did Luca take?', options: ['Coffee', 'Tea', 'Juice', 'Water'], answer: 'Coffee' },
      // Time expression
      { question: '"La settimana scorsa" means:', options: ['Last week', 'This week', 'Next week', 'Every week'], answer: 'Last week' },
      // Production
      { question: 'Write "I went to Rome" in Italian:', type: 'text', answer: 'Sono andato a Roma', acceptedAnswers: ['sono andato a roma', 'sono andata a roma', 'son andato a roma', 'ci sono andato a roma'] },
      // Production
      { question: 'Write "She ate pizza" in Italian:', type: 'text', answer: 'Ha mangiato la pizza', acceptedAnswers: ['ha mangiato la pizza', 'lei ha mangiato la pizza', 'ha mangiato pizza'] },
      // Dialogue comprehension (based on passage below)
      { question: 'READ FIRST: "ieri paola è uscita alle otto. è andata al lavoro in macchina. a pranzo ha mangiato una pizza con le colleghe. la sera è tornata a casa alle sette e ha cucinato la cena. dopo cena ha guardato un film in televisione."\n\nWhen did Paola leave?', options: ['At eight', 'At seven', 'At noon', 'At six'], answer: 'At eight' },
      { question: 'READ FIRST: "ieri paola è uscita alle otto. è andata al lavoro in macchina. a pranzo ha mangiato una pizza con le colleghe. la sera è tornata a casa alle sette e ha cucinato la cena. dopo cena ha guardato un film in televisione."\n\nHow did Paola go to work?', options: ['By car', 'By bus', 'On foot', 'By bike'], answer: 'By car' },
    ],
  },
];

export const passatoStories = [
  {
    title: 'Ieri di Marco',
    level: 'Beginner',
    wordCount: '~85',
    story: "Ieri Marco si è svegliato alle sette. Ha fatto colazione velocemente e poi è andato al lavoro in autobus. A pranzo ha mangiato un panino al bar vicino all'ufficio.\n\nLa sera è tornato a casa alle sei. Ha cucinato la pasta e ha guardato un film in televisione. Prima di dormire ha letto un libro per mezz'ora. Si è addormentato alle undici.",
    vocab: [
      { word: 'velocemente', meaning: 'quickly' },
      { word: 'autobus', meaning: 'bus' },
      { word: 'vicino', meaning: 'near' },
      { word: 'cucinato', meaning: 'cooked' },
      { word: 'addormentato', meaning: 'fell asleep' },
    ],
    translation: "Yesterday Marco woke up at seven. He had breakfast quickly and then went to work by bus. At lunch he ate a sandwich at the bar near the office.\n\nIn the evening he came home at six. He cooked pasta and watched a film on television. Before sleeping he read a book for half an hour. He fell asleep at eleven.",
    questions: [
      { question: 'What time did Marco wake up?', options: ['At seven', 'At six', 'At eight', 'At five'], answer: 'At seven', explanation: '"Si è svegliato alle sette."' },
      { question: 'How did Marco get to work?', options: ['By bus', 'By car', 'On foot', 'By bike'], answer: 'By bus', explanation: '"È andato al lavoro in autobus."' },
      { question: 'What did Marco eat for lunch?', options: ['A sandwich', 'Pasta', 'Pizza', 'Salad'], answer: 'A sandwich', explanation: '"Ha mangiato un panino."' },
      { question: 'Which verbs use ESSERE?', options: ['svegliarsi, andare, tornare, addormentarsi', 'fare, mangiare, cucinare, leggere', 'svegliarsi, fare, leggere, guardare', 'andare, mangiare, cucinare, tornare'], answer: 'svegliarsi, andare, tornare, addormentarsi', explanation: 'Verbs of movement/state change use essere.' },
      { question: 'Write one sentence about what Marco did yesterday.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Marco ha mangiato un panino. / Marco è andato al lavoro.' },
    ],
  },
  {
    title: 'Un weekend a Firenze',
    level: 'Intermediate',
    wordCount: '~110',
    story: "Sabato mattina Giulia e Marco sono partiti per Firenze. Sono partiti presto e sono arrivati alle nove. Hanno visitato il Duomo e hanno fatto molte foto.\n\nA pranzo hanno mangiato la fiorentina al ristorante. Nel pomeriggio hanno camminato lungo l'Arno e hanno comprato dei souvenir. Hanno bevuto un caffè in una piazza bellissima.\n\nLa sera sono tornati a casa in treno. Sono arrivati a casa alle dieci. Giulia ha detto che è stato un giorno perfetto.",
    vocab: [
      { word: 'partiti', meaning: 'left (partire → partito)' },
      { word: 'fiorentina', meaning: 'Florentine steak' },
      { word: 'camminato', meaning: 'walked (camminare)' },
      { word: 'souvenir', meaning: 'souvenirs' },
      { word: 'detto', meaning: 'said (dire → detto)' },
    ],
    translation: "Saturday morning Giulia and Marco left for Florence. They left early and arrived at nine. They visited the Cathedral and took many photos.\n\nAt lunch they had the Florentine steak at a restaurant. In the afternoon they walked along the Arno and bought souvenirs. They drank a coffee in a beautiful square.\n\nIn the evening they came home by train. They arrived home at ten. Giulia said it had been a perfect day.",
    questions: [
      { question: 'Where did they go?', options: ['Florence', 'Rome', 'Milan', 'Naples'], answer: 'Florence', explanation: '"Sono partiti per Firenze."' },
      { question: 'What did they eat at lunch?', options: ['Florentine steak', 'Pizza', 'Pasta', 'Sandwich'], answer: 'Florentine steak', explanation: '"Hanno mangiato la fiorentina."' },
      { question: 'How did they return home?', options: ['By train', 'By car', 'By bus', 'By plane'], answer: 'By train', explanation: '"Sono tornati a casa in treno."' },
      { question: 'What is the past participle of "dire" (to say)?', options: ['detto', 'ditto', 'diretto', 'dito'], answer: 'detto', explanation: 'Dire is irregular → detto.' },
      { question: 'Write one sentence using passato prossimo about what Giulia did.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Giulia ha fatto molte foto. / Giulia è partita per Firenze.' },
    ],
  },
  {
    title: 'Un giorno speciale',
    level: 'Challenge',
    wordCount: '~130',
    story: "Era il compleanno di mia nonna. Mi sono svegliato presto per preparare la torta. Ho comprato gli ingredienti al mercato e poi ho cucinato tutto il giorno. Mia mamma mi ha aiutato nella cucina.\n\nAlle otto di sera tutti i parenti sono arrivati a casa mia. Mia nonna è entrata per ultima e quando ha visto la torta ha pianto dalla felicità. Abbiamo mangiato, abbiamo bevuto, abbiamo riso e abbiamo cantato insieme.\n\nDopo la festa ho lavato i piatti e ho sparecchiato tutto. Mia nonna mi ha abbracciato e mi ha detto che è stato il compleanno più bello della sua vita. Io sono andato a letto alle undici, stanco ma felice.",
    vocab: [
      { word: 'compleanno', meaning: 'birthday' },
      { word: 'ingredienti', meaning: 'ingredients' },
      { word: 'parenti', meaning: 'relatives' },
      { word: 'pianto', meaning: 'cried (piangere → pianto)' },
      { word: 'abbracciato', meaning: 'hugged (abbracciare)' },
      { word: 'sparecchiato', meaning: 'cleared the table (sparecchiare)' },
    ],
    translation: "It was my grandmother's birthday. I woke up early to prepare the cake. I bought the ingredients at the market and then I cooked all day. My mum helped me in the kitchen.\n\nAt eight in the evening all the relatives arrived at my house. My grandmother came in last and when she saw the cake she cried with happiness. We ate, we drank, we laughed, and we sang together.\n\nAfter the party I washed the dishes and cleared everything. My grandmother hugged me and told me it was the most beautiful birthday of her life. I went to bed at eleven, tired but happy.",
    questions: [
      { question: 'Why did the narrator wake up early?', options: ['To prepare a cake', 'To go to work', 'To study', 'To exercise'], answer: 'To prepare a cake', explanation: '"Mi sono svegliato presto per preparare la torta."' },
      { question: 'What did the grandmother do when she saw the cake?', options: ['She cried with happiness', 'She laughed', 'She was angry', 'She left'], answer: 'She cried with happiness', explanation: '"Ha pianto dalla felicità."' },
      { question: 'What is the past participle of "piangere" (to cry)?', options: ['pianto', 'pianguto', 'piagito', 'pianto'], answer: 'pianto', explanation: 'Piangere is irregular → pianto.' },
      { question: 'How many uses of ESSERE can you find in this story?', options: ['At least 6', 'At least 2', 'None', 'Only 1'], answer: 'At least 6', explanation: 'svegliarsi, arrivare, entrare, andare (many more).' },
      { question: 'Write a sentence about what the narrator did after the party.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Ho lavato i piatti. / Ho sparecchiato tutto.' },
    ],
  },
];

export const passatoFinalTest = passatoExercises.find((e) => e.id === 30).questions;

export const passatoFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You can confidently understand and form common passato prossimo sentences. You have mastered the most important Italian past tense.' },
  { min: 75, grade: 'Very good!', message: 'You understand the main structure. Review avere/essere and agreement to reach full confidence.' },
  { min: 60, grade: 'Almost there!', message: 'Review auxiliary verbs and past participles, then try the exercises again.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the lessons before taking the final test again. Focus on auxiliary selection and agreement.' },
];
