export const pronomiRelativiStages = [
  {
    id: 'concept',
    title: 'What are Relative Pronouns?',
    subtitle: 'che, cui, il quale, chi — connecting two clauses',
    sections: [
      {
        heading: 'Part 1 — Two sentences, one noun',
        explanation: 'Relative pronouns (pronomi relativi) LINK two clauses that talk about the same noun. The noun that the pronoun replaces is called the ANTECEDENT.',
        bullets: [
          { text: 'Il ragazzo ha un libro. Il libro parla di Roma.', example: 'two sentences sharing the same noun: il libro' },
          { text: 'Il ragazzo ha un libro che parla di Roma.', example: 'one sentence — "che" replaces "il libro" (the antecedent)' },
          { text: 'La donna abita qui. La donna è simpatica.', example: '→ La donna che abita qui è simpatica.' },
        ],
        timeline: { left: 'ANTECEDENT (the noun)', center: 'RELATIVE PRONOUN', right: 'RELATIVE CLAUSE', examples: ['la casa', 'che · in cui', 'è bellissima'] },
        note: 'Without the relative pronoun you would repeat the noun twice; with it, the sentence flows as one unbroken idea.',
      },
      {
        heading: 'Part 2 — Meet the four',
        explanation: 'Italian has four main relative pronouns, each with its own job. You cannot use them interchangeably.',
        bullets: [
          { text: 'che — invariable: subject or direct object.', example: 'La casa che vedo. (object) · La casa che è grande. (subject)' },
          { text: 'cui — used after prepositions: di cui, in cui, a cui...', example: 'La casa in cui vivo.' },
          { text: 'il quale / la quale / i quali / le quali — agrees with the noun, more formal.', example: 'Le case, le quali sono antiche...' },
          { text: 'chi — "the one who", used with NO antecedent.', example: 'Chi cerca, trova.' },
          { text: 'il cui / la cui / i cui / le cui — possessive "whose".', example: 'La donna il cui nome comincia per A.' },
        ],
        patterns: ['che (subject / object)', 'cui (after prepositions)', 'il quale (formal, agreeing)', 'chi (free relative)', 'il cui (whose)'],
        note: 'Look at the noun before the gap and the verb after it: if no preposition is needed, use che; if a preposition is involved, use cui or il quale.',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Che & Il Quale',
    subtitle: 'The invariable che and the agreeing il quale',
    sections: [
      {
        heading: 'Part 3 — che as subject',
        explanation: 'When che replaces the SUBJECT of the relative clause (the person or thing doing the action), use plain che + the verb. che never changes form and never adds a preposition.',
        examples: [
          { italian: 'Il regista che ha vinto il premio è italiano.', translation: 'The director who won the prize is Italian.' },
          { italian: 'Le notizie che arrivano sono buone.', translation: 'The news that arrives is good.' },
          { italian: 'Il treno che parte alle otto è in ritardo.', translation: 'The train that leaves at eight is late.' },
        ],
        patterns: ['Il ragazzo che parla… (subject)', 'La pizza che è sul tavolo… (subject)', 'L\'autobus che parte… (subject)'],
        note: 'Test: replace "che" with the noun — if the noun is the one DOING the verb, it is the subject.',
      },
      {
        heading: 'Part 4 — che as direct object',
        explanation: 'When che replaces the DIRECT OBJECT (the person or thing receiving the action), it also stays che. Note that English often drops the pronoun ("the book I read") but Italian keeps it.',
        examples: [
          { italian: 'Il libro che leggo è bello.', translation: 'The book that I am reading is nice.' },
          { italian: 'La canzone che ascolto mi piace.', translation: 'The song that I listen to — I like it.' },
          { italian: 'La pizza che mangiamo è ottima.', translation: 'The pizza we are eating is excellent.' },
        ],
        patterns: ['Il libro che leggo… (object)', 'La pizza che mangiamo… (object)', 'I film che vediamo… (object)'],
        note: 'A verb without a preposition takes che. The moment a preposition appears (parlo DI, abito IN), che becomes impossible.',
      },
      {
        heading: 'Part 5 — il quale / la quale / i quali / le quali',
        explanation: 'Il quale (m sing), la quale (f sing), i quali (m pl), le quali (f pl) mean "the which / whom". They AGREE with the noun and can replace che in more formal Italian or follow any preposition.',
        examples: [
          { italian: 'La ragazza con la quale sono uscito è simpatica.', translation: 'The girl with whom I went out is nice.' },
          { italian: 'Le città dalle quali vengo sono antiche.', translation: 'The cities from which I come are ancient.' },
          { italian: 'Il film, il quale dura tre ore, è molto lungo.', translation: 'The film, which lasts three hours, is very long.' },
        ],
        patterns: ['il quale (masch sing)', 'la quale (fem sing)', 'i quali (masch plur)', 'le quali (fem plur)'],
        note: 'Il quale can replace che everywhere, but never forget the agreement: libro → il quale, lettera → la quale, libri → i quali, lettere → le quali.',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'Cui, Chi & Special Uses',
    subtitle: 'cui with prepositions, il cui (whose), and the free relative chi',
    sections: [
      {
        heading: 'Part 6 — cui after prepositions',
        explanation: 'When the relative clause needs a preposition (di, a, da, in, con, per, su), che is impossible in Italian. Use CUI after the right preposition — cui is invariable: identical for every gender and number.',
        bullets: [
          { text: 'parlare di → di cui', example: 'Il libro di cui parliamo.' },
          { text: 'scrivere a → a cui', example: 'La ragazza a cui ho scritto.' },
          { text: 'abitare in → in cui', example: 'La casa in cui abito.' },
          { text: 'uscire con → con cui', example: 'Le amiche con cui esco.' },
          { text: 'venire da → da cui', example: 'Il paese da cui vengo.' },
          { text: 'lavorare per → per cui', example: 'L\'azienda per cui lavoro.' },
        ],
        focus: { sentence: 'Il libro DI CUI parliamo è famoso.', breakdown: [{ part: 'parlare', role: 'verb' }, { part: 'di', role: 'needed preposition' }, { part: 'cui', role: 'relative pronoun' }, { part: 'famoso', role: 'adjective' }], meaning: 'you talk ABOUT a book, so "di" must stay: di cui.' },
        note: 'Translate the preposition together with cui: di cui = about/of which, in cui = in which, con cui = with whom... Learn each verb with its preposition.',
      },
      {
        heading: 'Part 7 — il cui, la cui, i cui, le cui (whose)',
        explanation: 'Il cui joins the words "di" + "il": di cui il → il cui. It is the POSSESSIVE relative pronoun = WHOSE. It agrees ONLY with the noun that FOLLOWS it (the possessed thing), never with the possessor.',
        bullets: [
          { text: 'La donna il cui nome è Emma.', example: 'whose name (nome — masch sing)' },
          { text: 'La ragazza la cui sorella canta.', example: 'whose sister (sorella — fem sing)' },
          { text: 'I bambini i cui giocattoli sono nuovi.', example: 'whose toys (giocattoli — masch plur)' },
          { text: 'Le città le cui strade sono antiche.', example: 'whose streets (strade — fem plur)' },
        ],
        patterns: ['il cui + masch sing', 'la cui + fem sing', 'i cui + masch plur', 'le cui + fem plur'],
        note: 'The possessor never decides the form: Carla and Marco both give "la cui sorella", because sorella is feminine singular either way.',
      },
      {
        heading: 'Part 8 — chi (the one who)',
        explanation: 'Chi is a "free" relative pronoun — it needs NO antecedent. It packs the meaning "the person who / anyone who" and always takes a third-person singular verb. It also appears in indirect questions (Non so chi sia).',
        bullets: [
          { text: 'Chi cerca, trova.', example: 'Whoever looks, finds.' },
          { text: 'Chi non lavora, non mangia.', example: 'Who does not work, does not eat.' },
          { text: 'Chi tace acconsente.', example: 'Silence means consent.' },
          { text: 'Non so chi sia arrivato.', example: 'I do not know who arrived.' },
        ],
        note: 'Handy rule: if there is NO noun before it → chi; if there is a noun → che / cui / quale.',
      },
    ],
  },
  {
    id: 'usage',
    title: 'Choosing the Right Pronoun',
    subtitle: 'che vs cui vs il quale vs chi',
    sections: [
      {
        heading: 'Part 9 — che vs cui',
        explanation: 'The fastest decision: does the verb need a preposition? If NO → che. If YES → that preposition + cui (or il quale).',
        examples: [
          { italian: 'Il libro che leggo.', translation: 'the book I read → che (no preposition)' },
          { italian: 'Il libro di cui parlo.', translation: 'the book I talk about → di cui (parlare di)' },
          { italian: 'La casa che compro.', translation: 'the house I buy → che (compro la casa)' },
          { italian: 'La casa in cui abito.', translation: 'the house I live in → in cui (abitare in)' },
        ],
        note: 'Hear the verb with its preposition first. Che cannot be mixed with a preposition — never "la casa che abito in".',
      },
      {
        heading: 'Part 10 — che vs il quale',
        explanation: 'Il quale / la quale are interchangeable with che but sound more formal and can prevent ambiguity. Use che in everyday speech; prefer il quale when writing or when "che" would repeat itself.',
        examples: [
          { italian: 'Il film che vediamo stasera. (informal)', translation: 'Il film il quale vediamo stasera. (formal)' },
          { italian: 'La ragazza con la quale parlo.', translation: 'with whom → la quale (che is impossible after con)' },
          { italian: 'Le scarpe che ho comprato, le quali costano molto.', translation: 'the shoes, which cost a lot (agreement avoids confusion)' },
        ],
        note: 'After a preposition you have a free choice: a cui or al quale, di cui or del quale. Both are correct.',
      },
      {
        heading: 'Part 11 — chi in daily life',
        explanation: 'Chi appears constantly in proverbs, general statements, and announcements — anywhere the speaker means "anyone who".',
        examples: [
          { italian: 'Chi ben comincia è a metà dell\'opera.', translation: 'Well begun is half done.' },
          { italian: 'Chi arriva in ritardo perde il treno.', translation: 'Anyone who arrives late misses the train.' },
          { italian: 'Chi vuole, può.', translation: 'Where there is a will, there is a way.' },
          { italian: 'Abbiamo aiutato chi aveva bisogno.', translation: 'We helped whoever needed it.' },
        ],
      },
      {
        heading: 'Part 12 — everyday combinations',
        explanation: 'Some relative expressions have frozen, everyday meanings. Learn them as chunks:',
        bullets: [
          { text: 'quello che', example: 'Tutto quello che so — everything that I know ("what").' },
          { text: 'per cui', example: 'Questo è il motivo per cui parto — that is why I am leaving.' },
          { text: 'il che', example: 'L\'autobus è in ritardo, il che mi secca — which (the whole clause) annoys me.' },
          { text: 'chi', example: 'Chi vuole partecipare, venga — anyone who wants to join, come.' },
        ],
        note: 'Notice that "il che" refers to the WHOLE previous clause, not to a single noun — a very Italian habit.',
      },
    ],
  },
];

export const pronomiRelativiExercises = [
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Meet the Relative Pronouns',
    instruction: 'Recognise what relative pronouns are and what they do.',
    questions: [
      { question: 'A relative pronoun like che, cui, or il quale:', options: ['connects two clauses that talk about the same noun', 'replaces an adjective', 'makes a verb negative', 'is only used in questions'], answer: 'connects two clauses that talk about the same noun', explanation: 'The pronoun links its clause to the antecedent noun.' },
      { question: 'In "Il ragazzo che parla è mio cugino", "che" refers to:', options: ['il ragazzo', 'parla', 'mio', 'cugino'], answer: 'il ragazzo', explanation: '"il ragazzo" is the antecedent that "che" replaces.' },
      { question: 'The relative pronoun that NEVER changes its form is:', options: ['che', 'il quale', 'la quale', 'le quali'], answer: 'che', explanation: 'che is invariable; il quale/la quale/le quali agree with the noun.' },
      { question: '"chi" means:', options: ['the one who', 'the thing which', 'the reason why', 'the time when'], answer: 'the one who', explanation: 'chi is a free relative pronoun: the one who / whoever.' },
      { question: 'Which of these is NOT a relative pronoun?', options: ['perché', 'che', 'cui', 'il quale'], answer: 'perché', explanation: 'perché (because) is a conjunction, not a relative pronoun.' },
      { question: 'A pronoun that can follow a preposition (a cui, di cui, in cui) is:', options: ['cui', 'che', 'li', 'lo'], answer: 'cui', explanation: 'cui works after prepositions; che cannot follow one.' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match the Pronoun to Its Job',
    instruction: 'Connect each pronoun with its role in the sentence.',
    pairs: [
      { left: 'che', right: 'subject or direct object (invariable)' },
      { left: 'cui', right: 'after prepositions (of which, in which…)' },
      { left: 'il quale', right: 'agreeing and formal ("the which")' },
      { left: 'chi', right: 'the one who (no antecedent)' },
      { left: 'la quale', right: 'the feminine singular form' },
      { left: 'i quali', right: 'the masculine plural form' },
    ],
    explanation: 'Keep the picture simple: che = subject/object, cui = after a preposition, il quale = agreeing and formal, chi = no antecedent ("the one who").',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Which Job in the Sentence?',
    instruction: 'Say what the relative pronoun does in each sentence.',
    questions: [
      { question: 'In "Il film che vediamo", "che" is the:', options: ['direct object', 'subject', 'verb', 'preposition'], answer: 'direct object', explanation: 'vediamo CHI? → il film (che) is the direct object.' },
      { question: 'In "La donna che parla", "che" is the:', options: ['subject', 'direct object', 'possessive', 'adverb'], answer: 'subject', explanation: 'parla CHI? → la donna (che) is the subject.' },
      { question: 'In "La città in cui vivo", "in cui" means:', options: ['in which', 'of which', 'with which', 'whose'], answer: 'in which', explanation: 'vivere IN a city → in cui = in which.' },
      { question: 'In "Le amiche con cui esco", "con cui" means:', options: ['with whom', 'to whom', 'from whom', 'of whom'], answer: 'with whom', explanation: 'uscire CON → con cui.' },
      { question: 'After a preposition, you CANNOT use:', options: ['che', 'cui', 'il quale', 'la quale'], answer: 'che', explanation: 'che never follows a preposition; use cui or il quale instead.' },
      { question: 'In "Grazie, chi mi ha aiutato", "chi" means:', options: ['the one who', 'the thing which', 'the reason why', 'nothing'], answer: 'the one who', explanation: '"thanks to the one who helped me".' },
    ],
  },
  {
    id: 4,
    type: 'multiple',
    level: 'Level 2 — Che as Subject & Object',
    title: 'Che as Subject',
    instruction: 'Choose "che" when it replaces the noun that acts.',
    questions: [
      { question: 'Il ragazzo ___ parla è mio cugino.', options: ['che', 'cui', 'in cui', 'di cui'], answer: 'che', explanation: 'che is the subject: il ragazzo parla.' },
      { question: 'La pizza ___ è sul tavolo è calda.', options: ['che', 'con cui', 'di cui', 'a cui'], answer: 'che', explanation: 'che is the subject: la pizza è sul tavolo.' },
      { question: 'I bambini ___ giocano sono felici.', options: ['che', 'cui', 'in cui', 'per cui'], answer: 'che', explanation: 'subject: i bambini giocano.' },
      { question: 'Il treno ___ parte alle otto è in ritardo.', options: ['che', 'in cui', 'di cui', 'con cui'], answer: 'che', explanation: 'subject: il treno parte.' },
      { question: 'La donna ___ abita qui è simpatica.', options: ['che', 'cui', 'il quale', 'le quali'], answer: 'che', explanation: 'subject: la donna abita qui.' },
      { question: 'Lo studente ___ ha vinto è italiano.', options: ['che', 'di cui', 'a cui', 'da cui'], answer: 'che', explanation: 'subject: lo studente ha vinto.' },
    ],
  },
  {
    id: 5,
    type: 'fillblank',
    level: 'Level 2 — Che as Subject & Object',
    title: 'Che as Direct Object',
    instruction: 'Choose "che" when it replaces the noun that receives the action.',
    questions: [
      { sentence: 'Il libro ___ leggo è bello.', options: ['che', 'cui', 'in cui', 'quale'], answer: 'che', explanation: 'object: leggo il libro (che).' },
      { sentence: 'La pizza ___ mangiamo è ottima.', options: ['che', 'di cui', 'a cui', 'con cui'], answer: 'che', explanation: 'object: mangiamo la pizza (che).' },
      { sentence: 'I film ___ vediamo sono nuovi.', options: ['che', 'per cui', 'da cui', 'cui si'], answer: 'che', explanation: 'object: vediamo i film (che).' },
      { sentence: 'La canzone ___ ascolto mi piace.', options: ['che', 'il cui', 'la cui', 'chi'], answer: 'che', explanation: 'object: ascolto la canzone (che).' },
      { sentence: 'Il problema ___ studio era difficile.', options: ['che', 'in cui', 'a cui', 'con cui'], answer: 'che', explanation: 'object: studio il problema (che).' },
      { sentence: 'Le lettere ___ scrivo sono lunghe.', options: ['che', 'di cui', 'cui a', 'il quale che'], answer: 'che', explanation: 'object: scrivo le lettere (che).' },
    ],
  },
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 2 — Che as Subject & Object',
    title: 'Object or Preposition?',
    instruction: 'If the verb needs no preposition, choose che. If it needs one, choose the preposition + cui.',
    questions: [
      { sentence: 'Il film ___ guardo è interessante.', options: ['che', 'di cui', 'in cui', 'con cui'], answer: 'che', explanation: 'guardare needs no preposition → che (object).' },
      { sentence: 'Il film ___ tutti parlano.', options: ['di cui', 'che', 'in cui', 'a cui'], answer: 'di cui', explanation: 'parlare DI → di cui.' },
      { sentence: 'La casa ___ abito è grande.', options: ['in cui', 'che', 'di cui', 'con cui'], answer: 'in cui', explanation: 'abitare IN → in cui.' },
      { sentence: 'La musica ___ ascolto è jazz.', options: ['che', 'di cui', 'in cui', 'per cui'], answer: 'che', explanation: 'ascoltare needs no preposition → che (object).' },
      { sentence: 'Il paese ___ vengo è piccolo.', options: ['da cui', 'che', 'in cui', 'con cui'], answer: 'da cui', explanation: 'venire DA → da cui.' },
      { sentence: 'L\'azienda ___ lavoro è grande.', options: ['per cui', 'che', 'in cui', 'a cui'], answer: 'per cui', explanation: 'lavorare PER → per cui.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 3 — Il Quale (agreement)',
    title: 'Agreeing with il quale',
    instruction: 'Fill in the agreement: quale (singular) or quali (plural).',
    questions: [
      { sentence: 'L\'amico con il ___ parlo è Marco.', options: ['quale', 'quali', 'cui', 'che'], answer: 'quale', explanation: 'amico (m sing) → il quale.' },
      { sentence: 'Le città dalle ___ vengo sono belle.', options: ['quali', 'quale', 'che', 'cui'], answer: 'quali', explanation: 'città (plural) → le quali.' },
      { sentence: 'Le ragazze con le ___ esco.', options: ['quali', 'quale', 'che', 'cui'], answer: 'quali', explanation: 'ragazze (f plural) → le quali.' },
      { sentence: 'Il discorso per il ___ sono qui.', options: ['quale', 'quali', 'che', 'cui'], answer: 'quale', explanation: 'discorso (m sing) → il quale.' },
      { sentence: 'Il libro del ___ parliamo.', options: ['quale', 'quali', 'che', 'cui'], answer: 'quale', explanation: 'libro (m sing) → del quale.' },
      { sentence: 'I libri dei ___ ti ho parlato.', options: ['quali', 'quale', 'chi', 'che'], answer: 'quali', explanation: 'libri (m plural) → dei quali.' },
    ],
  },
  {
    id: 8,
    type: 'multiple',
    level: 'Level 3 — Il Quale (agreement)',
    title: 'Che or Il Quale?',
    instruction: 'Use che when it is simple and natural; use il quale for formality or clarity.',
    questions: [
      { question: 'Il film ___ vedo stasera.', options: ['che', 'la quale', 'i quali', 'le quali'], answer: 'che', explanation: 'simple direct object → most natural with che.' },
      { question: 'Il film parla di Roma; ___ mi è piaciuto molto.', options: ['il quale', 'la quale', 'i quali', 'le quali'], answer: 'il quale', explanation: 'film (m sing) → il quale, to distinguish from other clauses.' },
      { question: 'La ragazza ___ viene da Milano è elegante.', options: ['che', 'il quale', 'i quali', 'le quali'], answer: 'che', explanation: 'as a plain subject, che is the most natural choice.' },
      { question: 'I turisti ___ hanno visitato il museo erano tanti.', options: ['che', 'il quale', 'la quale', 'le quali'], answer: 'che', explanation: 'subject → che remains the simplest option.' },
      { question: 'The formal equivalent of "La città che vediamo" is:', options: ['La città la quale vediamo', 'La città le quali vediamo', 'La città i quali vediamo', 'La città chi vediamo'], answer: 'La città la quale vediamo', explanation: 'città (f sing) → la quale in formal style.' },
      { question: 'il quale / la quale / i quali / le quali agree with the noun like:', options: ['an adjective', 'a verb', 'a preposition', 'an adverb'], answer: 'an adjective', explanation: 'They change gender and number to match the noun.' },
    ],
  },
  {
    id: 9,
    type: 'fillblank',
    level: 'Level 4 — Cui with Prepositions',
    title: 'Cui Behind the Right Preposition',
    instruction: 'Match the verb with its preposition: a, con, in, da, per.',
    questions: [
      { sentence: 'La ragazza ___ ho scritto è mia sorella.', options: ['a cui', 'con cui', 'in cui', 'che'], answer: 'a cui', explanation: 'scrivere A qualcuno → a cui.' },
      { sentence: 'Le amiche ___ esco il sabato.', options: ['con cui', 'a cui', 'di cui', 'che'], answer: 'con cui', explanation: 'uscire CON → con cui.' },
      { sentence: 'La casa ___ abito è vecchia.', options: ['in cui', 'a cui', 'con cui', 'che'], answer: 'in cui', explanation: 'abitare IN → in cui.' },
      { sentence: 'Il paese ___ vengo è in Sicilia.', options: ['da cui', 'a cui', 'in cui', 'che'], answer: 'da cui', explanation: 'venire DA → da cui.' },
      { sentence: 'L\'azienda ___ lavoro è a Milano.', options: ['per cui', 'a cui', 'in cui', 'che'], answer: 'per cui', explanation: 'lavorare PER → per cui.' },
      { sentence: 'La persona ___ parlo è paziente.', options: ['a cui', 'con cui', 'in cui', 'che'], answer: 'a cui', explanation: 'parlare A qualcuno → a cui.' },
    ],
  },
  {
    id: 10,
    type: 'multiple',
    level: 'Level 4 — Cui with Prepositions',
    title: 'Cui or Che?',
    instruction: 'The preposition decides: no preposition → che; a preposition → cui.',
    questions: [
      { question: 'Il libro ___ leggo.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'leggere takes no preposition → che.' },
      { question: 'Il libro ___ parlo.', options: ['di cui', 'che', 'in cui', 'con cui'], answer: 'di cui', explanation: 'parlare DI → di cui.' },
      { question: 'Questa è la penna ___ ti ho dato.', options: ['che', 'di cui', 'in cui', 'per cui'], answer: 'che', explanation: 'dare is transitive → direct object che.' },
      { question: 'Ecco la macchina ___ vado al lavoro.', options: ['con cui', 'che', 'di cui', 'in cui'], answer: 'con cui', explanation: 'andare CON la macchina → con cui.' },
      { question: 'La scuola ___ studio è in centro.', options: ['in cui', 'che', 'di cui', 'a cui'], answer: 'in cui', explanation: 'studiare in a school → in cui.' },
      { question: 'Il progetto ___ mi occuperò riguarda l\'energia.', options: ['di cui', 'che', 'in cui', 'con cui'], answer: 'di cui', explanation: 'occuparsi DI → di cui.' },
    ],
  },
  {
    id: 11,
    type: 'wordorder',
    level: 'Level 4 — Cui with Prepositions',
    title: 'Assemble the Relative Clause',
    instruction: 'Put the words in order to build a correct relative clause.',
    questions: [
      { words: ['il', 'ragazzo', 'che', 'parla'], answer: 'il ragazzo che parla', explanation: 'subject: il ragazzo che parla.' },
      { words: ['la', 'casa', 'in', 'cui', 'abito'], answer: 'la casa in cui abito', explanation: 'abitare in → la casa in cui abito.' },
      { words: ['la', 'ragazza', 'a', 'cui', 'ho', 'scritto'], answer: 'la ragazza a cui ho scritto', explanation: 'scrivere a → a cui.' },
      { words: ['il', 'libro', 'di', 'cui', 'parliamo'], answer: 'il libro di cui parliamo', explanation: 'parlare di → di cui.' },
      { words: ['gli', 'amici', 'con', 'cui', 'esco'], answer: 'gli amici con cui esco', explanation: 'uscire con → con cui.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 5 — Il Cui (whose)',
    title: 'Il cui, la cui, i cui, le cui',
    instruction: 'The possessive changes with the NOUN that follows it.',
    questions: [
      { sentence: 'Il signore ___ figlia è mia amica.', options: ['la cui', 'il cui', 'i cui', 'le cui'], answer: 'la cui', explanation: 'figlia (f sing) → la cui figlia.' },
      { sentence: 'La donna ___ marito lavora qui.', options: ['il cui', 'la cui', 'i cui', 'le cui'], answer: 'il cui', explanation: 'marito (m sing) → il cui marito.' },
      { sentence: 'Il professore ___ lezioni sono difficili.', options: ['le cui', 'il cui', 'la cui', 'i cui'], answer: 'le cui', explanation: 'lezioni (f plural) → le cui lezioni.' },
      { sentence: 'Gli studenti ___ libri sono pesanti.', options: ['i cui', 'il cui', 'la cui', 'le cui'], answer: 'i cui', explanation: 'libri (m plural) → i cui libri.' },
      { sentence: 'La città ___ nome è antichissimo.', options: ['il cui', 'la cui', 'i cui', 'le cui'], answer: 'il cui', explanation: 'nome (m sing) → il cui nome.' },
      { sentence: 'Le signore ___ borse sono belle.', options: ['le cui', 'il cui', 'la cui', 'i cui'], answer: 'le cui', explanation: 'borse (f plural) → le cui borse.' },
    ],
  },
  {
    id: 13,
    type: 'multiple',
    level: 'Level 5 — Il Cui (whose)',
    title: 'Whose...?',
    instruction: 'Practice the possessive relative pronoun in context.',
    questions: [
      { question: '"Il cui" in "La ragazza il cui padre è medico" corresponds to:', options: ['whose', 'which', 'whom', 'when'], answer: 'whose', explanation: 'il cui = di cui il/la = whose.' },
      { question: 'Correct agreement: "Il bambino ___ giocattoli sono rotti."', options: ['i cui', 'il cui', 'la cui', 'le cui'], answer: 'i cui', explanation: 'giocattoli (m plural) → i cui.' },
      { question: 'Correct: "La donna ___ nome è Anna."', options: ['il cui', 'la cui', 'i cui', 'le cui'], answer: 'il cui', explanation: 'nome (m sing) → il cui nome.' },
      { question: 'il cui / la cui agree with:', options: ['the noun that comes after', 'the possessor', 'the verb', 'the adjective'], answer: 'the noun that comes after', explanation: 'it agrees with the possessed noun that follows.' },
      { question: 'Correct: "Il ragazzo ___ padre è medico."', options: ['il cui', 'la cui', 'i cui', 'le cui'], answer: 'il cui', explanation: 'padre (m sing) → il cui.' },
      { question: 'Correct: "La signora ___ casa è in corso."', options: ['la cui', 'il cui', 'i cui', 'le cui'], answer: 'la cui', explanation: 'casa (f sing) → la cui.' },
    ],
  },
  {
    id: 14,
    type: 'multiple',
    level: 'Level 6 — Chi (the one who)',
    title: 'Chi — The One Who',
    instruction: 'Use chi when there is no previous noun to refer to.',
    questions: [
      { question: 'Chi (unlike che and cui) is used:', options: ['without a previous noun (free relative)', 'only after prepositions', 'only in questions', 'never in formal Italian'], answer: 'without a previous noun (free relative)', explanation: 'chi needs no antecedent.' },
      { question: '"___ non lavora, non mangia."', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'anyone who does not work, does not eat.' },
      { question: '"___ cerca, trova."', options: ['Chi', 'Che', 'Cui', 'Il quale'], answer: 'Chi', explanation: 'whoever looks, finds.' },
      { question: '"Non so ___ sia."', options: ['chi', 'che', 'cui', 'quale'], answer: 'chi', explanation: 'chi in an indirect question = who.' },
      { question: '"Grazie a ___ ha aiutato!"', options: ['chi', 'che', 'cui', 'quale'], answer: 'chi', explanation: 'thank the one who helped.' },
      { question: 'Chi is grammatically:', options: ['singular masculine', 'always plural', 'feminine plural', 'a verb'], answer: 'singular masculine', explanation: 'chi always takes a third-person singular verb.' },
    ],
  },
  {
    id: 15,
    type: 'fillblank',
    level: 'Level 6 — Chi (the one who)',
    title: 'Chi or Che?',
    instruction: 'No antecedent → chi. With an antecedent → che (or cui).',
    questions: [
      { sentence: '___ studia, passa l\'esame.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'no antecedent → chi.' },
      { sentence: 'La ragazza ___ studia è Anna.', options: ['che', 'chi', 'cui', 'quale'], answer: 'che', explanation: 'antecedent "la ragazza" → che.' },
      { sentence: 'Non ricordo ___ mi ha scritto.', options: ['chi', 'che', 'cui', 'quale'], answer: 'chi', explanation: 'indirect question, free relative → chi.' },
      { sentence: 'Il cane ___ abbaia è mio.', options: ['che', 'chi', 'cui', 'quale'], answer: 'che', explanation: 'antecedent "il cane" → che (subject).' },
      { sentence: '___ vuole, può venire.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'anyone who wants may come → chi.' },
      { sentence: 'La persona ___ vuole venire è libera.', options: ['che', 'chi', 'cui', 'quale'], answer: 'che', explanation: 'antecedent "la persona" → che.' },
    ],
  },
  {
    id: 16,
    type: 'multiple',
    level: 'Level 7 — Choosing the Right Pronoun',
    title: 'Choose the Pronoun',
    instruction: 'Decide by looking at the antecedent and the preposition.',
    questions: [
      { question: 'Il piatto ___ ho cucinato.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'cucinare is transitive → direct object che.' },
      { question: 'Il piatto ___ mi hai parlato.', options: ['di cui', 'che', 'in cui', 'con cui'], answer: 'di cui', explanation: 'parlare DI → di cui.' },
      { question: 'La città ___ vivo.', options: ['in cui', 'che', 'di cui', 'a cui'], answer: 'in cui', explanation: 'vivere in → in cui.' },
      { question: '___ canta bene è invitato.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'free relative with no antecedent → chi.' },
      { question: 'Le chiavi ___ cercavo.', options: ['che', 'di cui', 'in cui', 'con cui'], answer: 'che', explanation: 'cercare is transitive → che.' },
      { question: 'L\'agenzia ___ mi ha trovato un lavoro.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'subject of "ha trovato" → che.' },
    ],
  },
  {
    id: 17,
    type: 'fillblank',
    level: 'Level 7 — Choosing the Right Pronoun',
    title: 'Everything at Once',
    instruction: 'Mix of che, cui, il cui — read the verb and its preposition.',
    questions: [
      { sentence: 'Il computer ___ uso è nuovo.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'usare is transitive → che.' },
      { sentence: 'La musica ___ ascolto è jazz.', options: ['che', 'cui', 'in cui', 'di cui'], answer: 'che', explanation: 'ascoltare is transitive → che.' },
      { sentence: 'Il paese ___ andiamo in vacanza è bello.', options: ['in cui', 'che', 'di cui', 'con cui'], answer: 'in cui', explanation: 'we go to a country → in cui.' },
      { sentence: 'La collega ___ ho parlato del progetto.', options: ['a cui', 'che', 'in cui', 'con cui'], answer: 'a cui', explanation: 'parlare A qualcuno → a cui.' },
      { sentence: 'La collega ___ assistente è in ferie.', options: ['la cui', 'il cui', 'le cui', 'i cui'], answer: 'la cui', explanation: 'assistente (f, her assistant) → la cui.' },
      { sentence: 'Il cliente ___ accompagno all\'aeroporto.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'accompagnare is transitive → che.' },
    ],
  },
  {
    id: 18,
    type: 'matching',
    level: 'Level 7 — Choosing the Right Pronoun',
    title: 'Match & Practice',
    instruction: 'Link each relative pronoun to its meaning.',
    pairs: [
      { left: 'che', right: 'subject or direct object' },
      { left: 'in cui', right: 'in which' },
      { left: 'di cui', right: 'about which / of which' },
      { left: 'a cui', right: 'to whom' },
      { left: 'con cui', right: 'with whom' },
      { left: 'il cui', right: 'whose' },
    ],
    explanation: 'che has no preposition; every cui form is that preposition + cui; il cui is the possessive. Knowing your verb + preposition decides the rest.',
  },
  {
    id: 19,
    type: 'translation',
    level: 'Level 7 — Choosing the Right Pronoun',
    title: 'Relative Clauses to English',
    instruction: 'Choose the correct English translation of each relative clause.',
    direction: 'it-en',
    questions: [
      { sentence: 'Il libro che leggo è interessante.', options: ['The book that I am reading is interesting.', 'The book on which I am reading.', 'I am reading an interesting book.', 'The interesting book reads me.'], answer: 'The book that I am reading is interesting.', explanation: 'che (object) = that / which.' },
      { sentence: 'La città in cui vivo è piccola.', options: ['The city in which I live is small.', 'The small city lives in me.', 'The city where I die is small.', 'The city is my home.'], answer: 'The city in which I live is small.', explanation: 'in cui = in which.' },
      { sentence: 'La donna a cui ho scritto è mia zia.', options: ['The woman to whom I wrote is my aunt.', 'The woman about whom I read is my aunt.', 'The woman that writes is my aunt.', 'My aunt wrote to the woman.'], answer: 'The woman to whom I wrote is my aunt.', explanation: 'a cui = to whom.' },
      { sentence: 'Chi studia, passa.', options: ['Whoever studies, passes.', 'The person who passed studies.', 'Who passes, studies.', 'No one studies.'], answer: 'Whoever studies, passes.', explanation: 'chi = whoever / the one who.' },
      { sentence: 'La ragazza la cui sorella canta è famosa.', options: ['The girl whose sister sings is famous.', 'The girl who sings is my sister.', 'The famous sister sings.', 'The girl with the singer sister is not famous.'], answer: 'The girl whose sister sings is famous.', explanation: 'la cui = whose (possessive relative).' },
    ],
  },
  {
    id: 20,
    type: 'multiple',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Everyday Relative Clauses',
    instruction: 'Recognise the natural relative pronouns of daily Italian.',
    questions: [
      { question: 'Ecco il motivo ___ ti ho chiamato.', options: ['per cui', 'che', 'in cui', 'il quale'], answer: 'per cui', explanation: 'per cui = for which / that is why.' },
      { question: 'Il treno ___ parte alle nove è in ritardo.', options: ['che', 'di cui', 'a cui', 'con cui'], answer: 'che', explanation: 'subject → che.' },
      { question: 'Hai visto l\'articolo ___ parlo?', options: ['di cui', 'che', 'in cui', 'a cui'], answer: 'di cui', explanation: 'parlare DI → di cui.' },
      { question: 'L\'amico ___ vado tutte le domeniche.', options: ['da cui', 'che', 'di cui', 'in cui'], answer: 'da cui', explanation: 'andare DA qualcuno (at his place) → da cui.' },
      { question: '___ vuole la pace, prepari la guerra.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'classic saying: whoever wants peace prepares for war.' },
      { question: 'La bicicletta ___ vado al lavoro è nuova.', options: ['con cui', 'che', 'di cui', 'in cui'], answer: 'con cui', explanation: 'andare CON la bici → con cui.' },
    ],
  },
  {
    id: 21,
    type: 'fillblank',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Complex Sentences',
    instruction: 'Complete these longer everyday sentences with the right pronoun.',
    questions: [
      { sentence: 'Il film ___ hai visto era brutto.', options: ['che', 'di cui', 'in cui', 'da cui'], answer: 'che', explanation: 'direct object → che.' },
      { sentence: 'Il ristorante ___ la cena è deliziosa.', options: ['in cui', 'che', 'di cui', 'con cui'], answer: 'in cui', explanation: 'locative: in the restaurant → in cui.' },
      { sentence: 'I ragazzi ___ gioco a calcio.', options: ['con cui', 'che', 'di cui', 'in cui'], answer: 'con cui', explanation: 'giocare CON → con cui.' },
      { sentence: 'La notizia ___ ha sorpreso tutti.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'subject of "ha sorpreso" → che.' },
      { sentence: 'L\'allenatore ___ squadra gioca bene.', options: ['la cui', 'che', 'di cui', 'in cui'], answer: 'la cui', explanation: 'squadra (f sing) → la cui squadra.' },
      { sentence: 'L\'estate ___ ci siamo conosciuti era calda.', options: ['in cui', 'che', 'di cui', 'a cui'], answer: 'in cui', explanation: 'temporal/locative: in which (estate) → in cui.' },
    ],
  },
  {
    id: 22,
    type: 'wordorder',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Build the Sentence',
    instruction: 'Reorder the words to make natural sentences.',
    questions: [
      { words: ['il', 'caffè', 'che', 'bevi'], answer: 'il caffè che bevi', explanation: 'object: the coffee you drink.' },
      { words: ['la', 'scuola', 'in', 'cui', 'studio'], answer: 'la scuola in cui studio', explanation: 'studiare in → in cui.' },
      { words: ['la', 'ragazza', 'che', 'ho', 'incontrato'], answer: 'la ragazza che ho incontrato', explanation: 'object: the girl I met.' },
      { words: ['il', 'professore', 'di', 'cui', 'parliamo'], answer: 'il professore di cui parliamo', explanation: 'parlare di → di cui.' },
      { words: ['chi', 'cerca', 'trova'], answer: 'chi cerca trova', explanation: 'free relative: whoever looks, finds.' },
    ],
  },
  {
    id: 23,
    type: 'multiple',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Idiomatic & Advanced',
    instruction: 'Master the frozen expressions and proverbs with relative pronouns.',
    questions: [
      { question: '"quello che" means:', options: ['what / the thing that', 'who', 'whose', 'why'], answer: 'what / the thing that', explanation: '"Tutto quello che so" = all that I know.' },
      { question: 'Giulia è la donna a ___ ho fatto una domanda.', options: ['cui', 'che', 'chi', 'quale'], answer: 'cui', explanation: 'fare una domanda A qualcuno → a cui.' },
      { question: 'È il motivo ___ (per cui) è partito.', options: ['per cui', 'che', 'di cui', 'chi'], answer: 'per cui', explanation: 'the reason why → per cui.' },
      { question: 'Prendi quello ___ vuoi!', options: ['che', 'cui', 'chi', 'quale'], answer: 'che', explanation: '"quello che" = what (you want).' },
      { question: '___ ben comincia è a metà dell\'opera.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'well begun is half done → chi.' },
      { question: 'Gli amici ___ vado in vacanza sono studenti.', options: ['con cui', 'che', 'di cui', 'in cui'], answer: 'con cui', explanation: 'go on holiday WITH friends → con cui.' },
    ],
  },
  {
    id: 24,
    type: 'fillblank',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Grand Review',
    instruction: 'A little of everything: che, cui, il cui, chi.',
    questions: [
      { sentence: 'Il ristorante ___ ceno spesso è economico.', options: ['in cui', 'che', 'di cui', 'a cui'], answer: 'in cui', explanation: 'eating in a restaurant → in cui.' },
      { sentence: 'La macchina ___ guido è di mio padre.', options: ['che', 'di cui', 'in cui', 'con cui'], answer: 'che', explanation: 'guidare is transitive → che.' },
      { sentence: 'Le scarpe ___ ho comprato sono nuove.', options: ['che', 'di cui', 'in cui', 'per cui'], answer: 'che', explanation: 'comperare is transitive → che.' },
      { sentence: 'Il collega con ___ lavoravo prima è simpatico.', options: ['cui', 'che', 'chi', 'quale'], answer: 'cui', explanation: 'lavorare CON → con cui.' },
      { sentence: 'La città ___ nome deriva dal latino.', options: ['il cui', 'la cui', 'i cui', 'le cui'], answer: 'il cui', explanation: 'nome (m sing) → il cui.' },
      { sentence: '___ cerca trova.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'whoever looks finds → chi.' },
    ],
  },
  {
    id: 25,
    type: 'multiple',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Final Check',
    instruction: 'Confirm you can pick the right relative pronoun automatically.',
    questions: [
      { question: 'Il vestito ___ indosso è nuovo.', options: ['che', 'di cui', 'in cui', 'a cui'], answer: 'che', explanation: 'indossare is transitive → che.' },
      { question: 'L\'albero ___ frutti sono dolci.', options: ['i cui', 'il cui', 'la cui', 'le cui'], answer: 'i cui', explanation: 'frutti (m plural) → i cui frutti.' },
      { question: 'La donna ___ hai visto ieri.', options: ['che', 'cui', 'il cui', 'chi'], answer: 'che', explanation: 'direct object → che.' },
      { question: 'Il ristorante ___ ci ha consigliato Marco.', options: ['che', 'di cui', 'in cui', 'con cui'], answer: 'che', explanation: 'consigliare is transitive → che.' },
      { question: 'Fammi vedere l\'articolo ___ ti parlavo.', options: ['di cui', 'che', 'in cui', 'con cui'], answer: 'di cui', explanation: 'parlare DI → di cui.' },
      { question: '___ tace acconsente.', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi', explanation: 'whoever is silent agrees → chi.' },
    ],
  },
  {
    id: 26,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Looking for a House',
    storyTitle: 'La casa dei sogni',
    story: 'Agente: Questa è la casa che cercavi, Anna?\n\nAnna: Sì, è bellissima! È la casa in cui vorrei abitare.\n\nAgente: Il quartiere in cui si trova è tranquillo e il giardino, la cui vista è stupenda, è grande.\n\nAnna: Qual è il prezzo a cui è in vendita?\n\nAgente: La casa che ti interessa costa quattrocentomila euro.\n\nAnna: Chi può aiutarmi con i documenti?\n\nAgente: Il mio collega, del quale ti ho parlato ieri, si occuperà di tutto.',
    vocab: [
      { word: 'la casa in cui vorrei abitare', meaning: 'the house in which I would like to live' },
      { word: 'la cui vista', meaning: 'whose view (vista = f sing)' },
      { word: 'a cui è in vendita', meaning: 'at which it is for sale' },
      { word: 'del quale', meaning: 'about whom (formal)' },
      { word: 'che cercavi', meaning: 'that you were looking for (direct object)' },
      { word: 'chi può', meaning: 'who can / who is able to' },
    ],
    translation: 'Agent: Is this the house you were looking for, Anna?\n\nAnna: Yes, it is beautiful! It is the house I would like to live in.\n\nAgent: The neighbourhood where it is located is quiet and the garden, whose view is stupendous, is big.\n\nAnna: What is the price it is for sale at?\n\nAgent: The house that interests you costs four hundred thousand euros.\n\nAnna: Who can help me with the documents?\n\nAgent: My colleague, whom I told you about yesterday, will take care of everything.',
    questions: [
      { question: 'Dove vorrebbe abitare Anna?', options: ['Nella casa che l\'agente le mostra', 'In campagna', 'In un hotel', 'All\'estero'], answer: 'Nella casa che l\'agente le mostra', explanation: '"È la casa in cui vorrei abitare" — "casa" è l\'antecedente.' },
      { question: '"In cui" in "la casa in cui vorrei abitare" means:', options: ['in which', 'of which', 'with which', 'whose'], answer: 'in which', explanation: 'vorrei abitare in that house → in cui.' },
      { question: '"la cui vista è stupenda" — "la cui" corresponds to:', options: ['whose view', 'which vision', 'the who', 'for what'], answer: 'whose view', explanation: 'la cui + noun (vista) = possessive "whose".' },
      { question: 'Quanto costa la casa?', options: ['Quattrocentomila euro', 'Quarantamila euro', 'Quattromila euro', 'Un milione di euro'], answer: 'Quattrocentomila euro', explanation: '"costa quattrocentomila euro".' },
      { question: 'Chi aiuterà Anna con i documenti?', options: ['Il collega (del quale l\'agente ha parlato)', 'L\'agente stessa', 'La banca', 'Nessuno'], answer: 'Il collega (del quale l\'agente ha parlato)', explanation: 'Il mio collega, del quale ti ho parlato ieri, si occuperà di tutto.' },
      { question: 'Write one sentence using "che" or "cui" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Questa è la casa in cui abito. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'The New Colleague',
    storyTitle: 'Il collega nuovo',
    story: 'Marco: Conosci il collega che ho assunto?\n\nLucia: Certo! È la persona di cui tutti parlano in ufficio.\n\nMarco: Il progetto per il quale è stato scelto è molto ambizioso.\n\nLucia: Mi piace il modo in cui lavora: è preciso e veloce.\n\nMarco: Anche il capo, la cui fiducia è difficile da guadagnare, lo stima.\n\nLucia: Bene. Chi lavora bene merita di essere conosciuto.\n\nMarco: Sì, e con lui posso organizzare ogni cosa.',
    vocab: [
      { word: 'che ho assunto', meaning: 'whom I hired (direct object)' },
      { word: 'di cui tutti parlano', meaning: 'about whom everybody talks' },
      { word: 'per il quale è stato scelto', meaning: 'for which he was chosen' },
      { word: 'il modo in cui lavora', meaning: 'the way in which he works' },
      { word: 'la cui fiducia', meaning: 'whose trust' },
      { word: 'chi lavora bene', meaning: 'whoever works well' },
    ],
    translation: 'Marco: Do you know the colleague I hired?\n\nLucia: Of course! He is the person everybody talks about in the office.\n\nMarco: The project he was chosen for is very ambitious.\n\nLucia: I like the way he works: precise and fast.\n\nMarco: Even the boss, whose trust is hard to earn, respects him.\n\nLucia: Good. Whoever works well deserves to be known.\n\nMarco: Yes, and I can organise everything with him.',
    questions: [
      { question: 'Che cosa ha fatto Marco?', options: ['Ha assunto un nuovo collega', 'Ha licenziato qualcuno', 'Ha cambiato ufficio', 'Ha comprato un progetto'], answer: 'Ha assunto un nuovo collega', explanation: '"il collega che ho assunto".' },
      { question: '"di cui" in "la persona di cui tutti parlano" means:', options: ['about whom / of whom', 'in which', 'whose', 'for which'], answer: 'about whom / of whom', explanation: 'parlare DI qualcuno → di cui.' },
      { question: '"Il progetto per il quale è stato scelto" — "il quale" refers to:', options: ['il progetto', 'il collega', 'la fiducia', 'l\'ufficio'], answer: 'il progetto', explanation: 'il quale (m sing) refers back to "il progetto".' },
      { question: 'Che cosa piace a Lucia del nuovo collega?', options: ['Il modo in cui lavora', 'La sua macchina', 'Il suo stipendio', 'Il progetto finito'], answer: 'Il modo in cui lavora', explanation: '"Mi piace il modo in cui lavora: preciso e veloce."' },
      { question: '"Chi lavora bene merita di essere conosciuto." — "chi" here means:', options: ['whoever works well', 'the work', 'for those who work less', 'which work'], answer: 'whoever works well', explanation: 'free relative pronoun without an antecedent.' },
      { question: 'Write one sentence using "di cui" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: È la persona di cui ti ho parlato. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 28,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'The Perfect Gift',
    storyTitle: 'Il regalo perfetto',
    story: 'Giulia: Sto cercando un regalo che sorprenda mio padre.\n\nCommesso: Che tipo di oggetto ti piacerebbe? Un orologio, che è sempre apprezzato?\n\nGiulia: Ho già pensato all\'orologio, ma il prezzo è troppo alto per me.\n\nCommesso: Ecco questa penna, la cui qualità è ottima. È elegante e originale.\n\nGiulia: È bella. Chi può incidere il suo nome?\n\nCommesso: Noi, e lavoriamo anche di sabato. Questo è il motivo per cui tanti clienti ci scelgono.\n\nGiulia: Perfetto, prendo la penna a cui ho pensato più a lungo.',
    vocab: [
      { word: 'che sorprenda', meaning: 'that surprises (che as subject)' },
      { word: 'la cui qualità', meaning: 'whose quality' },
      { word: 'il motivo per cui', meaning: 'the reason why (for which)' },
      { word: 'a cui ho pensato', meaning: 'which I have been thinking about (pensare a)' },
      { word: 'che è sempre apprezzato', meaning: 'that is always appreciated' },
      { word: 'chi può incidere', meaning: 'who can engrave' },
    ],
    translation: 'Giulia: I am looking for a gift that will surprise my father.\n\nShop assistant: What kind of thing would you like? A watch, which is always appreciated?\n\nGiulia: I already thought about the watch, but the price is too high for me.\n\nShop assistant: Here is this pen, whose quality is excellent. It is elegant and original.\n\nGiulia: It is beautiful. Who can engrave his name on it?\n\nShop assistant: We can, and we also work on Saturdays. That is the reason why so many clients choose us.\n\nGiulia: Perfect, I will take the pen I have been thinking about the longest.',
    questions: [
      { question: 'Che regalo cerca Giulia?', options: ['Qualcosa che sorprenda suo padre', 'Un orologio da polso', 'Un portafoglio', 'Un libro'], answer: 'Qualcosa che sorprenda suo padre', explanation: '"un regalo che sorprenda mio padre" — che as subject of sorprenda.' },
      { question: '"la cui qualità" — "la cui" corrisponde a:', options: ['whose quality', 'which quality', 'of the who', 'whom the quality'], answer: 'whose quality', explanation: 'la cui + qualità = di cui la qualità = whose quality.' },
      { question: 'Chi può incidere il nome sulla penna?', options: ['I negozianti (lo staff del negozio)', 'Il padre', 'La banca', 'Nessuno'], answer: 'I negozianti (lo staff del negozio)', explanation: '"Noi, e lavoriamo anche di sabato" — the shop staff.' },
      { question: 'Per quale motivo tanti clienti scelgono il negozio?', options: ['Perché lavorano anche di sabato', 'Perché è economico', 'Perché è lontano', 'Perché è piccolo'], answer: 'Perché lavorano anche di sabato', explanation: '"Questo è il motivo per cui tanti clienti ci scelgono."' },
      { question: '"la penna a cui ho pensato" — "a cui" refers to:', options: ['la penna', 'il padre', 'il negozio', 'il prezzo'], answer: 'la penna', explanation: 'pensare A qualcosa → a cui = the pen Giulia has been thinking about.' },
      { question: 'Write one sentence using "che" or "cui" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Sto cercando un regalo che sorprenda. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Who Seeks, Finds',
    storyTitle: 'Chi cerca trova',
    story: 'Nonno: Chi cerca, trova!\n\nNina: Che vuol dire, nonno?\n\nNonno: Se cerchi bene, troverai la chiave che hai perso. Chi vuole, può.\n\nNina: Il posto in cui l\'ho lasciata non lo ricordo.\n\nNonno: Pensaci: il caffè in cui ci siamo fermati è il tuo preferito.\n\nNina: Ah, il tavolo al quale ci siamo seduti era nell\'angolo!\n\nNonno: Bravo. Vai a cercare, e se non c\'è, chiedi al cameriere con cui abbiamo parlato.\n\nNina: Grazie! Ricorderò: chi cerca, trova!',
    vocab: [
      { word: 'chi cerca, trova', meaning: 'whoever looks, finds' },
      { word: 'la chiave che hai perso', meaning: 'the key that you lost (direct object)' },
      { word: 'in cui l\'ho lasciata', meaning: 'in which I left it' },
      { word: 'al quale ci siamo seduti', meaning: 'at which we sat (sedersi a)' },
      { word: 'con cui abbiamo parlato', meaning: 'with whom we talked' },
      { word: 'chi vuole, può', meaning: 'whoever wants to, can' },
    ],
    translation: 'Grandfather: Who seeks, finds!\n\nNina: What does that mean, grandpa?\n\nGrandfather: If you look carefully, you will find the key you lost. Whoever wants to, can.\n\nNina: I do not remember the place where I left it.\n\nGrandfather: Think: the café where we stopped is your favourite.\n\nNina: Ah, the table at which we sat was in the corner!\n\nGrandfather: Well done. Go and look, and if it is not there, ask the waiter we talked to.\n\nNina: Thank you! I will remember: who seeks, finds!',
    questions: [
      { question: 'Che cosa insegna il nonno a Nina?', options: ['Chi cerca, trova', 'Il caffè è buono', 'I nonni sanno tutto', 'La chiave non esiste'], answer: 'Chi cerca, trova', explanation: '"Chi cerca, trova" = whoever searches, finds.' },
      { question: 'In "la chiave che hai perso", "che" is:', options: ['the direct object', 'the subject', 'a preposition', 'an adjective'], answer: 'the direct object', explanation: 'la chiave is the object that was lost.' },
      { question: '"Il caffè in cui ci siamo fermati" — "in cui" means:', options: ['in which', 'of which', 'with which', 'whose'], answer: 'in which', explanation: 'fermarsi IN a place → in cui.' },
      { question: '"il tavolo al quale ci siamo seduti" — "al quale" refers to:', options: ['il tavolo', 'il caffè', 'la chiave', 'il cameriere'], answer: 'il tavolo', explanation: 'sedersi A a table → al quale (m sing).' },
      { question: '"il cameriere con cui abbiamo parlato" — "con cui" means:', options: ['with whom', 'to whom', 'from whom', 'for whom'], answer: 'with whom', explanation: 'parlare CON qualcuno → con cui.' },
      { question: 'Write one sentence using "chi" (the one who) in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Chi non risica, non rosica. Any correct sentence with chi is accepted.' },
    ],
  },
  {
    id: 30,
    type: 'mastery',
    level: 'Level 10 — Final Proficiency Test',
    title: 'The Relative Pronouns Test',
    instruction: '27 questions — recognise, choose, translate, and produce. You must pass to complete the course.',
    questions: [
      // Recognition
      { question: 'A relative pronoun (che, cui, chi, quale):', options: ['connects two clauses about the same noun', 'replaces a verb', 'adds emphasis', 'is only used in questions'], answer: 'connects two clauses about the same noun' },
      { question: 'The ONLY pronoun that can act as plain subject or direct object (no preposition) is:', options: ['che', 'cui', 'il quale (only)', 'chi only'], answer: 'che' },
      { question: 'Which relative pronoun NEVER follows a preposition?', options: ['che', 'cui', 'il quale', 'la quale'], answer: 'che' },
      { question: 'chi means:', options: ['the one who', 'the thing which', 'the reason why', 'the time when'], answer: 'the one who' },
      // che
      { question: 'Il ragazzo ___ parla è mio fratello.', options: ['che', 'cui', 'in cui', 'di cui'], answer: 'che' },
      { question: 'Il libro ___ leggo è interessante.', options: ['che', 'cui', 'di cui', 'in cui'], answer: 'che' },
      // cui with prepositions
      { question: 'La città ___ vivo è grande.', options: ['in cui', 'che', 'il quale', 'con cui'], answer: 'in cui' },
      { question: 'Il motivo ___ sono qui.', options: ['per cui', 'che', 'in cui', 'il quale'], answer: 'per cui' },
      { question: 'La ragazza ___ ho scritto.', options: ['a cui', 'che', 'in cui', 'per cui'], answer: 'a cui' },
      { question: 'L\'amico ___ esco spesso è Marco.', options: ['con cui', 'che', 'di cui', 'in cui'], answer: 'con cui' },
      // il quale
      { question: 'Le ragazze con le ___ esco.', options: ['quali', 'che', 'quale', 'cui'], answer: 'quali' },
      { question: 'The feminine singular of il quale is:', options: ['la quale', 'le quali', 'il cui', 'chi'], answer: 'la quale' },
      { question: '"il quale" compared with "che" is:', options: ['more formal', 'always wrong', 'only plural', 'never used'], answer: 'more formal' },
      // il cui
      { question: 'La donna ___ nome è Emma.', options: ['il cui', 'la quale', 'di cui', 'che cui'], answer: 'il cui' },
      { question: 'La signora ___ figlia si chiama Anna.', options: ['la cui', 'il cui', 'le cui', 'i cui'], answer: 'la cui' },
      { question: 'il cui / la cui agree with:', options: ['the possessed noun', 'the possessor', 'the verb', 'never'], answer: 'the possessed noun' },
      // chi
      { question: '"___ non lavora non mangia."', options: ['Chi', 'Che', 'Cui', 'Quale'], answer: 'Chi' },
      { question: '"Non so ___ sia." (indirect question)', options: ['chi', 'che', 'cui', 'quale'], answer: 'chi' },
      // choosing & translation
      { question: 'Mi piace la città in cui vivo. =', options: ['I like the city in which I live', 'I live in the city I like', 'The city likes me', 'I live alone'], answer: 'I like the city in which I live' },
      { question: 'Prendi quello ___ vuoi!', options: ['che', 'cui', 'chi', 'quale che'], answer: 'che' },
      { question: '"quello che" means:', options: ['what / the thing that', 'who', 'whose', 'why'], answer: 'what / the thing that' },
      // Reading
      { question: 'READ FIRST: "L\'azienda per cui lavoro è grande. Il capo, con cui ho parlato questa mattina, mi ha detto che il progetto, il quale verrà presentato lunedì, è perfetto. La squadra, i cui sforzi sono notevoli, merita un premio. Chi lavora bene sarà premiato.\n\nDove lavora l\'autore?', options: ['In una grande azienda', 'In una scuola', 'Da casa', 'In un negozio'], answer: 'In una grande azienda' },
      { question: 'READ AGAIN: "Il capo, con cui ho parlato questa mattina" — con chi ha parlato l\'autore?', options: ['Il capo', 'La squadra', 'Un cliente', 'Il custode'], answer: 'Il capo' },
      { question: 'READ AGAIN: "i cui sforzi sono notevoli" — "i cui" corresponds to:', options: ['whose efforts', 'which efforts', 'the efforts for which', 'efforts that'], answer: 'whose efforts' },
      { question: 'READ AGAIN: "Chi lavora bene sarà premiato." — "chi" qui significa:', options: ['Anyone who works well', 'The workers that', 'The work which', 'Those who work badly'], answer: 'Anyone who works well' },
      // Production
      { question: 'Translate into Italian: "The person with whom I work."', type: 'text', answer: 'La persona con cui lavoro.', acceptedAnswers: ['la persona con cui lavoro'] },
      { question: 'Translate into Italian: "The city in which I live."', type: 'text', answer: 'La città in cui vivo.', acceptedAnswers: ['la città in cui vivo'] },
    ],
  },
];

export const pronomiRelativiStories = pronomiRelativiExercises.filter((e) => e.type === 'story');

export const pronomiRelativiFinalTest = pronomiRelativiExercises.find((e) => e.id === 30).questions;

export const pronomiRelativiFinalBands = [
  { min: 90, grade: 'Ottimo!', message: 'You master che, cui, il quale, and chi with true confidence.' },
  { min: 75, grade: 'Molto bene!', message: 'Solid command of relative pronouns — polish the finer choices between cui and il quale.' },
  { min: 60, grade: 'Bene!', message: 'Good grasp of the basics. Review cui with prepositions and the possessive il cui.' },
  { min: 40, grade: 'In progress', message: 'You recognise the forms. Focus on che vs cui and the agreement of il quale / il cui.' },
  { min: 0, grade: 'Keep going', message: 'Revisit the four pronouns: che (invariable), cui (after prepositions), il quale (agreeing), chi (free relative).' },
];