export const preposizioniStages = [
  {
    id: 'concept',
    title: 'What are Prepositions?',
    subtitle: 'Connect words and show relationships of place, time, and purpose',
    sections: [
      {
        heading: 'Part 1 — What are prepositions?',
        explanation: 'A preposition is a small word that connects other words and shows a relationship: where something is, where someone is going or coming from, who something belongs to, when or why something happens, and who someone is with.',
        bullets: [
          { text: 'Vado a Roma.', example: 'I go to Rome — "a" shows the destination.' },
          { text: 'Vengo da Roma.', example: 'I come from Rome — "da" shows the origin.' },
          { text: 'Il libro è di Marco.', example: 'The book is Marco\'s — "di" shows belonging.' },
          { text: 'Vivo in Italia.', example: 'I live in Italy — "in" shows a country / location.' },
          { text: 'Parlo con Maria.', example: 'I talk with Maria — "con" shows company.' },
        ],
        note: 'Prepositions are everywhere in Italian! They tell you where, when, why, and with whom things happen.',
      },
      {
        heading: 'Part 2 — The eight core prepositions',
        explanation: 'Italian has about eight prepositions you will use constantly. These are GENERAL meanings — do not learn just one translation:',
        table: [
          { form: 'di — of / from / about', example: 'il libro di Marco' },
          { form: 'a — to / at', example: 'vado a Roma' },
          { form: 'da — from / by / at someone\'s place', example: 'vengo da Roma' },
          { form: 'in — in / into', example: 'vivo in Italia' },
          { form: 'con — with', example: 'con Maria' },
          { form: 'su — on / about', example: 'sul tavolo' },
          { form: 'per — for / through / toward', example: 'per te' },
          { form: 'tra / fra — between / among', example: 'tra due giorni' },
        ],
        note: 'The same preposition can translate as many different English words. Learn patterns and contexts, not a single word-for-word translation.',
      },
    ],
  },
  {
    id: 'core',
    title: 'The Core Prepositions: Di, A, Da, In',
    subtitle: 'Belonging, destination, origin, and location — the four most useful prepositions',
    sections: [
      {
        heading: 'Part 3 — Di: belonging, origin, and more',
        explanation: 'Di is one of the most common Italian words. It usually expresses possession and origin, and it appears in many everyday patterns.',
        bullets: [
          { text: 'BELONGING — Il libro è di Marco.', example: 'The book is Marco\'s. La macchina è di Anna — the car is Anna\'s.' },
          { text: 'ORIGIN — Sono di Roma.', example: 'I am from Rome. Compare: Sono di Roma (where I\'m from) vs Vengo da Roma (I come from Rome — movement).' },
          { text: 'MATERIAL — Un tavolo di legno.', example: 'A wooden table. Una bottiglia di vetro — a glass bottle.' },
          { text: 'CONTENTS — Un bicchiere di vino.', example: 'A glass of wine. Una tazza di latte — a cup of milk.' },
          { text: 'TOPIC — Parliamo di sport.', example: 'We are talking about sports. Un libro di storia — a history book.' },
          { text: 'AGE — un ragazzo di vent\'anni.', example: 'a twenty-year-old boy. Una donna di trent\'anni — a thirty-year-old woman.' },
        ],
        focus: { sentence: 'Il libro è di Marco.', breakdown: [{ part: 'Il libro', role: 'subject' }, { part: 'è', role: 'verb' }, { part: 'di', role: 'preposition (of)' }, { part: 'Marco', role: 'owner' }], meaning: 'The book is Marco\'s.' },
      },
      {
        heading: 'Part 4 — A: to cities, at places, on clock times',
        explanation: 'A expresses a destination (with cities), being at certain places, and at + a clock time. It also introduces a person you talk or write to.',
        bullets: [
          { text: 'DESTINATION (city) — Vado a Roma.', example: 'I go to Rome. Andiamo a Milano — we are going to Milan.' },
          { text: 'LOCATION — Sono a casa.', example: 'I am at home. Sono a scuola — at school. Sono al lavoro — at work.' },
          { text: 'TIME — Parto alle otto.', example: 'I leave at eight. A mezzogiorno — at noon. A mezzanotte — at midnight.' },
          { text: 'PERSON — Parlo a Marco.', example: 'I talk to Marco. Scrivo a Maria — I write to Maria.' },
        ],
        patterns: ['a casa — at home', 'a scuola — at school', 'a lavoro / al lavoro — at work', 'a piedi — on foot', 'a destra — on the right', 'a sinistra — on the left'],
        note: 'With places, memorize fixed expressions as complete chunks: a casa, a scuola, al lavoro.',
      },
      {
        heading: 'Part 5 — Da: origin, from a person, and "for + time"',
        explanation: 'Da expresses movement from a place or a person, going to a person\'s place, and a duration that continues until now.',
        bullets: [
          { text: 'ORIGIN — Vengo da Roma.', example: 'I come from Rome. Torno da Milano — I return from Milan.' },
          { text: 'A PERSON\'S PLACE — Vado da Marco.', example: 'I am going to Marco\'s place. Sono da Maria — I am at Maria\'s house.' },
          { text: 'SINCE / FOR (until now) — Studio italiano da due anni.', example: 'I have been studying Italian for two years. Vivo qui da tre mesi — I have lived here for three months.' },
          { text: 'BY (agent) — Un libro scritto da Marco.', example: 'A book written by Marco.' },
          { text: 'PURPOSE / ITEM — occhiali da sole.', example: 'sunglasses. Scarpe da tennis — tennis shoes.' },
        ],
        patterns: ['da Roma', 'da Marco', 'da due anni', 'scritto da Marco', 'occhiali da sole'],
      },
      {
        heading: 'Part 6 — In: countries, regions, transport, and locations',
        explanation: 'In is used with countries, regions, vehicles, many places, and also to say how long something takes.',
        bullets: [
          { text: 'COUNTRIES — Vivo in Italia.', example: 'I live in Italy. Andiamo in Francia — we are going to France.' },
          { text: 'REGIONS — Andiamo in Toscana.', example: 'We are going to Tuscany. Vivo in Veneto — I live in Veneto.' },
          { text: 'TRANSPORT — Vado in treno.', example: 'I go by train. In macchina — by car. In autobus — by bus. On foot is a piedi!' },
          { text: 'LOCATION — Sono in ufficio.', example: 'I am in the office. Sono in cucina — in the kitchen. Sono in banca — at the bank.' },
          { text: 'TIME (in + amount) — Arrivo in dieci minuti.', example: 'I arrive in ten minutes. Finisco in due ore — I finish in two hours.' },
        ],
        note: 'Compare: "Arrivo in dieci minuti" (within ten minutes) vs "Arrivo tra dieci minuti" (ten minutes from now). Both are natural — tra is more literally "from now".',
      },
    ],
  },
  {
    id: 'others',
    title: 'Con, Su, Per, Tra/Fra',
    subtitle: 'With, on/about, purpose, and between — the other everyday prepositions',
    sections: [
      {
        heading: 'Part 7 — Con: with',
        explanation: 'Con means "with" — company, tools, or the person you do something with.',
        examples: [
          { italian: 'Vado con Marco.', translation: 'I go with Marco.' },
          { italian: 'Studio con Maria.', translation: 'I study with Maria.' },
          { italian: 'Mangio con i miei amici.', translation: 'I eat with my friends.' },
          { italian: 'Vieni con me?', translation: 'Are you coming with me?' },
        ],
        patterns: ['con me — with me', 'con te — with you', 'con lui — with him', 'con lei — with her', 'con noi — with us', 'con voi — with you (pl.)', 'con loro — with them'],
        note: 'With pronouns, con stays exactly the same: con me, con te, con lui...',
      },
      {
        heading: 'Part 8 — Su: on / about',
        explanation: 'Su means "on" (physical position) or "about" (a topic).',
        bullets: [
          { text: 'POSITION — Il libro è sul tavolo.', example: 'The book is on the table. Il telefono è sulla sedia — the phone is on the chair.' },
          { text: 'TOPIC — Un libro sulla storia italiana.', example: 'A book about Italian history. Un film sulla cucina italiana — a film about Italian food.' },
        ],
        note: 'With the definite article, su combines: su + il = sul, su + la = sulla. You will learn articulated prepositions in Part 15.',
      },
      {
        heading: 'Part 9 — Per: for / through / toward',
        explanation: 'Per expresses purpose, a destination, a duration, or a reason.',
        bullets: [
          { text: 'PURPOSE — Studio per l\'esame.', example: 'I study for the exam. Questo regalo è per Maria — this gift is for Maria.' },
          { text: 'DESTINATION — Parto per Roma.', example: 'I leave for Rome. Un treno per Milano — a train for Milan.' },
          { text: 'DURATION — Ho lavorato per tre giorni.', example: 'I worked for three days. Studio per due ore — I study for two hours.' },
          { text: 'REASON — Lo faccio per te.', example: 'I do it for you. Studio italiano per lavoro — I study Italian for work.' },
        ],
      },
      {
        heading: 'Part 10 — Tra / fra: between, among, and future time',
        explanation: 'Tra and fra have the same meaning — use whichever sounds better in the sentence.',
        bullets: [
          { text: 'BETWEEN — La casa è tra la scuola e il parco.', example: 'The house is between the school and the park.' },
          { text: 'AMONG — Sono tra amici.', example: 'I am among friends.' },
          { text: 'FUTURE TIME — Parto tra due giorni.', example: 'I leave in two days. Arrivo fra un\'ora — I will arrive in an hour.' },
        ],
        note: 'tra/fra + time = from NOW: "Parto tra due giorni" = I leave two days from now. Compare: "Studio italiano da due anni" = I have been studying for two years (still true until now).',
      },
    ],
  },
  {
    id: 'choose',
    title: 'Choices, Time & Articulated Forms',
    subtitle: 'Choosing the right preposition, time expressions, and preposition + article',
    sections: [
      {
        heading: 'Part 11 — Di vs Da',
        explanation: 'Both can mean "from". Di identifies origin or belonging. Da marks movement from a place or person, and duration that continues until now.',
        table: [
          { form: 'Sono di Roma.', example: 'I am from Rome — identity, where I\'m from.' },
          { form: 'Vengo da Roma.', example: 'I come from Rome — movement from a place.' },
          { form: 'Il libro è di Marco.', example: 'It belongs to Marco — possession.' },
          { form: 'Vado da Marco.', example: 'I\'m going to Marco\'s place — toward a person.' },
          { form: 'Studio italiano da due anni.', example: 'For two years — duration continuing to now.' },
        ],
      },
      {
        heading: 'Part 12 — A vs In: cities, countries, regions',
        explanation: 'Preposition choice depends on the type of place. Learn the common chunks as patterns:',
        groups: [
          { label: 'Cities', items: ['a Roma', 'a Milano', 'a Venezia', 'a Firenze'] },
          { label: 'Countries', items: ['in Italia', 'in Francia', 'in Spagna'] },
          { label: 'Regions', items: ['in Veneto', 'in Toscana'] },
          { label: 'Common expressions', items: ['a casa', 'a scuola', 'a lavoro', 'in ufficio', 'in cucina', 'in banca'] },
        ],
        note: 'These are common patterns, not a strict rule with no exceptions. Memorize the most frequent chunks first.',
      },
      {
        heading: 'Part 13 — A vs Da: destination vs origin',
        explanation: 'Think of arrows: A → destination, DA ← origin from a place.',
        table: [
          { form: 'Vado a Roma.', example: 'I go TO Rome — destination.' },
          { form: 'Vengo da Roma.', example: 'I come FROM Rome — origin.' },
          { form: 'Vado da Marco.', example: 'I go to Marco\'s — direction, but toward a person.' },
          { form: 'Torno da Marco.', example: 'I return from Marco\'s place.' },
        ],
        patterns: ['DA ← origin / from', 'A → destination / to'],
      },
      {
        heading: 'Part 14 — Prepositions of time',
        explanation: 'Five prepositions do most of the "when" work in Italian. Look at the timeline:',
        timeline: { left: 'PAST', center: 'NOW', right: 'FUTURE', examples: ['da due anni — for two years', 'per due ore — for two hours', 'tra due giorni — in two days'] },
        table: [
          { form: 'a / alle — clock time', example: 'alle otto — at eight; a mezzogiorno — at noon' },
          { form: 'di — part of the day', example: 'di mattina — in the morning; di sera — in the evening' },
          { form: 'da — since / for (until now)', example: 'da due anni — for two years (still true)' },
          { form: 'per — duration', example: 'per due ore — for two hours' },
          { form: 'tra / fra — from now', example: 'tra due giorni — in two days; fra un\'ora — in an hour' },
        ],
        note: 'Compare the two "for"s: "Studio italiano DA due anni" (still true now) vs "Ho studiato PER due ore" (a finished duration).',
      },
      {
        heading: 'Part 15 — Articulated prepositions: preposition + article',
        explanation: 'Some prepositions combine with the definite article (il, la, i, le...). You already saw several: al, del, dal, nel, sul. Don\'t memorize every form at once — learn the families and meet them in examples:',
        groups: [
          { label: 'di', items: ['del', 'dello', 'della', 'dei', 'degli', 'delle'] },
          { label: 'a', items: ['al', 'allo', 'alla', 'ai', 'agli', 'alle'] },
          { label: 'da', items: ['dal', 'dallo', 'dalla', 'dai', 'dagli', 'dalle'] },
          { label: 'in', items: ['nel', 'nello', 'nella', 'nei', 'negli', 'nelle'] },
          { label: 'su', items: ['sul', 'sullo', 'sulla', 'sui', 'sugli', 'sulle'] },
        ],
        note: 'Con and per usually do NOT combine: con gli amici, per il lavoro.',
      },
      {
        heading: 'Part 16 — Common articulated preposition examples',
        explanation: 'Here are everyday sentences that use articulated prepositions naturally:',
        table: [
          { form: 'Vado al cinema.', example: 'to the cinema (a + il)' },
          { form: 'Sono alla stazione.', example: 'at the station (a + la)' },
          { form: 'Vengo dal lavoro.', example: 'from work (da + il)' },
          { form: 'Il libro del professore.', example: 'the professor\'s book (di + il)' },
          { form: 'Il libro è nella borsa.', example: 'in the bag (in + la)' },
          { form: 'Il telefono è sul tavolo.', example: 'on the table (su + il)' },
        ],
        focus: { sentence: 'Vado al cinema.', breakdown: [{ part: 'Vado', role: 'I go' }, { part: 'al', role: 'a + il = to the' }, { part: 'cinema', role: 'cinema' }], meaning: 'I go to the cinema.' },
        note: 'Recognize each articulated form as preposition + article: al = a + il, del = di + il, dal = da + il, nel = in + il, sul = su + il.',
      },
    ],
  },
];

export const preposizioniExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Preposition',
    instruction: 'Read each sentence and find the preposition.',
    questions: [
      { question: '"Vado a Roma." — which word is the preposition?', options: ['a', 'Vado', 'Roma'], answer: 'a', explanation: '"a" is the preposition — it shows the destination.' },
      { question: '"Vengo da Milano." — which word is the preposition?', options: ['da', 'Vengo', 'Milano'], answer: 'da', explanation: '"da" is the preposition — it marks the origin.' },
      { question: '"Il libro è di Marco." — which word is the preposition?', options: ['di', 'libro', 'Marco'], answer: 'di', explanation: '"di" expresses belonging — the book belongs to Marco.' },
      { question: '"Vivo in Italia." — which word is the preposition?', options: ['in', 'Vivo', 'Italia'], answer: 'in', explanation: '"in" is the preposition — it shows the country.' },
      { question: '"Parlo con Maria." — which word is the preposition?', options: ['con', 'Parlo', 'Maria'], answer: 'con', explanation: '"con" is the preposition — it means "with".' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match Preposition to Meaning',
    instruction: 'Match each preposition with its common idea.',
    pairs: [
      { left: 'di', right: 'belonging / origin / topic' },
      { left: 'a', right: 'destination / location / time' },
      { left: 'da', right: 'origin / from a person' },
      { left: 'in', right: 'countries / regions / location' },
      { left: 'con', right: 'with' },
      { left: 'su', right: 'on / about' },
      { left: 'per', right: 'for / purpose' },
      { left: 'tra / fra', right: 'between / among' },
    ],
    explanation: 'These are general meanings, not one-to-one translations. The context decides the exact meaning.',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Find the Preposition',
    instruction: 'Find the preposition in each short sentence.',
    questions: [
      { question: '"Studio italiano per lavoro." — the preposition is:', options: ['per', 'Studio', 'lavoro'], answer: 'per', explanation: '"per" = for. "Studio italiano per lavoro."' },
      { question: '"Il telefono è sulla sedia." — the preposition is:', options: ['sulla', 'telefono', 'sedia'], answer: 'sulla', explanation: '"sulla" = su + la → on the chair.' },
      { question: '"Andiamo in Toscana." — the preposition is:', options: ['in', 'Andiamo', 'Toscana'], answer: 'in', explanation: '"in" is used with regions: in Toscana.' },
      { question: '"Vengo da casa." — the preposition is:', options: ['da', 'Vengo', 'casa'], answer: 'da', explanation: '"da" marks origin: I am coming from home.' },
      { question: '"Il regalo è per Maria." — the preposition is:', options: ['per', 'regalo', 'Maria'], answer: 'per', explanation: '"per" = for — the gift is for Maria.' },
    ],
  },
  {
    id: 4,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'One or More Prepositions?',
    instruction: 'Find ALL the prepositions in each sentence.',
    questions: [
      { question: '"Vado a Roma con Marco." →', options: ['a, con', 'a, di', 'con, da', 'a, in'], answer: 'a, con', explanation: 'Both "a" (destination) and "con" (with) are prepositions.' },
      { question: '"Vivo in Italia da tre anni." →', options: ['in, da', 'a, con', 'di, per', 'per, tra'], answer: 'in, da', explanation: '"in" (country) and "da" (duration until now).' },
      { question: '"Il libro è sul tavolo." →', options: ['sul', 'su, il', 'il, tavolo', 'di, per'], answer: 'sul', explanation: 'One preposition: sul = su + il (on the).' },
      { question: '"Parto per Roma alle otto." →', options: ['per, alle', 'a, per', 'da, in', 'con, tra'], answer: 'per, alle', explanation: '"per" (destination) and "alle" (a + le, clock time).' },
      { question: '"Parlo con Marco di cinema." →', options: ['con, di', 'di, a', 'per, con', 'su, da'], answer: 'con, di', explanation: '"con" (with) and "di" (topic).' },
    ],
  },
  {
    id: 5,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Preposition Recognition in Context',
    instruction: 'Read the paragraph and answer questions about the prepositions.',
    questions: [
      { question: '"Anna va al lavoro in treno." — the prepositions are:', options: ['al, in', 'va, Anna', 'lavoro, treno', 'per, da'], answer: 'al, in', explanation: '"al" = a + il, and "in" (transport).' },
      { question: '"La sera studia italiano per un\'ora." — the preposition is:', options: ['per', 'La', 'sera', 'un\''], answer: 'per', explanation: '"per" = for — a duration of one hour.' },
      { question: '"Parto da Milano per Venezia." — how many prepositions?', options: ['2', '1', '3', '0'], answer: '2', explanation: 'Two: "da" (from) and "per" (toward).' },
      { question: '"Di sera" — what does "di" express here?', options: ['Part of the day (in the evening)', 'Possession', 'Origin', 'Destination'], answer: 'Part of the day (in the evening)', explanation: '"di" + part of the day: di mattina, di sera.' },
      { question: '"Vado al cinema con Luca." — how many prepositions?', options: ['2 (al and con)', '1', '3', '0'], answer: '2 (al and con)', explanation: '"al" (a + il) and "con" (with).' },
    ],
  },
  // LEVEL 2 — DI / A / DA / IN
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 2 — Di / A / Da / In',
    title: 'Choose DI',
    instruction: 'Fill in the blank with the correct preposition.',
    questions: [
      { sentence: 'Il libro è ___ Marco.', options: ['di', 'a', 'da', 'con'], answer: 'di', explanation: '"di" expresses belonging: the book is Marco\'s.' },
      { sentence: 'La macchina è ___ Anna.', options: ['di', 'in', 'a', 'per'], answer: 'di', explanation: 'The car belongs to Anna → di.' },
      { sentence: 'Sono ___ Roma.', options: ['di', 'da', 'per', 'a'], answer: 'di', explanation: '"Sono di Roma" = I am from Rome (where I\'m from).' },
      { sentence: 'Un bicchiere ___ vino.', options: ['di', 'con', 'a', 'da'], answer: 'di', explanation: '"Un bicchiere di vino" — a glass of wine (contents).' },
      { sentence: 'Parliamo ___ sport.', options: ['di', 'in', 'per', 'su'], answer: 'di', explanation: '"Parliamo di sport" — to talk about a topic.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 2 — Di / A / Da / In',
    title: 'Choose A',
    instruction: 'Fill in the blank with the correct preposition.',
    questions: [
      { sentence: 'Domani vado ___ Roma.', options: ['a', 'in', 'da', 'di'], answer: 'a', explanation: 'We use "a" with cities: a Roma.' },
      { sentence: 'Siamo ___ scuola.', options: ['a', 'in', 'con', 'da'], answer: 'a', explanation: 'Fixed expression: a scuola.' },
      { sentence: 'Oggi sono ___ casa.', options: ['a', 'in', 'per', 'da'], answer: 'a', explanation: 'Fixed expression: a casa.' },
      { sentence: 'Parto ___ mezzogiorno.', options: ['a', 'alle', 'per', 'di'], answer: 'a', explanation: 'Clock time without an hour word: a mezzogiorno.' },
      { sentence: 'Scrivo ___ Maria.', options: ['a', 'con', 'da', 'per'], answer: 'a', explanation: '"Scrivo a Maria" — writing TO a person.' },
    ],
  },
  {
    id: 8,
    type: 'fillblank',
    level: 'Level 2 — Di / A / Da / In',
    title: 'Choose DA',
    instruction: 'Fill in the blank with the correct preposition.',
    questions: [
      { sentence: 'Vengo ___ Milano.', options: ['da', 'a', 'per', 'di'], answer: 'da', explanation: '"da" marks origin: Vengo da Milano.' },
      { sentence: 'Torno ___ scuola.', options: ['da', 'per', 'in', 'a'], answer: 'da', explanation: 'Returning FROM school → da.' },
      { sentence: 'Vado ___ Marco.', options: ['da', 'a', 'con', 'di'], answer: 'da', explanation: '"da + person" = to that person\'s place: To Marco\'s.' },
      { sentence: 'Studio italiano ___ due anni.', options: ['da', 'per', 'tra', 'alle'], answer: 'da', explanation: '"da + time" = for (until now): for two years.' },
      { sentence: 'Un libro scritto ___ Marco.', options: ['da', 'di', 'con', 'per'], answer: 'da', explanation: 'Agent: a book written BY Marco.' },
    ],
  },
  {
    id: 9,
    type: 'fillblank',
    level: 'Level 2 — Di / A / Da / In',
    title: 'Choose IN',
    instruction: 'Fill in the blank with the correct preposition.',
    questions: [
      { sentence: 'Vivo ___ Italia.', options: ['in', 'a', 'da', 'per'], answer: 'in', explanation: 'We use "in" with countries: in Italia.' },
      { sentence: 'Andiamo ___ Francia.', options: ['in', 'a', 'con', 'di'], answer: 'in', explanation: 'Country → in Francia.' },
      { sentence: 'Vado ___ treno.', options: ['in', 'a', 'da', 'per'], answer: 'in', explanation: 'Transport → in treno (by train).' },
      { sentence: 'Sono ___ ufficio.', options: ['in', 'a', 'da', 'con'], answer: 'in', explanation: 'Location → in ufficio.' },
      { sentence: 'Arrivo ___ dieci minuti.', options: ['in', 'a', 'per', 'tra'], answer: 'in', explanation: '"in + amount of time" = within: in ten minutes.' },
    ],
  },
  {
    id: 10,
    type: 'fillblank',
    level: 'Level 2 — Di / A / Da / In',
    title: 'Mixed DI / A / DA / IN',
    instruction: 'Choose the correct preposition for each sentence.',
    questions: [
      { sentence: 'Sono ___ Roma.', options: ['di', 'a', 'da', 'in'], answer: 'di', explanation: 'Where I\'m from → di Roma.' },
      { sentence: 'Vado ___ Italia.', options: ['in', 'a', 'da', 'di'], answer: 'in', explanation: 'Country → in Italia.' },
      { sentence: 'Vengo ___ Milano.', options: ['da', 'di', 'a', 'in'], answer: 'da', explanation: 'Movement from → da Milano.' },
      { sentence: 'Il libro è ___ Maria.', options: ['di', 'a', 'da', 'in'], answer: 'di', explanation: 'Belonging → di Maria.' },
      { sentence: 'Vivo ___ Toscana.', options: ['in', 'a', 'di', 'da'], answer: 'in', explanation: 'Region → in Toscana.' },
    ],
  },
  // LEVEL 3 — OTHER COMMON PREPOSITIONS
  {
    id: 11,
    type: 'fillblank',
    level: 'Level 3 — Con / Su / Per / Tra-Fra',
    title: 'Choose CON',
    instruction: 'Fill in the blank with "con".',
    questions: [
      { sentence: 'Vado ___ Marco.', options: ['con', 'a', 'da', 'di'], answer: 'con', explanation: '"con" = with.' },
      { sentence: 'Studio ___ Maria.', options: ['con', 'per', 'su', 'tra'], answer: 'con', explanation: 'I study WITH Maria.' },
      { sentence: 'Mangio ___ i miei amici.', options: ['con', 'a', 'in', 'da'], answer: 'con', explanation: 'I eat with my friends.' },
      { sentence: 'Sei ___ me?', options: ['con', 'per', 'di', 'su'], answer: 'con', explanation: '"con me" — with me.' },
      { sentence: 'Parlo ___ loro.', options: ['con', 'a', 'da', 'in'], answer: 'con', explanation: 'I talk with them.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 3 — Con / Su / Per / Tra-Fra',
    title: 'Choose SU',
    instruction: 'Fill in the blank with the correct form of "su".',
    questions: [
      { sentence: 'Il libro è ___ tavolo.', options: ['sul', 'sulla', 'su', 'il'], answer: 'sul', explanation: 'su + il = sul: on the table.' },
      { sentence: 'Il telefono è ___ sedia.', options: ['sulla', 'sul', 'su', 'la'], answer: 'sulla', explanation: 'su + la = sulla: on the chair.' },
      { sentence: 'Un libro ___ storia italiana.', options: ['sulla', 'sul', 'su', 'alle'], answer: 'sulla', explanation: 'Topic → on/about: sulla storia italiana.' },
      { sentence: 'Il caffè è ___ tavolo.', options: ['sul', 'sulla', 'nel', 'al'], answer: 'sul', explanation: 'su + il = sul.' },
      { sentence: 'Un film ___ cucina italiana.', options: ['sulla', 'sul', 'della', 'nel'], answer: 'sulla', explanation: 'A film about Italian food → sulla cucina.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 3 — Con / Su / Per / Tra-Fra',
    title: 'Choose PER',
    instruction: 'Fill in the blank with the correct preposition.',
    questions: [
      { sentence: 'Studio ___ l\'esame.', options: ['per', 'di', 'a', 'da'], answer: 'per', explanation: '"per" = for — purpose.' },
      { sentence: 'Questo regalo è ___ Maria.', options: ['per', 'con', 'a', 'da'], answer: 'per', explanation: 'The gift is FOR Maria.' },
      { sentence: 'Parto ___ Roma.', options: ['per', 'a', 'da', 'in'], answer: 'per', explanation: '"per" = toward: leaving for Rome.' },
      { sentence: 'Ho lavorato ___ tre giorni.', options: ['per', 'da', 'tra', 'alle'], answer: 'per', explanation: 'Duration → per three days.' },
      { sentence: 'Studio italiano ___ lavoro.', options: ['per', 'di', 'in', 'su'], answer: 'per', explanation: 'I study Italian FOR work.' },
    ],
  },
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 3 — Con / Su / Per / Tra-Fra',
    title: 'Choose TRA / FRA',
    instruction: 'Either tra or fra. Fill in with the best word.',
    questions: [
      { sentence: 'Parto ___ due giorni.', options: ['tra', 'fra', 'per', 'in'], answer: 'tra', explanation: 'tra + time = from now: in two days.' },
      { sentence: 'Arrivo ___ un\'ora.', options: ['fra', 'tra', 'da', 'alle'], answer: 'fra', explanation: 'fra un\'ora — in an hour.' },
      { sentence: 'La casa è ___ la scuola e il parco.', options: ['tra', 'per', 'con', 'da'], answer: 'tra', explanation: 'Between → tra la scuola e il parco.' },
      { sentence: 'Sono ___ amici.', options: ['tra', 'in', 'a', 'per'], answer: 'tra', explanation: 'Among friends → tra amici.' },
      { sentence: 'Ti chiamo ___ dieci minuti.', options: ['fra', 'tra', 'da', 'per'], answer: 'fra', explanation: 'In ten minutes (from now) → fra dieci minuti.' },
    ],
  },
  {
    id: 15,
    type: 'fillblank',
    level: 'Level 3 — Con / Su / Per / Tra-Fra',
    title: 'Mixed Prepositions',
    instruction: 'Choose the right preposition for each sentence.',
    questions: [
      { sentence: 'Vado ___ Roma.', options: ['a', 'in', 'di', 'da'], answer: 'a', explanation: 'City → a Roma.' },
      { sentence: 'Vivo ___ Italia.', options: ['in', 'a', 'da', 'con'], answer: 'in', explanation: 'Country → in Italia.' },
      { sentence: 'Vengo ___ Milano.', options: ['da', 'a', 'per', 'di'], answer: 'da', explanation: 'Origin → da Milano.' },
      { sentence: 'Il libro è ___ Marco.', options: ['di', 'a', 'con', 'per'], answer: 'di', explanation: 'Belonging → di Marco.' },
      { sentence: 'Parlo ___ Maria.', options: ['con', 'di', 'per', 'su'], answer: 'con', explanation: 'With → con Maria.' },
      { sentence: 'Studio ___ l\'esame.', options: ['per', 'di', 'a', 'tra'], answer: 'per', explanation: 'Purpose → per l\'esame.' },
    ],
  },
  // LEVEL 4 — MEANING AND CONTEXT
  {
    id: 16,
    type: 'multiple',
    level: 'Level 4 — Meaning and Context',
    title: 'Destination or Origin?',
    instruction: 'Decide what each sentence expresses.',
    questions: [
      { question: '"Vado a Roma." expresses:', options: ['Destination', 'Origin', 'Belonging', 'With'], answer: 'Destination', explanation: 'a + city = destination: going to Rome.' },
      { question: '"Vengo da Roma." expresses:', options: ['Origin', 'Destination', 'Topic', 'Clock time'], answer: 'Origin', explanation: 'da + place = coming from a place.' },
      { question: '"Torno da Milano." expresses:', options: ['Origin', 'Destination', 'Possession', 'Transport'], answer: 'Origin', explanation: 'Returning FROM Milan → origin.' },
      { question: '"Vado da Marco." expresses:', options: ['A person\'s place', 'A city', 'A country', 'A duration'], answer: 'A person\'s place', explanation: 'da + person = to that person\'s home.' },
      { question: '"Parto per Roma." expresses:', options: ['Destination / direction', 'Origin', 'With', 'A topic'], answer: 'Destination / direction', explanation: 'per + city = direction/toward.' },
    ],
  },
  {
    id: 17,
    type: 'multiple',
    level: 'Level 4 — Meaning and Context',
    title: 'City or Country?',
    instruction: 'Choose a (city) or in (country / region).',
    questions: [
      { question: '"Roma" →', options: ['a', 'in', 'da', 'per'], answer: 'a', explanation: 'Cities → a Roma.' },
      { question: '"Italia" →', options: ['in', 'a', 'con', 'di'], answer: 'in', explanation: 'Countries → in Italia.' },
      { question: '"Parigi" →', options: ['a', 'in', 'da', 'per'], answer: 'a', explanation: 'Cities → a Parigi.' },
      { question: '"Francia" →', options: ['in', 'a', 'da', 'con'], answer: 'in', explanation: 'Countries → in Francia.' },
      { question: '"Toscana" →', options: ['in', 'a', 'di', 'da'], answer: 'in', explanation: 'Regions → in Toscana.' },
    ],
  },
  {
    id: 18,
    type: 'multiple',
    level: 'Level 4 — Meaning and Context',
    title: 'Person or Place?',
    instruction: 'What does "da" mean when followed by a person?',
    questions: [
      { question: '"Vado da Marco." means:', options: ['To Marco\'s place', 'From Marco', 'With Marco', 'To a city called Marco'], answer: 'To Marco\'s place', explanation: 'da + person = to that person\'s house.' },
      { question: '"Sono da Maria." means:', options: ['I am at Maria\'s place', 'I am from Maria', 'I go with Maria', 'Maria is from here'], answer: 'I am at Maria\'s place', explanation: 'Being at someone\'s home → da Maria.' },
      { question: '"Vengo da Roma." — "Roma" here is:', options: ['A place', 'A person', 'A country', 'A time'], answer: 'A place', explanation: 'da + a place name = origin.' },
      { question: '"Un libro scritto da Marco." — "da" means:', options: ['by (the author)', 'with', 'to', 'from a place'], answer: 'by (the author)', explanation: 'Agent: a book written by Marco.' },
      { question: '"Vado dalla nonna." means:', options: ['To grandmother\'s house', 'From grandmother', 'With grandmother', 'Grandmother is going'], answer: 'To grandmother\'s house', explanation: 'dalla nonna = da + la nonna → to grandma\'s place.' },
    ],
  },
  {
    id: 19,
    type: 'fillblank',
    level: 'Level 4 — Meaning and Context',
    title: 'Time Expressions',
    instruction: 'Choose the correct preposition of time.',
    questions: [
      { sentence: 'Studio italiano ___ due anni.', options: ['da', 'per', 'tra', 'alle'], answer: 'da', explanation: 'Duration continuing to now → da due anni.' },
      { sentence: 'Parto ___ due giorni.', options: ['tra', 'da', 'per', 'alle'], answer: 'tra', explanation: 'From now → tra due giorni.' },
      { sentence: 'Studio ___ due ore.', options: ['per', 'da', 'tra', 'alle'], answer: 'per', explanation: 'Finished/simple duration → per due ore.' },
      { sentence: 'Arrivo ___ le otto.', options: ['alle', 'da', 'per', 'tra'], answer: 'alle', explanation: 'Clock time → alle otto.' },
      { sentence: 'Ho lavorato ___ tre giorni.', options: ['per', 'da', 'tra', 'con'], answer: 'per', explanation: 'Duration → per tre giorni.' },
    ],
  },
  {
    id: 20,
    type: 'multiple',
    level: 'Level 4 — Meaning and Context',
    title: 'Explain the Meaning',
    instruction: 'What does each preposition express in context?',
    questions: [
      { question: '"di" in "Sono di Roma" expresses:', options: ['Origin (where I\'m from)', 'Destination', 'With', 'On'], answer: 'Origin (where I\'m from)', explanation: 'Sono di Roma = I am from Rome.' },
      { question: '"a" in "Vado a Roma" expresses:', options: ['Destination', 'Origin', 'Belonging', 'Company'], answer: 'Destination', explanation: 'a + city = destination.' },
      { question: '"da" in "Vengo da Roma" expresses:', options: ['Origin (movement from)', 'Belonging', 'Purpose', 'Clock time'], answer: 'Origin (movement from)', explanation: 'Coming from a place → da Roma.' },
      { question: '"in" in "Vivo in Italia" expresses:', options: ['A country / location', 'Destination to a city', 'With someone', 'On the table'], answer: 'A country / location', explanation: 'Living in a country → in Italia.' },
      { question: '"con" in "Parlo con Maria" expresses:', options: ['Company (with someone)', 'Purpose', 'Origin', 'Time'], answer: 'Company (with someone)', explanation: 'con = with — speaking with Maria.' },
    ],
  },
  // LEVEL 5 — ARTICULATED PREPOSITIONS
  {
    id: 21,
    type: 'matching',
    level: 'Level 5 — Articulated Prepositions',
    title: 'Combine Preposition + Article',
    instruction: 'Match each combination with its articulated form.',
    pairs: [
      { left: 'a + il', right: 'al' },
      { left: 'di + il', right: 'del' },
      { left: 'da + il', right: 'dal' },
      { left: 'in + il', right: 'nel' },
      { left: 'su + il', right: 'sul' },
    ],
    explanation: 'These five are the most common articulated prepositions. Recognize each as preposition + article.',
  },
  {
    id: 22,
    type: 'fillblank',
    level: 'Level 5 — Articulated Prepositions',
    title: 'Choose the Correct Articulated Preposition',
    instruction: 'Fill in the blank with the correct articulated form.',
    questions: [
      { sentence: 'Vado ___ cinema.', options: ['al', 'del', 'dal', 'nel'], answer: 'al', explanation: 'a + il = al → to the cinema.' },
      { sentence: 'Sono ___ stazione.', options: ['alla', 'al', 'nella', 'sulla'], answer: 'alla', explanation: 'a + la = alla → at the station.' },
      { sentence: 'Vengo ___ lavoro.', options: ['dal', 'al', 'del', 'nel'], answer: 'dal', explanation: 'da + il = dal → from work.' },
      { sentence: 'Il libro è ___ borsa.', options: ['nella', 'della', 'alla', 'sul'], answer: 'nella', explanation: 'in + la = nella → in the bag.' },
      { sentence: 'Il telefono è ___ tavolo.', options: ['sul', 'sulla', 'nel', 'al'], answer: 'sul', explanation: 'su + il = sul → on the table.' },
    ],
  },
  {
    id: 23,
    type: 'fillblank',
    level: 'Level 5 — Articulated Prepositions',
    title: 'Complete the Articulated Preposition',
    instruction: 'Combine the preposition and article shown.',
    questions: [
      { sentence: 'di + la = ___', options: ['della', 'del', 'dalle', 'dallo'], answer: 'della', explanation: 'di + la = della.' },
      { sentence: 'a + gli = ___', options: ['agli', 'alle', 'ai', 'aglio'], answer: 'agli', explanation: 'a + gli = agli.' },
      { sentence: 'da + i = ___', options: ['dai', 'dal', 'dalle', 'degli'], answer: 'dai', explanation: 'da + i = dai.' },
      { sentence: 'in + le = ___', options: ['nelle', 'nella', 'nei', 'negli'], answer: 'nelle', explanation: 'in + le = nelle.' },
      { sentence: 'su + i = ___', options: ['sui', 'sul', 'sulla', 'sulle'], answer: 'sui', explanation: 'su + i = sui.' },
    ],
  },
  {
    id: 24,
    type: 'multiple',
    level: 'Level 5 — Articulated Prepositions',
    title: 'Deconstruct the Form',
    instruction: 'Break each articulated preposition into its parts.',
    questions: [
      { question: '"sulla" =', options: ['su + la', 'su + il', 'si + la', 'su + le'], answer: 'su + la', explanation: 'sulla → su + la.' },
      { question: '"dalle" =', options: ['da + le', 'di + la', 'da + il', 'de + le'], answer: 'da + le', explanation: 'dalle → da + le.' },
      { question: '"nel" =', options: ['in + il', 'a + il', 'da + il', 'su + il'], answer: 'in + il', explanation: 'nel → in + il.' },
      { question: '"al" =', options: ['a + il', 'di + il', 'in + il', 'da + il'], answer: 'a + il', explanation: 'al → a + il.' },
      { question: '"degli" =', options: ['di + gli', 'da + gli', 'su + gli', 'a + gli'], answer: 'di + gli', explanation: 'degli → di + gli.' },
    ],
  },
  {
    id: 25,
    type: 'fillblank',
    level: 'Level 5 — Articulated Prepositions',
    title: 'Mixed Articulated Prepositions',
    instruction: 'Choose the correct articulated preposition in context.',
    questions: [
      { sentence: 'Il libro è ___ professore.', options: ['del', 'al', 'nel', 'sul'], answer: 'del', explanation: 'di + il = del → the professor\'s book.' },
      { sentence: 'La macchina è ___ famiglia.', options: ['della', 'alla', 'nella', 'sulla'], answer: 'della', explanation: 'di + la = della → the family\'s car.' },
      { sentence: 'Vengo ___ lavoro alle sei.', options: ['dal', 'al', 'nel', 'sui'], answer: 'dal', explanation: 'da + il = dal → I come from work.' },
      { sentence: 'Il libro è ___ borsa.', options: ['nella', 'della', 'alla', 'sul'], answer: 'nella', explanation: 'in + la = nella → in the bag.' },
      { sentence: 'Il quaderno è ___ scrivania.', options: ['sulla', 'sul', 'nel', 'alla'], answer: 'sulla', explanation: 'su + la = sulla → on the desk.' },
      { sentence: 'Vado ___ supermercato.', options: ['al', 'del', 'dal', 'nel'], answer: 'al', explanation: 'a + il = al → to the supermarket.' },
    ],
  },
  // LEVEL 6 — SENTENCE BUILDING
  {
    id: 26,
    type: 'wordorder',
    level: 'Level 6 — Sentence Building',
    title: 'Put the Words in Order',
    instruction: 'Arrange the words to form a correct sentence.',
    questions: [
      { words: ['a', 'Roma', 'vado'], answer: 'Vado a Roma.', explanation: '"Vado a Roma." = I go to Rome.' },
      { words: ['con', 'Marco', 'parlo'], answer: 'Parlo con Marco.', explanation: '"Parlo con Marco." = I talk with Marco.' },
      { words: ['in', 'Italia', 'vivo'], answer: 'Vivo in Italia.', explanation: '"Vivo in Italia." = I live in Italy.' },
      { words: ['da', 'Milano', 'vengo'], answer: 'Vengo da Milano.', explanation: '"Vengo da Milano." = I come from Milan.' },
      { words: ['tra', 'giorni', 'parto', 'due'], answer: 'Parto tra due giorni.', explanation: '"Parto tra due giorni." = I leave in two days.' },
    ],
  },
  {
    id: 27,
    type: 'translation',
    level: 'Level 6 — Sentence Building',
    title: 'Translate English → Italian',
    instruction: 'Choose the correct Italian translation.',
    direction: 'en-it',
    questions: [
      { sentence: 'I live in Italy.', options: ['Vivo in Italia.', 'Vivo a Italia.', 'Vivo da Italia.', 'Vivo per Italia.'], answer: 'Vivo in Italia.', explanation: 'Country → in Italia.' },
      { sentence: 'I am going to Rome.', options: ['Vado a Roma.', 'Vado in Roma.', 'Vengo a Roma.', 'Vado da Roma.'], answer: 'Vado a Roma.', explanation: 'City + destination → a Roma.' },
      { sentence: 'I come from Milan.', options: ['Vengo da Milano.', 'Vado da Milano.', 'Vengo di Milano.', 'Vengo a Milano.'], answer: 'Vengo da Milano.', explanation: 'Origin → da Milano.' },
      { sentence: 'I am with Marco.', options: ['Sono con Marco.', 'Sono da Marco.', 'Sono di Marco.', 'Vado con Marco.'], answer: 'Sono con Marco.', explanation: 'Company → con Marco.' },
      { sentence: 'I have been studying Italian for two years.', options: ['Studio italiano da due anni.', 'Studio italiano per due anni.', 'Studio italiano tra due anni.', 'Studio italiano alle due.'], answer: 'Studio italiano da due anni.', explanation: 'Duration until now → da due anni.' },
    ],
  },
  // LEVEL 7 — STORIES
  {
    id: 28,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Beginner Story — Una giornata a Roma',
    storyTitle: 'Una giornata a Roma',
    story: 'Anna abita a Roma. Oggi è sabato. La mattina va al mercato con la sua amica Giulia. Loro comprano la frutta e un regalo per la madre di Anna. A mezzogiorno pranzano in un piccolo ristorante vicino al Colosseo. Nel pomeriggio camminano in centro e guardano i negozi. Poi prendono un caffè in una piazza famosa. Alla sera tornano a casa in autobus. Anna è contenta: a Roma c\'è sempre qualcosa da fare. Domani andranno al parco sul fiume Tevere.',
    vocab: [
      { word: 'il mercato', meaning: 'the market' },
      { word: 'il regalo', meaning: 'the gift' },
      { word: 'vicino a', meaning: 'near' },
      { word: 'nel pomeriggio', meaning: 'in the afternoon' },
      { word: 'la piazza', meaning: 'the square' },
      { word: 'il fiume', meaning: 'the river' },
      { word: 'l\'autobus', meaning: 'the bus' },
    ],
    translation: 'Anna lives in Rome. Today is Saturday. In the morning she goes to the market with her friend Giulia. They buy fruit and a gift for Anna\'s mother. At noon they have lunch in a small restaurant near the Colosseum. In the afternoon they walk around the centre and look at the shops. Then they have a coffee in a famous square. In the evening they return home by bus. Anna is happy: in Rome there is always something to do. Tomorrow they will go to the park on the Tiber river.',
    questions: [
      { question: 'Where does Anna live?', options: ['In Rome', 'In Milan', 'In Naples'], answer: 'In Rome', explanation: '"Anna abita a Roma." — a + city.' },
      { question: 'What do they buy at the market?', options: ['Fruit and a gift for Anna\'s mother', 'A book and shoes', 'Just coffee'], answer: 'Fruit and a gift for Anna\'s mother', explanation: '"comprano la frutta e un regalo per la madre di Anna."' },
      { question: 'Where do they have lunch?', options: ['In a small restaurant near the Colosseum', 'At home', 'On the bus'], answer: 'In a small restaurant near the Colosseum', explanation: '"in un piccolo ristorante vicino al Colosseo."' },
      { question: 'How do they return home in the evening?', options: ['By bus', 'On foot', 'By car'], answer: 'By bus', explanation: '"in autobus" — "in" is used for transport.' },
      { question: 'Which prepositions appear in "Anna va al mercato con Giulia"?', options: ['al and con', 'va and Anna', 'mercato and amica'], answer: 'al and con', explanation: '"al" = a + il, and "con" = with.' },
      { question: 'Write a sentence about where YOU live using "a" (city) or "in" (country).', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vivo in Italia. / Abito a Roma. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Intermediate Story — Un viaggio in Italia',
    storyTitle: 'Un viaggio in Italia',
    story: 'Anna: Marco, dove vai questo fine settimana?\n\nMarco: Vado in Toscana con la mia famiglia.\n\nAnna: Da dove venite?\n\nMarco: Veniamo da Milano. Prendiamo il treno per Firenze alle nove di mattina.\n\nAnna: E dopo?\n\nMarco: Andiamo al museo e camminiamo per le strade del centro.\n\nAnna: Quanto tempo restate in Toscana?\n\nMarco: Restiamo due giorni. Poi torniamo a casa in auto.\n\nAnna: E a Firenze, cosa fate la sera?\n\nMarco: La sera camminiamo per le strade del centro e mangiamo in un ristorante vicino al Duomo.\n\nAnna: Bellissimo! A me piace camminare per le piazze al tramonto.\n\nMarco: Sì, e dal treno si vedono le colline della Toscana.\n\nAnna: Che bello! Io parto per Roma con Luisa. Visiteremo il Colosseo.\n\nMarco: Perfetto. Vi mando una cartolina da Firenze.',
    vocab: [
      { word: 'la Toscana', meaning: 'Tuscany (a region)' },
      { word: 'veniamo', meaning: 'we come (venire)' },
      { word: 'prendiamo', meaning: 'we take (prendere)' },
      { word: 'mattina', meaning: 'morning' },
      { word: 'le strade', meaning: 'the streets' },
      { word: 'restiamo', meaning: 'we stay (restare)' },
      { word: 'la cartolina', meaning: 'the postcard' },
    ],
    translation: 'Anna: Marco, where are you going this weekend?\n\nMarco: I\'m going to Tuscany with my family.\n\nAnna: Where are you from?\n\nMarco: We come from Milan. We take the train to Florence at nine in the morning.\n\nAnna: And then?\n\nMarco: We go to the museum and walk through the streets of the centre.\n\nAnna: How long will you stay in Tuscany?\n\nMarco: We stay two days. Then we return home by car.\n\nAnna: And in Florence, what do you do in the evening?\n\nMarco: In the evening we walk through the streets of the centre and eat in a restaurant near the Duomo.\n\nAnna: Wonderful! I like walking through the squares at sunset.\n\nMarco: Yes, and from the train you can see the hills of Tuscany.\n\nAnna: Nice! I am leaving for Rome with Luisa. We will visit the Colosseum.\n\nMarco: Perfect. I will send you a postcard from Florence.',
    questions: [
      { question: 'Where is Marco going this weekend?', options: ['To Tuscany', 'To Rome', 'To Milan'], answer: 'To Tuscany', explanation: '"Vado in Toscana" — regions use "in".' },
      { question: 'Where do Marco and his family come from?', options: ['Milan', 'Florence', 'Rome'], answer: 'Milan', explanation: '"Veniamo da Milano." — origin with da.' },
      { question: 'How do they travel to Florence?', options: ['By train', 'By car', 'By bus'], answer: 'By train', explanation: '"Prendiamo il treno per Firenze."' },
      { question: 'At what time does their train leave?', options: ['At nine in the morning', 'At eight', 'At noon'], answer: 'At nine in the morning', explanation: '"alle nove di mattina" — clock time with alle.' },
      { question: 'Identify the prepositions in "Vado in Toscana con la mia famiglia."', options: ['in, con', 'a, per', 'da, di'], answer: 'in, con', explanation: '"in" (region) and "con" (with).' },
      { question: 'Which articulated prepositions appear in the dialogue?', options: ['al, del', 'di, con', 'su, a'], answer: 'al, del', explanation: '"al museo" (a + il) and "del centro" (di + il).' },
      { question: 'Write a sentence about where you will go next week using "a" or "in".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vado a Firenze. / Vado in Italia. Any correct sentence is accepted.' },
    ],
  },
  // LEVEL 8 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 8 — Final Proficiency Test',
    title: 'Italian Prepositions Mastery Test',
    instruction: 'Answer all the questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Identify prepositions
      { question: '"Anna va a Roma con Marco" — the prepositions are:', options: ['a, con', 'a, di', 'con, da', 'di, per'], answer: 'a, con' },
      // DI / A / DA / IN / CON / PER / SU / TRA
      { question: 'Il libro è ___ Marco.', options: ['di', 'a', 'da', 'con'], answer: 'di' },
      { question: 'Domani vado ___ Roma.', options: ['a', 'in', 'da', 'di'], answer: 'a' },
      { question: 'Vengo ___ Milano.', options: ['da', 'di', 'per', 'a'], answer: 'da' },
      { question: 'Vivo ___ Italia.', options: ['in', 'a', 'da', 'per'], answer: 'in' },
      { question: 'Parlo ___ Maria.', options: ['con', 'di', 'a', 'da'], answer: 'con' },
      { question: 'Studio ___ l\'esame.', options: ['per', 'di', 'a', 'da'], answer: 'per' },
      { question: 'Il telefono è ___ tavolo.', options: ['sul', 'sulla', 'nel', 'alla'], answer: 'sul' },
      { question: 'Parto ___ due giorni.', options: ['tra', 'da', 'per', 'alle'], answer: 'tra' },
      // Destination / origin / possession
      { question: '"Sono di Roma" means:', options: ['I am from Rome', 'I am going to Rome', 'I come from Rome (movement)', 'I live with Rome'], answer: 'I am from Rome' },
      { question: '"La macchina è di Anna" means:', options: ['The car is Anna\'s', 'Anna is in the car', 'The car goes to Anna', 'Anna drives the car'], answer: 'The car is Anna\'s' },
      { question: 'Choose: "Roma" →', options: ['a', 'in', 'di', 'da'], answer: 'a' },
      { question: 'Choose: "Toscana" →', options: ['in', 'a', 'di', 'per'], answer: 'in' },
      // Transportation / time
      { question: 'Vado ___ treno.', options: ['in', 'a', 'con', 'da'], answer: 'in' },
      { question: 'Arrivo ___ un\'ora. (in an hour)', options: ['fra', 'da', 'per', 'alle'], answer: 'fra' },
      { question: 'Ho lavorato ___ tre giorni.', options: ['per', 'da', 'tra', 'di'], answer: 'per' },
      // Person's place / purpose
      { question: '"Vado da Marco" means:', options: ['I go to Marco\'s place', 'I come from Marco', 'I go with Marco', 'I am Marco'], answer: 'I go to Marco\'s place' },
      { question: 'In "Questo regalo è per Maria", "per" expresses:', options: ['Purpose / receiver', 'Origin', 'Possession', 'Time'], answer: 'Purpose / receiver' },
      // Articulated prepositions
      { question: '"al" = a + ___', options: ['il', 'la', 'le', 'gli'], answer: 'il' },
      { question: '"della" = di + ___', options: ['la', 'il', 'le', 'lo'], answer: 'la' },
      { question: 'Vado ___ cinema.', options: ['al', 'del', 'dal', 'nel'], answer: 'al' },
      // Sentence ordering
      { question: 'Choose the correct order: "Roma / vado / a"', options: ['Vado a Roma.', 'Roma a vado.', 'Vado Roma a.', 'A vado Roma.'], answer: 'Vado a Roma.' },
      // Italian → English / English → Italian
      { question: '"I am going to Rome" =', options: ['Vado a Roma', 'Vengo a Roma', 'Vivo a Roma', 'Sono a Roma'], answer: 'Vado a Roma' },
      { question: '"I have been studying Italian for two years" =', options: ['Studio italiano da due anni', 'Studio italiano per due anni', 'Studio italiano tra due anni', 'Studio italiano alle due'], answer: 'Studio italiano da due anni' },
      // Reading passage (Story 3 — "Una giornata normale")
      { question: 'READ FIRST: "Marco si alza alle sette ogni mattina. Dopo la doccia prepara un caffè in cucina e mangia un cornetto. Alle otto esce di casa e va al lavoro in autobus, perché il suo ufficio è vicino al centro. Lavora dalle nove alle sei. A mezzogiorno pranza con i colleghi in un piccolo bar. Nel pomeriggio beve un caffè con la sua amica Giulia e parlano di viaggi. Alle sei esce dal lavoro e cammina fino alla stazione. La sera cena con la sua famiglia a casa e poi guardano un film sul divano. Prima di dormire studia l\'italiano per mezz\'ora. L\'anno scorso è andato a Roma due volte, e per il suo compleanno la moglie gli ha regalato un libro sul Colosseo. Tra un mese partirà con un amico per la Sardegna: sarà un viaggio bellissimo, e per questo ora studia ogni giorno con tanta passione."\n\nWhat time does Marco leave for work?', options: ['At eight (alle otto)', 'At seven', 'At noon', 'At six'], answer: 'At eight (alle otto)' },
      { question: 'READ AGAIN: How does Marco go to work?', options: ['By bus (in autobus)', 'By train', 'On foot', 'By car'], answer: 'By bus (in autobus)' },
      { question: 'READ AGAIN: In "va al lavoro", the articulated preposition is:', options: ['al', 'alla', 'dal', 'nel'], answer: 'al' },
      { question: 'READ AGAIN: "Tra un mese partirà per la Sardegna" — "tra" means:', options: ['In a month from now', 'Since a month', 'Last month', 'For a month'], answer: 'In a month from now' },
      // Sentence production
      { question: 'Write "I live in Italy" in Italian:', type: 'text', answer: 'Vivo in Italia', acceptedAnswers: ['vivo in italia', 'abito in italia'] },
      { question: 'Write one sentence about your morning using at least two prepositions.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: La mattina vado a scuola in autobus. Any correct sentence with prepositions is accepted.' },
    ],
  },
];

export const preposizioniFinalTest = preposizioniExercises.find((e) => e.id === 30).questions;

export const preposizioniFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You can confidently recognize, choose, and use the most common Italian prepositions.' },
  { min: 75, grade: 'Very good!', message: 'You understand the main patterns. Review articulated prepositions and common fixed expressions.' },
  { min: 60, grade: 'Almost there!', message: 'Review DI/A/DA/IN and practice them in context.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the core prepositions before taking the final test again.' },
];