export const modaliStages = [
  {
    id: 'concept',
    title: 'What are Modal Verbs?',
    subtitle: 'Dovere, Potere & Volere — obligation, ability, and desire before an infinitive',
    sections: [
      {
        heading: 'Part 1 — The three modal verbs',
        explanation: 'In Italian the most common modal verbs (verbi servili/modali) are dovere, potere, and volere. They are used for obligation, ability/permission, and desire, and they are always followed by an INFINITIVE or by the auxiliary + participle in compound tenses.',
        bullets: [
          { text: 'DOVERE = must / have to / should (obligation)', example: 'Devo studiare. → I must study.' },
          { text: 'POTERE = can / may / to be able to (permission, ability, possibility)', example: 'Posso entrare? → May I come in?' },
          { text: 'VOLERE = to want (desire, willingness)', example: 'Voglio un caffè. → I want a coffee.' },
        ],
        timeline: { left: 'OBLIGATION (dovere)', center: 'POSSIBILITY (potere)', right: 'DESIRE (volere)', examples: ['Devo lavorare', 'Posso aiutarti', 'Voglio parlare'] },
        note: 'Modal verbs usually modify another verb. When used alone they still carry the same meaning: non posso = I can\'t, devo andare = I must go.',
      },
      {
        heading: 'Part 2 — The structure: modal + infinitive',
        explanation: 'The modal verb is conjugated, and it is followed directly by the infinitive of the main action. This is different from English, where "to" or a that-clause often appears.',
        bullets: [
          { text: 'Devo partire domani.', example: 'I have to leave tomorrow.' },
          { text: 'Luca può venire con noi.', example: 'Luca can come with us.' },
          { text: 'Vuoi mangiare la pizza?', example: 'Do you want to eat pizza?' },
          { text: 'Non posso uscire stasera.', example: 'I can\'t go out tonight.' },
        ],
        focus: { sentence: 'Devo studiare l\'italiano.', breakdown: [{ part: 'Devo', role: 'modal (dovere, io)' }, { part: 'studiare', role: 'infinitive (main verb)' }, { part: 'l\'italiano', role: 'object' }], meaning: 'I must study Italian. Modal verb + infinitive.' },
        note: 'Other modal-like verbs you already know include sapere (to know how / can) and other verbs used similarly, but the core trio is dovere, potere, volere.',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Conjugating the Modals',
    subtitle: 'Present tense of dovere, potere, and volere',
    sections: [
      {
        heading: 'Part 3 — Dovere (present)',
        explanation: 'Dovere is irregular in the present. Learn it by heart:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'devo' }, { pronoun: 'tu', ending: 'devi' }, { pronoun: 'lui/lei', ending: 'deve' }, { pronoun: 'noi', ending: 'dobbiamo' }, { pronoun: 'voi', ending: 'dovete' }, { pronoun: 'loro', ending: 'devono' }] },
        examples: [
          { italian: 'Devo chiamare mia madre.', translation: 'I must call my mother.' },
          { italian: 'Devi studiare di più.', translation: 'You should study more.' },
          { italian: 'Dobbiamo partire adesso.', translation: 'We have to leave now.' },
        ],
      },
      {
        heading: 'Part 4 — Potere (present)',
        explanation: 'Potere is also irregular in the present. Note the forms posso, può, and possiamo:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'posso' }, { pronoun: 'tu', ending: 'puoi' }, { pronoun: 'lui/lei', ending: 'può' }, { pronoun: 'noi', ending: 'possiamo' }, { pronoun: 'voi', ending: 'potete' }, { pronoun: 'loro', ending: 'possono' }] },
        examples: [
          { italian: 'Posso usare il tuo telefono?', translation: 'Can I use your phone?' },
          { italian: 'Puoi venire domani?', translation: 'Can you come tomorrow?' },
          { italian: 'Non possiamo fumare qui.', translation: 'We can\'t smoke here.' },
        ],
        note: 'Attributes of permission: "Posso?" = May I? Perfect when asking to enter, sit, borrow, etc.',
      },
      {
        heading: 'Part 5 — Volere (present)',
        explanation: 'Volere has the forms voglio, vuoi, vuole, vogliamo, volete, vogliono:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'voglio' }, { pronoun: 'tu', ending: 'vuoi' }, { pronoun: 'lui/lei', ending: 'vuole' }, { pronoun: 'noi', ending: 'vogliamo' }, { pronoun: 'voi', ending: 'volete' }, { pronoun: 'loro', ending: 'vogliono' }] },
        examples: [
          { italian: 'Voglio un gelato.', translation: 'I want an ice cream.' },
          { italian: 'Vuoi un caffè?', translation: 'Do you want a coffee?' },
          { italian: 'Vogliamo vedere il film.', translation: 'We want to see the film.' },
        ],
        note: 'The accent on "può" is important — it distinguishes may/can (potere) from also (anche).',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'The Modals in Other Tenses',
    subtitle: 'Passato prossimo, imperfetto, futuro, and condizionale',
    sections: [
      {
        heading: 'Part 6 — Passato prossimo: avere + infinitive participle',
        explanation: 'In the passato prossimo the main verb stays in the infinitive and the modal takes the auxiliary AVERE: ho dovuto, ho potuto, ho voluto + infinitive. (With motion verbs many speakers also say "sono dovuto andare", but "ho dovuto andare" is standard and safe.)',
        bullets: [
          { text: 'Ho dovuto studiare tutto il giorno.', example: 'I had to study all day.' },
          { text: 'Non ho potuto venire alla festa.', example: 'I couldn\'t come to the party.' },
          { text: 'Ha voluto aspettare.', example: 'He wanted to wait.' },
          { text: 'Abbiamo dovuto tornare a casa.', example: 'We had to go back home.' },
        ],
        patterns: ['dovere → ho dovuto', 'potere → ho potuto', 'volere → ho voluto'],
        note: 'Remember: the main verb stays an INFINITIVE after the modal: ho dovuto + studiare, ho potuto + venire. The participle belongs to the modal.',
      },
      {
        heading: 'Part 7 — Imperfetto: dovevo, potevo, volevo',
        explanation: 'The imperfetto of the modals expresses repeated or ongoing obligation, ability, or desire in the past:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'dovevo / potevo / volevo' }, { pronoun: 'tu', ending: 'dovevi / potevi / volevi' }, { pronoun: 'lui/lei', ending: 'doveva / poteva / voleva' }, { pronoun: 'noi', ending: 'dovevamo / potevamo / volevamo' }, { pronoun: 'voi', ending: 'dovevate / potevate / volevate' }, { pronoun: 'loro', ending: 'dovevano / potevano / volevano' }] },
        examples: [
          { italian: 'Da piccolo dovevo andare a scuola la domenica.', translation: 'As a child I had to go to school on Sundays (habit).' },
          { italian: 'Potevo uscire quando volevo.', translation: 'I could go out whenever I wanted.' },
          { italian: 'Non volevo alzarmi presto.', translation: 'I didn\'t want to get up early.' },
        ],
        note: 'Compare: dovevo (imperfetto, repeated/ongoing) vs ho dovuto (passato prossimo, one completed obligation).',
      },
      {
        heading: 'Part 8 — Futuro & condizionale',
        explanation: 'Like all irregular verbs, dovere/potere/volere have a shortened future stem and use the same stem for the condizionale heading ending:',
        bullets: [
          { text: 'Futuro: dovrò, potrò, vorrò — avrò tempo, certo.', example: 'I will have to / be able to / want.' },
          { text: 'Condizionale: dovrei, potrei, vorrei — would have to / could / would like.', example: 'Polite requests and advice.' },
        ],
        patterns: ['dovere → dovrò / dovrei', 'potere → potrò / potrei', 'volere → vorrò / vorrei'],
        examples: [
          { italian: 'Domani dovrò lavorare.', translation: 'Tomorrow I will have to work.' },
          { italian: 'Potrei aiutarti, se vuoi.', translation: 'I could help you, if you want.' },
          { italian: 'Vorrei un caffè, per favore.', translation: 'I would like a coffee, please.' },
          { italian: 'Dovresti studiare di più.', translation: 'You should study more.' },
        ],
        note: 'vorrei, potrei, dovrei, potrebbe, potresti are the politest forms for requests, permission, and advice — essential in shops, restaurants, and offices.',
      },
    ],
  },
  {
    id: 'usage',
    title: 'Using the Modals',
    subtitle: 'Obligation, possibility, permission, desire — plus safety, negation, and questions',
    sections: [
      {
        heading: 'Part 9 — Dovere: obligation and advice',
        explanation: 'Dovere expresses strong obligation (must) or, in the condizionale, gentle advice (should).',
        bullets: [
          { text: 'Devo pagare il biglietto.', example: 'I must pay for the ticket. (obligation)' },
          { text: 'Devi andare dal medico.', example: 'You should go to the doctor. (advice)' },
          { text: 'Non devi fumare qui.', example: 'You must not smoke here. (prohibition)' },
        ],
        note: 'Non devo + infinitive = I must not / I shouldn\'t. It does NOT mean "I don\'t have to" (that is non devo-needed, better expressed with non è necessario).',
      },
      {
        heading: 'Part 10 — Potere: ability, permission, possibility',
        explanation: 'Potere is used for "can", "may", and "to be able to": physical ability, permission, and possibility.',
        bullets: [
          { text: 'So parlare un po\' d\'italiano, ma posso migliorare.', example: 'I know a little Italian, but I can improve.' },
          { text: 'Puoi uscire dopo i compiti.', example: 'You may go out after your homework. (permission)' },
          { text: 'Può darsi che piova. (possibility)', example: 'It may rain.' },
        ],
        note: '"Posso?" = "May I?" Use it when asking permission to enter, sit, smoke, use something, etc.',
      },
      {
        heading: 'Part 11 — Volere: desire and politeness',
        explanation: 'Volere is "to want". In the condizionale (vorrei, vorrebbe) it becomes the polite way to ask for something.',
        bullets: [
          { text: 'Voglio andare al cinema.', example: 'I want to go to the cinema.' },
          { text: 'Vuoi un bicchiere d\'acqua?', example: 'Do you want a glass of water?' },
          { text: 'Vorrei il conto, per favore.', example: 'I would like the bill, please.' },
        ],
        note: 'When you want to be polite, prefer "vorrei" over "voglio": Vorrei un caffè (polite) vs Voglio un caffè (direct).',
      },
      {
        heading: 'Part 12 — Negation, questions, and common patterns',
        explanation: 'Negation and questions work in the usual ways with modal verbs. The modal stays in the second position, and the infinitive follows.',
        bullets: [
          { text: 'Non posso venire oggi.', example: 'I can\'t come today.' },
          { text: 'Non dovevi dirglielo.', example: 'You shouldn\'t have told him.' },
          { text: 'Puoi aprire la finestra?', example: 'Can you open the window?' },
          { text: 'Cosa vuoi fare stasera?', example: 'What do you want to do tonight?' },
        ],
        patterns: ['Posso? = May I?', 'Non posso = I can\'t', 'Devo andare = I must go', 'Vorrei… = I would like…', 'Potrebbe…? = Could you…? (formal)', 'Dovresti… = You should…'],
        note: 'Like all verb helpers, the modal agrees with the subject and never changes for the infinitive that follows it.',
      },
    ],
  },
];

export const modaliExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Meet the Modal Verbs',
    instruction: 'Recognise dovere, potere, and volere in simple sentences.',
    questions: [
      { question: 'The three core modal verbs in Italian are:', options: ['dovere, potere, volere', 'essere, avere, fare', 'essere, stare, parlare', 'andare, venire, uscire'], answer: 'dovere, potere, volere', explanation: 'Modal verbs express obligation, possibility, and desire.' },
      { question: '"Devo" is the present form of:', options: ['dovere', 'potere', 'volere', 'dare'], answer: 'dovere', explanation: 'devo = I must (dovere).' },
      { question: '"Puoi" is the present form of:', options: ['potere', 'dovere', 'volere', 'partire'], answer: 'potere', explanation: 'puoi = you can (potere).' },
      { question: '"Voglio" is the present form of:', options: ['volere', 'dovere', 'potere', 'parlare'], answer: 'volere', explanation: 'voglio = I want (volere).' },
      { question: 'A modal verb is always followed by:', options: ['an infinitive', 'a past participle', 'an article', 'a preposition'], answer: 'an infinitive', explanation: 'Devo studiare, posso venire, vuole mangiare — modal + infinitive.' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Match the Meaning',
    instruction: 'Match each modal verb with its meaning.',
    pairs: [
      { left: 'dovere', right: 'must / have to' },
      { left: 'potere', right: 'can / may / be able to' },
      { left: 'volere', right: 'to want' },
      { left: 'Devo stare a casa', right: 'I must stay home' },
      { left: 'Posso uscire?', right: 'May I go out?' },
      { left: 'Voglio un gelato', right: 'I want an ice cream' },
    ],
    explanation: 'Check the first letter of the meaning: dovere → obligation, potere → possibility, volere → desire.',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Spot the Modal',
    instruction: 'Identify which word is the modal verb in each sentence.',
    questions: [
      { question: '"Devo chiamare Marco." — the modal is:', options: ['devo', 'chiamare', 'Marco', 'il'], answer: 'devo', explanation: 'devo (dovere) + chiamare.' },
      { question: '"La bambina vuole dormire." — the modal is:', options: ['vuole', 'bambina', 'dormire', 'la'], answer: 'vuole', explanation: 'vuole (volere) + dormire.' },
      { question: '"Possiamo venire con voi?" — the modal is:', options: ['possiamo', 'venire', 'con', 'voi'], answer: 'possiamo', explanation: 'possiamo (potere) + venire.' },
      { question: '"Non posso mangiare il pane." — "posso" is:', options: ['a modal verb', 'an infinitive', 'a noun', 'an adjective'], answer: 'a modal verb', explanation: 'posso = I can (potere).' },
      { question: 'Which verb is NOT a modal?', options: ['mangiare', 'dovere', 'potere', 'volere'], answer: 'mangiare', explanation: 'mangiare is a regular action verb, not a modal.' },
    ],
  },
  {
    id: 4,
    type: 'fillblank',
    level: 'Level 1 — Recognition',
    title: 'Modal + Infinitive Structure',
    instruction: 'Choose the modal that completes each sentence and its meaning.',
    questions: [
      { sentence: '___ (must) andare in ufficio.', options: ['Devo', 'Posso', 'Voglio', 'Sono'], answer: 'Devo', explanation: 'Devo + infinitive = I must.' },
      { sentence: '___ (can) parlare italiano.', options: ['Posso', 'Devo', 'Voglio', 'Ho'], answer: 'Posso', explanation: 'Posso + infinitive = I can.' },
      { sentence: '___ (want) un caffè, per favore.', options: ['Voglio', 'Devo', 'Posso', 'Sono'], answer: 'Voglio', explanation: 'Voglio + noun = I want.' },
      { sentence: 'Non ___ (must not) fumare qui.', options: ['devono', 'possono', 'vogliono', 'sono'], answer: 'devono', explanation: 'Non devono + infinitive = they must not.' },
      { sentence: '___ (may) entrare?', options: ['Posso', 'Devo', 'Voglio', 'Vado'], answer: 'Posso', explanation: 'Posso? = May I? (permission).' },
    ],
  },

  // LEVEL 2 — FORMATION
  {
    id: 5,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Present Tense of Dovere',
    instruction: 'Conjugate dovere in the present for each subject.',
    questions: [
      { sentence: 'Io ___ andare. (dovere)', options: ['devo', 'devi', 'deve', 'dobbiamo'], answer: 'devo', explanation: 'io devo.' },
      { sentence: 'Tu ___ studiare. (dovere)', options: ['devi', 'devo', 'deve', 'dovete'], answer: 'devi', explanation: 'tu devi.' },
      { sentence: 'Lei ___ chiamare il medico. (dovere)', options: ['deve', 'devi', 'devo', 'dobbiamo'], answer: 'deve', explanation: 'lui/lei deve.' },
      { sentence: 'Noi ___ partire presto. (dovere)', options: ['dobbiamo', 'dovete', 'devono', 'devo'], answer: 'dobbiamo', explanation: 'noi dobbiamo.' },
      { sentence: 'Voi ___ pagare il conto. (dovere)', options: ['dovete', 'dobbiamo', 'devono', 'devi'], answer: 'dovete', explanation: 'voi dovete.' },
      { sentence: 'Loro ___ tornare a casa. (dovere)', options: ['devono', 'dovevano', 'debbono', 'dove'], answer: 'devono', explanation: 'loro devono.' },
    ],
  },
  {
    id: 6,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Present Tense of Potere',
    instruction: 'Conjugate potere in the present for each subject.',
    questions: [
      { sentence: 'Io ___ (potere) aiutarti.', options: ['posso', 'puoi', 'può', 'possiamo'], answer: 'posso', explanation: 'io posso.' },
      { sentence: 'Tu ___ (potere) venire domani?', options: ['puoi', 'posso', 'può', 'possiamo'], answer: 'puoi', explanation: 'tu puoi.' },
      { sentence: 'Lui ___ (potere) fumare qui.', options: ['può', 'puoi', 'possono', 'potete'], answer: 'può', explanation: 'lui/lei può.' },
      { sentence: 'Noi ___ (potere) uscire stasera.', options: ['possiamo', 'potete', 'possono', 'può'], answer: 'possiamo', explanation: 'noi possiamo.' },
      { sentence: 'Voi ___ (potere) entrare.', options: ['potete', 'possiamo', 'possono', 'può'], answer: 'potete', explanation: 'voi potete.' },
      { sentence: 'Loro ___ (potere) dormire qui.', options: ['possono', 'potete', 'può', 'posso'], answer: 'possono', explanation: 'loro possono.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Present Tense of Volere',
    instruction: 'Conjugate volere in the present for each subject.',
    questions: [
      { sentence: 'Io ___ (volere) un cappuccino.', options: ['voglio', 'vuoi', 'vuole', 'vogliamo'], answer: 'voglio', explanation: 'io voglio.' },
      { sentence: 'Tu ___ (volere) venire?', options: ['vuoi', 'voglio', 'vuole', 'vogliamo'], answer: 'vuoi', explanation: 'tu vuoi.' },
      { sentence: 'Lui ___ (volere) mangiare la pizza.', options: ['vuole', 'vuoi', 'vogliamo', 'volete'], answer: 'vuole', explanation: 'lui/lei vuole.' },
      { sentence: 'Noi ___ (volere) vedere un film.', options: ['vogliamo', 'volete', 'vogliono', 'vuole'], answer: 'vogliamo', explanation: 'noi vogliamo.' },
      { sentence: 'Voi ___ (volere) un caffè?', options: ['volete', 'vogliamo', 'vogliono', 'vuole'], answer: 'volete', explanation: 'voi volete.' },
      { sentence: 'Loro ___ (volere) dormire.', options: ['vogliono', 'volete', 'vogliamo', 'vuole'], answer: 'vogliono', explanation: 'loro vogliono.' },
    ],
  },
  {
    id: 8,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Match the Subject',
    instruction: 'Match each subject pronoun with the correct present form.',
    pairs: [
      { left: 'io', right: 'devo / posso / voglio' },
      { left: 'tu', right: 'devi / puoi / vuoi' },
      { left: 'noi', right: 'dobbiamo / possiamo / vogliamo' },
      { left: 'loro', right: 'devono / possono / vogliono' },
      { left: 'lui/lei', right: 'deve / può / vuole' },
      { left: 'voi', right: 'dovete / potete / volete' },
    ],
    explanation: 'Learn the pattern of the three modals together: -o (io), -i (tu), -e (lui), -amo/-ete/-ono for the rest.',
  },

  // LEVEL 3 — CHOOSING THE RIGHT MODAL
  {
    id: 9,
    type: 'multiple',
    level: 'Level 3 — Choosing the Right Modal',
    title: 'Dovere, Potere, or Volere?',
    instruction: 'Choose the modal that fits the situation.',
    questions: [
      { question: 'Rules on the wall say you ___ smoke here. (it is forbidden)', options: ['non devi', 'non puoi', 'non vuoi', 'non hai'], answer: 'non puoi', explanation: 'Prohibition = non puoi + infinitive.' },
      { question: 'It is your driving test tomorrow — you ___ drive well.', options: ['devi', 'puoi', 'vuoi', 'sei'], answer: 'devi', explanation: 'Obligation/necessity = devi.' },
      { question: '"I want a chocolate" = "___ un cioccolato."', options: ['Voglio', 'Devo', 'Posso', 'Sono'], answer: 'Voglio', explanation: 'Desire = volere.' },
      { question: '"___ aprire la finestra?" (asking your boss politely)', options: ['Potrei', 'Devo', 'Voglio', 'Ho'], answer: 'Potrei', explanation: 'Potrei? = polite "Could I?"' },
      { question: 'It is raining and you have no umbrella — you ___ take shelter.', options: ['devi', 'puoi non', 'vuoi', 'potrei'], answer: 'devi', explanation: 'Necessity/obligation = devi.' },
    ],
  },
  {
    id: 10,
    type: 'fillblank',
    level: 'Level 3 — Choosing the Right Modal',
    title: 'Choose the Modal in Context',
    instruction: 'Complete each sentence with the correct modal form.',
    questions: [
      { sentence: 'Scusa, ___ usare il tuo mouse?', options: ['posso', 'devo', 'voglio', 'dovrei'], answer: 'posso', explanation: 'Asking permission: posso?' },
      { sentence: 'Ho sete. ___ una bottiglia d\'acqua.', options: ['Voglio', 'Devo', 'Posso', 'Sarò'], answer: 'Voglio', explanation: 'Desire: voglio una bottiglia.' },
      { sentence: 'Il treno parte tra cinque minuti. ___ correre!', options: ['Dobbiamo', 'Possiamo', 'Vogliamo', 'Siamo'], answer: 'Dobbiamo', explanation: 'Obligation: dobbiamo correre.' },
      { sentence: 'Sei libero? ___ venire alla festa stasera?', options: ['Puoi', 'Devi', 'Vuoi non', 'Hai'], answer: 'Puoi', explanation: 'Ability/possibility: puoi venire?' },
      { sentence: 'Mi scusi, ___ (volere, condizionale) un chilo di mele.', options: ['vorrei', 'voglio', 'vuoi', 'vorrò'], answer: 'vorrei', explanation: 'Polite wish: Vorrei un chilo di mele.' },
    ],
  },

  // LEVEL 4 — MODAL + INFINITIVE
  {
    id: 11,
    type: 'multiple',
    level: 'Level 4 — Modal + Infinitive',
    title: 'Modal + Infinitive Placement',
    instruction: 'Choose the correct way to combine the modal with the infinitive.',
    questions: [
      { question: 'Correct structure for "I must study":', options: ['Devo studiare', 'Devo studio', 'Studiare devo io', 'Studio devo'], answer: 'Devo studiare', explanation: 'Modal conjugated + infinitive directly after.' },
      { question: 'Correct for "Can you come?":', options: ['Puoi venire?', 'Vieni puoi?', 'Puoi vieni?', 'Venire puoi tu?'], answer: 'Puoi venire?', explanation: 'Puoi + venire.' },
      { question: 'Correct for "They want to leave":', options: ['Vogliono partire', 'Partire vogliono', 'Vogliono partono', 'Vogliono partiremo'], answer: 'Vogliono partire', explanation: 'Vogliono + partire.' },
      { question: 'Correct for "I couldn\'t eat":', options: ['Non ho potuto mangiare', 'Non potevo mangiare solo', 'Non potuto mangiare ho', 'Non ho mangiato poter(e)'], answer: 'Non ho potuto mangiare', explanation: 'Passato prossimo: ho potuto + mangiare.' },
      { question: 'Which order is correct?', options: ['devo / prima / studiare', 'studiare / prima / devo', 'prima / studiare / devo', 'devo / studiare / prima'], answer: 'devo / studiare / prima', explanation: 'Adverbs like prima can follow the infinitive: Devo studiare prima.' },
    ],
  },
  {
    id: 12,
    type: 'wordorder',
    level: 'Level 4 — Modal + Infinitive',
    title: 'Build the Sentence',
    instruction: 'Put the words in the correct order to make a correct sentence.',
    questions: [
      { words: ['devo', 'studiare', 'io'], answer: 'io devo studiare', explanation: 'io + devo + infinitive.' },
      { words: ['posso', 'entrare', '?'], answer: 'posso entrare ?', explanation: 'Question: posso entrare? (subject omitted).' },
      { words: ['vogliamo', 'vedere', 'un', 'film'], answer: 'vogliamo vedere un film', explanation: 'vogliamo + vedere + un film.' },
      { words: ['non', 'possono', 'fumare', 'qui'], answer: 'non possono fumare qui', explanation: 'non + possono + fumare + qui.' },
      { words: ['vorrei', 'un', 'caffè', 'per favore'], answer: 'vorrei un caffè per favore', explanation: 'Polite request: vorrei + noun.' },
    ],
  },

  // LEVEL 5 — MEANINGS & SHADES
  {
    id: 13,
    type: 'multiple',
    level: 'Level 5 — Meanings & Shades',
    title: 'Must, Should, Can',
    instruction: 'Choose the modal that best expresses the meaning in italics.',
    questions: [
      { question: '"You ___ see the doctor." (strong recommendation)', options: ['devi', 'puoi', 'vuoi', 'hai'], answer: 'devi', explanation: 'devi + infinitive = strong advice.' },
      { question: '"We ___ leave now, or we\'ll be late." (obligation)', options: ['dobbiamo', 'possiamo', 'vogliamo', 'siamo'], answer: 'dobbiamo', explanation: 'Obligation = dobbiamo.' },
      { question: '"She ___ speak three languages." (ability)', options: ['può', 'deve', 'vuole', 'ha'], answer: 'può', explanation: 'Can/be able to = può.' },
      { question: '"I ___ like a tea instead of coffee." (polite)', options: ['vorrei', 'voglio', 'devo', 'può'], answer: 'vorrei', explanation: 'vorrei = polite form of voglio.' },
      { question: '"You ___ be tired after such a long trip." (probability)', options: ['devi', 'vuoi', 'sei', 'hai'], answer: 'devi', explanation: 'dovere also indicates logical deduction: Devi essere stanco.' },
    ],
  },
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 5 — Meanings & Shades',
    title: 'Shades of Meaning',
    instruction: 'Fill in the best modal or modal expression.',
    questions: [
      { sentence: 'Scusi, ___ (potere, condizionale) indicarmi la stazione?', options: ['potrebbe', 'potrei', 'può', 'potrà'], answer: 'potrebbe', explanation: 'Polite you-form: Potrebbe (Lei)?' },
      { sentence: 'Non ___ (potere, neg) dormire bene.', options: ['posso', 'devo', 'voglio', 'ho'], answer: 'posso', explanation: 'Non posso dormire = I can\'t sleep.' },
      { sentence: 'Da domani ___ (dovere) alzarmi prima.', options: ['dovrò', 'devo', 'dovrei', 'posso'], answer: 'dovrò', explanation: 'Future obligation: dovrò alzarmi.' },
      { sentence: 'Se hai un minuto, ___ (potere, cond) aiutarmi?', options: ['potresti', 'potresti non', 'puoi', 'potrai'], answer: 'potresti', explanation: 'Polite: Potresti aiutarmi?' },
      { sentence: 'Il bambino non ___ dormire senza il suo orsacchiotto. (volere)', options: ['vuole', 'voglio', 'può', 'deve'], answer: 'vuole', explanation: 'Non vuole dormire = he doesn\'t want to sleep.' },
    ],
  },

  // LEVEL 6 — PAST: PASSATO PROSSIMO & IMPERFETTO
  {
    id: 15,
    type: 'fillblank',
    level: 'Level 6 — Passato prossimo & Imperfetto',
    title: 'Passato prossimo of the Modals',
    instruction: 'Complete the passato prossimo with ho/hai/ha… + dovuto/potuto/voluto.',
    questions: [
      { sentence: 'Ieri ___ dovuto lavorare fino a tardi. (io)', options: ['ho', 'sono', 'avrei', 'ha'], answer: 'ho', explanation: 'io ho dovuto.' },
      { sentence: 'Non ___ potuto venire al cinema. (io)', options: ['ho', 'sono', 'avrei', 'avevo'], answer: 'ho', explanation: 'non ho potuto.' },
      { sentence: 'Marco ___ voluto aspettare. (lui)', options: ['ha', 'è', 'aveva', 'avrebbe'], answer: 'ha', explanation: 'lui ha voluto.' },
      { sentence: 'Tu ___ dovuto stare a casa? (tu)', options: ['hai', 'sei', 'hai dovuto non', 'avevi'], answer: 'hai', explanation: 'tu hai dovuto.' },
      { sentence: 'Noi ___ potuto prenotare il tavolo.', options: ['abbiamo', 'siamo', 'avevamo', 'saremmo'], answer: 'abbiamo', explanation: 'noi abbiamo potuto.' },
    ],
  },
  {
    id: 16,
    type: 'multiple',
    level: 'Level 6 — Passato prossimo & Imperfetto',
    title: 'Imperfetto or Passato prossimo?',
    instruction: 'Choose dovevo / potevo / volevo (imperfetto) or ho dovuto etc. (passato prossimo).',
    questions: [
      { question: '"Non ___ venire ieri, avevo un impegno." (one completed fact)', options: ['sono potuto', 'ho potuto non', 'potrei', 'posso'], answer: 'sono potuto', explanation: 'Both "non ho potuto" and "non sono potuto" are used; "non sono potuto venire" is natural with motion verbs.' },
      { question: '"Da piccolo ___ andare a letto presto." (habit)', options: ['dovevo', 'ho dovuto non', 'dovrò', 'dovrei'], answer: 'dovevo', explanation: 'Imperfetto for a repeated past habit: dovevo.' },
      { question: '"Jeri ___ comprare il pane, ma il negozio era chiuso." (one completed attempt)', options: ['ho dovuto', 'dovevo', 'devo', 'dovrò'], answer: 'ho dovuto', explanation: 'Passato prossimo for a finished action: ho dovuto comprare.' },
      { question: '"Non ___ mangiare la sera." (in general, ongoing)', options: ['volevo', 'voglio', 'vorrei', 'ho voluto'], answer: 'volevo', explanation: 'imperfetto: non volevo = I didn\'t want to (in general).' },
      { question: 'Which is a passato prossimo form?', options: ['ho potuto', 'potevo', 'poterò', 'potrei'], answer: 'ho potuto', explanation: 'ho potuto = one-time completed "I was able to".' },
    ],
  },
  {
    id: 17,
    type: 'fillblank',
    level: 'Level 6 — Passato prossimo & Imperfetto',
    title: 'Imperfetto of the Modals',
    instruction: 'Complete with dovevo / potevo / volevo (imperfetto).',
    questions: [
      { sentence: 'Da piccolo ___ (dovere) aiutare nei campi.', options: ['dovevo', 'devo', 'dovrò', 'dovrei'], answer: 'dovevo', explanation: 'repeated habit: dovevo.' },
      { sentence: 'Quando abitavo a Roma, ___ (potere) andare al cinema spesso.', options: ['potevo', 'posso', 'potrò', 'potrei'], answer: 'potevo', explanation: 'ongoing ability in the past: potevo.' },
      { sentence: 'Non ___ (volere) alzarmi presto la domenica.', options: ['volevo', 'voglio', 'vorrei', 'vorrò'], answer: 'volevo', explanation: 'ongoing desire: volevo.' },
      { sentence: 'Da studente, alla sera ___ (dovere) fare i compiti.', options: ['dovevo', 'devo', 'dovrò', 'dovrei'], answer: 'dovevo', explanation: 'habit in the past: dovevo.' },
      { sentence: 'Mia madre non ___ (potere) lasciare il lavoro prima delle sei.', options: ['poteva', 'può', 'potrà', 'potrebbe'], answer: 'poteva', explanation: 'lui/lei imperfetto: poteva.' },
    ],
  },

  // LEVEL 7 — FUTURO & CONDIZIONALE
  {
    id: 18,
    type: 'multiple',
    level: 'Level 7 — Futuro & Condizionale',
    title: 'Future of the Modals',
    instruction: 'Choose the correct future forms dovrò, potrò, vorrò.',
    questions: [
      { question: 'Domani ___ (io, dovere) partire presto.', options: ['dovrò', 'devo', 'dovevo', 'dovrei'], answer: 'dovrò', explanation: 'Future: dovrò.' },
      { question: '___ (tu, potere) aiutarmi dopo il lavoro?', options: ['potrai', 'puoi', 'potevi', 'potresti'], answer: 'potrai', explanation: 'Future: potrai.' },
      { question: 'Lui ___ (volere) ... ma non è sicuro. (future, want)', options: ['vorrà', 'vuole', 'voleva', 'vorrebbe'], answer: 'vorrà', explanation: 'Future: vorrà.' },
      { question: 'Il futuro di "dovere" (io) è:', options: ['dovrò', 'dovederò', 'dovrerei', 'dovro'], answer: 'dovrò', explanation: 'dovere → dovrò.' },
      { question: 'Il futuro di "potere" (noi) è:', options: ['potremo', 'poteremo', 'potteremo', 'potrassimo'], answer: 'potremo', explanation: 'potere → potremo.' },
    ],
  },
  {
    id: 19,
    type: 'fillblank',
    level: 'Level 7 — Futuro & Condizionale',
    title: 'Condizionale: would, could, should',
    instruction: 'Complete with dovrei / potrei / vorrei (condizionale).',
    questions: [
      { sentence: '___ (io, dovere) telefonare a mia nonna.', options: ['Dovrei', 'Devo', 'Dovrò', 'Dovevo'], answer: 'Dovrei', explanation: 'Dovrei = I should (advice).' },
      { sentence: '___ (io, potere) scambiare il tavolo?', options: ['Potrei', 'Posso', 'Potrò', 'Potevo'], answer: 'Potrei', explanation: 'Potrei? = polite Could I?' },
      { sentence: '___ (io, volere) il menù, per favore.', options: ['Vorrei', 'Voglio', 'Vorrò', 'Volevo'], answer: 'Vorrei', explanation: 'Vorrei = I would like (polite).' },
      { sentence: 'Tu ___ (dovere) riposarti di più.', options: ['dovresti', 'devi', 'dovrai', 'dovevi'], answer: 'dovresti', explanation: 'Dovresti = you should (advice).' },
      { sentence: 'Signora, ___ (potere) cambiarmi... mi perdoni, ___ (potere, Lei) chiamare un taxi?', options: ['potrebbe', 'potresti', 'potrai', 'può'], answer: 'potrebbe', explanation: 'Potrebbe (Lei) = polite formal Could you?' },
    ],
  },
  {
    id: 20,
    type: 'translation',
    level: 'Level 7 — Futuro & Condizionale',
    title: 'Translate with Modals',
    instruction: 'Choose the correct English equivalent.',
    direction: 'it-en',
    questions: [
      { sentence: 'Vorrei un caffè, per favore.', options: ['I would like a coffee, please', 'I want to make coffee, please', 'I will make a coffee now', 'I have made coffee'], answer: 'I would like a coffee, please', explanation: 'Vorrei = polite "would like".' },
      { sentence: 'Potresti chiudere la porta?', options: ['Could you close the door?', 'You have closed the door?', 'Will you close the door behind?', 'You will have to close it'], answer: 'Could you close the door?', explanation: 'Potresti? = polite "Could you?"' },
      { sentence: 'Dovremmo partire adesso.', options: ['We should leave now', 'We can leave now', 'We want to leave now', 'We will leave later'], answer: 'We should leave now', explanation: 'Dovremmo = we should.' },
      { sentence: 'Non ho potuto dormire bene.', options: ['I couldn\'t sleep well', 'I don\'t want to sleep well', 'I won\'t sleep well', 'I should not sleep well'], answer: 'I couldn\'t sleep well', explanation: 'Non ho potuto = I couldn\'t.' },
      { sentence: 'Domani dovrò lavorare.', options: ['Tomorrow I will have to work', 'Tomorrow I can work', 'Tomorrow I want to work', 'Tomorrow I should have worked'], answer: 'Tomorrow I will have to work', explanation: 'Dovrò = I will have to.' },
    ],
  },

  // LEVEL 8 — NEGATION, QUESTIONS & MIXED
  {
    id: 21,
    type: 'multiple',
    level: 'Level 8 — Negation, Questions & Mixed',
    title: 'Negation and Questions',
    instruction: 'Choose the correct negation or question with a modal.',
    questions: [
      { question: '"I can\'t come tonight" =', options: ['Non posso venire stasera', 'Non devo venire stasera', 'Non voglio venire stasera', 'Non sono venuto stasera'], answer: 'Non posso venire stasera', explanation: 'non + posso + infinitive.' },
      { question: '"May I sit here?" =', options: ['Posso sedermi qui?', 'Devo sedermi qui?', 'Sedermi devo qui?', 'Mi siedo qui posso?'], answer: 'Posso sedermi qui?', explanation: 'Posso? = May I?' },
      { question: '"You shouldn\'t smoke so much" =', options: ['Non dovresti fumare tanto', 'Non puoi fumare tanto', 'Non vuoi fumare tanto', 'Fumare non devi'], answer: 'Non dovresti fumare tanto', explanation: 'dovresti neg = shouldn\'t.' },
      { question: '"Will you be able to help?" =', options: ['Potrai aiutare?', 'Potresti aiutare?', 'Puoi aiutare?', 'Aiutare potrai?'], answer: 'Potrai aiutare?', explanation: 'Question with future modal: potrai?' },
      { question: '"I don\'t want to eat pizza" =', options: ['Non voglio mangiare la pizza', 'Non posso mangiare la pizza', 'Non devo mangiare la pizza', 'Mangiare non voglio'], answer: 'Non voglio mangiare la pizza', explanation: 'non + voglio + infinitive.' },
    ],
  },
  {
    id: 22,
    type: 'wordorder',
    level: 'Level 8 — Negation, Questions & Mixed',
    title: 'Build Sentences with Modals',
    instruction: 'Put the words in the correct order.',
    questions: [
      { words: ['non', 'posso', 'venire', 'oggi'], answer: 'non posso venire oggi', explanation: 'non + posso + venire + oggi.' },
      { words: ['puoi', 'aprire', 'la', 'finestra', '?'], answer: 'puoi aprire la finestra ?', explanation: 'puoi + aprire la finestra?' },
      { words: ['vorrei', 'il', 'conto', 'per favore'], answer: 'vorrei il conto per favore', explanation: 'vorrei + il conto + per favore.' },
      { words: ['dovreste', 'venire', 'presto'], answer: 'dovreste venire presto', explanation: 'voi dovreste + venire presto.' },
      { words: ['non', 'ha', 'potuto', 'telefonare'], answer: 'non ha potuto telefonare', explanation: 'non + ha potuto + telefonare.' },
    ],
  },
  {
    id: 23,
    type: 'matching',
    level: 'Level 8 — Negation, Questions & Mixed',
    title: 'Match the Use',
    instruction: 'Match each modal expression with its use.',
    pairs: [
      { left: 'Posso?', right: 'permission' },
      { left: 'Devo', right: 'obligation' },
      { left: 'Vorrei', right: 'polite request' },
      { left: 'Dovresti', right: 'advice' },
      { left: 'Non posso', right: 'prohibition / impossibility' },
      { left: 'Vuole', right: 'desire' },
    ],
    explanation: 'Learn the everyday set: Posso? (permission), devo (obligation), vorrei (polite wish), dovresti (advice).',
  },
  {
    id: 24,
    type: 'multiple',
    level: 'Level 8 — Negation, Questions & Mixed',
    title: 'Mixed Modal Tenses',
    instruction: 'Choose the form that fits the tense required by the time expression.',
    questions: [
      { question: '"Ieri ___ dovuto andare a casa."', options: ['ho', 'ho avuto', 'avevo', 'avrò'], answer: 'ho', explanation: 'Ieri + passato prossimo: ho dovuto.' },
      { question: '"Domani ___ (io, volere) provare il nuovo ristorante."', options: ['vorrò', 'voglio', 'vorrei', 'volevo'], answer: 'vorrò', explanation: 'Domani + futuro: vorrò.' },
      { question: '"Ora ___ (io, avere voglia di) ... voglio andare al mare."', options: ['voglio', 'vorrò', 'vorrei', 'volevo'], answer: 'voglio', explanation: 'Present desire: voglio.' },
      { question: '"Quando ero piccolo, ___ (io, potere) giocare in strada."', options: ['potevo', 'posso', 'potrei', 'potrò'], answer: 'potevo', explanation: 'Past habit: imperfetto potevo.' },
      { question: '"Secondo me, tu ___ (dovere) riposare." (advice)', options: ['dovresti', 'devi', 'dovrai', 'dovevi'], answer: 'dovresti', explanation: 'Advice uses the condizionale: dovresti.' },
    ],
  },
  {
    id: 25,
    type: 'fillblank',
    level: 'Level 8 — Negation, Questions & Mixed',
    title: 'Complete the Modal Sentence',
    instruction: 'Choose the correct modal form to complete each sentence.',
    questions: [
      { sentence: '___, mi aiuti per favore? (formal)', options: ['Potrebbe', 'Potresti', 'Poteva', 'Potrà'], answer: 'Potrebbe', explanation: 'Lei-form polite: Potrebbe?' },
      { sentence: 'Non ___ venire alla festa. (lui, poter, neg)', options: ['può', 'deve', 'vuole', 'potrà'], answer: 'può', explanation: 'lui non può venire.' },
      { sentence: '___ un bicchiere d\'acqua, per cortesia. (io, volere, polite)', options: ['Vorrei', 'Voglio', 'Vorrò', 'Volevo'], answer: 'Vorrei', explanation: 'Vorrei = polite request.' },
      { sentence: 'Tu ___ andare dal dentista questo mese. (advice)', options: ['dovresti', 'devi', 'dovrai', 'dovevi'], answer: 'dovresti', explanation: 'Dovresti = you should (advice).' },
      { sentence: 'Che cosa ___ fare stasera? (tu, volere)', options: ['vuoi', 'vuole', 'vogliono', 'vogliamo'], answer: 'vuoi', explanation: 'tu vuoi.' },
    ],
  },

  // LEVEL 9 — REAL-LIFE COMMUNICATION (STORIES)
  {
    id: 26,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Permission',
    storyTitle: 'Posso uscire?',
    story: 'Anna: Mamma, posso uscire stasera con gli amici?\n\nMamma: Certo che puoi! Ma devi tornare prima delle undici.\n\nAnna: Posso prendere la macchina?\n\nMamma: No, non puoi guidare: hai solo diciassette anni. Devi prendere l\'autobus.\n\nAnna: Voglio andare al cinema, poi tutti vogliono mangiare una pizza.\n\nMamma: Benissimo, divertitevi! Ma non devi mangiare troppo.\n\nAnna: Prometto! Posso usare il tuo telefono per chiamare Luca?\n\nMamma: Sì, cerca di tornare in tempo.',
    vocab: [
      { word: 'posso', meaning: 'I can / may I (potere)' },
      { word: 'devi', meaning: 'you must (dovere)' },
      { word: 'voglio', meaning: 'I want (volere)' },
      { word: 'vogliono', meaning: 'they want (volere)' },
      { word: 'prometto', meaning: 'I promise' },
    ],
    translation: 'Anna: Mum, can I go out tonight with my friends?\n\nMum: Of course you can! But you must be back before eleven.\n\nAnna: Can I take the car?\n\nMum: No, you can\'t drive: you\'re only seventeen. You must take the bus.\n\nAnna: I want to go to the cinema, then everyone wants to eat a pizza.\n\nMum: Great, have fun! But you mustn\'t eat too much.\n\nAnna: I promise! Can I use your phone to call Luca?\n\nMum: Yes, try to be back on time.',
    questions: [
      { question: 'Does the mum let Anna go out?', options: ['Yes', 'No', 'Only on Sunday', 'She doesn\'t answer'], answer: 'Yes', explanation: '"Certo che puoi!" → permission.' },
      { question: 'What time must Anna be back?', options: ['Before eleven', 'At midnight', 'Before nine', 'At ten'], answer: 'Before eleven', explanation: '"Devi tornare prima delle undici."' },
      { question: 'Why can\'t Anna drive?', options: ['She is only 17', 'She is tired', 'The car is broken', 'She can\'t drive'], answer: 'She is only 17', explanation: '"hai solo diciassette anni."' },
      { question: 'What does Anna want to eat?', options: ['Pizza', 'Pasta', 'Gelato', 'Panini'], answer: 'Pizza', explanation: '"tutti vogliono mangiare una pizza."' },
      { question: 'Find two modal verbs for obligation in the dialogue.', options: ['devi and devi non', 'voglio and posso', 'posso and può', 'chiamare and tornare'], answer: 'devi and devi non', explanation: '"Devi tornare..." and "Non devi mangiare" → dovere.' },
      { question: 'Write the question you would ask to get permission to go out.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Posso uscire? Any correct "Posso…?" question is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Obligation and Advice',
    storyTitle: 'Devi o dovresti?',
    story: 'Dottore: Buongiorno, signora Rosa. Deve perdere qualche chilo.\n\nRosa: Lo so. Dovrei fare più sport, ma non ho tempo.\n\nDottore: Deve mangiare più verdura e deve bere più acqua.\n\nRosa: Posso mangiare il pane? Voglio mangiarlo ogni giorno.\n\nDottore: Puoi mangiarlo, ma non devi esagerare. Dovresti fare una passeggiata ogni sera.\n\nRosa: Posso camminare anche la mattina?\n\nDottore: Certo, puoi camminare quando vuoi! Ma deve continuare con la medicina.',
    vocab: [
      { word: 'deve', meaning: 'you must (formal Lei)' },
      { word: 'dovrei', meaning: 'I should (advice)' },
      { word: 'dovresti', meaning: 'you should' },
      { word: 'esagerare', meaning: 'to exaggerate / overdo' },
      { word: 'passeggiata', meaning: 'walk/stroll' },
    ],
    translation: 'Doctor: Good morning, Mrs. Rosa. You must lose some weight.\n\nRosa: I know. I should do more sport, but I don\'t have time.\n\nDoctor: You must eat more vegetables and you must drink more water.\n\nRosa: Can I eat bread? I want to eat it every day.\n\nDoctor: You can eat it, but you must not overdo it. You should take a walk every evening.\n\nRosa: Can I walk in the morning too?\n\nDoctor: Of course, you can walk whenever you want! But you must continue with the medicine.',
    questions: [
      { question: 'What must Rosa do about her weight?', options: ['Lose some weight', 'Gain weight', 'Eat more sweets', 'Drink less water'], answer: 'Lose some weight', explanation: '"Deve perdere qualche chilo."' },
      { question: 'What does the doctor say about bread?', options: ['You can eat it, but not too much', 'You must not eat bread', 'You must eat bread every day', 'Bread is forbidden'], answer: 'You can eat it, but not too much', explanation: '"Puoi mangiarlo, ma non devi esagerare."' },
      { question: 'Which modal expresses the doctor\'s advice?', options: ['dovresti', 'devo', 'posso', 'voglio'], answer: 'dovresti', explanation: '"Dovresti fare una passeggiata" = you should (advice).' },
      { question: 'What does "Deve" mean here?', options: ['You (formal) must', 'You (informal) should', 'I must', 'They must'], answer: 'You (formal) must', explanation: 'Deve = Lei must (formal).' },
      { question: 'Rosa says "Posso mangiare il pane?" — this asks for:', options: ['permission', 'obligation', 'desire', 'advice'], answer: 'permission', explanation: 'Posso? = May I? (permission).' },
      { question: 'Write one piece of advice using "dovresti".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Dovresti fare una passeggiata. Any correct advice is accepted.' },
    ],
  },
  {
    id: 28,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Polite Requests',
    storyTitle: 'Vorrei e Potrebbe',
    story: 'Cliente: Buongiorno, vorrei un appartamento in affitto.\n\nAgente: Certo! Potrebbe dirmi il suo budget mensile?\n\nCliente: Vorrei spendere al massimo seicento euro al mese.\n\nAgente: Potrebbe essere possibile con questa cifra, ma deve scegliere tra centro e periferia.\n\nCliente: Posso vedere un appartamento questo weekend?\n\nAgente: Preferirei mostrarle due o tre opzioni. Può venire domenica alle dieci?\n\nCliente: Sì, posso. Vorrei anche sapere se le spese sono incluse.\n\nAgente: Sono incluse. Potrebbe portare i documenti domenica?',
    vocab: [
      { word: 'vorrei', meaning: 'I would like (volere, polite)' },
      { word: 'potrebbe', meaning: 'could you (Lei, polite)' },
      { word: 'budget', meaning: 'budget' },
      { word: 'affitto', meaning: 'rent' },
      { word: 'periferia', meaning: 'outskirts' },
    ],
    translation: 'Client: Good morning, I would like an apartment to rent.\n\nAgent: Certainly! Could you tell me your monthly budget?\n\nClient: I would like to spend at most six hundred euros a month.\n\nAgent: It could be possible with that amount, but you must choose between centre and outskirts.\n\nClient: Can I see an apartment this weekend?\n\nAgent: I would prefer to show you two or three options. Can you come on Sunday at ten?\n\nClient: Yes, I can. I would also like to know if the expenses are included.\n\nAgent: They are included. Could you bring the documents on Sunday?',
    questions: [
      { question: 'What does the client want?', options: ['An apartment to rent', 'A house to buy', 'A hotel room', 'A shared room'], answer: 'An apartment to rent', explanation: '"vorrei un appartamento in affitto."' },
      { question: 'What is the client\'s maximum budget?', options: ['600 euros a month', '300 euros a month', '900 euros a month', 'No budget'], answer: '600 euros a month', explanation: '"Vorrei spendere al massimo seicento euro al mese."' },
      { question: 'What must the client choose between?', options: ['Centre and outskirts', 'City and country', 'Two and three rooms', 'Old and new building'], answer: 'Centre and outskirts', explanation: '"deve scegliere tra centro e periferia."' },
      { question: 'The polite "would like" used by the client is:', options: ['vorrei', 'voglio', 'vuole', 'vogliamo'], answer: 'vorrei', explanation: 'Vorrei = polite form of volere.' },
      { question: '"Potrebbe…?" here is:', options: ['a polite formal request', 'a past statement', 'an obligation', 'a desire'], answer: 'a polite formal request', explanation: 'Potrebbe (Lei) = Could you?' },
      { question: 'Write a polite request you could say to an estate agent.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vorrei vedere un appartamento. Any polite request is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'Mixed Modals in Action',
    storyTitle: 'Un giorno a Milano',
    story: 'Lucia: Cosa vuoi fare oggi?\n\nMarco: Vorrei visitare il Duomo, anche se dobbiamo camminare molto.\n\nLucia: Possiamo prendere la metro, non dobbiamo camminare!\n\nMarco: Vero! Posso consultare l\'app della metro. Dobbiamo scendere a Duomo.\n\nLucia: Posso pagare con la carta?\n\nMarco: Sì, puoi. Io devo comprare un biglietto perché ho la tessera.\n\nLucia: Dopo vorrei mangiare un gelato. Puoi aiutarmi a trovare una gelateria?\n\nMarco: Certo, posso! Dovresti provare il pistacchio: è famoso qui.',
    vocab: [
      { word: 'vuoi', meaning: 'you want (volere)' },
      { word: 'vorrei', meaning: 'I would like (polite)' },
      { word: 'dobbiamo', meaning: 'we must (dovere)' },
      { word: 'scendere', meaning: 'to get off (public transport)' },
      { word: 'tessera', meaning: 'travel card' },
      { word: 'gelateria', meaning: 'ice-cream shop' },
    ],
    translation: 'Lucia: What do you want to do today?\n\nMarco: I would like to visit the Duomo, even though we must walk a lot.\n\nLucia: We can take the metro, we don\'t have to walk!\n\nMarco: True! I can check the metro app. We must get off at Duomo.\n\nLucia: Can I pay with card?\n\nMarco: Yes, you can. I must buy a ticket because I have the travel card.\n\nLucia: Afterwards I would like to eat an ice cream. Can you help me find an ice-cream shop?\n\nMarco: Of course I can! You should try the pistachio: it\'s famous here.',
    questions: [
      { question: 'What would Marco like to visit?', options: ['The Duomo', 'The museum', 'The castle', 'The park'], answer: 'The Duomo', explanation: '"Vorrei visitare il Duomo."' },
      { question: 'How can they avoid walking a lot?', options: ['By taking the metro', 'By taking a taxi', 'By staying home', 'By renting a bike'], answer: 'By taking the metro', explanation: '"Possiamo prendere la metro."' },
      { question: 'Why must Marco buy a ticket?', options: ['Because of his travel card', 'Because he is a tourist', 'Because he wants to', 'Lucia asked him to'], answer: 'Because of his travel card', explanation: '"Devo comprare un biglietto perché ho la tessera."' },
      { question: '"Dovresti provare il pistacchio" is:', options: ['advice', 'obligation', 'permission', 'a wish'], answer: 'advice', explanation: 'Dovresti = you should (advice).' },
      { question: 'The modal "dobbiamo" expresses:', options: ['obligation', 'permission', 'desire', 'probability'], answer: 'obligation', explanation: 'Dobbiamo = we must.' },
      { question: 'Write what you would like to do today using "vorrei".', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Vorrei visitare il Duomo. Any correct sentence with vorrei is accepted.' },
    ],
  },

  // LEVEL 10 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 10 — Final Proficiency Test',
    title: 'Modal Verbs Mastery Test',
    instruction: 'Answer all the questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Recognition
      { question: 'The three core modal verbs are:', options: ['dovere, potere, volere', 'essere, avere, fare', 'andare, venire, stare', 'parlare, mangiare, dormire'], answer: 'dovere, potere, volere' },
      { question: 'A modal verb is followed by:', options: ['an infinitive', 'a past participle', 'a noun only', 'a preposition'], answer: 'an infinitive' },
      // Present forms
      { question: 'Devo, devi, deve are the present of:', options: ['dovere', 'potere', 'volere', 'dare'], answer: 'dovere' },
      { question: 'Posso, puoi, può are the present of:', options: ['potere', 'dovere', 'volere', 'parlare'], answer: 'potere' },
      { question: 'Voglio, vuoi, vuole are the present of:', options: ['volere', 'dovere', 'potere', 'venire'], answer: 'volere' },
      { question: '"Noi ___ partire." (dovere)', options: ['dobbiamo', 'dovete', 'devono', 'devo'], answer: 'dobbiamo' },
      { question: '"Loro ___ dormire." (potere)', options: ['possono', 'potete', 'può', 'posso'], answer: 'possono' },
      { question: 'Complete: "Che cosa ___ fare stasera?" (tu, volere)', options: ['vuoi', 'vuole', 'voglio', 'vogliono'], answer: 'vuoi' },
      // Choosing meaning
      { question: '"Devo" is used for:', options: ['obligation', 'permission', 'desire', 'probability only'], answer: 'obligation' },
      { question: '"Posso uscire?" is:', options: ['asking for permission', 'stating an obligation', 'expressing a wish', 'giving an order'], answer: 'asking for permission' },
      { question: '"Voglio un caffè" is:', options: ['a direct desire', 'a very polite request', 'an obligation', 'a deduction'], answer: 'a direct desire' },
      // Passato prossimo
      { question: 'Ieri ___ dovuto lavorare. (io)', options: ['ho', 'sono', 'avevo', 'avrò'], answer: 'ho' },
      { question: 'Non ___ potuto venire. (io)', options: ['ho', 'sono', 'avrei', 'ho avuto'], answer: 'ho' },
      { question: 'Lui ___ voluto aspettare.', options: ['ha', 'è', 'aveva', 'sarà'], answer: 'ha' },
      // Imperfetto
      { question: 'Da piccolo ___ andare a letto presto. (habit)', options: ['dovevo', 'ho dovuto', 'devo', 'dovrò'], answer: 'dovevo' },
      // Future & conditional
      { question: 'Domani ___ (io, dovere) partire presto.', options: ['dovrò', 'devo', 'dovevo', 'dovrei'], answer: 'dovrò' },
      { question: '"Vorrei un caffè" means:', options: ['I would like a coffee', 'I want a coffee (direct)', 'I will make a coffee', 'I had a coffee'], answer: 'I would like a coffee' },
      { question: '"Dovresti riposare" is:', options: ['advice', 'a strong command', 'permission', 'a wish'], answer: 'advice' },
      { question: 'Potrebbe…? is used to:', options: ['ask politely (formal)', 'ask as a child', 'express obligation', 'express impossibility'], answer: 'ask politely (formal)' },
      // Structure & translation
      { question: 'Correct structure for "I must study":', options: ['Devo studiare', 'Devo studio', 'Studiare devo', 'Studio da devo'], answer: 'Devo studiare' },
      { question: '"Non posso venire stasera" means:', options: ['I can\'t come tonight', 'I don\'t want to come tonight', 'I must not come tonight', 'I don\'t come often'], answer: 'I can\'t come tonight' },
      // Reading
      { question: 'READ FIRST: "Anna deve andare al lavoro in centro. Non può prendere la macchina perché non la ha. Può prendere l\'autobus, ma deve uscire presto. Vorrebbe invece camminare, ma è troppo lontano. Alla fine chiama Luca: «Puoi accompagnarmi?» Luca risponde: «Certo che posso! Non devo lavorare oggi.»"\n\nWhy can\'t Anna take the car?', options: ['She doesn\'t have one', 'It\'s broken', 'She can\'t drive', 'It\'s too cold'], answer: 'She doesn\'t have one' },
      { question: 'READ AGAIN: "Vorrebbe invece camminare" — "vorrebbe" means:', options: ['she would like', 'she wants', 'she must', 'she will like'], answer: 'she would like' },
      { question: 'READ AGAIN: "Non devo lavorare oggi" means:', options: ['I don\'t have to work today', 'I must not work today', 'I can\'t work today', 'I don\'t want to work today'], answer: 'I don\'t have to work today' },
      // Production
      { question: 'Write "I can help you" in Italian:', type: 'text', answer: 'Posso aiutarti', acceptedAnswers: ['posso aiutarti', 'io posso aiutarti', 'posso aiutare te'] },
      { question: 'Write "We would like two tickets" in Italian:', type: 'text', answer: 'Vorremmo due biglietti', acceptedAnswers: ['vorremmo due biglietti', 'noi vorremmo due biglietti', 'vorremmo due biglietti per favore'] },
    ],
  },
];

export const modaliStories = modaliExercises.filter((e) => e.type === 'story');

export const modaliFinalTest = modaliExercises.find((e) => e.id === 30).questions;

export const modaliFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You confidently understand and use dovere, potere, and volere in all the main tenses.' },
  { min: 75, grade: 'Very good!', message: 'You understand the modal system. Review the irregular forms and the passato prossimo/imperfetto contrast.' },
  { min: 60, grade: 'Almost there!', message: 'Review the present forms of dovere/potere/volere and the polite condizionale forms.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the lessons before taking the final test again.' },
];