export const imperfettoStages = [
  {
    id: 'concept',
    title: 'What is the Imperfetto?',
    subtitle: 'Understanding what the imperfetto means and its three main uses',
    sections: [
      {
        heading: 'Part 1 — What is the imperfetto?',
        explanation: 'The imperfetto is used to talk about things that happened regularly, were ongoing, or described a situation in the past. It often expresses the ideas of "was doing", "used to do", or "was like".',
        bullets: [
          { text: 'Oggi gioco a calcio. → Today I play soccer. (present)', example: 'Da bambino giocavo a calcio. → When I was a child, I used to play soccer. (imperfetto)' },
          { text: 'Oggi lavoro. → Today I work. (present)', example: 'Quando vivevo a Roma, lavoravo ogni giorno. → When I lived in Rome, I worked every day.' },
        ],
        timeline: { left: 'PAST', center: 'NOW', right: 'FUTURE', examples: ['Ogni estate andavamo al mare', 'Oggi gioco a calcio', 'Domani lavorerò'] },
        note: 'Italian uses the imperfetto according to the FUNCTION of the action in the past — not as a rigid English translation.',
      },
      {
        heading: 'Part 2 — The three main uses',
        explanation: 'There are three beginner uses of the imperfetto that cover most everyday situations:',
        bullets: [
          { text: 'HABIT / REPEATED ACTION — Ogni giorno andavo a scuola.', example: 'Every day I used to go to school. Signal words: sempre, spesso, ogni giorno, ogni estate, di solito.' },
          { text: 'ONGOING ACTION / BACKGROUND — Mentre studiavo, ascoltavo la musica.', example: 'While I was studying, I listened to music. Imagine the action while it is in progress.' },
          { text: 'DESCRIPTION / STATE — Era una giornata bellissima.', example: 'It was a beautiful day. Also: age, time, weather, feelings.' },
        ],
        note: 'Think of the imperfetto as the "camera" that shows the background of a past scene.',
      },
    ],
  },
  {
    id: 'formation',
    title: 'Forming the Imperfetto',
    subtitle: 'Regular -are, -ere, and -ire endings',
    sections: [
      {
        heading: 'Part 3 — The regular endings',
        explanation: 'The imperfetto endings are very predictable. Remove the -re of the infinitive and add the endings.',
        comparison: [
          { form: 'io', are: '-avo', ere: '-evo', ire: '-ivo' },
          { form: 'tu', are: '-avi', ere: '-evi', ire: '-ivi' },
          { form: 'lui/lei', are: '-ava', ere: '-eva', ire: '-iva' },
          { form: 'noi', are: '-avamo', ere: '-evamo', ire: '-ivamo' },
          { form: 'voi', are: '-avate', ere: '-evate', ire: '-ivate' },
          { form: 'loro', are: '-avano', ere: '-evano', ire: '-ivano' },
        ],
        note: 'Memorise this table — it is the same for almost every regular verb.',
      },
      {
        heading: 'Part 4 — Regular -ARE verbs',
        explanation: 'Examples: parlare → parlavo, mangiare → mangiavo, lavorare → lavoravo, studiare → studiavo, giocare → giocavo.',
        verbs: [
          { infinitive: 'parlare', meaning: 'parlavo — I used to speak' },
          { infinitive: 'mangiare', meaning: 'mangiavo — I used to eat' },
          { infinitive: 'lavorare', meaning: 'lavoravo — I used to work' },
          { infinitive: 'studiare', meaning: 'studiavo — I used to study' },
          { infinitive: 'giocare', meaning: 'giocavo — I used to play' },
          { infinitive: 'guardare', meaning: 'guardavo — I used to watch' },
          { infinitive: 'abitare', meaning: 'abitavo — I used to live' },
          { infinitive: 'ascoltare', meaning: 'ascoltavo — I used to listen' },
          { infinitive: 'camminare', meaning: 'camminavo — I used to walk' },
        ],
        group: '-ARE',
      },
      {
        heading: 'Part 5 — Regular -ERE verbs',
        explanation: 'Examples: vedere → vedevo, leggere → leggevo, scrivere → scrivevo, prendere → prendevo, vivere → vivevo, conoscere → conoscevo.',
        verbs: [
          { infinitive: 'vedere', meaning: 'vedevo — I used to see' },
          { infinitive: 'leggere', meaning: 'leggevo — I used to read' },
          { infinitive: 'scrivere', meaning: 'scrivevo — I used to write' },
          { infinitive: 'prendere', meaning: 'prendevo — I used to take' },
          { infinitive: 'vivere', meaning: 'vivevo — I used to live' },
          { infinitive: 'conoscere', meaning: 'conoscevo — I used to know' },
          { infinitive: 'ricevere', meaning: 'ricevevo — I used to receive' },
        ],
        group: '-ERE',
      },
      {
        heading: 'Part 6 — Regular -IRE verbs',
        explanation: 'Examples: dormire → dormivo, partire → partivo, sentire → sentivo, finire → finivo, aprire → aprivo, seguire → seguivo.',
        verbs: [
          { infinitive: 'dormire', meaning: 'dormivo — I used to sleep' },
          { infinitive: 'partire', meaning: 'partivo — I used to leave' },
          { infinitive: 'sentire', meaning: 'sentivo — I used to hear/feel' },
          { infinitive: 'finire', meaning: 'finivo — I used to finish' },
          { infinitive: 'aprire', meaning: 'aprivo — I used to open' },
          { infinitive: 'seguire', meaning: 'seguivo — I used to follow' },
        ],
        group: '-IRE',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'Essere, Avere, Fare',
    subtitle: 'The three most important irregular verbs in the imperfetto',
    sections: [
      {
        heading: 'Part 7 — Essere',
        explanation: 'Essere is irregular in the imperfetto. Learn these six forms:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'ero' }, { pronoun: 'tu', ending: 'eri' }, { pronoun: 'lui/lei', ending: 'era' }, { pronoun: 'noi', ending: 'eravamo' }, { pronoun: 'voi', ending: 'eravate' }, { pronoun: 'loro', ending: 'erano' }] },
        examples: [
          { italian: 'Ero stanco.', translation: 'I was tired.' },
          { italian: 'Era una bella giornata.', translation: 'It was a beautiful day.' },
          { italian: 'Eravamo a casa.', translation: 'We were at home.' },
          { italian: 'Erano studenti.', translation: 'They were students.' },
        ],
      },
      {
        heading: 'Part 8 — Avere',
        explanation: 'Avere is also irregular. The forms are:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'avevo' }, { pronoun: 'tu', ending: 'avevi' }, { pronoun: 'lui/lei', ending: 'aveva' }, { pronoun: 'noi', ending: 'avevamo' }, { pronoun: 'voi', ending: 'avevate' }, { pronoun: 'loro', ending: 'avevano' }] },
        examples: [
          { italian: 'Avevo dieci anni.', translation: 'I was ten years old.' },
          { italian: 'Avevamo una casa grande.', translation: 'We had a big house.' },
          { italian: 'Luca aveva fame.', translation: 'Luca was hungry.' },
        ],
        note: 'Avere is used in common expressions: avere fame (hungry), avere sete (thirsty), avere sonno (sleepy), avere paura (scared), avere freddo (cold), avere caldo (hot).',
      },
      {
        heading: 'Part 9 — Fare',
        explanation: 'Fare is extremely useful for describing past routines. The forms are:',
        conjugations: { rows: [{ pronoun: 'io', ending: 'facevo' }, { pronoun: 'tu', ending: 'facevi' }, { pronoun: 'lui/lei', ending: 'faceva' }, { pronoun: 'noi', ending: 'facevamo' }, { pronoun: 'voi', ending: 'facevate' }, { pronoun: 'loro', ending: 'facevano' }] },
        examples: [
          { italian: 'Facevo sport ogni giorno.', translation: 'I used to exercise every day.' },
          { italian: 'Faceva caldo.', translation: 'It was hot.' },
          { italian: 'Cosa facevi da bambino?', translation: 'What did you use to do as a child?' },
        ],
      },
    ],
  },
  {
    id: 'timecompare',
    title: 'Time, Age & Comparing',
    subtitle: 'Time, weather, age, signal words, and imperfetto vs passato prossimo',
    sections: [
      {
        heading: 'Part 10 — Time and weather',
        explanation: 'The imperfetto is used to describe time and weather in the past:',
        examples: [
          { italian: 'Era mezzogiorno.', translation: 'It was noon.' },
          { italian: 'Erano le otto.', translation: 'It was eight o\'clock.' },
          { italian: 'Faceva caldo.', translation: 'It was hot.' },
          { italian: 'Pioveva.', translation: 'It was raining.' },
          { italian: 'Nevicava.', translation: 'It was snowing.' },
          { italian: 'C\'era il sole.', translation: 'It was sunny.' },
        ],
      },
      {
        heading: 'Part 11 — Age',
        explanation: 'To say age in the past, Italian uses avere in the imperfetto:',
        examples: [
          { italian: 'Avevo dieci anni.', translation: 'I was ten years old.' },
          { italian: 'Quando avevo cinque anni, vivevo a Roma.', translation: 'When I was five, I lived in Rome.' },
          { italian: 'Quando Marco aveva otto anni, giocava a calcio.', translation: 'When Marco was eight, he played soccer.' },
        ],
        note: 'Contrast: "Ho dieci anni" (I am ten — now) vs "Avevo dieci anni" (I was ten — in the past).',
      },
      {
        heading: 'Part 12 — Signal words',
        explanation: 'These words frequently appear with the imperfetto. Learn to recognise them:',
        examples: [
          { italian: 'sempre / spesso', translation: 'always / often' },
          { italian: 'di solito', translation: 'usually' },
          { italian: 'ogni giorno / ogni settimana', translation: 'every day / every week' },
          { italian: 'ogni estate / ogni domenica', translation: 'every summer / every Sunday' },
          { italian: 'da bambino/a', translation: 'as a child' },
          { italian: 'quando ero piccolo/a', translation: 'when I was little' },
          { italian: 'mentre', translation: 'while' },
        ],
      },
      {
        heading: 'Part 13 — Imperfetto vs Passato Prossimo',
        explanation: 'These two tenses work together. The imperfetto shows the BACKGROUND (habit, description, ongoing action). The passato prossimo shows the EVENT that happened.',
        examples: [
          { italian: 'Ieri ho mangiato una pizza. — Completed event.', translation: 'Yesterday I ate a pizza. → Passato prossimo.' },
          { italian: 'Da bambino mangiavo spesso la pizza. — Habit.', translation: 'As a child I often used to eat pizza. → Imperfetto.' },
          { italian: 'Mentre studiavo (background), è arrivato Marco (event).', translation: 'While I was studying, Marco arrived.' },
        ],
        focus: { sentence: 'Mentre studiavo, Maria è arrivata.', breakdown: [{ part: 'studiavo', role: 'imperfetto — background' }, { part: 'è arrivata', role: 'passato prossimo — event' }], meaning: 'Action in progress + completed event.' },
        note: 'IMPERFETTO = what was happening / used to happen / was like. PASSATO PROSSIMO = a completed event. Together they tell the story.',
      },
    ],
  },
];

export const imperfettoExercises = [
  // LEVEL 1 — RECOGNITION
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Present or Imperfetto?',
    instruction: 'Is this sentence in the present or the past?',
    questions: [
      { question: 'Oggi lavoro.', options: ['Present', 'Past'], answer: 'Present', explanation: '"Oggi" (today) with "lavoro" = present tense.' },
      { question: 'Quando ero giovane, lavoravo molto.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Ero" and "lavoravo" are imperfetto forms — past.' },
      { question: 'Da bambino giocavo a calcio.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Giocavo" is imperfetto — habitual action in the past.' },
      { question: 'Oggi mangio una pizza.', options: ['Present', 'Past'], answer: 'Present', explanation: '"Mangio" = present tense.' },
      { question: 'Ogni estate andavamo al mare.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Andavamo" is imperfetto — repeated action in the past.' },
      { question: 'Pioveva molto ieri.', options: ['Present', 'Past'], answer: 'Past', explanation: '"Pioveva" is imperfetto — ongoing action/weather in the past.' },
    ],
  },
  {
    id: 2,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Imperfetto Verb',
    instruction: 'Which word is the imperfetto verb in each sentence?',
    questions: [
      { question: 'Maria studiava ogni sera.', options: ['Maria', 'studiava', 'ogni', 'sera'], answer: 'studiava', explanation: '"Studiava" is the imperfetto verb (studiare).' },
      { question: 'Quando ero piccolo, vivevo a Roma.', options: ['Quando', 'piccolo', 'vivevo', 'Roma'], answer: 'vivevo', explanation: '"Vivevo" is the imperfetto verb (vivere).' },
      { question: 'Mia nonna cucinava sempre la domenica.', options: ['Mia', 'nonna', 'cucinava', 'domenica'], answer: 'cucinava', explanation: '"Cucinava" is the imperfetto verb (cucinare).' },
      { question: 'Era molto caldo.', options: ['Era', 'molto', 'caldo'], answer: 'Era', explanation: '"Era" is the imperfetto of essere.' },
      { question: 'Giocavamo a calcio ogni giorno.', options: ['Giocavamo', 'calcio', 'giorno'], answer: 'Giocavamo', explanation: '"Giocavamo" is the imperfetto of giocare.' },
    ],
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Identify the Ending',
    instruction: 'What ending is used on the imperfetto verb?',
    questions: [
      { question: 'parlavo — what is the ending?', options: ['-avo', '-ato', '-ere', '-ava'], answer: '-avo', explanation: 'parlavo = parl- + -avo (io, -ARE verbs).' },
      { question: 'mangiavo — what is the ending?', options: ['-avo', '-ato', '-ava', '-avi'], answer: '-avo', explanation: 'mangiavo = mangi- + -avo (io, -ARE verbs).' },
      { question: 'dormivamo — what is the ending?', options: ['-ivamo', '-evano', '-avamo', '-ivi'], answer: '-ivamo', explanation: 'dormivamo = dorm- + -ivamo (noi, -IRE verbs).' },
      { question: 'vedeva — what is the ending?', options: ['-eva', '-aveva', '-iva', '-avano'], answer: '-eva', explanation: 'vedeva = ved- + -eva (lui/lei, -ERE verbs).' },
      { question: 'finivano — what is the ending?', options: ['-ivano', '-avo', '-evano', '-iva'], answer: '-ivano', explanation: 'finivano = fin- + -ivano (loro, -IRE verbs).' },
    ],
  },
  {
    id: 4,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Infinitive → Imperfetto Stem',
    instruction: 'Match each infinitive to its imperfetto stem.',
    pairs: [
      { left: 'parlare', right: 'parl-' },
      { left: 'mangiare', right: 'mangi-' },
      { left: 'dormire', right: 'dorm-' },
      { left: 'vedere', right: 'ved-' },
      { left: 'giocare', right: 'gioc-' },
      { left: 'finire', right: 'fin-' },
    ],
    explanation: 'Remove the -re and add the imperfetto ending: -avo/-evo/-ivo etc.',
  },
  {
    id: 5,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Choose the Correct Imperfetto Ending',
    instruction: 'Select the correct ending for each person.',
    questions: [
      { question: 'io parl___', options: ['-avo', '-avi', '-avano', '-ava'], answer: '-avo', explanation: 'io + -ARE verbs → -avo.' },
      { question: 'tu mangi___', options: ['-avi', '-avo', '-ava', '-avate'], answer: '-avi', explanation: 'tu + -ARE verbs → -avi.' },
      { question: 'lui/lei ved___', options: ['-eva', '-evi', '-evano', '-evo'], answer: '-eva', explanation: 'lui/lei + -ERE verbs → -eva.' },
      { question: 'noi dorm___', options: ['-ivamo', '-ivo', '-ivate', '-ivano'], answer: '-ivamo', explanation: 'noi + -IRE verbs → -ivamo.' },
      { question: 'loro legge___', options: ['-evano', '-evamo', '-eva', '-evi'], answer: '-evano', explanation: 'loro + -ERE verbs → -evano.' },
    ],
  },
  // LEVEL 2 — FORMATION
  {
    id: 6,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Conjugate -ARE Verbs',
    instruction: 'Match each subject to the correct imperfetto form.',
    pairs: [
      { left: 'io + giocare', right: 'giocavo' },
      { left: 'tu + parlare', right: 'parlavi' },
      { left: 'lui + lavorare', right: 'lavorava' },
      { left: 'noi + studiare', right: 'studiavamo' },
      { left: 'voi + guardare', right: 'guardavate' },
      { left: 'loro + ascoltare', right: 'ascoltavano' },
    ],
    explanation: '-ARE imperfetto: -avo, -avi, -ava, -avamo, -avate, -avano.',
  },
  {
    id: 7,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Conjugate -ERE Verbs',
    instruction: 'Match each subject to the correct imperfetto form.',
    pairs: [
      { left: 'io + vedere', right: 'vedevo' },
      { left: 'tu + leggere', right: 'leggevi' },
      { left: 'lui + scrivere', right: 'scriveva' },
      { left: 'noi + vivere', right: 'vivevamo' },
      { left: 'voi + prendere', right: 'prendevate' },
      { left: 'loro + ricevere', right: 'ricevevano' },
    ],
    explanation: '-ERE imperfetto: -evo, -evi, -eva, -evamo, -evate, -evano.',
  },
  {
    id: 8,
    type: 'matching',
    level: 'Level 2 — Formation',
    title: 'Conjugate -IRE Verbs',
    instruction: 'Match each subject to the correct imperfetto form.',
    pairs: [
      { left: 'io + dormire', right: 'dormivo' },
      { left: 'tu + partire', right: 'partivi' },
      { left: 'lei + sentire', right: 'sentiva' },
      { left: 'noi + finire', right: 'finivamo' },
      { left: 'voi + aprire', right: 'aprivate' },
      { left: 'loro + seguire', right: 'seguivano' },
    ],
    explanation: '-IRE imperfetto: -ivo, -ivi, -iva, -ivamo, -ivate, -ivano.',
  },
  {
    id: 9,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Complete the Conjugation',
    instruction: 'Complete the conjugation of the imperfetto verb.',
    questions: [
      { sentence: 'parlare — io parl___.', options: ['parlavo', 'parlava', 'parlavi', 'parlavamo'], answer: 'parlavo', explanation: 'io + parlare → parlavo.' },
      { sentence: 'parlare — tu parl___.', options: ['parlavi', 'parlavo', 'parlava', 'parlavano'], answer: 'parlavi', explanation: 'tu + parlare → parlavi.' },
      { sentence: 'parlare — lui parl___.', options: ['parlava', 'parlavi', 'parlavo', 'parlavamo'], answer: 'parlava', explanation: 'lui + parlare → parlava.' },
      { sentence: 'parlare — noi parl___.', options: ['parlavamo', 'parlava', 'parlavate', 'parlavamo'], answer: 'parlavamo', explanation: 'noi + parlare → parlavamo.' },
      { sentence: 'parlare — loro parl___.', options: ['parlavano', 'parlavate', 'parlavamo', 'parlava'], answer: 'parlavano', explanation: 'loro + parlare → parlavano.' },
    ],
  },
  {
    id: 10,
    type: 'fillblank',
    level: 'Level 2 — Formation',
    title: 'Complete the Sentence',
    instruction: 'Complete the sentence with the correct imperfetto form.',
    questions: [
      { sentence: 'Da bambino, io ___ a calcio. (giocare)', options: ['giocavo', 'giocavi', 'giocava', 'giocavano'], answer: 'giocavo', explanation: '"Da bambino" + io → giocavo (habit in the past).' },
      { sentence: 'Quando ero piccolo, Nonna ___ la pasta. (cucinare)', options: ['cucinava', 'cucinavo', 'cucinavi', 'cucinavano'], answer: 'cucinava', explanation: 'Nonna (lei) → cucinava.' },
      { sentence: 'Ogni sera io ___ la musica. (ascoltare)', options: ['ascoltavo', 'ascoltava', 'ascoltavi', 'ascoltavano'], answer: 'ascoltavo', explanation: 'io → ascoltavo (repeated action).' },
      { sentence: 'I miei amici ___ a scuola. (camminare)', options: ['camminavano', 'camminavo', 'camminava', 'camminavi'], answer: 'camminavano', explanation: 'gli amici (loro) → camminavano.' },
    ],
  },
  // LEVEL 3 — IRREGULAR HIGH-FREQUENCY VERBS
  {
    id: 11,
    type: 'fillblank',
    level: 'Level 3 — Irregular Verbs',
    title: 'Essere in the Imperfetto',
    instruction: 'Complete with the correct form of essere.',
    questions: [
      { sentence: 'Io ___ stanco ieri sera.', options: ['ero', 'eri', 'era', 'erano'], answer: 'ero', explanation: 'io + essere → ero.' },
      { sentence: 'Tu ___ felice.', options: ['eri', 'ero', 'era', 'eravate'], answer: 'eri', explanation: 'tu + essere → eri.' },
      { sentence: 'Lei ___ una brava studentessa.', options: ['era', 'eri', 'ero', 'erano'], answer: 'era', explanation: 'lei + essere → era.' },
      { sentence: 'Noi ___ a casa.', options: ['eravamo', 'ero', 'era', 'eravate'], answer: 'eravamo', explanation: 'noi + essere → eravamo.' },
      { sentence: 'Loro ___ studenti.', options: ['erano', 'eravate', 'era', 'eri'], answer: 'erano', explanation: 'loro + essere → erano.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 3 — Irregular Verbs',
    title: 'Avere in the Imperfetto',
    instruction: 'Complete with the correct form of avere.',
    questions: [
      { sentence: 'Io ___ dieci anni.', options: ['avevo', 'avevi', 'aveva', 'avevano'], answer: 'avevo', explanation: 'io + avere → avevo (age in the past).' },
      { sentence: 'Tu ___ fame.', options: ['avevi', 'avevo', 'aveva', 'avevamo'], answer: 'avevi', explanation: 'tu + avere → avevi (you were hungry).' },
      { sentence: 'Mio fratello ___ sonno.', options: ['aveva', 'avevo', 'avevi', 'avevano'], answer: 'aveva', explanation: 'mio fratello (lui) → aveva.' },
      { sentence: 'Noi ___ una casa grande.', options: ['avevamo', 'avevo', 'aveva', 'avevate'], answer: 'avevamo', explanation: 'noi + avere → avevamo.' },
      { sentence: 'Loro ___ paura del buio.', options: ['avevano', 'avevo', 'aveva', 'avevamo'], answer: 'avevano', explanation: 'loro + avere → avevano.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 3 — Irregular Verbs',
    title: 'Fare in the Imperfetto',
    instruction: 'Complete with the correct form of fare.',
    questions: [
      { sentence: 'Io ___ sport ogni giorno.', options: ['facevo', 'facevi', 'faceva', 'facevano'], answer: 'facevo', explanation: 'io + fare → facevo (routine in the past).' },
      { sentence: 'Tu ___ i compiti la sera.', options: ['facevi', 'facevo', 'faceva', 'facevamo'], answer: 'facevi', explanation: 'tu + fare → facevi.' },
      { sentence: 'Marco ___ caldo.', options: ['faceva', 'facevo', 'facevi', 'facevano'], answer: 'faceva', explanation: '"Faceva caldo" = it was hot. Faceva is impersonal here.' },
      { sentence: 'Noi ___ colazione insieme.', options: ['facevamo', 'facevo', 'faceva', 'facevate'], answer: 'facevamo', explanation: 'noi + fare → facevamo.' },
      { sentence: 'Loro ___ sempre i compiti.', options: ['facevano', 'facevo', 'faceva', 'facevate'], answer: 'facevano', explanation: 'loro + fare → facevano.' },
    ],
  },
  {
    id: 14,
    type: 'fillblank',
    level: 'Level 3 — Irregular Verbs',
    title: 'Mixed Essere / Avere / Fare',
    instruction: 'Choose the correct irregular form.',
    questions: [
      { sentence: 'Quando ero bambino, ___ dieci anni. (avere)', options: ['avevo', 'ero', 'facevo', 'aveva'], answer: 'avevo', explanation: '"Avevo dieci anni" = I was ten years old.' },
      { sentence: 'Cosa ___ da bambino? (fare)', options: ['facevi', 'eri', 'avevi', 'faceva'], answer: 'facevi', explanation: 'tu + fare → facevi ("What did you used to do?").' },
      { sentence: 'Mia nonna ___ molto gentile. (essere)', options: ['era', 'aveva', 'faceva', 'eri'], answer: 'era', explanation: 'Lei + essere → era (description).' },
      { sentence: 'Quando ___ piccolo, vivevo a Roma. (essere)', options: ['ero', 'avevo', 'facevo', 'era'], answer: 'ero', explanation: 'io + essere → ero ("When I was little").' },
    ],
  },
  {
    id: 15,
    type: 'fillblank',
    level: 'Level 3 — Irregular Verbs',
    title: 'Complete the Description',
    instruction: 'Complete the short description with the imperfetto forms.',
    questions: [
      { sentence: 'Quando ero piccolo, ___ molto timido. (essere)', options: ['ero', 'avevo', 'facevo', 'era'], answer: 'ero', explanation: 'io + essere → ero (describe what you were like).' },
      { sentence: 'Quando ero piccolo, ___ molti amici. (avere)', options: ['avevo', 'ero', 'facevo', 'aveva'], answer: 'avevo', explanation: 'io + avere → avevo (possession in the past).' },
      { sentence: 'Quando ero piccolo, ___ i compiti ogni sera. (fare)', options: ['facevo', 'ero', 'avevo', 'faceva'], answer: 'facevo', explanation: 'io + fare → facevo (habit).' },
      { sentence: 'La mia casa ___ piccola ma bella. (essere)', options: ['era', 'ero', 'aveva', 'erano'], answer: 'era', explanation: 'la casa (lei) + essere → era (description).' },
    ],
  },
  // LEVEL 4 — USE AND MEANING
  {
    id: 16,
    type: 'multiple',
    level: 'Level 4 — Use and Meaning',
    title: 'Habit or Completed Event?',
    instruction: 'Is the action a HABIT (repeated) or a COMPLETED EVENT (one time)?',
    questions: [
      { question: 'Ogni estate andavamo al mare.', options: ['Habit', 'Completed event'], answer: 'Habit', explanation: '"Ogni estate" (every summer) shows repetition → imperfetto.' },
      { question: 'Ieri ho comprato un libro.', options: ['Habit', 'Completed event'], answer: 'Completed event', explanation: '"Ieri ho comprato" = one finished action → passato prossimo.' },
      { question: 'Di solito studiavo la sera.', options: ['Habit', 'Completed event'], answer: 'Habit', explanation: '"Di solito" (usually) → repeated habit → imperfetto.' },
      { question: 'La domenica mangiavamo insieme.', options: ['Habit', 'Completed event'], answer: 'Habit', explanation: '"La domenica" (every Sunday) → repetition → imperfetto.' },
      { question: 'Marco è arrivato alle otto.', options: ['Habit', 'Completed event'], answer: 'Completed event', explanation: '"È arrivato" = a finished arrival → passato prossimo.' },
    ],
  },
  {
    id: 17,
    type: 'multiple',
    level: 'Level 4 — Use and Meaning',
    title: 'Description or Event?',
    instruction: 'Is the sentence a DESCRIPTION (background/state) or a COMPLETED EVENT?',
    questions: [
      { question: 'Era una giornata calda.', options: ['Description', 'Completed event'], answer: 'Description', explanation: 'Describes the weather/background → imperfetto.' },
      { question: 'La casa era grande.', options: ['Description', 'Completed event'], answer: 'Description', explanation: 'Describes what the house was like → imperfetto.' },
      { question: 'Avevo dieci anni.', options: ['Description', 'Completed event'], answer: 'Description', explanation: 'Describes age/state in the past → imperfetto.' },
      { question: 'Pioveva tutta la mattina.', options: ['Description', 'Completed event'], answer: 'Description', explanation: 'Ongoing weather → imperfetto.' },
      { question: 'Maria è tornata ieri.', options: ['Description', 'Completed event'], answer: 'Completed event', explanation: 'A finished return → passato prossimo.' },
    ],
  },
  {
    id: 18,
    type: 'fillblank',
    level: 'Level 4 — Use and Meaning',
    title: 'Choose Imperfetto or Passato Prossimo',
    instruction: 'Select the correct tense for each sentence.',
    questions: [
      { sentence: 'Ieri ___ una pizza. (mangiare)', options: ['ho mangiato', 'mangiavo'], answer: 'ho mangiato', explanation: '"Ieri" (yesterday) + one finished action → passato prossimo.' },
      { sentence: 'Da bambino ___ spesso la pizza. (mangiare)', options: ['mangiavo', 'ho mangiato'], answer: 'mangiavo', explanation: '"Da bambino" + "spesso" → repeated habit → imperfetto.' },
      { sentence: 'Quando ero studente, ___ italiano ogni giorno. (studiare)', options: ['studiavo', 'ho studiato'], answer: 'studiavo', explanation: '"Ogni giorno" → repeated habit → imperfetto.' },
      { sentence: 'Ieri ___ italiano per due ore. (studiare)', options: ['ho studiato', 'studiavo'], answer: 'ho studiato', explanation: 'A specific finished study session yesterday → passato prossimo.' },
      { sentence: 'Mentre ___ , è arrivato Marco. (studiare)', options: ['studiavo', 'ho studiato'], answer: 'studiavo', explanation: '"Mentre" + ongoing action in progress → imperfetto (background).' },
    ],
  },
  {
    id: 19,
    type: 'fillblank',
    level: 'Level 4 — Use and Meaning',
    title: 'Choose Based on Context',
    instruction: 'Read the context and choose the correct tense.',
    questions: [
      { sentence: 'Ogni domenica, noi ___ dai nonni. (andare)', options: ['andavamo', 'siamo andati'], answer: 'andavamo', explanation: '"Ogni domenica" → repeated habit → imperfetto.' },
      { sentence: 'Domenica scorsa, noi ___ dai nonni. (andare)', options: ['siamo andati', 'andavamo'], answer: 'siamo andati', explanation: '"Domenica scorsa" (last Sunday) → one finished event → passato prossimo.' },
      { sentence: 'Da bambino, io ___ a calcio. (giocare)', options: ['giocavo', 'ho giocato'], answer: 'giocavo', explanation: '"Da bambino" → habitual in the past → imperfetto.' },
      { sentence: 'Ieri pomeriggio, io ___ a calcio. (giocare)', options: ['ho giocato', 'giocavo'], answer: 'ho giocato', explanation: '"Ieri pomeriggio" → one finished event → passato prossimo.' },
    ],
  },
  {
    id: 20,
    type: 'translation',
    level: 'Level 4 — Use and Meaning',
    title: 'Explain Why',
    instruction: 'Choose the best explanation for why the imperfetto is used.',
    direction: 'it-en',
    questions: [
      { sentence: 'Quando ero piccolo, giocavo a calcio ogni giorno. — Why imperfetto?', options: ['It describes a repeated/habitual action in the past.', 'It describes a single completed event.', 'It talks about the future.', 'It is a present-tense action.'], answer: 'It describes a repeated/habitual action in the past.', explanation: '"Ogni giorno" shows repetition → imperfetto.' },
      { sentence: 'Era una giornata bellissima. — Why imperfetto?', options: ['It describes the background/situation.', 'It describes a completed event.', 'It talks about tomorrow.', 'It is a command.'], answer: 'It describes the background/situation.', explanation: 'The imperfetto sets the scene/background.' },
      { sentence: 'Mentre studiavo, ascoltavo la musica. — Why imperfetto?', options: ['Both actions were ongoing at the same time.', 'One action was finished.', 'They happened in the future.', 'They describe the weather.'], answer: 'Both actions were ongoing at the same time.', explanation: '"Mentre" (while) + ongoing actions → imperfetto.' },
      { sentence: 'Avevo dieci anni. — Why imperfetto?', options: ['It describes age/state in the past.', 'It describes a completed event.', 'It is present tense.', 'It describes what will happen.'], answer: 'It describes age/state in the past.', explanation: 'Age is a state in the past → imperfetto.' },
    ],
  },
  // LEVEL 5 — SENTENCE BUILDING
  {
    id: 21,
    type: 'wordorder',
    level: 'Level 5 — Sentence Building',
    title: 'Put the Words in Order',
    instruction: 'Arrange the words to form a correct imperfetto sentence.',
    questions: [
      { words: ['ogni', 'giorno', 'scuola', 'andavo', 'a'], answer: 'ogni giorno andavo a scuola', explanation: '"Ogni giorno andavo a scuola." = Every day I used to go to school.' },
      { words: ['da', 'bambino', 'a', 'calcio', 'giocavo'], answer: 'da bambino giocavo a calcio', explanation: '"Da bambino giocavo a calcio." = As a child I played soccer.' },
      { words: ['al', 'ogni', 'estate', 'mare', 'andavamo'], answer: 'ogni estate andavamo al mare', explanation: '"Ogni estate andavamo al mare." = Every summer we went to the seaside.' },
    ],
  },
  {
    id: 22,
    type: 'fillblank',
    level: 'Level 5 — Sentence Building',
    title: 'Complete the Sentence',
    instruction: 'Fill in the blank with the correct imperfetto form.',
    questions: [
      { sentence: 'Quando ero bambino, ___ sempre con i miei amici. (giocare)', options: ['giocavo', 'giocavi', 'giocava', 'giocavano'], answer: 'giocavo', explanation: 'io + giocare → giocavo (habit).' },
      { sentence: 'Mia madre ___ in ufficio. (lavorare)', options: ['lavorava', 'lavoravo', 'lavoravi', 'lavoravano'], answer: 'lavorava', explanation: 'mia madre (lei) → lavorava.' },
      { sentence: 'Ogni sera, noi ___ la televisione. (guardare)', options: ['guardavamo', 'guardavo', 'guardava', 'guardavate'], answer: 'guardavamo', explanation: 'noi + guardare → guardavamo.' },
      { sentence: 'Quando eravamo piccoli, ___ molti libri. (leggere)', options: ['leggevamo', 'leggevo', 'leggeva', 'leggevano'], answer: 'leggevamo', explanation: 'noi + leggere → leggevamo.' },
    ],
  },
  {
    id: 23,
    type: 'multiple',
    level: 'Level 5 — Sentence Building',
    title: 'Change the Subject',
    instruction: 'Rewrite the sentence with the new subject.',
    questions: [
      { question: 'Io studiavo italiano. → Tu ___ italiano.', options: ['studiavi', 'studiavo', 'studiava', 'studiavamo'], answer: 'studiavi', explanation: 'tu + studiare → studiavi.' },
      { question: 'Io studiavo italiano. → Lui ___ italiano.', options: ['studiava', 'studiavo', 'studiavi', 'studiavano'], answer: 'studiava', explanation: 'lui + studiare → studiava.' },
      { question: 'Io studiavo italiano. → Noi ___ italiano.', options: ['studiavamo', 'studiavo', 'studiava', 'studiavate'], answer: 'studiavamo', explanation: 'noi + studiare → studiavamo.' },
      { question: 'Io studiavo italiano. → Voi ___ italiano.', options: ['studiavate', 'studiavamo', 'studiavo', 'studiavano'], answer: 'studiavate', explanation: 'voi + studiare → studiavate.' },
      { question: 'Io studiavo italiano. → Loro ___ italiano.', options: ['studiavano', 'studiavo', 'studiava', 'studiavate'], answer: 'studiavano', explanation: 'loro + studiare → studiavano.' },
    ],
  },
  {
    id: 24,
    type: 'fillblank',
    level: 'Level 5 — Sentence Building',
    title: 'Transform Present → Imperfetto',
    instruction: 'Change the present-tense sentence to the imperfetto.',
    questions: [
      { sentence: 'Io lavoro ogni giorno → Quando ero giovane, io ___ ogni giorno. (lavorare)', options: ['lavoravo', 'lavoro', 'lavorava', 'lavoravi'], answer: 'lavoravo', explanation: 'Present → imperfetto: lavoro → lavoravo.' },
      { sentence: 'Noi andiamo al mare ogni estate → Ogni estate, noi ___ al mare. (andare)', options: ['andavamo', 'andiamo', 'andava', 'andavano'], answer: 'andavamo', explanation: 'andiamo → andavamo.' },
      { sentence: 'Loro giocano insieme → Quando erano piccoli, loro ___ insieme. (giocare)', options: ['giocavano', 'giocano', 'giocava', 'giocavi'], answer: 'giocavano', explanation: 'giocano → giocavano.' },
    ],
  },
  {
    id: 25,
    type: 'translation',
    level: 'Level 5 — Sentence Building',
    title: 'Create Your Own Sentence',
    instruction: 'Build the sentence described by the cues.',
    direction: 'en-it',
    questions: [
      { sentence: 'As a child, I played every day. (da bambino + giocare + ogni giorno)', options: ['Da bambino giocavo ogni giorno.', 'Da bambino ho giocato ogni giorno.', 'Da bambino gioca ogni giorno.', 'Da bambino giocherò ogni giorno.'], answer: 'Da bambino giocavo ogni giorno.', explanation: '"Da bambino" + habit → imperfetto: giocavo.' },
      { sentence: 'Every summer we went to the seaside. (ogni estate + andare al mare)', options: ['Ogni estate andavamo al mare.', 'Ogni estate siamo andati al mare.', 'Ogni estate andiamo al mare.', 'Ogni estate andremo al mare.'], answer: 'Ogni estate andavamo al mare.', explanation: '"Ogni estate" → repeated → imperfetto: andavamo.' },
      { sentence: 'It was very hot and it was raining. (molto caldo + piovere)', options: ['Faceva molto caldo e pioveva.', 'Ha fatto molto caldo e ha piovuto.', 'Fa molto caldo e piove.', 'Farà molto caldo e pioverà.'], answer: 'Faceva molto caldo e pioveva.', explanation: 'Weather in the past → imperfetto.' },
    ],
  },
  // LEVEL 6 — REAL-LIFE COMMUNICATION
  {
    id: 26,
    type: 'story',
    level: 'Level 6 — Real-Life Communication',
    title: 'Childhood Conversation',
    storyTitle: 'Com\'eri da bambino?',
    story: 'Anna: Com\'eri da bambino?\n\nMarco: Ero molto tranquillo. Giocavo spesso con i miei amici e di solito studiavo la sera.\n\nAnna: E a scuola, eri bravo?\n\nMarco: Sì, ero abbastanza bravo. Amavo la lettura e scrivevo sempre le mie storie.\n\nAnna: Che cosa facevi la domenica?\n\nMarco: La domenica tutta la famiglia andava dai nonni. Mangiavamo insieme e giocavamo a carte.',
    vocab: [
      { word: 'tranquillo', meaning: 'calm/quiet' },
      { word: 'di solito', meaning: 'usually' },
      { word: 'bravo', meaning: 'good at school' },
      { word: 'lettura', meaning: 'reading' },
      { word: 'carte', meaning: 'cards' },
    ],
    translation: 'Anna: What were you like as a child?\n\nMarco: I was very calm. I often played with my friends and I usually studied in the evening.\n\nAnna: And at school, were you good?\n\nMarco: Yes, I was quite good. I loved reading and I always wrote my own stories.\n\nAnna: What did you do on Sundays?\n\nMarco: On Sunday the whole family went to my grandparents. We ate together and played cards.',
    questions: [
      { question: 'How was Marco as a child?', options: ['Very calm', 'Very loud', 'Very shy', 'Very strict'], answer: 'Very calm', explanation: '"Ero molto tranquillo." = I was very calm.' },
      { question: 'What did Marco love?', options: ['Reading', 'Cooking', 'Football', 'Music'], answer: 'Reading', explanation: '"Amavo la lettura." = I loved reading.' },
      { question: 'What did the family do on Sundays?', options: ['Went to the grandparents', 'Went to the cinema', 'Went shopping', 'Stayed home'], answer: 'Went to the grandparents', explanation: '"Tutta la famiglia andava dai nonni."' },
      { question: 'Which word is the imperfetto of essere used here?', options: ['Ero', 'Giocavo', 'Studiavo', 'Amavo'], answer: 'Ero', explanation: '"Ero" is the imperfetto of essere (I was).' },
      { question: 'Write one sentence about what Marco was like as a child.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Marco era tranquillo. / Marco giocava con gli amici. Any correct imperfetto is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 6 — Real-Life Communication',
    title: 'Past Routine Conversation',
    storyTitle: 'Quando vivevi a Roma',
    story: 'Anna: Quando vivevi a Roma, cosa facevi?\n\nMarco: Lavoravo durante il giorno e la sera uscivo con gli amici.\n\nAnna: E nel fine settimana?\n\nMarco: Il sabato andavo al mercato e compravo il cibo. La domenica facevamo lunghe passeggiate e mangiavamo in trattoria.\n\nAnna: Faceva sempre bello?\n\nMarco: No, a volte pioveva. Ma anche quando pioveva, la città era bellissima.',
    vocab: [
      { word: 'uscivo', meaning: 'I used to go out (uscire)' },
      { word: 'mercato', meaning: 'market' },
      { word: 'trattoria', meaning: 'simple restaurant' },
      { word: 'a volte', meaning: 'sometimes' },
      { word: 'pioveva', meaning: 'it was raining' },
    ],
    translation: 'Anna: When you lived in Rome, what did you do?\n\nMarco: I worked during the day and in the evening I went out with friends.\n\nAnna: And at the weekend?\n\nMarco: On Saturday I went to the market and bought food. On Sunday we went on long walks and ate at a trattoria.\n\nAnna: Was it always nice weather?\n\nMarco: No, sometimes it rained. But even when it rained, the city was beautiful.',
    questions: [
      { question: 'What did Marco do in the evening in Rome?', options: ['Went out with friends', 'Stayed home', 'Studied', 'Worked more'], answer: 'Went out with friends', explanation: '"La sera uscivo con gli amici."' },
      { question: 'What did Marco do on Saturdays?', options: ['Went to the market', 'Went to the office', 'Slept late', 'Went to the sea'], answer: 'Went to the market', explanation: '"Il sabato andavo al mercato."' },
      { question: 'Where did they eat on Sundays?', options: ['At a trattoria', 'At home', 'At the cinema', 'At a bar'], answer: 'At a trattoria', explanation: '"Mangiavamo in trattoria."' },
      { question: 'How many imperfetto verbs can you find?', options: ['At least 8', 'Only 2', 'None', 'Just 1'], answer: 'At least 8', explanation: 'vivevi, facevi, lavoravo, uscivo, andavo, compravo, facevamo, mangiavamo, pioveva, era.' },
      { question: 'Write a sentence about what Marco used to do in Rome.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Lavorava durante il giorno. / Usciva con gli amici.' },
    ],
  },
  // LEVEL 7 — STORIES
  {
    id: 28,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Beginner Story — La mia infanzia',
    storyTitle: 'La mia infanzia',
    story: 'Quando ero piccolo, vivevo in una casa con un grande giardino. Ogni mattina mia madre preparava la colazione e poi mi portava a scuola a piedi.\n\nDopo la scuola giocavo con i miei amici nel parco. Amavo l\'estate: ogni estate andavamo al mare e facevo il bagno tutti i giorni.\n\nLa domenica eravamo sempre insieme. Mia nonna cucinava il pranzo e tutti mangiavamo nel giardino. Era una vita semplice ma felice.',
    vocab: [
      { word: 'giardino', meaning: 'garden' },
      { word: 'portava', meaning: 'used to take/carry' },
      { word: 'bagno', meaning: 'swim/bath' },
      { word: 'semplice', meaning: 'simple' },
    ],
    translation: 'When I was little, I lived in a house with a big garden. Every morning my mother made breakfast and then took me to school on foot.\n\nAfter school I played with my friends in the park. I loved summer: every summer we went to the sea and I swam every day.\n\nOn Sundays we were always together. My grandmother cooked lunch and everyone ate in the garden. It was a simple but happy life.',
    questions: [
      { question: 'Where did the narrator live as a child?', options: ['In a house with a big garden', 'In a flat', 'In a small town', 'By the sea'], answer: 'In a house with a big garden', explanation: '"Vivevo in una casa con un grande giardino."' },
      { question: 'How did they go to school?', options: ['On foot', 'By car', 'By bus', 'By bike'], answer: 'On foot', explanation: '"Mi portava a scuola a piedi."' },
      { question: 'What did they do every summer?', options: ['Went to the sea', 'Went to the mountains', 'Stayed home', 'Went to school'], answer: 'Went to the sea', explanation: '"Ogni estate andavamo al mare."' },
      { question: 'What did the grandmother cook?', options: ['Lunch', 'Breakfast', 'Dinner', 'Dessert'], answer: 'Lunch', explanation: '"Mia nonna cucinava il pranzo."' },
      { question: 'Which word means "always" in the story?', options: ['sempre', 'spesso', 'mai', 'oggi'], answer: 'sempre', explanation: '"Sempre" = always, a key signal word for the imperfetto.' },
      { question: 'Write a sentence about your own childhood using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Da bambino giocavo molto. / Vivevo in una città grande.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Story With Missing Verbs',
    storyTitle: 'Quando vivevo in una piccola città',
    story: 'Quando ___ (essere) ragazzo, ___ (vivere) in una piccola città vicino al mare. Ogni giorno ___ (andare) a scuola con i miei amici. ___ (Avere) una bicicletta rossa e ci ___ (andare) ovunque.\n\nNel weekend, la mia famiglia ___ (fare) sempre qualcosa di speciale. D\'estate ___ (mangiare) il gelato sulla spiaggia e ___ (guardare) il tramonto. D\'inverno, ___ (essere) freddo e ___ (piovere) spesso, ma la città era comunque bellissima.\n\nOra ___ (vivere) in una grande città, ma ricordo con affetto quegli anni.',
    vocab: [
      { word: 'bicicletta', meaning: 'bicycle' },
      { word: 'ovunque', meaning: 'everywhere' },
      { word: 'tramonto', meaning: 'sunset' },
      { word: 'inverno', meaning: 'winter' },
      { word: 'ricordare', meaning: 'to remember' },
      { word: 'affetto', meaning: 'affection' },
    ],
    questions: [
      { question: 'Fill blank 1: Quando ___ ragazzo. (essere)', options: ['ero', 'era', 'eri', 'eravamo'], answer: 'ero', explanation: 'io + essere → ero.' },
      { question: 'Fill blank 2: ___ in una piccola città. (vivere)', options: ['vivevo', 'viveva', 'vivevi', 'vivevamo'], answer: 'vivevo', explanation: 'io + vivere → vivevo.' },
      { question: 'Fill blank 3: Ogni giorno ___ a scuola. (andare)', options: ['andavo', 'andava', 'andavi', 'andavano'], answer: 'andavo', explanation: 'io + andare → andavo.' },
      { question: 'Fill blank 4: ___ una bicicletta rossa. (avere)', options: ['Avevo', 'Ero', 'Facevo', 'Aveva'], answer: 'Avevo', explanation: 'io + avere → avevo.' },
      { question: 'Fill blank 5: Ci ___ ovunque. (andare)', options: ['andavo', 'andava', 'andavi', 'andavano'], answer: 'andavo', explanation: 'Continuation of "io" → andavo.' },
      { question: 'Fill blank 6: La famiglia ___ qualcosa di speciale. (fare)', options: ['faceva', 'facevo', 'facevi', 'facevano'], answer: 'faceva', explanation: 'la famiglia (lei) + fare → faceva.' },
      { question: 'Fill blank 7: D\'estate ___ il gelato. (mangiare)', options: ['mangiavamo', 'mangiavo', 'mangiava', 'mangiavano'], answer: 'mangiavamo', explanation: '"noi" (la famiglia) → mangiavamo.' },
      { question: 'Fill blank 8: D\'inverno ___ freddo. (essere)', options: ['era', 'ero', 'eri', 'erano'], answer: 'era', explanation: '"Faceva/era freddo" — impersonal → era.' },
      { question: 'Fill blank 9: ___ spesso. (piovere)', options: ['pioveva', 'piovevo', 'piovevi', 'piovevano'], answer: 'pioveva', explanation: 'Weather → impersonal imperfetto: pioveva.' },
      { question: 'Fill blank 10: Dall\'ultima blank — Ora ___ in una grande città. (vivere)', options: ['vivo', 'vivevo', 'viveva', 'vivrò'], answer: 'vivo', explanation: '"Ora" (now) → present tense: vivo.' },
    ],
  },
  {
    id: 31,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Beginner Story — Le vacanze d\'estate',
    storyTitle: 'Le vacanze d\'estate',
    story: 'Quando ero bambino, le vacanze d\'estate erano sempre meravigliose. Ogni anno la mia famiglia partiva per la montagna e passava due settimane in una casetta di legno.\n\nOgni mattina mi svegliavo presto e uscivo a giocare. Gli uccelli cantavano e l\'aria era fresca. Mia madre preparava la colazione e poi noi facevamo lunghe passeggiate nei boschi.\n\nIl pomeriggio lo passavamo al lago. Nuotavo, pescavo e stavo con i miei amici. La sera eravamo stanchi ma felici. Erano davvero i giorni più belli della mia vita.',
    vocab: [
      { word: 'le vacanze', meaning: 'the holidays' },
      { word: 'una casetta di legno', meaning: 'a wooden chalet' },
      { word: 'gli uccelli', meaning: 'the birds' },
      { word: 'i boschi', meaning: 'the woods' },
      { word: 'pescavo', meaning: 'I used to fish' },
      { word: 'al lago', meaning: 'at the lake' },
    ],
    translation: 'When I was a child, the summer holidays were always wonderful. Every year my family left for the mountains and spent two weeks in a little wooden chalet.\n\nEvery morning I woke up early and went out to play. The birds sang and the air was fresh. My mother made breakfast and then we went on long walks in the woods.\n\nWe spent the afternoon at the lake. I swam, fished and stayed with my friends. In the evening we were tired but happy. They were truly the most beautiful days of my life.',
    questions: [
      { question: 'Where did the family go every summer?', options: ['To the mountains', 'To the sea', 'To a big city', 'To a lake'], answer: 'To the mountains', explanation: '"Ogni anno la mia famiglia partiva per la montagna."' },
      { question: 'What did the narrator do every morning?', options: ['Woke up early and went out to play', 'Slept until noon', 'Went fishing alone'], answer: 'Woke up early and went out to play', explanation: '"Ogni mattina mi svegliavo presto e uscivo a giocare."' },
      { question: 'Where was the afternoon spent?', options: ['At the lake', 'At home', 'At school', 'In the city centre'], answer: 'At the lake', explanation: '"Il pomeriggio lo passavamo al lago."' },
      { question: 'Which verb is the imperfetto of "partire"?', options: ['partiva', 'partivo', 'parte', 'partì'], answer: 'partiva', explanation: 'partire → partiva (he/she/it used to leave).' },
      { question: 'Why does the story use the imperfetto (not the passato prossimo) for almost every verb?', options: ['It describes repeated, habitual actions and a past scene', 'Because it happened yesterday', 'Because the verbs are irregular'], answer: 'It describes repeated, habitual actions and a past scene', explanation: 'Words like "ogni mattina / ogni anno / eravamo / facevamo" describe habits and settings of the past → imperfetto.' },
      { question: 'Write one sentence about your own summers using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Da piccolo andavo al mare ogni estate. Any correct imperfetto is accepted.' },
    ],
  },
  {
    id: 32,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Beginner Story — Il bar del quartiere',
    storyTitle: 'Il bar del quartiere',
    story: 'Quando vivevo in città, il bar del quartiere era il cuore della vita sociale. Ogni mattina al bar c\'erano sempre molte persone: le signore compravano il pane, gli uomini leggevano il giornale e bevevano il caffè.\n\nDopo la scuola, noi ragazzi andavamo lì per comprare i dolci e giocare ai videogiochi. Il signor Rossi, il proprietario, conosceva tutti e raccontava tante storie divertenti.\n\nIl sabato sera il bar restava aperto fino a tardi. La musica suonava e le persone ballavano in strada. Era un posto semplice, ma pieno di vita e di amicizia.',
    vocab: [
      { word: 'il quartiere', meaning: 'the neighbourhood' },
      { word: 'il cuore', meaning: 'the heart' },
      { word: 'il proprietario', meaning: 'the owner' },
      { word: 'conosceva', meaning: 'he knew (conoscere)' },
      { word: 'pieno di vita', meaning: 'full of life' },
      { word: 'i videogiochi', meaning: 'the videogames' },
    ],
    translation: 'When I lived in the city, the neighbourhood bar was the heart of social life. Every morning there were always many people at the bar: the ladies bought bread, the men read the newspaper and drank coffee.\n\nAfter school, we kids went there to buy sweets and play videogames. Mr. Rossi, the owner, knew everyone and told lots of funny stories.\n\nOn Saturday evenings the bar stayed open until late. The music played and people danced in the street. It was a simple place, but full of life and friendship.',
    questions: [
      { question: 'Who bought bread in the morning?', options: ['The ladies', 'The men', 'Mr. Rossi', 'The students'], answer: 'The ladies', explanation: '"le signore compravano il pane."' },
      { question: 'Why did the kids go to the bar after school?', options: ['To buy sweets and play videogames', 'To study', 'To help Mr. Rossi', 'To read the newspaper'], answer: 'To buy sweets and play videogames', explanation: '"noi ragazzi andavamo lì per comprare i dolci e giocare ai videogiochi."' },
      { question: 'Who was Mr. Rossi?', options: ['The owner', 'A customer', 'The baker', 'The musician'], answer: 'The owner', explanation: '"Il signor Rossi, il proprietario."' },
      { question: 'What happened on Saturday evenings?', options: ['It stayed open until late with music and dancing', 'It closed early', 'Nothing special', 'The signora served dinner'], answer: 'It stayed open until late with music and dancing', explanation: '"Il sabato sera il bar restava aperto fino a tardi... La musica suonava e le persone ballavano."' },
      { question: '"C\'erano sempre molte persone" — what does "c\'erano" mean?', options: ['There were', 'There was', 'There are', 'There will be'], answer: 'There were', explanation: 'c\'erano = there were, imperfetto of esserci (used for habitual scenes of the past).' },
      { question: 'Write one sentence about a place you used to go to in the past, using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Andavo spesso al parco. / Il bar era sempre pieno. Any correct imperfetto is accepted.' },
    ],
  },
  {
    id: 33,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Intermediate Story — Quando lavoravo a Roma',
    storyTitle: 'Quando lavoravo a Roma',
    story: 'Prima di trasferirmi qui, vivevo a Roma. Era una città splendida ma caotica. Io e il mio collega Paolo lavoravamo in un ufficio vicino al Colosseo.\n\nOgni mattina prendevo la metro alle sette e mezza. I treni erano sempre pieni, ma dopo un po\' ci facevo il callo. L\'ufficio era piccolo e i computer erano vecchi, ma il lavoro mi piaceva lo stesso.\n\nIl venerdì sera uscivamo con gli altri colleghi. Mangiavamo la pizza in una piccola trattoria vicino all\'ufficio. Mi mancava tutto questo quando sono partito. Adesso vivo tranquillo, ma a volte penso alla vita di Roma.',
    vocab: [
      { word: 'trasferirmi', meaning: 'to move (myself)' },
      { word: 'caotica', meaning: 'chaotic' },
      { word: 'ci facevo il callo', meaning: 'I got used to it' },
      { word: 'mi mancava', meaning: 'I missed (lit. it was missing to me)' },
      { word: 'la trattoria', meaning: 'the simple restaurant' },
      { word: 'il venerdì', meaning: 'on Fridays' },
    ],
    translation: 'Before moving here, I lived in Rome. It was a splendid but chaotic city. My colleague Paolo and I worked in an office near the Colosseum.\n\nEvery morning I took the metro at seven thirty. The trains were always full, but after a while I got used to it. The office was small and the computers were old, but I liked the job anyway.\n\nOn Friday evenings we went out with the other colleagues. We ate pizza in a small trattoria near the office. I missed all of this when I left. Now I live quietly, but sometimes I think about life in Rome.',
    questions: [
      { question: 'Where did the narrator work?', options: ['In an office near the Colosseum', 'In a trattoria', 'At the station'], answer: 'In an office near the Colosseum', explanation: '"lavoravamo in un ufficio vicino al Colosseo."' },
      { question: 'How did he get to work?', options: ['By metro at seven thirty', 'By car', 'On foot'], answer: 'By metro at seven thirty', explanation: '"Ogni mattina prendevo la metro alle sette e mezza."' },
      { question: 'What was the office like?', options: ['Small with old computers', 'Big and modern', 'Next to the sea'], answer: 'Small with old computers', explanation: '"L\'ufficio era piccolo e i computer erano vecchi."' },
      { question: 'What did they eat on Friday evenings?', options: ['Pizza in a small trattoria', 'Pasta at home', 'Fish at the market'], answer: 'Pizza in a small trattoria', explanation: '"Mangiavamo la pizza in una piccola trattoria."' },
      { question: 'Which tense is used throughout the story and why?', options: ['Imperfetto — it describes a past situation and habits', 'Passato prossimo — single finished actions', 'Presente — current routine'], answer: 'Imperfetto — it describes a past situation and habits', explanation: 'Life in Rome is described as a habitual background of the past: lavoravo, prendevo, uscivamo, mangiavamo.' },
      { question: 'Write one sentence about a place where you used to work or study, using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Frequentavo l\'università a Milano. Any correct imperfetto is accepted.' },
    ],
  },
  {
    id: 34,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Intermediate Story — Mentre guardavo la partita',
    storyTitle: 'Mentre guardavo la partita',
    story: 'Domenica scorsa, mentre io guardavo la partita, mia moglie preparava la cena. La partita era emozionante, quindi urlavo tanto. Mia moglie rideva e scherzava: diceva che ero peggio di un bambino.\n\nMentre noi gridavamo, il cane abbaiava e correva per casa. A un certo punto è suonato il campanello: erano arrivati i nostri amici. Mentre parlavamo del più e del meno, la cena era pronta.\n\nAlla fine abbiamo mangiato tutti insieme davanti alla televisione. È stata una serata perfetta, anche se la mia squadra ha perso!',
    vocab: [
      { word: 'mentre', meaning: 'while' },
      { word: 'urlavo', meaning: 'I was shouting (gridare)' },
      { word: 'scherzava', meaning: 'she was joking' },
      { word: 'abbaiava', meaning: 'he was barking' },
      { word: 'è suonato il campanello', meaning: 'the doorbell rang' },
      { word: 'la squadra', meaning: 'the team' },
    ],
    translation: 'Last Sunday, while I was watching the match, my wife was preparing dinner. The match was exciting, so I shouted a lot. My wife laughed and joked: she said I was worse than a child.\n\nWhile we were shouting, the dog barked and ran around the house. At one point the doorbell rang: our friends had arrived. While we were chatting, dinner was ready.\n\nIn the end we all ate together in front of the television. It was a perfect evening, even though my team lost!',
    questions: [
      { question: 'What was the wife doing while the narrator watched the match?', options: ['Preparing dinner', 'Reading', 'Watching television'], answer: 'Preparing dinner', explanation: '"mentre io guardavo la partita, mia moglie preparava la cena."' },
      { question: 'What was the dog doing?', options: ['Barking and running around the house', 'Sleeping', 'Eating'], answer: 'Barking and running around the house', explanation: '"il cane abbaiava e correva per casa."' },
      { question: 'What happened "a un certo punto"?', options: ['The doorbell rang: friends arrived', 'The match ended', 'The television broke'], answer: 'The doorbell rang: friends arrived', explanation: '"A un certo punto è suonato il campanello: erano arrivati i nostri amici."' },
      { question: 'Which action in the story is a one-time, FINISHED event (passato prossimo)?', options: ['è suonato il campanello', 'preparava la cena', 'urlavo tanto'], answer: 'è suonato il campanello', explanation: 'è suonato is a punctual event in the past (passato prossimo). Imperfetto actions (urlavo, preparava) form the background.' },
      { question: 'Why do we use the imperfetto with "mentre" here?', options: ['It describes actions in progress simultaneously', 'Because it happened yesterday', 'Because it is a future plan'], answer: 'It describes actions in progress simultaneously', explanation: '"Mentre + imperfetto" shows two actions happening at the same time in the past.' },
      { question: 'Write one sentence with "mentre" that describes two simultaneous past actions using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Mentre cucinavo, ascoltavo la musica. Any correct sentence with mentre + imperfetto is accepted.' },
    ],
  },
  {
    id: 35,
    type: 'story',
    level: 'Level 7 — Stories',
    title: 'Read and Answer in Italian — Quando ero studente',
    storyTitle: 'Quando ero studente',
    story: 'Quando ero studente all\'università, vivevo in una camera condivisa con altri tre ragazzi. Le nostre giornate erano sempre piene: c\'erano le lezioni al mattino e lo studio nel pomeriggio.\n\nNei giorni di festa tornavamo a casa in treno. Il viaggio durava quattro ore e i treni erano spesso pieni di studenti come noi. Sul treno ascoltavamo la musica e parlavamo dei nostri sogni.\n\nRicordo che i soldi non bastavano mai. Mio padre mandava un po\' di soldi ogni mese e io lavoravo il sabato in una libreria. Erano anni difficili, ma erano anche gli anni più belli.',
    vocab: [
      { word: 'una camera condivisa', meaning: 'a shared room' },
      { word: 'i giorni di festa', meaning: 'the holidays' },
      { word: 'il viaggio', meaning: 'the journey' },
      { word: 'i sogni', meaning: 'the dreams' },
      { word: 'i soldi', meaning: 'the money' },
      { word: 'la libreria', meaning: 'the bookshop' },
    ],
    translation: 'When I was a university student, I lived in a room shared with three other boys. Our days were always full: there were lessons in the morning and study in the afternoon.\n\nOn holidays we went home by train. The journey lasted four hours and the trains were often full of students like us. On the train we listened to music and talked about our dreams.\n\nI remember that money was never enough. My father sent a bit of money every month and I worked on Saturdays in a bookshop. They were hard years, but they were also the most beautiful years.',
    questions: [
      { question: 'Dove viveva lo studente? (Where did the student live?)', type: 'text', acceptedAnswers: ['in una camera condivisa', 'in una camera condivisa con altri tre ragazzi', 'in una camera condivisa con tre ragazzi', 'viveva in una camera condivisa'], answer: 'Viveva in una camera condivisa con altri tre ragazzi.', explanation: 'The story says: "vivevo in una camera condivisa con altri tre ragazzi."' },
      { question: 'Cosa c\'era al mattino e al pomeriggio? (What was there in the morning and afternoon?)', type: 'text', acceptedAnswers: ['le lezioni al mattino e lo studio nel pomeriggio', 'le lezioni e lo studio', 'c\'erano le lezioni al mattino e lo studio nel pomeriggio'], answer: 'Al mattino c\'erano le lezioni e nel pomeriggio lo studio.', explanation: 'The story says: "c\'erano le lezioni al mattino e lo studio nel pomeriggio."' },
      { question: 'Quando tornavano a casa? (When did they return home?)', type: 'text', acceptedAnswers: ['nei giorni di festa', 'tornavano a casa nei giorni di festa', 'nei giorni di festa tornavamo a casa'], answer: 'Nei giorni di festa.', explanation: 'The story says: "Nei giorni di festa tornavamo a casa in treno."' },
      { question: 'Quanto durava il viaggio? (How long did the journey last?)', type: 'text', acceptedAnswers: ['quattro ore', 'durava quattro ore', 'il viaggio durava quattro ore'], answer: 'Il viaggio durava quattro ore.', explanation: 'The story says: "Il viaggio durava quattro ore."' },
      { question: 'Dove lavorava il sabato? (Where did he work on Saturdays?)', type: 'text', acceptedAnswers: ['in una libreria', 'lavorava in una libreria', 'in una libreria lavorava'], answer: 'Lavorava in una libreria.', explanation: 'The story says: "io lavoravo il sabato in una libreria."' },
      { question: 'Trova due verbi all\'imperfetto nella storia. (Find two imperfetto verbs in the story.)', type: 'text', acceptedAnswers: [], answer: 'Any two, e.g. ero, vivevo, erano, c\'erano, tornavamo, durava, ascoltavamo, parlavamo, mandava, lavoravo.', explanation: 'Examples: ero, vivevo, erano, tornavamo, durava, ascoltavamo, parlavamo, mandava, lavoravo.' },
    ],
  },
  // LEVEL 8 — FINAL PROFICIENCY TEST
  {
    id: 30,
    type: 'mastery',
    level: 'Level 8 — Final Proficiency Test',
    title: 'Imperfetto Mastery Test',
    instruction: 'Answer all 25 questions to complete the test. Take your time — accuracy matters more than speed.',
    questions: [
      // Present vs imperfetto
      { question: '"Oggi lavoro" is:', options: ['Present', 'Past'], answer: 'Present' },
      // Imperfetto verb identification
      { question: '"Maria studiava ogni sera" — the imperfetto verb is:', options: ['studiava', 'Maria', 'ogni', 'sera'], answer: 'studiava' },
      // Regular -are formation
      { question: 'Da bambino, io ___ a calcio. (giocare)', options: ['giocavo', 'giocavi', 'giocava', 'giocavano'], answer: 'giocavo' },
      // Regular -ere formation
      { question: 'Mentre leggeva, il telefono ___ . (suonare)', options: ['suonava', 'suonavo', 'suonavi', 'suonavano'], answer: 'suonava' },
      // Regular -ire
      { question: 'Ogni sera noi ___ alle dieci. (dormire)', options: ['dormivamo', 'dormivo', 'dormivate', 'dormivano'], answer: 'dormivamo' },
      // Essere
      { question: 'Noi ___ a casa ieri sera.', options: ['eravamo', 'ero', 'era', 'erano'], answer: 'eravamo' },
      // Avere
      { question: 'Luca ___ sette anni quando è arrivato qui.', options: ['aveva', 'avevo', 'avevi', 'avevano'], answer: 'aveva' },
      // Fare
      { question: 'Cosa ___ da bambino?', options: ['facevi', 'facevo', 'faceva', 'facevano'], answer: 'facevi' },
      // Time expression
      { question: '"Erano le otto" means:', options: ['It was eight o\'clock', 'It is eight o\'clock', 'It will be eight o\'clock', 'Eight people'], answer: 'It was eight o\'clock' },
      // Weather expression
      { question: '"Pioveva" means:', options: ['It was raining', 'It is raining', 'It will rain', 'It rained once'], answer: 'It was raining' },
      // Age
      { question: 'I was ten years old =', options: ['Avevo dieci anni', 'Ho dieci anni', 'Avrò dieci anni', 'Avessi dieci anni'], answer: 'Avevo dieci anni' },
      // Habitual action
      { question: '"Ogni domenica andavamo dai nonni" describes:', options: ['A habit', 'A completed event', 'The future', 'A command'], answer: 'A habit' },
      // Ongoing action
      { question: '"Mentre studiavo, ascoltavo la musica" describes:', options: ['Two ongoing actions', 'Two completed events', 'A future plan', 'The weather'], answer: 'Two ongoing actions' },
      // Description
      { question: '"La casa era grande" is a:', options: ['Description', 'Completed event', 'Command', 'Question'], answer: 'Description' },
      // Imperfetto vs passato prossimo
      { question: 'Ieri ___ una pizza. (mangiare)', options: ['ho mangiato', 'mangiavo'], answer: 'ho mangiato' },
      // Imperfetto vs passato prossimo
      { question: 'Da bambino ___ spesso la pizza. (mangiare)', options: ['mangiavo', 'ho mangiato'], answer: 'mangiavo' },
      // Italian → English
      { question: '"Avevo dieci anni e vivevo a Roma" means:', options: ['I was ten and I lived in Rome', 'I am ten and I live in Rome', 'I was ten and I live in Rome', 'I will be ten and I will live in Rome'], answer: 'I was ten and I lived in Rome' },
      // English → Italian
      { question: '"Every summer we went to the seaside" =', options: ['Ogni estate andavamo al mare', 'Ogni estate siamo andati al mare', 'Ogni estate andiamo al mare', 'Ogni estate andremo al mare'], answer: 'Ogni estate andavamo al mare' },
      // Sentence ordering
      { question: 'Choose the correct order: "giorno / lavoravo / ogni / io"', options: ['Io lavoravo ogni giorno', 'Ogni giorno io lavoravo', 'Lavoravo io ogni giorno', 'Ogni io lavoravo giorno'], answer: 'Io lavoravo ogni giorno' },
      // Signal word
      { question: '"Di solito" means:', options: ['Usually', 'Always', 'Never', 'Yesterday'], answer: 'Usually' },
      // Reading passage (Challenge story "Un giorno della mia infanzia") — imperfetto background + passato prossimo events
      { question: 'READ FIRST: "era un sabato mattina e il sole brillava. i miei tre fratelli e io giocavamo nel giardino, mentre mia madre preparava il pranzo in cucina. nostro padre lavorava in ufficio. a un certo punto il cane scappò dal cancello. abbiamo corso tutti, ma quel giorno, il cane tornò solo la sera. mia madre era triste, ma noi eravamo felici perché in fondo era stata una giornata divertente."\n\nWhat was the mother doing?', options: ['Preparing lunch', 'Working', 'Sleeping', 'Reading'], answer: 'Preparing lunch' },
      { question: 'READ AGAIN: "era un sabato mattina e il sole brillava..." — "il sole brillava" is an example of:', options: ['Background description (imperfetto)', 'Completed event (passato prossimo)', 'Future action', 'Present tense'], answer: 'Background description (imperfetto)' },
      { question: 'READ AGAIN: "...il cane scappò dal cancello" — this uses:', options: ['Passato remoto (a completed event)', 'Imperfetto', 'Present tense', 'Future'], answer: 'Passato remoto (a completed event)' },
      // Production
      { question: 'Write "I was very tired" in Italian:', type: 'text', answer: 'Ero molto stanco', acceptedAnswers: ['ero molto stanco', 'ero stanco', 'ero molto stanca', 'ero stanca'] },
      { question: 'Write "Every day I used to study" in Italian:', type: 'text', answer: 'Ogni giorno studiavo', acceptedAnswers: ['ogni giorno studiavo', 'studiavo ogni giorno'] },
    ],
  },
];

export const imperfettoStories = [
  {
    title: 'La mia infanzia',
    level: 'Beginner',
    wordCount: '~75',
    story: 'Quando ero piccolo, vivevo in una casa con un grande giardino. Ogni mattina mia madre preparava la colazione e poi mi portava a scuola a piedi.\n\nDopo la scuola giocavo con i miei amici nel parco. Amavo l\'estate: ogni estate andavamo al mare e facevo il bagno tutti i giorni.\n\nLa domenica eravamo sempre insieme. Mia nonna cucinava il pranzo e tutti mangiavamo nel giardino. Era una vita semplice ma felice.',
    vocab: [
      { word: 'giardino', meaning: 'garden' },
      { word: 'portava', meaning: 'used to take' },
      { word: 'bagno', meaning: 'swim' },
      { word: 'semplice', meaning: 'simple' },
    ],
    translation: 'When I was little, I lived in a house with a big garden. Every morning my mother made breakfast and then took me to school on foot.\n\nAfter school I played with my friends in the park. I loved summer: every summer we went to the sea and I swam every day.\n\nOn Sundays we were always together. My grandmother cooked lunch and everyone ate in the garden. It was a simple but happy life.',
    questions: [
      { question: 'Where did the narrator live as a child?', options: ['In a house with a big garden', 'In a flat', 'In a distant city', 'On a boat'], answer: 'In a house with a big garden', explanation: '"Vivevo in una casa con un grande giardino."' },
      { question: 'How did they get to school?', options: ['On foot', 'By bus', 'By car', 'By bike'], answer: 'On foot', explanation: '"Mi portava a scuola a piedi."' },
      { question: 'What did they do every summer?', options: ['Went to the sea', 'Went to the mountains', 'Stayed home', 'Studied'], answer: 'Went to the sea', explanation: '"Ogni estate andavamo al mare."' },
      { question: 'What is the imperfetto of "essere" used in the story?', options: ['ero, eravamo, era', 'sono, siamo, è', 'sarò, saremo, sarà', 'ero solo'], answer: 'ero, eravamo, era', explanation: '"Ero" (I was), "eravamo" (we were), "era" (it was).' },
      { question: 'Write a sentence about your own childhood using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Da bambino giocavo molto. Any correct imperfetto is accepted.' },
    ],
  },
  {
    title: 'Quando vivevo in una piccola città',
    level: 'Intermediate',
    wordCount: '~110',
    story: 'Quando ___ (essere) ragazzo, ___ (vivere) in una piccola città vicino al mare. Ogni giorno ___ (andare) a scuola con i miei amici. ___ (Avere) una bicicletta rossa e ci ___ (andare) ovunque.\n\nNel weekend, la mia famiglia ___ (fare) sempre qualcosa di speciale. D\'estate ___ (mangiare) il gelato sulla spiaggia e ___ (guardare) il tramonto. D\'inverno ___ (essere) freddo e ___ (piovere) spesso, ma la città era comunque bellissima.\n\nOra ___ (vivere) in una grande città, ma ricordo con affetto quegli anni.',
    vocab: [
      { word: 'bicicletta', meaning: 'bicycle' },
      { word: 'ovunque', meaning: 'everywhere' },
      { word: 'tramonto', meaning: 'sunset' },
      { word: 'inverno', meaning: 'winter' },
      { word: 'affetto', meaning: 'affection' },
    ],
    translation: 'When I was a boy, I lived in a small city near the sea. Every day I went to school with my friends. I had a red bicycle and I went everywhere on it.\n\nAt the weekend, my family always did something special. In summer we ate ice cream on the beach and watched the sunset. In winter it was cold and it often rained, but the city was still beautiful.\n\nNow I live in a big city, but I remember those years with affection.',
    questions: [
      { question: 'What colour was the narrator\'s bicycle?', options: ['Red', 'Blue', 'Green', 'Black'], answer: 'Red', explanation: '"Avevo una bicicletta rossa."' },
      { question: 'What did the family do in summer?', options: ['Ate ice cream on the beach', 'Went skiing', 'Stayed home', 'Worked'], answer: 'Ate ice cream on the beach', explanation: '"D\'estate mangiavamo il gelato sulla spiaggia."' },
      { question: 'What was the weather like in winter?', options: ['Cold and rainy', 'Hot and sunny', 'Snowy and calm', 'Windy'], answer: 'Cold and rainy', explanation: '"D\'inverno era freddo e pioveva spesso."' },
      { question: 'The word "sempre" appears with ___.', options: ['faceva (fare)', 'andavo (andare)', 'ero (essere)', 'vivere'], answer: 'faceva (fare)', explanation: '"La famiglia faceva sempre qualcosa di speciale."' },
      { question: 'Write a sentence describing your own routine in the past.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Ogni giorno andavo a scuola. Any correct imperfetto is accepted.' },
    ],
  },
  {
    title: 'Un giorno della mia infanzia',
    level: 'Challenge',
    wordCount: '~130',
    story: 'Era un sabato mattina e il sole brillava. I miei tre fratelli e io giocavamo nel giardino, mentre mia madre preparava il pranzo in cucina. Nostro padre lavorava in ufficio.\n\nA un certo punto, il cane scappò dal cancello. Ho corso con i miei fratelli, ma quel giorno il cane tornò solo la sera. Mia madre era triste, ma noi eravamo felici, perché in fondo era stata una giornata divertente.\n\nQuando il sole tramontava, tutta la famiglia si metteva sotto la veranda e raccontava storie. Mio padre rideva e mia madre ci guardava con amore. Questo ricordo è ancora uno dei più belli della mia vita.',
    vocab: [
      { word: 'brillava', meaning: 'was shining' },
      { word: 'scappò', meaning: 'escaped (scappare)' },
      { word: 'cancello', meaning: 'gate' },
      { word: 'tramontava', meaning: 'was setting (of sun)' },
      { word: 'veranda', meaning: 'veranda/porch' },
      { word: 'ricordo', meaning: 'memory' },
    ],
    translation: 'It was a Saturday morning and the sun was shining. My three brothers and I were playing in the garden, while my mother was preparing lunch in the kitchen. Our father worked in an office.\n\nAt a certain point, the dog escaped from the gate. I ran with my brothers, but that day the dog came back only in the evening. My mother was sad, but we were happy, because after all it had been a fun day.\n\nWhen the sun was setting, the whole family sat on the veranda and told stories. My father laughed and my mother watched us with love. This memory is still one of the most beautiful of my life.',
    questions: [
      { question: 'Where were the narrator and his brothers playing?', options: ['In the garden', 'In the kitchen', 'At school', 'On the street'], answer: 'In the garden', explanation: '"Giocavamo nel giardino" — ongoing action (imperfetto).' },
      { question: 'What escaped from the gate?', options: ['The dog', 'The cat', 'The horse', 'The bird'], answer: 'The dog', explanation: '"Il cane scappò dal cancello" — a completed event.' },
      { question: 'When did the dog come back?', options: ['Only in the evening', 'Immediately', 'The next day', 'Never'], answer: 'Only in the evening', explanation: '"Il cane tornò solo la sera."' },
      { question: 'The verbs "brillava" and "giocavamo" are ___.', options: ['Imperfetto — background/ongoing', 'Passato prossimo — completed events', 'Present tense', 'Future'], answer: 'Imperfetto — background/ongoing', explanation: 'The imperfetto sets the scene; the passato prossimo reports the events.' },
      { question: 'Why is the imperfetto used for "il sole tramontava"?', options: ['It describes an ongoing background action', 'It is a completed event', 'It is future', 'It is a command'], answer: 'It describes an ongoing background action', explanation: 'The setting sun is part of the scene/background → imperfetto.' },
      { question: 'Write a sentence about a childhood memory using the imperfetto.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Quando ero piccolo, giocavo nel giardino. Any correct imperfetto is accepted.' },
    ],
  },
];

export const imperfettoFinalTest = imperfettoExercises.find((e) => e.id === 30).questions;

export const imperfettoFinalBands = [
  { min: 90, grade: 'Excellent!', message: 'You can confidently recognize and form common imperfetto sentences.' },
  { min: 75, grade: 'Very good!', message: 'You understand the main uses. Review irregular forms and the difference between imperfetto and passato prossimo.' },
  { min: 60, grade: 'Almost there!', message: 'Review the three main uses of imperfetto and practice sentence formation.' },
  { min: 0, grade: 'Keep practicing!', message: 'Review the lessons before taking the final test again.' },
];