export const dimostrativiStages = [
  {
    id: 'concept',
    title: 'What are Demonstratives?',
    subtitle: 'questo, quello — pointing near and far',
    sections: [
      {
        heading: 'Part 1 — Pointing near and far',
        explanation: 'Demonstratives (il dimostrativo) POINT at things: questo (this) is near the speaker, quello (that) is far. They are the everyday words for describing, comparing, choosing, and telling stories.',
        bullets: [
          { text: 'Questo libro è mio.', example: 'this book, near me' },
          { text: 'Quel libro è tuo.', example: 'that book, far from me' },
          { text: 'Questa sera andiamo al mare.', example: 'this evening (near in time)' },
          { text: 'Quella sera era fredda.', example: 'that evening (far in time)' },
        ],
        timeline: { left: 'QUESTO (near)', center: 'DIMOSTRATIVO', right: 'QUELLO (far)', examples: ['questo libro', 'questo · quello', 'quel libro'] },
        note: 'The same idea applies to time: questa settimana (this week, now) vs quella settimana (that week, then).',
      },
      {
        heading: 'Part 2 — Adjective or pronoun',
        explanation: 'The same word has two jobs. As an AGGETTIVO (adjective) it accompanies the noun: questo libro. As a PRONOME (pronoun) it stands alone: Questo è bello — this one is beautiful.',
        bullets: [
          { text: 'Questo libro è interessante.', example: 'adjective — before the noun' },
          { text: 'Questo è interessante.', example: 'pronoun — no noun after it' },
          { text: 'Preferisco quella casa.', example: 'adjective (quel- + casa)' },
          { text: 'Preferisco quella.', example: 'pronoun (that one)' },
        ],
        patterns: ['questo + nome = aggettivo', 'questo (da solo) = pronome', 'quello + nome = aggettivo', 'quello (da solo) = pronome'],
      },
    ],
  },
  {
    id: 'formation',
    title: 'Questo & Quello',
    subtitle: 'all the adjective forms, gender & number, and the special quello forms',
    sections: [
      {
        heading: 'Part 3 — Questo, questa, questi, queste',
        explanation: 'Questo agrees with the noun like an adjective: -o (m sing), -a (f sing), -i (m plur), -e (f plur). Before a vowel, questo can lose its -o and become quest\'.',
        examples: [
          { italian: 'Questo zaino è pesante.', translation: 'this backpack is heavy (no elision before z)' },
          { italian: 'Questa settimana sono occupata.', translation: 'this week I am busy' },
          { italian: 'Questi studenti studiano sodo.', translation: 'these students study hard' },
          { italian: 'Queste penne sono nuove.', translation: 'these pens are new' },
          { italian: 'Quest\'anno partiamo per Roma.', translation: 'this year we leave for Rome' },
        ],
        patterns: ['questo (m sing)', 'questa (f sing)', 'questi (m plur)', 'queste (f plur)', 'quest\' + vowel'],
        note: 'Detect the noun\'s gender and number first; then pick the right form of questo.',
      },
      {
        heading: 'Part 4 — Quello, quel, quell\' and the family',
        explanation: 'Quello is trickier: it changes depending on the FIRST SOUND of the following word. Before a plain consonant → quel. Before a vowel → quell\'. Before s + consonant, z, gn, ps, or x → the full form quello.',
        bullets: [
          { text: 'quel + consonant', example: 'quel libro, quel caffè, quel telefono' },
          { text: 'quell\' + vowel', example: 'quell\'amico, quell\'uomo, quell\'orologio' },
          { text: 'quello + s+cons / z / gn / ps / x', example: 'quello studente, quello zaino, quello psicologo' },
          { text: 'Plural: quei / quegli', example: 'quei libri (consonant) · quegli amici (vowel) · quegli studenti (s+cons)' },
          { text: 'quella / quelle (feminine)', example: 'quella casa, quelle case' },
        ],
        patterns: ['quel + consonante', 'quell\' + vocale', 'quello + s+cons / z / gn / ps / x', 'quella (f sing) · quelle (f plur) · quei / quegli (m plur)'],
        note: 'The feminine forms are easy: quello → quella (sing), quelle (plur). All the work is in the masculine: quel, quell\', quello, quei, quegli.',
      },
    ],
  },
  {
    id: 'irregulars',
    title: 'Pronouns, Ciò & Specials',
    subtitle: 'pronoun forms, ciò, colui/colei/coloro, stesso and tale',
    sections: [
      {
        heading: 'Part 5 — Pronouns: this one / that one',
        explanation: 'On its own, questo and quello become PRONOUNS meaning "this one / that one" — perfect for choosing and comparing. quello che (or ciò che) means "what / that which".',
        examples: [
          { italian: 'Preferisco questo, non quello.', translation: 'I prefer this one, not that one.' },
          { italian: 'Quale gelato vuoi? — Questo, grazie.', translation: 'Which ice cream do you want? — This one, thanks.' },
          { italian: 'Quello che dici è vero.', translation: 'What you say is true.' },
          { italian: 'Questa è la mia città.', translation: 'This (one) is my city.' },
          { italian: 'Prendo queste, non quelle.', translation: 'I take these ones, not those ones.' },
        ],
        note: 'If there is NO noun after it, the demonstrative is a pronoun; translate it with "one" in English.',
      },
      {
        heading: 'Part 6 — Ciò, colui, colei, coloro, costui',
        explanation: 'Ciò is a neutral pronoun for ideas ("this matter / that idea"); ciò che = what. For formal or literary style, use colui che (he who), colei che (she who), coloro che (those who). costui / costoro are rare and can sound dismissive.',
        examples: [
          { italian: 'Ciò che voglio è semplice.', translation: 'What I want is simple.' },
          { italian: 'Colui che semina vento raccoglie tempesta.', translation: 'Whoever sows wind reaps storm.' },
          { italian: 'Colei che ha vinto è mia sorella.', translation: 'She who won is my sister.' },
          { italian: 'Coloro che arrivano in ritardo perdono il treno.', translation: 'Those who arrive late miss the train.' },
          { italian: 'Costui non merita fiducia.', translation: 'This fellow does not deserve trust.' },
        ],
        patterns: ['ciò — this matter / that idea (neutral)', 'ciò che — what / that which', 'colui che — he who', 'colei che — she who', 'coloro che — those who'],
        note: 'Everyday speech prefers quello che; keep colui/colei/coloro for proverbs, books, and formal texts.',
      },
      {
        heading: 'Part 7 — Stesso, tale, simile',
        explanation: 'stesso means "the same" and also reinforces -self (io stesso = I myself). tale = such / such a. simile = similar.',
        examples: [
          { italian: 'Abbiamo la stessa idea.', translation: 'We have the same idea.' },
          { italian: 'L\'ho fatto io stesso.', translation: 'I did it myself.' },
          { italian: 'Non ho mai visto tale cosa!', translation: 'I have never seen such a thing!' },
          { italian: 'Dimmi una cosa simile.', translation: 'Tell me something similar.' },
        ],
        patterns: ['lo stesso giorno (same day)', 'la stessa ora (same time)', 'gli stessi amici', 'le stesse idee', 'io stesso / lei stessa (-self)'],
        note: 'stesso agrees with the noun exactly like an adjective: lo stesso, la stessa, gli stessi, le stesse.',
      },
    ],
  },
  {
    id: 'usage',
    title: 'Choosing the Right One',
    subtitle: 'near vs far, adjective vs pronoun, in everyday Italian',
    sections: [
      {
        heading: 'Part 8 — Questo vs quello (near/far)',
        explanation: 'Choose with your eyes and your mind: near or just mentioned → questo; far or distant in time → quello. Comparisons almost always pair them.',
        examples: [
          { italian: 'Questa casa è più grande di quella.', translation: 'This house is bigger than that one.' },
          { italian: 'In questo momento non posso parlare.', translation: 'Right now I cannot talk.' },
          { italian: 'Quegli anni furono difficili.', translation: 'Those years were difficult.' },
          { italian: 'Quelle scarpe costano meno di queste.', translation: 'Those shoes cost less than these.' },
        ],
        note: 'The pair "questo / quello" is the classic of comparisons: questo è più bello di quello.',
      },
      {
        heading: 'Part 9 — quello che & everyday chunks',
        explanation: 'Master the fixed expressions: quello che / ciò che (what), in questo momento (right now), quest\'anno (this year), tale e quale (just like), lo stesso (the same).',
        bullets: [
          { text: 'quello che', example: 'Quello che conta è lo stile.' },
          { text: 'ciò che', example: 'Ciò che è vero non cambia.' },
          { text: 'quest\'anno / questa sera', example: 'Quest\'anno andiamo in Italia.' },
          { text: 'tale e quale', example: 'Tale e quale a suo padre!' },
          { text: 'lo stesso / la stessa', example: 'È la stessa cosa.' },
        ],
      },
      {
        heading: 'Part 10 — Demonstratives in real speech',
        explanation: 'Listen for them in shops, directions, restaurants. Whenever you choose, compare, or point — a demonstrative is usually nearby.',
        bullets: [
          { text: 'Commessa: Questa camicia è in saldo.', example: 'the assistant points at the near item' },
          { text: 'Turista: Quella torre è antica?', example: 'that tower across the square' },
          { text: 'Cameriere: Questo o quello?', example: 'which dish do you want' },
          { text: 'Amico: Questo è il miglior caffè della città.', example: 'this one, right here' },
        ],
      },
    ],
  },
];

export const dimostrativiExercises = [
  {
    id: 1,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Say This, Say That',
    instruction: 'Recognise what demonstratives do and point correctly.',
    questions: [
      { question: 'The demonstrative pronouns and adjectives point to:', options: ['who or what is near or far', 'always the past', 'the future only', 'a person\'s name'], answer: 'who or what is near or far', explanation: 'questo = near; quello = far.' },
      { question: '"questo" (this) refers to something:', options: ['near the speaker', 'far away', 'in the future', 'invisible'], answer: 'near the speaker', explanation: 'questo = this, close to me.' },
      { question: '"quello" (that) refers to something:', options: ['far from the speaker', 'next to me', 'always plural', 'a name'], answer: 'far from the speaker', explanation: 'quello = that, away from me.' },
      { question: 'Demonstrative ADJECTIVES (questo libro) go:', options: ['before the noun, agreeing with it', 'after the verb', 'at the end of the sentence', 'only with names'], answer: 'before the noun, agreeing with it', explanation: 'they accompany and agree with the noun.' },
      { question: 'Demonstrative PRONOUNS (Questo è il mio) stand:', options: ['alone, in place of the noun', 'before every verb', 'only in questions', 'only in writing'], answer: 'alone, in place of the noun', explanation: 'the pronoun replaces the noun entirely.' },
      { question: 'Demostrativi like questo/quello change with:', options: ['gender and number of the noun', 'the tense of the verb', 'the speaker\'s mood', 'the city'], answer: 'gender and number of the noun', explanation: 'this-o/-a/-i/-e and quello/-a/i/e follow the noun.' },
    ],
  },
  {
    id: 2,
    type: 'matching',
    level: 'Level 1 — Recognition',
    title: 'Adjective or Pronoun?',
    instruction: 'Decide for each sentence whether the demonstrative is an adjective or a pronoun.',
    pairs: [
      { left: 'Questo libro è nuovo.', right: 'adjective (before the noun)' },
      { left: 'Questo è nuovo.', right: 'pronoun (stands alone)' },
      { left: 'Quella casa è grande.', right: 'adjective' },
      { left: 'Quella è grande.', right: 'pronoun' },
      { left: 'Preferisco queste scarpe.', right: 'adjective (these shoes)' },
      { left: 'Preferisco queste.', right: 'pronoun (these ones)' },
    ],
    explanation: 'Same form, two jobs: with a noun → adjective (aggettivo); alone → pronoun (pronome).',
  },
  {
    id: 3,
    type: 'multiple',
    level: 'Level 1 — Recognition',
    title: 'Gender and Number',
    instruction: 'Move through the four forms of questo and quello.',
    questions: [
      { question: 'The feminine singular of "questo" is:', options: ['questa', 'queste', 'questi', 'quest\''], answer: 'questa', explanation: 'this-a = feminine singular.' },
      { question: 'The feminine singular of "quello" is:', options: ['quella', 'quelli', 'quelle', 'quel'], answer: 'quella', explanation: 'that-a = feminine singular.' },
      { question: 'The masculine plural of "questo" is:', options: ['questi', 'queste', 'questa', 'questo'], answer: 'questi', explanation: 'these-i = masculine plural.' },
      { question: 'The feminine plural of "questa" is:', options: ['queste', 'questi', 'questa', 'questo'], answer: 'queste', explanation: 'these-e = feminine plural.' },
      { question: 'The masculine plural of "quello" (as a pronoun) is:', options: ['quelli', 'quello', 'quelle', 'quel'], answer: 'quelli', explanation: 'those = quelli (as a pronoun).' },
      { question: 'The feminine plural of "quella" is:', options: ['quelle', 'quelli', 'quello', 'quella'], answer: 'quelle', explanation: 'those = quelle (feminine plural).' },
    ],
  },
  {
    id: 4,
    type: 'fillblank',
    level: 'Level 2 — Questo & Questa',
    title: 'Questo, questa, questi, queste',
    instruction: 'Match the form of questo to the noun.',
    questions: [
      { sentence: '___ libro è interessante.', options: ['Questo', 'Questa', 'Questi', 'Queste'], answer: 'Questo', explanation: 'libro (m sing) → questo.' },
      { sentence: '___ casa è vecchia.', options: ['Questa', 'Questo', 'Questi', 'Queste'], answer: 'Questa', explanation: 'casa (f sing) → questa.' },
      { sentence: '___ studenti studiano molto.', options: ['Questi', 'Questo', 'Questa', 'Queste'], answer: 'Questi', explanation: 'studenti (m plural) → questi.' },
      { sentence: '___ penne sono nuove.', options: ['Queste', 'Questo', 'Questi', 'Questa'], answer: 'Queste', explanation: 'penne (f plural) → queste.' },
      { sentence: '___ mese andiamo in Italia.', options: ['Questo', 'Questa', 'Questi', 'Queste'], answer: 'Questo', explanation: 'mese (m sing) → questo.' },
      { sentence: '___ settimana sono occupata.', options: ['Questa', 'Questo', 'Questi', 'Queste'], answer: 'Questa', explanation: 'settimana (f sing) → questa.' },
    ],
  },
  {
    id: 5,
    type: 'fillblank',
    level: 'Level 2 — Questo & Questa',
    title: 'Quest\' before a vowel',
    instruction: 'Elide questo to quest\' only before a vowel.',
    questions: [
      { sentence: '___ orologio è un regalo.', options: ['Quest\'', 'Questo', 'Questa', 'Questi'], answer: 'Quest\'', explanation: 'orologio starts with o (vowel) → quest\'.' },
      { sentence: '___ uomo è gentile.', options: ['Quest\'', 'Questo', 'Questa', 'Questi'], answer: 'Quest\'', explanation: 'uomo starts with u (vowel) → quest\'.' },
      { sentence: '___ amico è caro.', options: ['Quest\'', 'Questo', 'Questi', 'Questa'], answer: 'Quest\'', explanation: 'amico starts with a (vowel) → quest\'.' },
      { sentence: '___ aereo parte adesso.', options: ['Quest\'', 'Questo', 'Questa', 'Questi'], answer: 'Quest\'', explanation: 'aereo starts with a (vowel) → quest\'.' },
      { sentence: 'Paghi tu ___ volta?', options: ['questa', 'questo', 'questi', 'queste'], answer: 'questa', explanation: 'volta (f sing) → questa.' },
      { sentence: '___ zaino è pesante.', options: ['Questo', 'Quest\'', 'Questa', 'Questi'], answer: 'Questo', explanation: 'before z no elision: questo zaino.' },
    ],
  },
  {
    id: 6,
    type: 'multiple',
    level: 'Level 2 — Questo & Questa',
    title: 'Adjective or pronoun with questo',
    instruction: 'Use questo as adjective with a noun, as pronoun without one.',
    questions: [
      { question: 'In "Questo libro è mio", "questo" is:', options: ['an adjective (questo libro)', 'a pronoun', 'a verb', 'a preposition'], answer: 'an adjective (questo libro)', explanation: 'it accompanies the noun libro.' },
      { question: 'In "Questo è mio", "questo" is:', options: ['a pronoun (this one)', 'an adjective', 'a conjunction', 'an adverb'], answer: 'a pronoun (this one)', explanation: 'no noun after it → pronoun.' },
      { question: 'Which is correct?', options: ['Questi libri sono nuovi.', 'Queste libro è nuovo.', 'Questa libri sono nuovi.', 'Questo libri sono nuovi.'], answer: 'Questi libri sono nuovi.', explanation: 'libri (m plural) → questi.' },
      { question: 'Which is correct?', options: ['Questa casa è grande.', 'Questo casa è grande.', 'Questi casa è grande.', 'Queste casa è grande.'], answer: 'Questa casa è grande.', explanation: 'casa (f sing) → questa.' },
      { question: 'Before "amico" (a vowel), we write:', options: ['quest\'amico', 'questa amico', 'questi amico', 'questo amico'], answer: 'quest\'amico', explanation: 'elision → quest\'amico.' },
      { question: 'Grazie per ___ regalo!', options: ['questo', 'questa', 'questi', 'queste'], answer: 'questo', explanation: 'regalo (m sing) → questo.' },
    ],
  },
  {
    id: 7,
    type: 'fillblank',
    level: 'Level 3 — Quello & Quella',
    title: 'Quel, quello, quell\'',
    instruction: 'Choose the right masculine form of that.',
    questions: [
      { sentence: '___ libro è mio.', options: ['Quel', 'Quello', 'Quell\'', 'Quella'], answer: 'Quel', explanation: 'before a consonant → quel libro.' },
      { sentence: '___ uomo è alto.', options: ['Quell\'', 'Quel', 'Quello', 'Quella'], answer: 'Quell\'', explanation: 'uomo starts with u (vowel) → quell\'.' },
      { sentence: '___ studente è bravo.', options: ['Quello', 'Quel', 'Quell\'', 'Quella'], answer: 'Quello', explanation: 'studente starts with s+cons → quello.' },
      { sentence: '___ zaino è nuovo.', options: ['Quello', 'Quel', 'Quell\'', 'Quella'], answer: 'Quello', explanation: 'before z the full form stands: quello zaino.' },
      { sentence: '___ amico è italiano.', options: ['Quell\'', 'Quel', 'Quello', 'Quelli'], answer: 'Quell\'', explanation: 'amico starts with a (vowel) → quell\'.' },
      { sentence: '___ caffè è ottimo.', options: ['Quel', 'Quello', 'Quell\'', 'Quella'], answer: 'Quel', explanation: 'caffè starts with c (consonant) → quel.' },
    ],
  },
  {
    id: 8,
    type: 'multiple',
    level: 'Level 3 — Quello & Quella',
    title: 'Which Form Fits?',
    instruction: 'Practise the transformation rules of quello.',
    questions: [
      { question: 'Before a plain consonant (libro), we write:', options: ['quel', 'quello', 'quell\'', 'quella'], answer: 'quel', explanation: 'quel libro.' },
      { question: 'Before a vowel (amico), we write:', options: ['quell\'', 'quel', 'quello', 'quelli'], answer: 'quell\'', explanation: 'quell\'amico.' },
      { question: 'Before s + consonant (studente), we write:', options: ['quello', 'quel', 'quell\'', 'quella'], answer: 'quello', explanation: 'quello studente.' },
      { question: 'The plural of "quel libro" is:', options: ['quei libri', 'quegli libri', 'quelle libri', 'quelli libri'], answer: 'quei libri', explanation: 'consonant plural → quei libri.' },
      { question: 'The plural of "quell\'amico" is:', options: ['quegli amici', 'quei amici', 'quelli amici', 'quelle amici'], answer: 'quegli amici', explanation: 'vowel plural → quegli amici.' },
      { question: 'The plural of "quello studente" is:', options: ['quegli studenti', 'quei studenti', 'quelli studenti', 'quel studenti'], answer: 'quegli studenti', explanation: 's+cons plural → quegli studenti.' },
    ],
  },
  {
    id: 9,
    type: 'fillblank',
    level: 'Level 3 — Quello & Quella',
    title: 'The Feminine Family',
    instruction: 'Use quella / quelle and the special masculine forms.',
    questions: [
      { sentence: '___ borsa è mia.', options: ['Quella', 'Quello', 'Quei', 'Quelle'], answer: 'Quella', explanation: 'borsa (f sing) → quella.' },
      { sentence: '___ ragazze sono simpatiche.', options: ['Quelle', 'Quella', 'Quei', 'Quegli'], answer: 'Quelle', explanation: 'ragazze (f plural) → quelle.' },
      { sentence: 'Preferisco ___ telefono.', options: ['quel', 'quello', 'quell\'', 'quella'], answer: 'quel', explanation: 'telefono (m sing, consonant) → quel.' },
      { sentence: '___ notizia è sorprendente.', options: ['Quella', 'Quello', 'Quelli', 'Quelle'], answer: 'Quella', explanation: 'notizia (f sing) → quella.' },
      { sentence: '___ erba è verde.', options: ['Quell\'', 'Quella', 'Quello', 'Quelle'], answer: 'Quell\'', explanation: 'erba starts with e (vowel) → quell\'.' },
      { sentence: 'Conosco ___ signora.', options: ['quella', 'quello', 'quelle', 'quel'], answer: 'quella', explanation: 'signora (f sing) → quella.' },
    ],
  },
  {
    id: 10,
    type: 'multiple',
    level: 'Level 4 — Pronoun Forms',
    title: 'This one / That one',
    instruction: 'Use questo and quello as pronouns — standing alone.',
    questions: [
      { question: 'In "Prendo questo, non quello", "questo" and "quello" are:', options: ['pronouns (this one / that one)', 'adjectives', 'verbs', 'adverbs'], answer: 'pronouns (this one / that one)', explanation: 'no nouns follow → pronouns.' },
      { question: '"Questo è il mio libro" — "questo" is:', options: ['a pronoun (subject)', 'an adjective', 'an object', 'a name'], answer: 'a pronoun (subject)', explanation: 'it replaces the noun as subject.' },
      { question: 'Which is a correct PRONOUN use?', options: ['Preferisco questi.', 'Questa libri sono nuovi.', 'Quello libro è bello.', 'Questi casa è grande.'], answer: 'Preferisco questi.', explanation: 'questi alone = these ones; the others are wrong forms.' },
      { question: '— Quale vuoi? — ___, grazie.', options: ['Questo', 'Questa', 'Queste', 'Questo nome'], answer: 'Questo', explanation: '"this one" — pronoun answering alone.' },
      { question: '"quello che" means:', options: ['what / that which', 'who', 'whose', 'these ones'], answer: 'what / that which', explanation: 'Quello che dici — what you say.' },
      { question: '"___ che hai detto non è giusto."', options: ['Quello', 'Quella', 'Questo libro', 'Quei'], answer: 'Quello', explanation: '"that which you said" → quello che.' },
    ],
  },
  {
    id: 11,
    type: 'wordorder',
    level: 'Level 4 — Pronoun Forms',
    title: 'Assemble the Sentence',
    instruction: 'Put the words in order.',
    questions: [
      { words: ['questo', 'libro', 'è', 'nuovo'], answer: 'questo libro è nuovo', explanation: 'adjective + noun.' },
      { words: ['quella', 'casa', 'è', 'grande'], answer: 'quella casa è grande', explanation: 'quella (f sing) + casa.' },
      { words: ['preferisco', 'questo', 'non', 'quello'], answer: 'preferisco questo non quello', explanation: 'this one, not that one — pronouns.' },
      { words: ['quello', 'che', 'hai', 'detto', 'è', 'vero'], answer: 'quello che hai detto è vero', explanation: 'quello che = what you said.' },
      { words: ['questi', 'studenti', 'studiano', 'molto'], answer: 'questi studenti studiano molto', explanation: 'questi (m pl) + studenti.' },
    ],
  },
  {
    id: 12,
    type: 'fillblank',
    level: 'Level 4 — Pronoun Forms',
    title: 'Demonstrative Pronouns',
    instruction: 'Stand alone: this one, these ones, that one — and quello che = what.',
    questions: [
      { sentence: 'Quale gelato vuoi? — ___, per favore.', options: ['Questo', 'Questa', 'Queste', 'Questi'], answer: 'Questo', explanation: 'gelato (m sing) → questo, this one.' },
      { sentence: 'Quali scarpe prendi? — Prendo ___.', options: ['queste', 'questo', 'questa', 'questi'], answer: 'queste', explanation: 'scarpe (f plural) → queste, these ones.' },
      { sentence: '"___ che dici è interessante."', options: ['Quello', 'Quella', 'Quelli', 'Quei'], answer: 'Quello', explanation: 'quello che = what (neutral).' },
      { sentence: '"___ che mi preoccupa è il tempo."', options: ['Quello', 'Quella', 'Quei', 'Quel'], answer: 'Quello', explanation: 'quello che = that which worries me.' },
      { sentence: 'Mangio ___, non quello.', options: ['questo', 'questa', 'queste', 'questi'], answer: 'questo', explanation: 'this one (neutral) vs that one.' },
      { sentence: '___ è la mia città preferita.', options: ['Questa', 'Questo', 'Questi', 'Queste'], answer: 'Questa', explanation: 'città (f sing) → questa, this one.' },
    ],
  },
  {
    id: 13,
    type: 'fillblank',
    level: 'Level 5 — Questo vs Quello',
    title: 'Near or Far?',
    instruction: 'Look at the distance in space or time.',
    questions: [
      { sentence: 'Parlo di ___ piatto qui davanti a me.', options: ['questo', 'quello', 'questa', 'quelle'], answer: 'questo', explanation: 'near → questo.' },
      { sentence: 'Parlo di ___ montagna in lontananza.', options: ['quella', 'questa', 'questo', 'quelli'], answer: 'quella', explanation: 'far → quella.' },
      { sentence: '"___ giorni tutto era diverso."', options: ['Quei', 'Quelli', 'Questi', 'Quelle'], answer: 'Quei', explanation: 'far in time → quei giorni (m pl, consonant).' },
      { sentence: '"Vieni ___ sera da me!"', options: ['questa', 'quella', 'questo', 'quelle'], answer: 'questa', explanation: 'near in time → questa sera.' },
      { sentence: 'In ___ momento non posso parlare.', options: ['questo', 'quello', 'quella', 'questi'], answer: 'questo', explanation: 'right now → questo momento.' },
      { sentence: '"___ è la differenza: questo è mio, quello è tuo."', options: ['Questa', 'Questo', 'Questi', 'Queste'], answer: 'Questa', explanation: 'differenza (f sing) → questa.' },
    ],
  },
  {
    id: 14,
    type: 'matching',
    level: 'Level 5 — Questo vs Quello',
    title: 'This vs That Pairs',
    instruction: 'Match every pair with its meaning.',
    pairs: [
      { left: 'questo libro', right: 'this book (near me)' },
      { left: 'quel libro', right: 'that book (far)' },
      { left: 'questa casa', right: 'this house (near)' },
      { left: 'quella casa', right: 'that house (far)' },
      { left: 'queste penne', right: 'these pens (near)' },
      { left: 'quei computer', right: 'those computers (far)' },
    ],
    explanation: 'The QUEST- family is near the speaker; the QUEL- family is far. Only the article-like transformations of quello need practice.',
  },
  {
    id: 15,
    type: 'multiple',
    level: 'Level 5 — Questo vs Quello',
    title: 'questo / quello in context',
    instruction: 'Use the right side of the near/far contrast.',
    questions: [
      { question: '"In questo momento" means:', options: ['right now', 'later', 'yesterday', 'never'], answer: 'right now', explanation: 'questo momento = this (present) moment.' },
      { question: '"Questo piatto è il migliore" — "questo" points to:', options: ['something near', 'something far', 'the future', 'a name'], answer: 'something near', explanation: 'this dish, near the speaker.' },
      { question: '"Non capisco ___, capisco quello."', options: ['questo', 'questa', 'questi', 'queste'], answer: 'questo', explanation: 'this thing (neutral) vs that thing.' },
      { question: 'When comparing two things at a distance from both speaker and listener, Italian often uses:', options: ['quello (that one)', 'questo', 'questa', 'questi'], answer: 'quello (that one)', explanation: 'that one for things already discussed or far.' },
      { question: '"___ è la cosa più importante."', options: ['Questa', 'Questo', 'Quelli', 'Quei'], answer: 'Questa', explanation: 'cosa (f sing) → questa.' },
      { question: '"Tutti amano ___ che è giusto."', options: ['quello', 'quella', 'questo libro', 'questi'], answer: 'quello', explanation: 'that which is right → quello che.' },
    ],
  },
  {
    id: 16,
    type: 'multiple',
    level: 'Level 6 — Ciò, Colui & Company',
    title: 'Ciò & the Literary Forms',
    instruction: 'Master the neutral and formal demonstratives.',
    questions: [
      { question: '"ciò" means:', options: ['this / that (neutral)', 'this book', 'these ones', 'the one who'], answer: 'this / that (neutral)', explanation: 'ciò stands for a whole idea or situation.' },
      { question: '"ciò che" means:', options: ['what / that which', 'who', 'whose', 'this one here'], answer: 'what / that which', explanation: 'ciò che = what.' },
      { question: '"Colui che vince" means:', options: ['the one (he) who wins', 'this wins', 'that winner here', 'they who lose'], answer: 'the one (he) who wins', explanation: 'colui = he who (formal/literary).' },
      { question: 'The feminine of "colui" is:', options: ['colei', 'coloro', 'costei', 'quella'], answer: 'colei', explanation: 'colei che = she who.' },
      { question: '"coloro" is:', options: ['they / those people (plural)', 'she who', 'this thing', 'the man'], answer: 'they / those people (plural)', explanation: 'coloro che = those who.' },
      { question: '"costui" is rare and refers to someone:', options: ['nearby or just mentioned (sometimes pejorative)', 'far away', 'in the sky', 'in the past'], answer: 'nearby or just mentioned (sometimes pejorative)', explanation: 'costui/costoro have a dismissive flavour.' },
    ],
  },
  {
    id: 17,
    type: 'fillblank',
    level: 'Level 6 — Ciò, Colui & Company',
    title: 'Ciò & Company in Context',
    instruction: 'Complete with ciò, colui, colei, coloro, costui.',
    questions: [
      { sentence: 'Tutto ___ che vediamo è antico.', options: ['ciò', 'questo libro', 'quele', 'cui'], answer: 'ciò', explanation: 'all that which we see → ciò che.' },
      { sentence: '___ che ho sentito è vero.', options: ['Ciò', 'Questo libro', 'Co', 'Coloro'], answer: 'Ciò', explanation: 'ciò che for an idea heard.' },
      { sentence: '___ che voglio è semplicità.', options: ['Ciò', 'Colui', 'Colei', 'Costui'], answer: 'Ciò', explanation: 'what I want → ciò che.' },
      { sentence: '___ che non muore diventa leggenda.', options: ['Ciò', 'Colui', 'Colei', 'Costui'], answer: 'Ciò', explanation: 'that which never dies → ciò che.' },
      { sentence: '___ che semina vento raccoglie tempesta.', options: ['Colui', 'Colei', 'Coloro', 'Costui'], answer: 'Colui', explanation: 'he who sows wind reaps storm (proverb).' },
      { sentence: '___ che arrivano in ritardo perdono il treno.', options: ['Coloro', 'Colui', 'Colei', 'Costoro'], answer: 'Coloro', explanation: 'those (plural) who arrive late → coloro.' },
    ],
  },
  {
    id: 18,
    type: 'matching',
    level: 'Level 6 — Ciò, Colui & Company',
    title: 'The Formal Family',
    instruction: 'Match each formal demonstrative with its meaning.',
    pairs: [
      { left: 'ciò', right: 'this matter / that idea (neutral)' },
      { left: 'ciò che', right: 'what / that which' },
      { left: 'colui che', right: 'he who (the man that)' },
      { left: 'colei che', right: 'she who (the woman that)' },
      { left: 'coloro che', right: 'those who (they that)' },
      { left: 'costui', right: 'this fellow (nearby, often pejorative)' },
    ],
    explanation: 'ciò is neutral; colui/colei/coloro are the formal "he who / she who / those who"; costui keeps a dismissive nuance.',
  },
  {
    id: 19,
    type: 'fillblank',
    level: 'Level 7 — Stesso, Tale & Simile',
    title: 'stesso / stessa / stessi / stesse',
    instruction: 'Agree stesso with the noun.',
    questions: [
      { sentence: 'È la ___ cosa.', options: ['stessa', 'stesso', 'stessi', 'stesse'], answer: 'stessa', explanation: 'cosa (f sing) → stessa.' },
      { sentence: 'Stamattina ho visto lo ___ film.', options: ['stesso', 'stessa', 'stessi', 'stesse'], answer: 'stesso', explanation: 'film (m sing) → stesso.' },
      { sentence: 'Andiamo nello ___ posto.', options: ['stesso', 'stessa', 'stessi', 'stesse'], answer: 'stesso', explanation: 'posto (m sing) → stesso.' },
      { sentence: 'Abbiamo le ___ idee.', options: ['stesse', 'stessi', 'stesso', 'stessa'], answer: 'stesse', explanation: 'idee (f plural) → stesse.' },
      { sentence: 'Sono le ___ persone di ieri.', options: ['stesse', 'stessi', 'stesso', 'stessa'], answer: 'stesse', explanation: 'persone (f plural) → stesse.' },
      { sentence: 'Parliamo la ___ lingua.', options: ['stessa', 'stesso', 'stessi', 'stesse'], answer: 'stessa', explanation: 'lingua (f sing) → stessa.' },
    ],
  },
  {
    id: 20,
    type: 'multiple',
    level: 'Level 7 — Stesso, Tale & Simile',
    title: 'stesso, tale, simile',
    instruction: 'Recognise these three useful words.',
    questions: [
      { question: '"stesso" means:', options: ['same (and also -self)', 'this', 'that', 'different'], answer: 'same (and also -self)', explanation: 'lo stesso giorno = the same day; me stesso = myself.' },
      { question: '"tale" means:', options: ['such / such a', 'which', 'who', 'what'], answer: 'such / such a', explanation: 'Non ho mai visto tale cosa! = I never saw such a thing!' },
      { question: '"Non ho mai visto ___ cosa!"', options: ['tale', 'questa libro', 'quelle', 'quei'], answer: 'tale', explanation: 'tale cosa = such a thing.' },
      { question: 'In "me stesso", "stesso" reinforces:', options: ['the person (-self)', 'the time', 'the place', 'the reason'], answer: 'the person (-self)', explanation: 'me stesso = myself.' },
      { question: '"una cosa simile" means:', options: ['a similar thing', 'the same thing', 'the opposite', 'a new thing'], answer: 'a similar thing', explanation: 'simile = similar.' },
      { question: 'Loro sono ___ persone.', options: ['le stesse', 'lo stesso', 'la stessa', 'il stesso'], answer: 'le stesse', explanation: 'persone (f pl) → le stesse (the same people).' },
    ],
  },
  {
    id: 21,
    type: 'fillblank',
    level: 'Level 7 — Stesso, Tale & Simile',
    title: 'stesso, tale, simile in Context',
    instruction: 'Put the right word into each sentence.',
    questions: [
      { sentence: 'Ripeti la ___ cosa domani.', options: ['stessa', 'stesso', 'stessi', 'stesse'], answer: 'stessa', explanation: 'cosa (f sing) → stessa.' },
      { sentence: 'Abbiamo la ___ età.', options: ['stessa', 'stesso', 'stessi', 'stesse'], answer: 'stessa', explanation: 'età (f) → stessa.' },
      { sentence: '___ comportamento è inaccettabile.', options: ['Tale', 'Questa', 'Quel', 'Quei'], answer: 'Tale', explanation: 'tale comportamento = such behaviour.' },
      { sentence: 'Dimmi una cosa ___.', options: ['simile', 'stessa', 'tale', 'questo'], answer: 'simile', explanation: 'a similar thing.' },
      { sentence: 'Ieri e oggi: la ___ soluzione.', options: ['stessa', 'stesso', 'stessi', 'stesse'], answer: 'stessa', explanation: 'soluzione (f sing) → stessa.' },
      { sentence: 'Facciamo le ___ scelte.', options: ['stesse', 'stessi', 'stesso', 'stessa'], answer: 'stesse', explanation: 'scelte (f plural) → stesse.' },
    ],
  },
  {
    id: 22,
    type: 'multiple',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Everyday Demonstratives',
    instruction: 'Use the right demonstrative in natural Italian.',
    questions: [
      { question: '"Questa è la mia città." — "questa" è:', options: ['un pronome', 'un aggettivo', 'una preposizione', 'un verbo'], answer: 'un pronome', explanation: 'stands alone → pronoun.' },
      { question: '___ sera andiamo al cinema.', options: ['Questa', 'Questo', 'Queste', 'Quei'], answer: 'Questa', explanation: 'sera (f sing) → questa (tonight).' },
      { question: '"Quello che è successo" means:', options: ['what happened', 'the one who happened', 'these things', 'how happen'], answer: 'what happened', explanation: 'quello che = what.' },
      { question: 'Choose the WRONG sentence:', options: ['Questi studenti studiano.', 'Queste case sono alte.', 'Questa libri sono nuovi.', 'Quei film sono belli.'], answer: 'Questa libri sono nuovi.', explanation: 'libri is m plural → questi libri, not questa.' },
      { question: 'In ___ periodo lavoro molto.', options: ['questo', 'quello', 'questa', 'quelle'], answer: 'questo', explanation: 'this period → questo (m sing).' },
      { question: 'Preferisco ___ a ___, sono più comode.', options: ['queste / quelle', 'questo / quello', 'questa / quella', 'queste / quelli'], answer: 'queste / quelle', explanation: 'f plural comparison → queste/quelle.' },
    ],
  },
  {
    id: 23,
    type: 'translation',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Demonstratives to English',
    instruction: 'Choose the correct English translation.',
    direction: 'it-en',
    questions: [
      { sentence: 'Questo libro è mio, quello è tuo.', options: ['This book is mine, that one is yours.', 'That book is mine, this one is yours.', 'This book and yours are mine.', 'Those books are not here.'], answer: 'This book is mine, that one is yours.', explanation: 'questo (near) vs quello (far as pronoun).' },
      { sentence: 'Quella casa è più grande di questa.', options: ['That house is bigger than this one.', 'This house is bigger than that one.', 'That house is small.', 'These houses are big.'], answer: 'That house is bigger than this one.', explanation: 'quella casa (far) bigger than questa (near).' },
      { sentence: 'Quello che dici è vero.', options: ['What you say is true.', 'The one who says it is true.', 'That says the truth.', 'This thing you say is false.'], answer: 'What you say is true.', explanation: 'quello che = what you say.' },
      { sentence: 'Questi pantaloni mi piacciono di più.', options: ['I like these trousers more.', 'I like those trousers more.', 'These trousers are bigger.', 'Trousers like me.'], answer: 'I like these trousers more.', explanation: 'questi (m pl) = these (near).' },
      { sentence: 'L\'ho fatto io stesso.', options: ['I did it myself.', 'He did it.', 'I did the same.', 'You did it yourself.'], answer: 'I did it myself.', explanation: 'stesso = himself/myself (reinforcement).' },
    ],
  },
  {
    id: 24,
    type: 'wordorder',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Build the Sentence',
    instruction: 'Reorder the words.',
    questions: [
      { words: ['quel', 'ragazzo', 'è', 'simpatico'], answer: 'quel ragazzo è simpatico', explanation: 'quel (consonant) + ragazzo.' },
      { words: ['questa', 'città', 'è', 'bellissima'], answer: 'questa città è bellissima', explanation: 'questa (f sing) + città.' },
      { words: ['preferisco', 'queste', 'a', 'quelle'], answer: 'preferisco queste a quelle', explanation: 'these ones vs those ones (pronouns).' },
      { words: ['quello', 'che', 'so', 'è', 'poco'], answer: 'quello che so è poco', explanation: 'quello che so = what I know.' },
      { words: ['gli', 'stessi', 'amici', 'di', 'sempre'], answer: 'gli stessi amici di sempre', explanation: 'the same friends as always (gli stessi).' },
    ],
  },
  {
    id: 25,
    type: 'fillblank',
    level: 'Level 8 — Complex & Everyday Sentences',
    title: 'Grand Review',
    instruction: 'A little of everything: questo/quello, ciò, colui, stesso.',
    questions: [
      { sentence: '"___ casa in fondo alla strada è mia."', options: ['Quella', 'Questa', 'Quell\'', 'Queste'], answer: 'Quella', explanation: 'far → quella casa.' },
      { sentence: '"___ zaino pesa molto."', options: ['Questo', 'Questa', 'Questi', 'Queste'], answer: 'Questo', explanation: 'questo zaino (no elision before z).' },
      { sentence: '"___ che mi hai detto è importante."', options: ['Quello', 'Quella', 'Quei', 'Quel'], answer: 'Quello', explanation: 'quello che = what (neutral).' },
      { sentence: 'Vieni anche tu ___ sera?', options: ['questa', 'quella', 'questo', 'questi'], answer: 'questa', explanation: 'questa sera (f sing, tonight).' },
      { sentence: 'Siamo sempre gli ___.', options: ['stessi', 'stesso', 'stesse', 'stessa'], answer: 'stessi', explanation: 'gli stessi (m plural).' },
      { sentence: '"___ che vince riceve un premio."', options: ['Colui', 'Colei', 'Coloro', 'Costui'], answer: 'Colui', explanation: 'he who wins → colui che (literary).' },
    ],
  },
  {
    id: 26,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'This or That?',
    storyTitle: 'Questo o quello?',
    story: 'Luca: Questa camicia è bellissima. Quanto costa?\n\nCommessa: Quella costa cinquanta euro, questa trenta.\n\nLuca: Questa è più economica, ma quella è più elegante.\n\nCommessa: Questo modello si lava facilmente. Quello no.\n\nLuca: Prendo questa. Quei pantaloni, invece, quanto costano?\n\nCommessa: Quei pantaloni sono in saldo: venti euro.\n\nLuca: Perfetto! Prendo questa camicia e quei pantaloni.\n\nLeo: E quello che diceva la mamma sul risparmio?\n\nLuca: Zitto! Quello che conta è lo stile!',
    vocab: [
      { word: 'questa camicia', meaning: 'this shirt (near)' },
      { word: 'quella / questa', meaning: 'that one / this one (pronouns)' },
      { word: 'quei pantaloni', meaning: 'those trousers (quei + consonant)' },
      { word: 'questo modello', meaning: 'this model' },
      { word: 'quello che conta', meaning: 'what matters' },
      { word: 'quello che diceva', meaning: 'what she used to say' },
    ],
    translation: 'Luca: This shirt is beautiful. How much is it?\n\nSales assistant: That one costs fifty euros, this one thirty.\n\nLuca: This one is cheaper, but that one is more elegant.\n\nSales assistant: This model washes easily. That one does not.\n\nLuca: I will take this one. Those trousers, instead, how much do they cost?\n\nSales assistant: Those trousers are on sale: twenty euros.\n\nLuca: Perfect! I take this shirt and those trousers.\n\nLeo: And what mum said about saving?\n\nLuca: Shush! What matters is style!',
    questions: [
      { question: 'Quanto costa la camicia elegante (quella)?', options: ['Cinquanta euro', 'Trenta euro', 'Venti euro', 'Dieci euro'], answer: 'Cinquanta euro', explanation: '"Quella costa cinquanta euro, questa trenta."' },
      { question: 'Quale camicia compra Luca?', options: ['Questa (la più economica)', 'Quella (la più elegante)', 'Tutte e due', 'Nessuna'], answer: 'Questa (la più economica)', explanation: '"Prendo questa."' },
      { question: '"Quei pantaloni" — "quei" è la forma plurale usata prima di:', options: ['consonante', 'vocale', 's + consonante', 'sempre'], answer: 'consonante', explanation: 'pantaloni starts with p (consonant) → quei.' },
      { question: 'Che cosa aveva detto la mamma?', options: ['Di risparmiare', 'Di comprare tutto', 'Di stare zitto', 'Di cambiare negozio'], answer: 'Di risparmiare', explanation: '"quello che diceva la mamma sul risparmio".' },
      { question: '"Quello che conta è lo stile" — "quello che" significa:', options: ['what matters', 'the one who counts', 'that counts money', 'this style'], answer: 'what matters', explanation: 'quello che = what / that which.' },
      { question: 'Write one sentence using "questo" or "quello" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Questa camicia è in saldo. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 27,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'The House Ahead',
    storyTitle: 'La casa in fondo',
    story: 'Giulia: Quella casa in fondo alla strada è in vendita?\n\nMarco: Sì, e questa qua accanto è la mia preferita.\n\nGiulia: Quella ha un giardino enorme, ma questa è più vicina al centro.\n\nMarco: Colui che la vende è un mio amico d\'infanzia.\n\nGiulia: Che fortuna! Coloro che trattano con gli amici ottengono prezzi migliori.\n\nMarco: Questo è vero: gli affari con gli amici sono i migliori.\n\nGiulia: Allora, ciò che dobbiamo decidere è solo il prezzo!',
    vocab: [
      { word: 'quella casa', meaning: 'that house (far)' },
      { word: 'questa qua accanto', meaning: 'this one right next to us' },
      { word: 'colui che la vende', meaning: 'he who sells it (formal)' },
      { word: 'coloro che trattano', meaning: 'those who negotiate (formal)' },
      { word: 'questo è vero', meaning: 'this is true (pronoun)' },
      { word: 'ciò che dobbiamo decidere', meaning: 'what we must decide' },
    ],
    translation: 'Giulia: Is that house at the end of the street for sale?\n\nMarco: Yes, and this one right next to us is my favourite.\n\nGiulia: That one has a huge garden, but this one is closer to the centre.\n\nMarco: The one (he) who is selling it is a childhood friend of mine.\n\nGiulia: How lucky! Those who deal with friends get better prices.\n\nMarco: This is true: business with friends is the best.\n\nGiulia: Then, what we must decide is only the price!',
    questions: [
      { question: 'Quale casa è in vendita?', options: ['La casa in fondo alla strada (quella)', 'La casa accanto (questa)', 'Tutte e due', 'Nessuna'], answer: 'La casa in fondo alla strada (quella)', explanation: '"Quella casa in fondo alla strada è in vendita?"' },
      { question: 'Quale casa preferisce Marco?', options: ['Questa, vicina al centro', 'Quella con il giardino', 'Quella in fondo', 'Nessuna'], answer: 'Questa, vicina al centro', explanation: '"questa è più vicina al centro."' },
      { question: '"Colui che la vende" — "colui che" significa:', options: ['he who', 'she who', 'those who', 'what'], answer: 'he who', explanation: 'colui che = he who (formal).' },
      { question: '"Coloro che trattano con gli amici" — "coloro che" significa:', options: ['those who', 'the one who', 'this which', 'she who'], answer: 'those who', explanation: 'coloro che = those who (plural).' },
      { question: '"Ciò che dobbiamo decidere" — "ciò che" significa:', options: ['what we must decide', 'who decides', 'that decides', 'why decide'], answer: 'what we must decide', explanation: 'ciò che = what / that which.' },
      { question: 'Write one sentence using "colui che" or "ciò che" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Ciò che conta è il prezzo. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 28,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'The Same Tastes',
    storyTitle: 'Gli stessi gusti',
    story: 'Anna: Vuoi quella pizza o questa?\n\nPaolo: Non posso scegliere! Ogni volta è lo stesso dilemma.\n\nAnna: A noi due piace la stessa cosa: quella con la mozzarella.\n\nPaolo: Allora prendiamo questa, insieme.\n\nAnna: D\'accordo. Quel caffè del bar qui accanto è buono?\n\nPaolo: Sì, è talmente buono che prendo il caffè per tutti!\n\nAnna: Tale e quale a te: pensare subito al caffè!\n\nPaolo: E questa è la storia di come facciamo sempre le stesse scelte.',
    vocab: [
      { word: 'quella pizza o questa', meaning: 'that pizza or this one' },
      { word: 'lo stesso dilemma', meaning: 'the same dilemma' },
      { word: 'la stessa cosa', meaning: 'the same thing' },
      { word: 'quel caffè', meaning: 'that coffee (quel + consonant)' },
      { word: 'tale e quale', meaning: 'just like / exactly the same' },
      { word: 'le stesse scelte', meaning: 'the same choices' },
    ],
    translation: 'Anna: Do you want that pizza or this one?\n\nPaolo: I cannot choose! Every time it is the same dilemma.\n\nAnna: The two of us like the same thing: the one with mozzarella.\n\nPaolo: Then let us take this one, together.\n\nAnna: OK. Is that coffee from the bar next door good?\n\nPaolo: Yes, it is so good that I will get coffee for everyone!\n\nAnna: Just like you: thinking about coffee right away!\n\nPaolo: And this is the story of how we always make the same choices.',
    questions: [
      { question: 'Quale pizza piace a tutti e due?', options: ['Quella con mozzarella', 'Questa senza mozzarella', 'Nessuna', 'La pizza al pomodoro'], answer: 'Quella con mozzarella', explanation: '"ci piace la stessa cosa: quella con la mozzarella."' },
      { question: '"Ogni volta lo stesso dilemma" — "lo stesso" qui significa:', options: ['the same', 'different', 'this', 'nothing'], answer: 'the same', explanation: 'lo stesso dilemma = the same dilemma.' },
      { question: '"Tale e quale" è un\'espressione che significa:', options: ['just like / exactly the same', 'different', 'nearby', 'come here'], answer: 'just like / exactly the same', explanation: '"Tale e quale a te" = just like you.' },
      { question: 'La scelta finale del gruppo è:', options: ['prendere il caffè per tutti', 'dividersi la pizza', 'cambiare posto', 'andare a casa'], answer: 'prendere il caffè per tutti', explanation: '"prendo il caffè per tutti!"' },
      { question: '"Questa è la storia..." — "questa" è:', options: ['un pronome', 'un aggettivo', 'un verbo', 'una preposizione'], answer: 'un pronome', explanation: 'stands alone → pronoun (this is the story).' },
      { question: 'Write one sentence using "stesso/stessa" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Abbiamo la stessa pizza. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 29,
    type: 'story',
    level: 'Level 9 — Real-Life Communication',
    title: 'The Silent Sage',
    storyTitle: 'Colui che sapeva',
    story: 'Una volta, lì in campagna, viveva colui che tutti chiamavano il Saggio.\n\nColoro che andavano da lui tornavano sempre più sereni.\n\nLa sua filosofia era semplice: ciò che conta non è possedere, è essere.\n\nQuesta idea, tramandata di voce in voce, ancora oggi illumina quel villaggio.\n\nE chi vuole ascoltarla, trovi quel vecchio albero sotto il quale amava sedersi.\n\nCostoro, i nuovi visitatori, spesso si chiedono: chi era davvero?\n\nE la risposta è quella che lui stesso sussurrava: "Tutti."',
    vocab: [
      { word: 'colui che tutti chiamavano', meaning: 'he whom everyone called' },
      { word: 'coloro che andavano', meaning: 'those who went' },
      { word: 'ciò che conta', meaning: 'what matters' },
      { word: 'questa idea', meaning: 'this idea' },
      { word: 'quel vecchio albero', meaning: 'that old tree' },
      { word: 'lui stesso', meaning: 'he himself' },
    ],
    translation: 'Once, there in the countryside, lived he whom everyone called the Sage.\n\nThose who went to him always came back more serene.\n\nHis philosophy was simple: what matters is not possessing, it is being.\n\nThis idea, passed on by word of mouth, still illuminates that village today.\n\nAnd whoever wants to hear it, let them find that old tree under which he loved to sit.\n\nThese newcomers, the new visitors, often wonder: who was he really?\n\nAnd the answer is the one he himself whispered: "Everyone."',
    questions: [
      { question: 'Chi viveva in campagna?', options: ['Colui che chiamavano il Saggio', 'Un sarto', 'Un insegnante', 'Un professore'], answer: 'Colui che chiamavano il Saggio', explanation: '"viveva colui che tutti chiamavano il Saggio."' },
      { question: '"Coloro che andavano da lui" — "coloro che" significa:', options: ['those who', 'he who', 'she who', 'this which'], answer: 'those who', explanation: 'coloro che = those who (plural).' },
      { question: 'Qual è la filosofia del Saggio?', options: ['Che conta essere, non possedere', 'Che conta possedere', 'Che conta viaggiare', 'Che conta dormire'], answer: 'Che conta essere, non possedere', explanation: '"ciò che conta non è possedere, è essere."' },
      { question: 'Dove amava sedersi?', options: ['Sotto un vecchio albero', 'Su una panchina', 'In chiesa', 'Sul porto'], answer: 'Sotto un vecchio albero', explanation: '"quel vecchio albero sotto il quale amava sedersi."' },
      { question: '"La risposta è quella che lui stesso sussurrava" — "stesso" qui significa:', options: ['-self (himself)', 'same', 'this evening', 'there'], answer: '-self (himself)', explanation: 'stesso reinforces the subject: "he himself".' },
      { question: 'Write one sentence using "colui che" or "ciò che" in Italian.', type: 'text', answer: 'any', acceptedAnswers: [], explanation: 'Example: Colui che cerca trova. Any correct sentence is accepted.' },
    ],
  },
  {
    id: 30,
    type: 'mastery',
    level: 'Level 10 — Final Proficiency Test',
    title: 'The Demonstratives Test',
    instruction: '27 questions — recognise, choose, translate, and produce. You must pass to complete the course.',
    questions: [
      // Recognition
      { question: 'Demonstratives (questo/quello) point to:', options: ['near or far', 'the past only', 'names only', 'numbers'], answer: 'near or far' },
      { question: 'The feminine singular of "questo" is:', options: ['questa', 'queste', 'questi', 'quest\''], answer: 'questa' },
      { question: 'The masculine plural of "quello" (as a pronoun) is:', options: ['quelli', 'quei', 'quelle', 'quello'], answer: 'quelli' },
      // quello transformations
      { question: 'Before a vowel, "quello" becomes:', options: ['quell\'', 'quel', 'quello', 'quelli'], answer: 'quell\'' },
      { question: 'Before a plain consonant (libro), "quello" becomes:', options: ['quel', 'quello', 'quell\'', 'quelle'], answer: 'quel' },
      { question: 'Before "studente" (s + consonant), the form is:', options: ['quello', 'quel', 'quell\'', 'quella'], answer: 'quello' },
      // adjective vs pronoun
      { question: 'In "Questo libro è mio", "questo" is:', options: ['an adjective', 'a pronoun', 'a verb', 'a preposition'], answer: 'an adjective' },
      { question: 'In "Questo è mio", "questo" is:', options: ['a pronoun', 'an adjective', 'a conjunction', 'an adverb'], answer: 'a pronoun' },
      // agreement
      { question: '___ casa è vecchia.', options: ['Questa', 'Questo', 'Questi', 'Queste'], answer: 'Questa' },
      { question: '___ libri sono nuovi.', options: ['Questi', 'Questo', 'Questa', 'Queste'], answer: 'Questi' },
      { question: 'Prendo ___ scarpe.', options: ['queste', 'questo', 'questa', 'questi'], answer: 'queste' },
      { question: 'The plural of "quel libro" is:', options: ['quei libri', 'quegli libri', 'quelli libri', 'quelle libri'], answer: 'quei libri' },
      { question: 'The plural of "quell\'amico" is:', options: ['quegli amici', 'quei amici', 'quelli amici', 'quelli amici'], answer: 'quegli amici' },
      // quello che
      { question: '"quello che" means:', options: ['what / that which', 'who', 'whose', 'these ones'], answer: 'what / that which' },
      { question: 'Preferisco ___, non quello.', options: ['questo', 'questa', 'queste', 'quei'], answer: 'questo' },
      { question: 'Quella casa è più grande di ___.', options: ['questa', 'questo', 'questi', 'quei'], answer: 'questa' },
      // ciò, colui...
      { question: '"ciò" is:', options: ['this matter / that idea (neutral)', 'this book', 'the man', 'the woman'], answer: 'this matter / that idea (neutral)' },
      { question: '"colui che" means:', options: ['he who / the one who (m)', 'she who', 'those who', 'what'], answer: 'he who / the one who (m)' },
      { question: 'The feminine of "colui" is:', options: ['colei', 'coloro', 'costoro', 'quella'], answer: 'colei' },
      { question: 'The plural of "colui/colei" is:', options: ['coloro', 'quei', 'ciò', 'quelli'], answer: 'coloro' },
      // stesso/tale
      { question: '"stesso" can mean:', options: ['same or -self', 'this or that', 'near and far', 'new or old'], answer: 'same or -self' },
      { question: '"tale" means:', options: ['such', 'who', 'what', 'why'], answer: 'such' },
      // translation
      { question: 'Questa città è più grande di quella. =', options: ['This city is bigger than that one.', 'That city is bigger than this one.', 'These cities are big.', 'This city is small.'], answer: 'This city is bigger than that one.' },
      // Reading
      { question: 'READ FIRST: "Quella casa in fondo alla strada è la mia preferita. Questo quartiere è tranquillo e quei negozi sono utilissimi. Colui che vende la casa chiede un prezzo giusto, e ciò che mi manca è solo il coraggio di comprarla. Domani stesso ci penso."\n\nChe casa è la preferita?', options: ['Quella in fondo alla strada', 'Questa casa nuova', 'Un palazzo a Milano', 'Dei negozi'], answer: 'Quella in fondo alla strada' },
      { question: 'READ AGAIN: "ciò che mi manca è solo il coraggio" — "ciò che" significa:', options: ['what is missing for me', 'who misses me', 'that misses me', 'why I miss'], answer: 'what is missing for me' },
      // Production
      { question: 'Translate into Italian: "That house is mine."', type: 'text', answer: 'Quella casa è mia.', acceptedAnswers: ['quella casa è mia'] },
      { question: 'Translate into Italian: "These books are new."', type: 'text', answer: 'Questi libri sono nuovi.', acceptedAnswers: ['questi libri sono nuovi'] },
    ],
  },
];

export const dimostrativiStories = dimostrativiExercises.filter((e) => e.type === 'story');

export const dimostrativiFinalTest = dimostrativiExercises.find((e) => e.id === 30).questions;

export const dimostrativiFinalBands = [
  { min: 90, grade: 'Ottimo!', message: 'You master questo/quello in every gender, form, and context, plus ciò, colui and stesso.' },
  { min: 75, grade: 'Molto bene!', message: 'Great feel for demonstratives — brush up the quel/quello/quell\' alternation and the formal colui/colei/coloro.' },
  { min: 60, grade: 'Bene!', message: 'Good command of the basics. Review the agreement of questo/quello and the special forms before vowels and consonants.' },
  { min: 40, grade: 'In progress', message: 'Focus on the questo (near) vs quello (far) contrast and on pronoun vs adjective usage.' },
  { min: 0, grade: 'Keep going', message: 'Revisit the demonstratives: questo (near) and quello (far), their agreements, and the pronoun forms.' },
];